### ISSUE TITLE
XWayland became hard requirement?

### ISSUE THREAD

**Issue by gnidorah** [swaywm/sway#1428]
Hi.
After updating from 0.13 to 0.14 Sway segfaults if XWayland is not installed on the system.
Any plans to eliminate this requirement?

**Comment by SirCmpwn** [comment]
Test this on [0.15-rc3](https://github.com/swaywm/sway/releases/tag/0.15-rc3) and provide **WAY** more context.

**Comment by gnidorah** [comment]
@SirCmpwn Ok, sorry! Same with 0.15-rc3
Context: https://github.com/NixOS/nixpkgs/pull/30493#issuecomment-337249453
Issue: https://github.com/NixOS/nixpkgs/pull/30493#issuecomment-337439145
The question is what brought XWayland into runtime dependence. Perhaps change in wlc?
Sway 0.13 and wlc 0.0.9 worked fine with and without XWayland installed.

**Comment by SirCmpwn** [comment]
How about a backtrace?

**Comment by gnidorah** [comment]
@SirCmpwn Copypasted from the above link
```
gdb> bt
#0  0x00007f4798edf0f7 in wl_list_remove () from /nix/store/xyajc0iyp9z1pkmssfazjjsvw1r9kc68-wayland-1.12.0/lib/libwayland-server.so.0
#1  0x00007f47997ce3a7 in wlc_xwm_release () from /nix/store/ia6jgf3yw2nrz0704dbnnk09bcrx6rsj-wlc-0.0.10/lib/libwlc.so.0
#2  0x00007f47997b34c0 in xwayland_event () from /nix/store/ia6jgf3yw2nrz0704dbnnk09bcrx6rsj-wlc-0.0.10/lib/libwlc.so.0
#3  0x00007f47997cbafc in wlc_xwayland_terminate () from /nix/store/ia6jgf3yw2nrz0704dbnnk09bcrx6rsj-wlc-0.0.10/lib/libwlc.so.0
#4  0x00007f47997cc422 in destroy_event () from /nix/store/ia6jgf3yw2nrz0704dbnnk09bcrx6rsj-wlc-0.0.10/lib/libwlc.so.0
#5  0x00007f4798eda7bc in wl_client_destroy () from /nix/store/xyajc0iyp9z1pkmssfazjjsvw1r9kc68-wayland-1.12.0/lib/libwayland-server.so.0
#6  0x00007f4798eda8d8 in wl_client_connection_data () from /nix/store/xyajc0iyp9z1pkmssfazjjsvw1r9kc68-wayland-1.12.0/lib/libwayland-server.so.0
#7  0x00007f4798edcae2 in wl_event_loop_dispatch () from /nix/store/xyajc0iyp9z1pkmssfazjjsvw1r9kc68-wayland-1.12.0/lib/libwayland-server.so.0
#8  0x00007f4798edaf8a in wl_display_run () from /nix/store/xyajc0iyp9z1pkmssfazjjsvw1r9kc68-wayland-1.12.0/lib/libwayland-server.so.0
#9  0x00007f47997c992c in wlc_run () from /nix/store/ia6jgf3yw2nrz0704dbnnk09bcrx6rsj-wlc-0.0.10/lib/libwlc.so.0
#10 0x000000000040bc81 in main ()
#11 0x00007f47974f4560 in __libc_start_main () from /nix/store/yydnhs7migvlbl48wpsxan1yvq2icbr9-glibc-2.25-49/lib/libc.so.6
#12 0x000000000040be3a in _start ()
```

**Comment by SirCmpwn** [comment]
This isn't useful. Compile with debug symbols.

**Comment by gnidorah** [comment]
@SirCmpwn 
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff72c90f7 in wl_list_remove () from /nix/store/xyajc0iyp9z1pkmssfazjjsvw1r9kc68-wayland-1.12.0/lib/libwayland-server.so.0
(gdb) bt
#0  0x00007ffff72c90f7 in wl_list_remove () from /nix/store/xyajc0iyp9z1pkmssfazjjsvw1r9kc68-wayland-1.12.0/lib/libwayland-server.so.0
#1  0x00007ffff7bba95e in wlc_xwm_selection_release (xwm=<optimized out>) at /tmp/nix-build-wlc-0.0.10.drv-0/wlc-v0.0.10-src/src/xwayland/selection.c:460
#2  0x00007ffff7bb9997 in wlc_xwm_release (xwm=xwm@entry=0x7ffff7dd73b0 <wlc+2544>) at /tmp/nix-build-wlc-0.0.10.drv-0/wlc-v0.0.10-src/src/xwayland/xwm.c:853
#3  0x00007ffff7b9d620 in xwayland_event (listener=0x7ffff7dd7c00 <wlc+4672>, data=<optimized out>) at /tmp/nix-build-wlc-0.0.10.drv-0/wlc-v0.0.10-src/src/compositor/compositor.c:318
#4  0x00007ffff7bb6f7c in wl_signal_emit (data=0x7fffffffc8ef, signal=0x7ffff7dd7e00 <wlc+5184>) at /nix/store/xyajc0iyp9z1pkmssfazjjsvw1r9kc68-wayland-1.12.0/include/wayland-server-core.h:357
#5  wlc_xwayland_terminate () at /tmp/nix-build-wlc-0.0.10.drv-0/wlc-v0.0.10-src/src/xwayland/xwayland.c:225
#6  0x00007ffff7bb78a2 in destroy_event (listener=<optimized out>, data=<optimized out>) at /tmp/nix-build-wlc-0.0.10.drv-0/wlc-v0.0.10-src/src/xwayland/xwayland.c:209
#7  0x00007ffff72c47bc in wl_client_destroy () from /nix/store/xyajc0iyp9z1pkmssfazjjsvw1r9kc68-wayland-1.12.0/lib/libwayland-server.so.0
#8  0x00007ffff72c48d8 in wl_client_connection_data () from /nix/store/xyajc0iyp9z1pkmssfazjjsvw1r9kc68-wayland-1.12.0/lib/libwayland-server.so.0
#9  0x00007ffff72c6ae2 in wl_event_loop_dispatch () from /nix/store/xyajc0iyp9z1pkmssfazjjsvw1r9kc68-wayland-1.12.0/lib/libwayland-server.so.0
#10 0x00007ffff72c4f8a in wl_display_run () from /nix/store/xyajc0iyp9z1pkmssfazjjsvw1r9kc68-wayland-1.12.0/lib/libwayland-server.so.0
#11 0x00007ffff7bb4cfc in wlc_run () at /tmp/nix-build-wlc-0.0.10.drv-0/wlc-v0.0.10-src/src/wlc.c:260
#12 0x000000000040c018 in main (argc=<optimized out>, argv=<optimized out>) at /tmp/nix-build-sway-0.15-rc3.drv-0/sway-0.15-rc3-src/sway/main.c:464
```

**Comment by SirCmpwn** [comment]
Thanks. This was fixed here: https://github.com/Cloudef/wlc/pull/280

It will be shipped in the upcoming release.

**Comment by gnidorah** [comment]
@SirCmpwn Thank you much!
