### ISSUE TITLE
segfault in output_get_scaled_size

### ISSUE THREAD

**Issue by dlrobertson** [swaywm/sway#1435]
I don't know what the steps are to reproduce this yet, but I have hit a segfault in `output_get_scaled_size` twice now on exit from sway.

```
(gdb) bt full
#0  0x0000000000437c46 in output_get_scaled_size (handle=1, size=0x7ffe3c57b5f0) at ../sway/output.c:9
        scale = 572533814
#1  0x0000000000434243 in arrange_windows_r (container=0xf3b2c0, width=1920, height=1080) at ../sway/layout.c:982
        resolution = {w = 1684633378, h = 975333492}
        i = 0
        x = 0
        y = 0
#2  0x000000000043420d in arrange_windows_r (container=0x652520 <root_container>, width=1920, height=1080) at ../sway/layout.c:976
        output = 0xf3b2c0
        i = 0
        x = 0
        y = 0
#3  0x00000000004359ab in arrange_windows (container=0x652520 <root_container>, width=-1, height=-1) at ../sway/layout.c:1378
No locals.
#4  0x0000000000425b83 in panel_surface_destructor (resource=0x1109580) at ../sway/extensions.c:57
        config = 0xeabed0
        i = 0
#5  0x00007fd3d402c1bc in destroy_resource (element=0x1109580, data=data@entry=0x0) at /var/tmp/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0/src/wayland-server.c:675
        resource = 0x1109580
        client = 0x1107a00
        flags = 0
#6  0x00007fd3d402c1f4 in wl_resource_destroy (resource=<optimized out>) at /var/tmp/portage/dev-libs/wayland-1.14.0/work/wayland-1.14.0/src/wayland-server.c:690
        client = 0x1107a00
        id = 11
#7  0x00007fd3d4913793 in handle_release (pool=pool@entry=0x7fd3d4b39020 <resources>, handle=0x1117e10,
    preremove=preremove@entry=0x7fd3d4913600 <resource_prerelase at /usr/src/debug/dev-libs/wlc-0.0.10/wlc-0.0.10/src/resources/resources.c:242>) at /usr/src/debug/dev-libs/wlc-0.0.10/wlc-0.0.10/src/resources/resources.c:185
        original = <optimized out>
#8  0x00007fd3d4913e9b in resource_release (resource=<optimized out>) at /usr/src/debug/dev-libs/wlc-0.0.10/wlc-0.0.10/src/resources/resources.c:262
No locals.
#9  wlc_source_release (source=source@entry=0x7fd3d4b38800 <wlc+4096>) at /usr/src/debug/dev-libs/wlc-0.0.10/wlc-0.0.10/src/resources/resources.c:311
        _I = 13
        h = <optimized out>
        r = <optimized out>
#10 0x00007fd3d4904251 in wlc_compositor_release (compositor=compositor@entry=0x7fd3d4b37800 <wlc>) at /usr/src/debug/dev-libs/wlc-0.0.10/wlc-0.0.10/src/compositor/compositor.c:736
No locals.
#11 0x00007fd3d491939b in wlc_cleanup () at /usr/src/debug/dev-libs/wlc-0.0.10/wlc-0.0.10/src/wlc.c:162
No locals.
#12 0x0000000000437bd3 in main (argc=1, argv=0x7ffe3c57b918) at ../sway/main.c:488
        verbose = 0
        debug = 0
        validate = 0
        long_options = {{name = 0x448e64 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x448e69 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x448e70 "validate", has_arg = 0, flag = 0x0, val = 67}, {
            name = 0x448e79 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x448e7f "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x448e87 "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x448e8f "get-socketpath",
            has_arg = 0, flag = 0x0, val = 112}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        config_path = 0x0
        usage = 0x4489f8 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = -1
        suid = false
```

**Comment by SirCmpwn** [comment]
Without steps to reproduce there's not much I can do.

**Comment by dlrobertson** [comment]
Makes sense
