### ISSUE TITLE
Crash in Xwayland unmap

### ISSUE THREAD

**Issue by ascent12** [swaywm/sway#1806]
Random crash in sway while using it. I stupidly overwrote the logs with the next launch, but I have the coredump:
```
#0  0x000055bdf6906c4d in surface_for_each_surface (surface=0x0, ox=2938, oy=-34, geo=0x7ffdbd983880, iterator=0x55bdf69079c4 <damage_surface_iterator>, user_data=0x7ffdbd983880) at ../sway/desktop/output.c:107
#1  0x000055bdf6907cbb in output_damage_surface (output=0x55bdf815d820, ox=2938, oy=-34, surface=0x0, whole=true) at ../sway/desktop/output.c:455
#2  0x000055bdf69067f4 in desktop_damage_surface (surface=0x0, lx=2938, ly=62, whole=true) at ../sway/desktop/desktop.c:10
#3  0x000055bdf690a408 in unmanaged_handle_unmap (listener=0x55bdf8658c58, data=0x55bdf8312e10) at ../sway/desktop/xwayland.c:77
#4  0x00007fbeaffc6946 in wlr_signal_emit_safe (signal=0x55bdf8312f70, data=0x55bdf8312e10) at ../util/signal.c:29
#5  0x00007fbeaff88cfb in xwm_handle_unmap_notify (xwm=0x55bdf8548260, ev=0x55bdf864c0b0) at ../xwayland/xwm.c:783
#6  0x00007fbeaff8980e in x11_event_handler (fd=18, mask=0, data=0x55bdf8548260) at ../xwayland/xwm.c:1161
#7  0x00007fbeb01f9a08 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#8  0x00007fbeb01f814c in wl_display_run () at /usr/lib/libwayland-server.so.0
#9  0x000055bdf68fe4ef in server_run (server=0x55bdf6b362e0 <server>) at ../sway/server.c:140
#10 0x000055bdf68fddf8 in main (argc=2, argv=0x7ffdbd983d98) at ../sway/main.c:418
```
I haven't dug into it too deeply (I'm not too familiar with xwayland), but there is some situation where in `unmanaged_handle_unmap`, `xsurface->surface` can be NULL.
```
gdb print *xsurface
$5 = {
  window_id = 6297090, 
  xwm = 0x55bdf8548260, 
  surface_id = 0, 
  link = {
    prev = 0x55bdf8664a08, 
    next = 0x55bdf86600f8
  }, 
  unpaired_link = {
    prev = 0x0, 
    next = 0x0
  }, 
  surface = 0x0, 
  x = 2938, 
  y = 62, 
  width = 481, 
  height = 41, 
  saved_width = 0, 
  saved_height = 0, 
  override_redirect = true, 
  mapped = false, 
  added = true, 
  title = 0x55bdf8646070 "", 
  class = 0x55bdf865b510 "Firefox", 
  instance = 0x55bdf8655f00 "Popup", 
  pid = 669, 
  children = {
    prev = 0x55bdf8312e80, 
    next = 0x55bdf8312e80
  }, 
  parent = 0x55bdf86146d0, 
  parent_link = {
    prev = 0x55bdf8614740, 
    next = 0x55bdf85f7078
  }, 
  window_type = 0x55bdf8591c00, 
  window_type_len = 1, 
  protocols = 0x55bdf865d460, 
  protocols_len = 4, 
  decorations = 0, 
  hints = 0x55bdf8658030, 
  hints_urgency = 0, 
  size_hints = 0x55bdf8658c90, 
  pinging = false, 
  ping_timer = 0x55bdf865dc90, 
  fullscreen = false, 
  maximized_vert = false, 
  maximized_horz = false, 
  has_alpha = false, 
  events = {
    destroy = {
      listener_list = {
        prev = 0x55bdf8658c70, 
        next = 0x55bdf8658c70
      }
    }, 
    request_configure = {
        prev = 0x55bdf8658c10, 
        next = 0x55bdf8658c10
      }
    }, 
    request_move = {
      listener_list = {
        prev = 0x55bdf8312f20, 
        next = 0x55bdf8312f20
      }
    }, 
    request_resize = {
      listener_list = {
        prev = 0x55bdf8312f30, 
        next = 0x55bdf8312f30
      }
    }, 
    request_maximize = {
      listener_list = {
        prev = 0x55bdf8312f40, 
        next = 0x55bdf8312f40
      }
    }, 
    request_fullscreen = {
      listener_list = {
        prev = 0x55bdf8312f50, 
        next = 0x55bdf8312f50
      }
    }, 
    map = {
      listener_list = {
        prev = 0x55bdf8658c40, 
        next = 0x55bdf8658c40
      }
    }, 
    unmap = {
      listener_list = {
        prev = 0x7ffdbd983980, 
        next = 0x55bdf8658c58
      }
    }, 
    set_title = {
      listener_list = {
        prev = 0x55bdf8312f80, 
        next = 0x55bdf8312f80
      }
    }, 
    set_class = {
      listener_list = {
        prev = 0x55bdf8312f90, 
        next = 0x55bdf8312f90
      }
    }, 
    set_parent = {
      listener_list = {
        prev = 0x55bdf8312fa0, 
        next = 0x55bdf8312fa0
      }
    },
    set_pid = {
      listener_list = {
        prev = 0x55bdf8312fb0, 
        next = 0x55bdf8312fb0
      }
    }, 
    set_window_type = {
      listener_list = {
        prev = 0x55bdf8312fc0, 
        next = 0x55bdf8312fc0
      }
    }, 
    ping_timeout = {
      listener_list = {
        prev = 0x55bdf8312fd0, 
        next = 0x55bdf8312fd0
      }
    }
  }, 
  surface_destroy = {
    link = {
      prev = 0x55bdf8652518, 
      next = 0x55bdf8652518
    }, 
    notify = 0x7fbeaff8860f <handle_surface_destroy>
  }, 
  data = 0x0
}
```

**Comment by emersion** [comment]
Are you sure you have the latest wlroots? This shouldn't happen with https://github.com/swaywm/wlroots/pull/843

**Comment by ascent12** [comment]
My local wlroots was checked out at swaywm/wlroots@7efd9885b65d0115e30f2253a30f165c12a07d2a, which is after that PR was merged. I'll admit that there is a possibility that this isn't the version I actually have installed.
I'll make absolutely sure I'm not on an old version, and see if it randomly happens again.

**Comment by ascent12** [comment]
I haven't had this happen again, so I'm just going to assume some recent work fixed this.
