### ISSUE TITLE
sway crashes when launching program from dmenu

### ISSUE THREAD

**Issue by mulimoen** [swaywm/sway#1963]
Sway crashes with the last error message
[sway/tree/container.c:342] container_view_create:container_view_create called with NULL sibling/parent
Probably due to lack of NULL-check of "cont" from line 379 in sway/tree/view.c

Steps to reproduce:
1. start sway
2. launch dmenu
3. start program from dmenu

**Comment by ascent12** [comment]
Yeah. I've run into this recently too. I was sitting on an old version for awhile, so I didn't notice it straight away.
Specifically launching things from dmenu is what's causing the crash. It doesn't happen when opening something from a hotkey or a terminal.
I've tried both Nautilus and Firefox, so it seems to affect both Wayland native and Xwayland programs.

Here is a captured stack trace:
```
#0  0x00007ff5c9fc686b in raise () at /usr/lib/libc.so.6
#1  0x000055a51a1b9338 in _sway_assert (condition=false, format=0x55a51a1c2c00 "[%s:%d] %s:container_view_create called with NULL sibling/parent") at ../common/log.c:27
#2  0x000055a51a1b1d6b in container_view_create (sibling=0x0, sway_view=0x55a51c50d350) at ../sway/tree/container.c:341
#3  0x000055a51a1b6522 in view_map (view=0x55a51c50d350, wlr_surface=0x55a51c4ee590) at ../sway/tree/view.c:377
#4  0x000055a51a19ccfb in handle_map (listener=0x55a51c50d4c8, data=0x55a51c50d150) at ../sway/desktop/xwayland.c:268
#5  0x00007ff5ca801095 in wlr_signal_emit_safe (signal=0x55a51c50d2a0, data=0x55a51c50d150) at ../util/signal.c:29
#6  0x00007ff5ca7c0f0f in handle_surface_commit (wlr_surface=0x55a51c4ee590, role_data=0x55a51c50d150) at ../xwayland/xwm.c:633
#7  0x00007ff5ca7f302a in surface_commit_pending (surface=0x55a51c4ee590) at ../types/wlr_surface.c:432
#8  0x00007ff5ca7f32ef in surface_commit (client=0x55a51c1164f0, resource=0x55a51c4de060) at ../types/wlr_surface.c:516
#9  0x00007ff5c79861c8 in ffi_call_unix64 () at /usr/lib/libffi.so.6
#10 0x00007ff5c7985c2a in ffi_call () at /usr/lib/libffi.so.6
#11 0x00007ff5caa337fd in  () at /usr/lib/libwayland-server.so.0
#12 0x00007ff5caa2ff79 in  () at /usr/lib/libwayland-server.so.0
#13 0x00007ff5caa319b2 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#14 0x00007ff5caa3014c in wl_display_run () at /usr/lib/libwayland-server.so.0
#15 0x000055a51a18ee04 in server_run (server=0x55a51a3cd4a0 <server>) at ../sway/server.c:145
#16 0x000055a51a18e6ad in main (argc=2, argv=0x7fff39df5c88) at ../sway/main.c:418
```

**Comment by SirCmpwn** [comment]
I reverted the change that caused this.
