### ISSUE TITLE
Assertion failure when running qutebrowser on Xwayland

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/sway#1965]
This doesn't happen every time, but happens often.

```
#0  0x00007fc909a2786b in raise () at /usr/lib/libc.so.6
#1  0x000056406946c366 in _sway_assert (condition=false, format=0x564069475c40 "[%s:%d] %s:container_view_create called with NULL sibling/parent") at ../common/log.c:27
#2  0x0000564069464d8b in container_view_create (sibling=0x0, sway_view=0x56406a017360)
    at ../sway/tree/container.c:341
#3  0x0000564069469550 in view_map (view=0x56406a017360, wlr_surface=0x56406a41a560)
    at ../sway/tree/view.c:379
#4  0x000056406944fd1b in handle_map (listener=0x56406a0174d8, data=0x56406a44b540)
    at ../sway/desktop/xwayland.c:268
#5  0x00007fc90bd490ec in wlr_signal_emit_safe (signal=0x56406a44b690, data=0x56406a44b540)
    at ../subprojects/wlroots/util/signal.c:29
#6  0x00007fc90bd08eef in handle_surface_commit (wlr_surface=0x56406a41a560, role_data=0x56406a44b540) at ../subprojects/wlroots/xwayland/xwm.c:633
#7  0x00007fc90bd3af70 in surface_commit_pending (surface=0x56406a41a560)
    at ../subprojects/wlroots/types/wlr_surface.c:432
#8  0x00007fc90bd3b235 in surface_commit (client=0x564069e93670, resource=0x564069f4aba0)
    at ../subprojects/wlroots/types/wlr_surface.c:516
#9  0x00007fc9058f21c8 in ffi_call_unix64 () at /usr/lib/libffi.so.6
#10 0x00007fc9058f1c2a in ffi_call () at /usr/lib/libffi.so.6
#11 0x00007fc90a2047fd in  () at /usr/lib/libwayland-server.so.0
#12 0x00007fc90a200f79 in  () at /usr/lib/libwayland-server.so.0
#13 0x00007fc90a2029b2 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#14 0x00007fc90a20114c in wl_display_run () at /usr/lib/libwayland-server.so.0
#15 0x0000564069441e24 in server_run (server=0x5640696804a0 <server>) at ../sway/server.c:145
#16 0x00005640694416cd in main (argc=2, argv=0x7fffb7bca408) at ../sway/main.c:418
```

**Comment by SirCmpwn** [comment]
Duplicate of https://github.com/swaywm/sway/issues/1963
