### ISSUE TITLE
Switching workspaces while lockscreen is active makes sway crash

### ISSUE THREAD

**Issue by emersion** [swaywm/sway#1976]
```
#0  0x00007f577f8d486b in raise () at /usr/lib/libc.so.6
#1  0x0000556ab60e0356 in _sway_assert (condition=false, format=0x556ab60e9740 "[%s:%d] %s:container is NULL") at ../common/log.c:27
#2  0x0000556ab60d82b1 in container_parent (container=0x0, type=C_OUTPUT) at ../sway/tree/container.c:404
#3  0x0000556ab60d21fb in cmd_workspace (argc=1, argv=0x556ab78e7738) at ../sway/commands/workspace.c:95
#4  0x0000556ab60b1dd8 in execute_command (_exec=0x556ab75e8630 "workspace 2", seat=0x556ab74d7620) at ../sway/commands.c:374
#5  0x0000556ab60c769d in keyboard_execute_command (keyboard=0x556ab77f42a0, binding=0x556ab75e8ed0) at ../sway/input/keyboard.c:100
#6  0x0000556ab60c6ffe in keyboard_execute_bindsym (keyboard=0x556ab77f42a0, pressed_keysyms=0x556ab77f4364, modifiers=64, key_state=WLR_KEY_PRESSED)
    at ../sway/input/keyboard.c:168
#7  0x0000556ab60c6c4f in handle_keyboard_key (listener=0x556ab77f42b0, data=0x7fffc1ac4b70) at ../sway/input/keyboard.c:375
#8  0x00007f5781f15d0c in wlr_signal_emit_safe (signal=0x556ab7811158, data=0x7fffc1ac4b70) at ../subprojects/wlroots/util/signal.c:29
#9  0x00007f5781ef9390 in wlr_keyboard_notify_key (keyboard=0x556ab7811060, event=0x7fffc1ac4b70) at ../subprojects/wlroots/types/wlr_keyboard.c:125
#10 0x00007f5781edc794 in handle_keyboard_key (event=0x556ab7920250, libinput_dev=0x556ab777d140) at ../subprojects/wlroots/backend/libinput/keyboard.c:73
#11 0x00007f5781edbc57 in handle_libinput_event (backend=0x556ab6d471c0, event=0x556ab7920250) at ../subprojects/wlroots/backend/libinput/events.c:213
#12 0x00007f5781edb8bb in handle_libinput_readable (fd=30, mask=1, _backend=0x556ab6d471c0) at ../subprojects/wlroots/backend/libinput/backend.c:35
#13 0x00007f57800af9b2 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#14 0x00007f57800ae14c in wl_display_run () at /usr/lib/libwayland-server.so.0
#15 0x0000556ab60b12b4 in server_run (server=0x556ab62f4470 <server>) at ../sway/server.c:152
#16 0x0000556ab60b03f2 in main (argc=1, argv=0x7fffc1ac5008) at ../sway/main.c:418
```

**Comment by martinetd** [comment]
IPC commands should work, really. It's going to be not-so-well tested but if folks want to run a background script that shuffles all their window while the screen is locked I don't see why we shouldn't let them (or more realistically, for example, someone on IRC was talking about automatic/regular background image changes that could happen while the screen is locked)

keybindings should be denied though, for sure, #592 mentions implementing a new switch to allow some commands to pass and deny others but default has to be denied.

I think we should also consider denying switching to another tty if we can (or make that an option somehow) even if it's not an explicit bindsym command
