### ISSUE TITLE
Complete head freeze

### ISSUE THREAD

**Issue by includereserved** [swaywm/sway#2319]
So I was in the middle of writing this and it happened right then and there, fun.

I can't figure out what keeps causing this, my system doesn't last a full day. It seems to always happen in a browser.
Programs still run (for example I hear my music still playing) but the mouse, keyboard, and display freeze. I can't change TTYs. I can SSH into the machine as normal and get a backtrace (same thing every time), but killing xwayland/sway doesn't unfreeze it. Trying to shutdown kicks me out of SSH but the machine never fully powers off.

Distro: Arch Linux
Motherboard: Gigabyte AX370 Gaming 5
CPU: Ryzen 5 1400
Graphics Card: EVGA GTX 770 SC 4GB

Backtrace:
```(gdb) bt
#0  0x00007fdcd5a4b667 in ioctl () at /usr/lib/libc.so.6
#1  0x00007fdcd454aed1 in drmIoctl () at /usr/lib/libdrm.so.2
#2  0x00007fdcd454b548 in drmModeMoveCursor () at /usr/lib/libdrm.so.2
#3  0x00007fdcd81c4d94 in legacy_crtc_move_cursor (drm=0x55e5aede6b00, crtc=0x55e5aedd4390, x=364, y=504) at ../backend/drm/legacy.c:59
#4  0x00007fdcd81c3839 in drm_connector_move_cursor (output=0x55e5aeed3cc0, x=368, y=508) at ../backend/drm/drm.c:765
#5  0x00007fdcd81f797e in wlr_output_cursor_move (cursor=0x55e5aeff8730, x=368, y=508) at ../types/wlr_output.c:895
#6  0x00007fdcd81eb351 in cursor_warp_unchecked (cur=0x55e5aefd1470, lx=368, ly=508) at ../types/wlr_cursor.c:187
#7  0x00007fdcd81eb617 in cursor_warp_closest (cur=0x55e5aefd1470, dev=0x55e5af1adf90, lx=368, ly=508) at ../types/wlr_cursor.c:265
#8  0x00007fdcd81eb893 in wlr_cursor_move (cur=0x55e5aefd1470, dev=0x55e5af1adf90, delta_x=0, delta_y=1) at ../types/wlr_cursor.c:299
#9  0x000055e5aea88e1a in handle_cursor_motion (listener=0x55e5aefd1350, data=0x7ffccb010910) at ../sway/input/cursor.c:230
#10 0x00007fdcd820640d in wlr_signal_emit_safe (signal=0x55e5aefd1488, data=0x7ffccb010910) at ../util/signal.c:29
#11 0x00007fdcd81eba18 in handle_pointer_motion (listener=0x55e5af1aa5d0, data=0x7ffccb010910) at ../types/wlr_cursor.c:330
#12 0x00007fdcd820640d in wlr_signal_emit_safe (signal=0x55e5af192fe8, data=0x7ffccb010910) at ../util/signal.c:29
#13 0x00007fdcd81c9332 in handle_pointer_motion (event=0x55e5af41dd20, libinput_dev=0x55e5af137cb0) at ../backend/libinput/pointer.c:39
#14 0x00007fdcd81c8e07 in handle_libinput_event (backend=0x55e5aedd2f10, event=0x55e5af41dd20) at ../backend/libinput/events.c:216
#15 0x00007fdcd81c7cf3 in handle_libinput_readable (fd=26, mask=1, _backend=0x55e5aedd2f10) at ../backend/libinput/backend.c:35
#16 0x00007fdcd6396a42 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#17 0x00007fdcd639514c in wl_display_run () at /usr/lib/libwayland-server.so.0
#18 0x000055e5aea7095e in server_run (server=0x55e5aecc18e0 <server>) at ../sway/server.c:148
#19 0x000055e5aea70210 in main (argc=1, argv=0x7ffccb010d38) at ../sway/main.c:448
```

**Comment by martinetd** [comment]
If it's stuck in a drm ioctl you'll have better chance figuring it out looking at dmesg (should print a backtrace after it's stuck for a couple of minutes), or recompiling a kernel with CONFIG_DEBUG_INFO=y (iirc not set on arch) and investigating why it's stuck with [crash](https://people.redhat.com/anderson/)

**Comment by Marteon** [comment]
I don't really know much about the technical stuff but I had the exact (as far as I can tell) same issue.
The problem had something to do with the nouveau drivers. There was a bugreport somewhere, when I find it again I'll add it here.
Sadly there was no fix at the time I was using Nvidia graphics cards.

**Comment by SirCmpwn** [comment]
This is probably a nouveau bug.

**Comment by f4814** [comment]
I have the same issue on 0.15. And I, too, am using a nvidia card and nouveau.

Dmesg spits this: (seems to be a noveau bug)
```
[  614.018177] INFO: task kworker/u16:1:87 blocked for more than 120 seconds.
[  614.018184]       Not tainted 4.18.5-arch1-1-ARCH #1
[  614.018186] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  614.018189] kworker/u16:1   D    0    87      2 0x80000000
[  614.018255] Workqueue: events_unbound nv50_disp_atomic_commit_work [nouveau]
[  614.018257] Call Trace:
[  614.018268]  ? __schedule+0x29b/0x8b0
[  614.018271]  schedule+0x32/0x90
[  614.018275]  schedule_timeout+0x311/0x4a0
[  614.018279]  ? _raw_spin_unlock+0x16/0x30
[  614.018285]  dma_fence_default_wait+0x1e8/0x270
[  614.018288]  ? dma_fence_default_wait+0x270/0x270
[  614.018292]  dma_fence_wait_timeout+0x39/0x110
[  614.018305]  drm_atomic_helper_wait_for_fences+0x38/0xc0 [drm_kms_helper]
[  614.018355]  nv50_disp_atomic_commit_tail+0x7c/0x860 [nouveau]
[  614.018360]  ? _raw_spin_unlock_irq+0x1d/0x30
[  614.018364]  ? __switch_to_asm+0x40/0x70
[  614.018369]  process_one_work+0x1eb/0x3c0
[  614.018372]  worker_thread+0x2d/0x3d0
[  614.018375]  ? process_one_work+0x3c0/0x3c0
[  614.018379]  kthread+0x112/0x130
[  614.018382]  ? kthread_flush_work_fn+0x10/0x10
[  614.018386]  ret_from_fork+0x35/0x40
```

**Comment by SirCmpwn** [comment]
Please report nouveau bugs to nouveau.
