### ISSUE TITLE
mpv segfault with wayland backend

### ISSUE THREAD

**Issue by Rikorose** [swaywm/sway#2359]
I'm getting segfaults when skipping the video to a specific time. With xwayland this works fine.

I don't know if this is a wayland

```
[I][rik@T450 ~]$ mpv https://www.youtube.com/watch?v=FcL-VdnmmE8
Playing: https://www.youtube.com/watch?v=FcL-VdnmmE8
 (+) Video --vid=1 (*) (h264 1920x1080 24.000fps)
 (+) Audio --aid=1 --alang=und (*) 'DASH audio' (aac 2ch 44100Hz) (external)
AO: [pulse] 44100Hz stereo 2ch float
Using hardware decoding (vaapi).
VO: [gpu] 1920x1080 vaapi[nv12]
Segmentation fault (core dumped)
[I][rik@T450 ~]$ coredumpctl gdb
           PID: 10226 (mpv)
           UID: 1000 (rik)
           GID: 1001 (rik)
        Signal: 11 (SEGV)
     Timestamp: Thu 2018-07-26 10:14:29 CEST (57s ago)
  Command Line: mpv https://www.youtube.com/watch?v=FcL-VdnmmE8
    Executable: /usr/bin/mpv
 Control Group: /user.slice/user-1000.slice/session-8.scope
          Unit: session-8.scope
         Slice: user-1000.slice
       Session: 8
     Owner UID: 1000 (rik)
       Boot ID: 07338421336d4b90926a603a6858e177
    Machine ID: 9ada6c77f16845cea1d15a0707e6172f
      Hostname: T450
       Storage: /var/lib/systemd/coredump/core.mpv.1000.07338421336d4b90926a603a6858e177.10226.1532592869000000.lz4
       Message: Process 10226 (mpv) of user 1000 dumped core.
                
                Stack trace of thread 10242:
                #0  0x00007ff48b766e7b get_next_argument (libwayland-client.so.0)
                #1  0x00007ff48b76775a wl_argument_from_va_list (libwayland-client.so.0)
                #2  0x00007ff48b765151 wl_proxy_marshal (libwayland-client.so.0)
                #3  0x000055eb2e649dca vo_wayland_control (mpv)
                #4  0x000055eb2e62c6b4 wayland_egl_control (mpv)
                #5  0x000055eb2e6356b4 control (mpv)
                #6  0x000055eb2e630808 run_control (mpv)
                #7  0x000055eb2e59e192 mp_dispatch_queue_process (mpv)
                #8  0x000055eb2e632d46 vo_thread (mpv)
                #9  0x00007ff484a0b594 start_thread (libpthread.so.0)
                #10 0x00007ff4835510df __clone (libc.so.6)
                
                Stack trace of thread 10226:
                #0  0x00007ff484a1152c futex_wait_cancelable (libpthread.so.0)
                #1  0x000055eb2e59e11d mp_dispatch_queue_process (mpv)
                #2  0x000055eb2e5d15cc mp_wait_events (mpv)
                #3  0x000055eb2e5d31f0 run_playloop (mpv)
                #4  0x000055eb2e5c8f90 mp_play_files (mpv)
                #5  0x000055eb2e5c9c05 mpv_main (mpv)
                #6  0x00007ff48347a24b __libc_start_main (libc.so.6)
                #7  0x000055eb2e55ae2a _start (mpv)
                
                Stack trace of thread 10238:
                #0  0x00007ff484a1187a futex_abstimed_wait_cancelable (libpthread.so.0)
                #1  0x000055eb2e5da401 cache_wakeup_and_wait (mpv)
                #2  0x000055eb2e5dadbb cache_fill_buffer (mpv)
                #3  0x000055eb2e5dfda3 stream_read_unbuffered (mpv)
                #4  0x000055eb2e5849cb mp_read (mpv)
                #5  0x00007ff488cf6473 read_packet_wrapper (libavformat.so.58)
                #6  0x00007ff488cf719c fill_buffer (libavformat.so.58)
                #7  0x00007ff488cf80ad avio_read (libavformat.so.58)
                #8  0x00007ff488e03711 append_packet_chunked (libavformat.so.58)
                #9  0x00007ff488d6256f mov_read_packet (libavformat.so.58)
                #10 0x00007ff488e07782 ff_read_packet (libavformat.so.58)
                #11 0x00007ff488e07dfd read_frame_internal (libavformat.so.58)
                #12 0x00007ff488e08b98 av_read_frame (libavformat.so.58)
                #13 0x000055eb2e585857 demux_lavf_fill_buffer (mpv)
                #14 0x000055eb2e57e056 thread_work (mpv)
                #15 0x000055eb2e57e361 demux_thread (mpv)
                #16 0x00007ff484a0b594 start_thread (libpthread.so.0)
                #17 0x00007ff4835510df __clone (libc.so.6)
                
                Stack trace of thread 10232:
                #0  0x00007ff484a1187a futex_abstimed_wait_cancelable (libpthread.so.0)
                #1  0x000055eb2e5b2d83 wait_wakeup (mpv)
                #2  0x000055eb2e5b4e0b mpv_wait_event (mpv)
                #3  0x000055eb2e5ce655 script_wait_event (mpv)
                #4  0x00007ff4838221fd luaD_precall (liblua-5.1.so)
                #5  0x00007ff48382d07d luaV_execute (liblua-5.1.so)
                #6  0x00007ff48382276d luaD_call (liblua-5.1.so)
                #7  0x00007ff48381e3e9 lua_call (liblua-5.1.so)
                #8  0x000055eb2e5cd6fd load_scripts (mpv)
                #9  0x00007ff4838221fd luaD_precall (liblua-5.1.so)
                #10 0x00007ff483822738 luaD_call (liblua-5.1.so)
                #11 0x00007ff483821a66 luaD_rawrunprotected (liblua-5.1.so)
                #12 0x00007ff483822901 luaD_pcall (liblua-5.1.so)
                #13 0x00007ff48381e47c lua_pcall (liblua-5.1.so)
                #14 0x000055eb2e5cf2b6 run_lua (mpv)
                #15 0x00007ff4838221fd luaD_precall (liblua-5.1.so)
                #16 0x00007ff483822738 luaD_call (liblua-5.1.so)
                #17 0x00007ff483821a66 luaD_rawrunprotected (liblua-5.1.so)
                #18 0x00007ff483822901 luaD_pcall (liblua-5.1.so)
                #19 0x00007ff48381e50b lua_cpcall (liblua-5.1.so)
                #20 0x000055eb2e5cc1e1 load_lua (mpv)
                #21 0x000055eb2e5d4dfb script_thread (mpv)
                #22 0x00007ff484a0b594 start_thread (libpthread.so.0)
                #23 0x00007ff4835510df __clone (libc.so.6)
                
                Stack trace of thread 10240:
                #0  0x00007ff483546659 __GI___poll (libc.so.6)
                #1  0x00007ff488da2c90 ff_network_wait_fd (libavformat.so.58)
                #2  0x00007ff488da2cfa ff_network_wait_fd_timeout (libavformat.so.58)
                #3  0x00007ff488df94f7 tcp_read (libavformat.so.58)
                #4  0x00007ff488cf5e5a ffurl_read (libavformat.so.58)
                #5  0x00007ff488dfc53a gnutls_url_pull (libavformat.so.58)
                #6  0x00007ff47da12b60 _gnutls_io_read_buffered (libgnutls.so.30)
                #7  0x00007ff47da0dd91 _gnutls_recv_in_buffers (libgnutls.so.30)
                #8  0x00007ff47da0f134 _gnutls_recv_int (libgnutls.so.30)
                #9  0x00007ff488dfc506 tls_read (libavformat.so.58)
                #10 0x00007ff488cf5e5a ffurl_read (libavformat.so.58)
                #11 0x00007ff488d35216 http_buf_read (libavformat.so.58)
                #12 0x00007ff488d382fa http_read_stream (libavformat.so.58)
                #13 0x00007ff488d387d4 http_read (libavformat.so.58)
                #14 0x00007ff488cf5e5a ffurl_read (libavformat.so.58)
                #15 0x00007ff488cf6473 read_packet_wrapper (libavformat.so.58)
                #16 0x00007ff488cf719c fill_buffer (libavformat.so.58)
                #17 0x00007ff488cf8284 avio_read_partial (libavformat.so.58)
                #18 0x000055eb2e5e95b6 fill_buffer (mpv)
                #19 0x000055eb2e5dfda3 stream_read_unbuffered (mpv)
                #20 0x000055eb2e5db361 cache_thread (mpv)
                #21 0x00007ff484a0b594 start_thread (libpthread.so.0)
                #22 0x00007ff4835510df __clone (libc.so.6)
                
                Stack trace of thread 10231:
                #0  0x00007ff484a1187a futex_abstimed_wait_cancelable (libpthread.so.0)
                #1  0x000055eb2e5b2d83 wait_wakeup (mpv)
                #2  0x000055eb2e5b4e0b mpv_wait_event (mpv)
                #3  0x000055eb2e5ce655 script_wait_event (mpv)
                #4  0x00007ff4838221fd luaD_precall (liblua-5.1.so)
                #5  0x00007ff48382d07d luaV_execute (liblua-5.1.so)
                #6  0x00007ff48382276d luaD_call (liblua-5.1.so)
                #7  0x00007ff48381e3e9 lua_call (liblua-5.1.so)
                #8  0x000055eb2e5cd6fd load_scripts (mpv)
                #9  0x00007ff4838221fd luaD_precall (liblua-5.1.so)
                #10 0x00007ff483822738 luaD_call (liblua-5.1.so)
                #11 0x00007ff483821a66 luaD_rawrunprotected (liblua-5.1.so)
                #12 0x00007ff483822901 luaD_pcall (liblua-5.1.so)
                #13 0x00007ff48381e47c lua_pcall (liblua-5.1.so)
                #14 0x000055eb2e5cf2b6 run_lua (mpv)
                #15 0x00007ff4838221fd luaD_precall (liblua-5.1.so)
                #16 0x00007ff483822738 luaD_call (liblua-5.1.so)
                #17 0x00007ff483821a66 luaD_rawrunprotected (liblua-5.1.so)
                #18 0x00007ff483822901 luaD_pcall (liblua-5.1.so)
                #19 0x00007ff48381e50b lua_cpcall (liblua-5.1.so)
                #20 0x000055eb2e5cc1e1 load_lua (mpv)
                #21 0x000055eb2e5d4dfb script_thread (mpv)
                #22 0x00007ff484a0b594 start_thread (libpthread.so.0)
                #23 0x00007ff4835510df __clone (libc.so.6)
                
                Stack trace of thread 10244:
                #0  0x00007ff484a1152c futex_wait_cancelable (libpthread.so.0)
                #1  0x000055eb2e5725e0 playthread (mpv)
                #2  0x00007ff484a0b594 start_thread (libpthread.so.0)
                #3  0x00007ff4835510df __clone (libc.so.6)
                
                Stack trace of thread 10243:
                #0  0x00007ff483546659 __GI___poll (libc.so.6)
                #1  0x00007ff4873c8e35 poll_func (libpulse.so.0)
                #2  0x00007ff4873ba418 pa_mainloop_poll (libpulse.so.0)
                #3  0x00007ff4873baa62 pa_mainloop_iterate (libpulse.so.0)
                #4  0x00007ff4873bab10 pa_mainloop_run (libpulse.so.0)
                #5  0x00007ff4873c8d7d thread (libpulse.so.0)
                #6  0x00007ff47c45b9ac internal_thread_func (libpulsecommon-12.0.so)
                #7  0x00007ff484a0b594 start_thread (libpthread.so.0)
                #8  0x00007ff4835510df __clone (libc.so.6)
                
                Stack trace of thread 10230:
                #0  0x00007ff484a11f8c futex_wake (libpthread.so.0)
                #1  0x000055eb2e59e45f mp_dispatch_unlock (mpv)
                #2  0x000055eb2e5b57cd mpv_get_property (mpv)
                #3  0x000055eb2e5cdce5 script_get_property (mpv)
                #4  0x00007ff4838221fd luaD_precall (liblua-5.1.so)
                #5  0x00007ff48382d07d luaV_execute (liblua-5.1.so)
                #6  0x00007ff48382276d luaD_call (liblua-5.1.so)
                #7  0x00007ff48381e3e9 lua_call (liblua-5.1.so)
                #8  0x000055eb2e5cd6fd load_scripts (mpv)
                #9  0x00007ff4838221fd luaD_precall (liblua-5.1.so)
                #10 0x00007ff483822738 luaD_call (liblua-5.1.so)
                #11 0x00007ff483821a66 luaD_rawrunprotected (liblua-5.1.so)
                #12 0x00007ff483822901 luaD_pcall (liblua-5.1.so)
                #13 0x00007ff48381e47c lua_pcall (liblua-5.1.so)
                #14 0x000055eb2e5cf2b6 run_lua (mpv)
                #15 0x00007ff4838221fd luaD_precall (liblua-5.1.so)
                #16 0x00007ff483822738 luaD_call (liblua-5.1.so)
                #17 0x00007ff483821a66 luaD_rawrunprotected (liblua-5.1.so)
                #18 0x00007ff483822901 luaD_pcall (liblua-5.1.so)
                #19 0x00007ff48381e50b lua_cpcall (liblua-5.1.so)
                #20 0x000055eb2e5cc1e1 load_lua (mpv)
                #21 0x000055eb2e5d4dfb script_thread (mpv)
                #22 0x00007ff484a0b594 start_thread (libpthread.so.0)
                #23 0x00007ff4835510df __clone (libc.so.6)
                
                Stack trace of thread 10229:
                #0  0x00007ff483546659 __GI___poll (libc.so.6)
                #1  0x000055eb2e6517c4 terminal_thread (mpv)
                #2  0x00007ff484a0b594 start_thread (libpthread.so.0)
                #3  0x00007ff4835510df __clone (libc.so.6)
                
                Stack trace of thread 10241:
                #0  0x00007ff484a1187a futex_abstimed_wait_cancelable (libpthread.so.0)
                #1  0x000055eb2e5da401 cache_wakeup_and_wait (mpv)
                #2  0x000055eb2e5dadbb cache_fill_buffer (mpv)
                #3  0x000055eb2e5dfda3 stream_read_unbuffered (mpv)
                #4  0x000055eb2e5849cb mp_read (mpv)
                #5  0x00007ff488cf6473 read_packet_wrapper (libavformat.so.58)
                #6  0x00007ff488cf719c fill_buffer (libavformat.so.58)
                #7  0x00007ff488cf80ad avio_read (libavformat.so.58)
                #8  0x00007ff488e03711 append_packet_chunked (libavformat.so.58)
                #9  0x00007ff488d6256f mov_read_packet (libavformat.so.58)
                #10 0x00007ff488e07782 ff_read_packet (libavformat.so.58)
                #11 0x00007ff488e07dfd read_frame_internal (libavformat.so.58)
                #12 0x00007ff488e08b98 av_read_frame (libavformat.so.58)
                #13 0x000055eb2e585857 demux_lavf_fill_buffer (mpv)
                #14 0x000055eb2e57e056 thread_work (mpv)
                #15 0x000055eb2e57e361 demux_thread (mpv)
                #16 0x00007ff484a0b594 start_thread (libpthread.so.0)
                #17 0x00007ff4835510df __clone (libc.so.6)
                
                Stack trace of thread 10237:
                #0  0x00007ff483546659 __GI___poll (libc.so.6)
                #1  0x00007ff488da2c90 ff_network_wait_fd (libavformat.so.58)
                #2  0x00007ff488da2cfa ff_network_wait_fd_timeout (libavformat.so.58)
                #3  0x00007ff488df94f7 tcp_read (libavformat.so.58)
                #4  0x00007ff488cf5e5a ffurl_read (libavformat.so.58)
                #5  0x00007ff488dfc53a gnutls_url_pull (libavformat.so.58)
                #6  0x00007ff47da12b60 _gnutls_io_read_buffered (libgnutls.so.30)
                #7  0x00007ff47da0dd91 _gnutls_recv_in_buffers (libgnutls.so.30)
                #8  0x00007ff47da0f134 _gnutls_recv_int (libgnutls.so.30)
                #9  0x00007ff488dfc506 tls_read (libavformat.so.58)
                #10 0x00007ff488cf5e5a ffurl_read (libavformat.so.58)
                #11 0x00007ff488d35216 http_buf_read (libavformat.so.58)
                #12 0x00007ff488d382fa http_read_stream (libavformat.so.58)
                #13 0x00007ff488d387d4 http_read (libavformat.so.58)
                #14 0x00007ff488cf5e5a ffurl_read (libavformat.so.58)
                #15 0x00007ff488cf6473 read_packet_wrapper (libavformat.so.58)
                #16 0x00007ff488cf719c fill_buffer (libavformat.so.58)
                #17 0x00007ff488cf8284 avio_read_partial (libavformat.so.58)
                #18 0x000055eb2e5e95b6 fill_buffer (mpv)
                #19 0x000055eb2e5dfda3 stream_read_unbuffered (mpv)
                #20 0x000055eb2e5db361 cache_thread (mpv)
                #21 0x00007ff484a0b594 start_thread (libpthread.so.0)
                #22 0x00007ff4835510df __clone (libc.so.6)

GNU gdb (GDB) Fedora 8.1-23.fc28
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/mpv...Reading symbols from /usr/bin/mpv...(no debugging symbols found)...done.
(no debugging symbols found)...done.
[New LWP 10242]
[New LWP 10226]
[New LWP 10238]
[New LWP 10232]
[New LWP 10240]
[New LWP 10231]
[New LWP 10244]
[New LWP 10243]
[New LWP 10230]
[New LWP 10229]
[New LWP 10241]
[New LWP 10237]

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments

warning: Loadable section ".note.gnu.property" outside of ELF segments
Core was generated by `mpv https://www.youtube.com/watch?v=FcL-VdnmmE8'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  get_next_argument (signature=0x55 <error: Cannot access memory at address 0x55>, details=details@entry=0x7ff44382c590)
    at src/connection.c:437
437		for(; *signature; ++signature) {
[Current thread is 1 (Thread 0x7ff44382d700 (LWP 10242))]
Missing separate debuginfos, use: dnf debuginfo-install mpv-0.28.2-4.fc28.x86_64
[I](gdb) bt full
#0  0x00007ff48b766e7b in get_next_argument (signature=0x55 <error: Cannot access memory at address 0x55>, details=details@entry=0x7ff44382c590) at src/connection.c:437
#1  0x00007ff48b76775a in wl_argument_from_va_list (signature=<optimized out>, args=<optimized out>, count=<optimized out>, ap=0x7ff44382c5c8) at src/connection.c:500
        i = <optimized out>
        sig_iter = <optimized out>
        arg = {type = 96 '`', nullable = 0}
#2  0x00007ff48b765151 in wl_proxy_marshal (proxy=0x7ff43c2529c0, opcode=0) at src/wayland-client.c:787
        args = 
            {{i = 0, u = 0, f = 0, s = 0x0, o = 0x0, n = 0, a = 0x0, h = 0}, {i = 1, u = 1, f = 1, s = 0x1 <error: Cannot access memory at address 0x1>, o = 0x1, n = 1, a = 0x1, h = 1}, {i = 2, u = 2, f = 2, s = 0x7ff400000002 <error: Cannot access memory at address 0x7ff400000002>, o = 0x7ff400000002, n = 2, a = 0x7ff400000002, h = 2}, {i = -1955160196, u = 2339807100, f = -1955160196, s = 0x7ff48b769f7c "\374\342\377\377\334\343\377\377\334\343\377\377\334\343\377\377\334\343\377\377\324\342\377\377\334\343\377\377\324\342\377\377\324\342\377\377\334\343\377\377\334\343\377\377\334\343\377\377\334\343\377\377\264\343\377\377\374\342\377\377\334\343\377\377\334\343\377\377\334\343\377\377\374\342\377\377\334\343\377\377\224\343\377\377\070\350\377\377\270\346\377\377\270\346\377\377\270\346\377\377\270\346\377\377\360\347\377\377\270\346\377\377\210\350\377\377`\350\377\377\270\346\377\377\270\346\377\377\270\346\377\377\270\346\377\377\220\347\377\377X\347\377\377\270\346\377\377\270\346\377\377\270\346\377\377\360\346\377\377\270\346\377\377\230\346\377\377", o = 0x7ff48b769f7c, n = 2339807100, a = 0x7ff48b769f7c, h = -1955160196}, {i = 1132643968, u = 1132643968, f = 1132643968, s = 0x7ff44382c680 "\030", o = 0x7ff44382c680, n = 1132643968, a = 0x7ff44382c680, h = 1132643968}, {i = -33030656, u = 4261936640, f = -33030656, s = 0x2625d321fe07fe00 <error: Cannot access memory at address 0x2625d321fe07fe00>, o = 0x2625d321fe07fe00, n = 4261936640, a = 0x2625d321fe07fe00, h = -33030656}, {i = 1132644176, u = 1132644176, f = 1132644176, s = 0x7ff44382c750 "", o = 0x7ff44382c750, n = 1132644176, a = 0x7ff44382c750, h = 1132644176}, {i = 781161600, u = 781161600, f = 781161600, s = 0x55eb2e8f9480 "p\222d.\353U", o = 0x55eb2e8f9480, n = 781161600, a = 0x55eb2e8f9480, h = 781161600}, {i = 1019162688, u = 1019162688, f = 1019162688, s = 0x7ff43cbf3040 "\220\267\032\060\353U", o = 0x7ff43cbf3040, n = 1019162688, a = 0x7ff43cbf3040, h = 1019162688}, {i = -1955172581, u = 2339794715, f = -1955172581, s = 0x7ff48b766f1b <wl_closure_clear_fds+59> "\200<$hu\tC\307D\323\030\377\377\377\377I\203\302\001E9\023\177\335H\213D$\bdH3\004%(", o = 0x7ff48b766f1b <wl_closure_clear_fds+59>, n = 2339794715, a = 0x7ff48b766f1b <wl_closure_clear_fds+59>, h = -1955172581}, {i = 1132643957, u = 1132643957, f = 1132643957, s = 0x4382c675 <error: Cannot access memory at address 0x4382c675>, o = 0x4382c675, n = 1132643957, a = 0x4382c675, h = 1132643957}, {i = -33030656, u = 4261936640, f = -33030656, s = 0x2625d321fe07fe00 <error: Cannot access memory at address 0x2625d321fe07fe00>, o = 0x2625d321fe07fe00, n = 4261936640, a = 0x2625d321fe07fe00, h = -33030656}, {i = 781161600, u = 781161600, f = 781161600, s = 0x55eb2e8f9480 "p\222d.\353U", o = 0x55eb2e8f9480, n = 781161600, a = 0x55eb2e8f9480, h = 781161600}, {i = 1009365264, u = 1009365264, f = 1009365264, s = 0x7ff43c29b110 "\300\243 <\364\177", o = 0x7ff43c29b110, n = 1009365264, a = 0x7ff43c29b110, h = 1009365264}, {i = 1, u = 1, f = [I]---Type <return> to continue, or q <return> to quit---
= 0x0, o = 0x0, n = 0, a = 0x0, h = 0}, {i = 1132644416, u = 1132644416, f = 1132644416, s = 0x7ff44382c840 "", o = 0x7ff44382c840, n = 1132644416, a = 0x7ff44382c840, h = 1132644416}, {i = 803030720, u = 803030720, f = 803030720, s = 0x55eb2fdd46c0 "@\206\217.\353U", o = 0x55eb2fdd46c0, n = 803030720, a = 0x55eb2fdd46c0, h = 803030720}, {i = 804304096, u = 804304096, f = 804304096, s = 0x55eb2ff0b4e0 "\320\ac.\353U", o = 0x55eb2ff0b4e0, n = 804304096, a = 0x55eb2ff0b4e0, h = 804304096}, {i = 777490803, u = 777490803, f = 777490803, s = 0x55eb2e579173 <mp_msg+147> "H\213D$\030dH3\004%(", o = 0x55eb2e579173 <mp_msg+147>, n = 777490803, a = 0x55eb2e579173 <mp_msg+147>, h = 777490803}}
        ap = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7ff44382c760, reg_save_area = 0x7ff44382c690}}
#3  0x000055eb2e649dca in vo_wayland_control ()
#4  0x000055eb2e62c6b4 in wayland_egl_control ()
#5  0x000055eb2e6356b4 in control ()
#6  0x000055eb2e630808 in run_control ()
#7  0x000055eb2e59e192 in mp_dispatch_queue_process ()
#8  0x000055eb2e632d46 in vo_thread ()
#9  0x00007ff484a0b594 in start_thread (arg=<optimized out>) at pthread_create.c:463
        pd = <optimized out>
        now = <optimized out>
        unwind_buf = 
              {cancel_jmp_buf = {{jmp_buf = {140687081395968, 3800016748757225113, 140722088321694, 140722088321695, 140722088321696, 0, -3795170970814804327, -3795032171131728231}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#10 0x00007ff4835510df in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

```

**Comment by emersion** [comment]
Fixed in mpv master.
