### ISSUE TITLE
Segfault at transaction_destroy

### ISSUE THREAD

**Issue by apreiml** [swaywm/sway#2462]
Got a segfault in transaction_destroy. I didn't interact with sway before the crash, just reading stuff on the monitor. Current master branch at commit b4887ba154ab0d659c560a21194c8ca43b953632

```
#0  0x000055bc0d37623b in transaction_destroy (transaction=0x55bc0dbcabc0) at ../../sway/desktop/transaction.c:71
#1  0x000055bc0d376a15 in transaction_progress_queue () at ../../sway/desktop/transaction.c:229
#2  0x000055bc0d376adc in transaction_progress_queue () at ../../sway/desktop/transaction.c:252
#3  0x000055bc0d376b4b in handle_timeout (data=0x55bc0dc0c4a0) at ../../sway/desktop/transaction.c:260
#4  0x00007f6f8cdbd35a in  () at /usr/lib/libwayland-server.so.0
#5  0x00007f6f8cdbda42 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#6  0x00007f6f8cdbc14c in wl_display_run () at /usr/lib/libwayland-server.so.0
#7  0x000055bc0d36fa7f in server_run (server=0x55bc0d3c1a00 <server>) at ../../sway/server.c:163
#8  0x000055bc0d36f202 in main (argc=1, argv=0x7ffe4990ac58) at ../../sway/main.c:439
```

**Comment by apreiml** [comment]
It's crashing when I use DrRacket 7.0-1. It crashes after a minute using it at no particular action. I just write some code and run it. This is the log of the last second:

```
Gdk-Message: 19:40:34.182: Window 0x558761974b10 is a temporary window without parent, application will not be able to position it on screen.
Gdk-Message: 19:40:34.182: Window 0x558761974b10 is a temporary window without parent, application will not be able to position it on screen.
2018-08-15 19:40:34 - [types/wlr_surface.c:621] New wlr_surface 0x55d51bcde6b0 (res 0x55d51bc51ec0)
2018-08-15 19:40:34 - [types/xdg_shell/wlr_xdg_surface.c:445] new xdg_surface 0x55d51bce6ee0 (res 0x55d51bc8b6e0)
2018-08-15 19:40:34 - [sway/desktop/xdg_shell.c:451] New xdg_shell toplevel title='' app_id='drracket'
2018-08-15 19:40:34 - [sway/tree/root.c:173] Looking up workspace for pid 2706
2018-08-15 19:40:34 - [sway/tree/container.c:453] Adding new view 0x55d51bcee310: to container 0x55d51bcece70 4 Chapter 2.scm - DrRacket*
2018-08-15 19:40:34 - [sway/ipc-server.c:324] Sending window::new event
2018-08-15 19:40:34 - [sway/tree/layout.c:110] Adding 0x55d51bcee310 (4, 0.000000x0.000000) to 0x55d51ba1e0f0 (3, 0.000000x0.000000)
2018-08-15 19:40:34 - [sway/ipc-server.c:324] Sending window::floating event
2018-08-15 19:40:34 - [sway/ipc-server.c:324] Sending window::focus event
2018-08-15 19:40:34 - [sway/ipc-server.c:324] Sending window::title event
2018-08-15 19:40:34 - [sway/tree/arrange.c:165] Arranging layout for 0x55d51ba1e0f0 (null) 0.000000x0.000000+0.000000,0.000000
2018-08-15 19:40:34 - [sway/desktop/transaction.c:293] Transaction 0x55d51bcec780 committing with 4 instructions
2018-08-15 19:40:34 - [sway/ipc-server.c:324] Sending window::focus event
2018-08-15 19:40:34 - [sway/ipc-server.c:324] Sending window::close event
2018-08-15 19:40:34 - [sway/tree/arrange.c:165] Arranging layout for 0x55d51ba1e0f0 (null) 0.000000x0.000000+0.000000,0.000000
2018-08-15 19:40:34 - [sway/desktop/transaction.c:258] Transaction 0x55d51bcec780 timed out (1 waiting)
2018-08-15 19:40:34 - [sway/desktop/transaction.c:145] Applying transaction 0x55d51bcec780
2018-08-15 19:40:34 - [sway/desktop/transaction.c:293] Transaction 0x55d51bd04350 committing with 4 instructions
2018-08-15 19:40:34 - [sway/desktop/transaction.c:339] Transaction 0x55d51bd04350 has nothing to wait for
2018-08-15 19:40:34 - [sway/desktop/transaction.c:145] Applying transaction 0x55d51bd04350
Gdk-Message: 19:40:34.405: Window 0x558761974b10 is a temporary window without parent, application will not be able to position it on screen.
Gdk-Message: 19:40:34.405: Window 0x558761974b10 is a temporary window without parent, application will not be able to position it on screen.
2018-08-15 19:40:34 - [types/wlr_surface.c:621] New wlr_surface 0x55d51bd070c0 (res 0x55d51bced760)
2018-08-15 19:40:34 - [types/xdg_shell/wlr_xdg_surface.c:445] new xdg_surface 0x55d51bce6ee0 (res 0x55d51bcdf670)
2018-08-15 19:40:34 - [sway/desktop/xdg_shell.c:451] New xdg_shell toplevel title='' app_id='drracket'
2018-08-15 19:40:34 - [sway/tree/root.c:173] Looking up workspace for pid 2706
2018-08-15 19:40:34 - [sway/tree/container.c:453] Adding new view 0x55d51bcee310: to container 0x55d51bcece70 4 Chapter 2.scm - DrRacket*
2018-08-15 19:40:34 - [sway/ipc-server.c:324] Sending window::new event
2018-08-15 19:40:34 - [sway/tree/layout.c:110] Adding 0x55d51bcee310 (4, 0.000000x0.000000) to 0x55d51ba1e0f0 (3, 0.000000x0.000000)
2018-08-15 19:40:34 - [sway/ipc-server.c:324] Sending window::floating event
2018-08-15 19:40:34 - [sway/ipc-server.c:324] Sending window::focus event
2018-08-15 19:40:34 - [sway/ipc-server.c:324] Sending window::title event
2018-08-15 19:40:34 - [sway/tree/arrange.c:165] Arranging layout for 0x55d51ba1e0f0 (null) 0.000000x0.000000+0.000000,0.000000
2018-08-15 19:40:34 - [sway/desktop/transaction.c:293] Transaction 0x55d51bcef0e0 committing with 4 instructions
2018-08-15 19:40:34 - [sway/desktop/transaction.c:370] Transaction 0x55d51bcef0e0 is ready
2018-08-15 19:40:34 - [sway/desktop/transaction.c:145] Applying transaction 0x55d51bcef0e0
2018-08-15 19:40:34 - [sway/ipc-server.c:324] Sending window::focus event
2018-08-15 19:40:34 - [sway/ipc-server.c:324] Sending window::close event
2018-08-15 19:40:34 - [sway/tree/arrange.c:165] Arranging layout for 0x55d51ba1e0f0 (null) 0.000000x0.000000+0.000000,0.000000
2018-08-15 19:40:34 - [sway/desktop/transaction.c:293] Transaction 0x55d51bcef0e0 committing with 4 instructions
2018-08-15 19:40:34 - [sway/desktop/transaction.c:339] Transaction 0x55d51bcef0e0 has nothing to wait for
2018-08-15 19:40:34 - [sway/desktop/transaction.c:145] Applying transaction 0x55d51bcef0e0
Gdk-Message: 19:40:34.676: Window 0x558761974b10 is a temporary window without parent, application will not be able to position it on screen.
Gdk-Message: 19:40:34.676: Window 0x558761974b10 is a temporary window without parent, application will not be able to position it on screen.
2018-08-15 19:40:34 - [types/wlr_surface.c:621] New wlr_surface 0x55d51bd056c0 (res 0x55d51bd01040)
2018-08-15 19:40:34 - [types/xdg_shell/wlr_xdg_surface.c:445] new xdg_surface 0x55d51bce6ee0 (res 0x55d51bced760)
2018-08-15 19:40:34 - [sway/desktop/xdg_shell.c:451] New xdg_shell toplevel title='' app_id='drracket'
2018-08-15 19:40:34 - [sway/tree/root.c:173] Looking up workspace for pid 2706
2018-08-15 19:40:34 - [sway/tree/container.c:453] Adding new view 0x55d51bd03d30: to container 0x55d51bcece70 4 Chapter 2.scm - DrRacket*
2018-08-15 19:40:34 - [sway/ipc-server.c:324] Sending window::new event
2018-08-15 19:40:34 - [sway/tree/layout.c:110] Adding 0x55d51bd03d30 (4, 0.000000x0.000000) to 0x55d51ba1e0f0 (3, 0.000000x0.000000)
2018-08-15 19:40:34 - [sway/ipc-server.c:324] Sending window::floating event
2018-08-15 19:40:34 - [sway/ipc-server.c:324] Sending window::focus event
2018-08-15 19:40:34 - [sway/ipc-server.c:324] Sending window::title event
2018-08-15 19:40:34 - [sway/tree/arrange.c:165] Arranging layout for 0x55d51ba1e0f0 (null) 0.000000x0.000000+0.000000,0.000000
2018-08-15 19:40:34 - [sway/desktop/transaction.c:293] Transaction 0x55d51bcef0e0 committing with 4 instructions
2018-08-15 19:40:34 - [sway/desktop/transaction.c:370] Transaction 0x55d51bcef0e0 is ready
2018-08-15 19:40:34 - [sway/desktop/transaction.c:145] Applying transaction 0x55d51bcef0e0
2018-08-15 19:40:34 - [sway/ipc-server.c:324] Sending window::focus event
2018-08-15 19:40:34 - [sway/ipc-server.c:324] Sending window::close event
2018-08-15 19:40:34 - [sway/tree/arrange.c:165] Arranging layout for 0x55d51ba1e0f0 (null) 0.000000x0.000000+0.000000,0.000000
2018-08-15 19:40:34 - [sway/desktop/transaction.c:293] Transaction 0x55d51bcef0e0 committing with 4 instructions
2018-08-15 19:40:34 - [sway/desktop/transaction.c:339] Transaction 0x55d51bcef0e0 has nothing to wait for
2018-08-15 19:40:34 - [sway/desktop/transaction.c:145] Applying transaction 0x55d51bcef0e0
Gdk-Message: 19:40:34.954: Window 0x558761974b10 is a temporary window without parent, application will not be able to position it on screen.
Gdk-Message: 19:40:34.955: Window 0x558761974b10 is a temporary window without parent, application will not be able to position it on screen.
2018-08-15 19:40:34 - [types/wlr_surface.c:621] New wlr_surface 0x55d51bd056c0 (res 0x55d51bc8b6e0)
2018-08-15 19:40:34 - [types/xdg_shell/wlr_xdg_surface.c:445] new xdg_surface 0x55d51bce6ee0 (res 0x55d51bce6d80)
2018-08-15 19:40:34 - [sway/desktop/xdg_shell.c:451] New xdg_shell toplevel title='' app_id='drracket'
2018-08-15 19:40:34 - [sway/tree/root.c:173] Looking up workspace for pid 2706
2018-08-15 19:40:34 - [sway/tree/container.c:453] Adding new view 0x55d51bd07370: to container 0x55d51bcece70 4 Chapter 2.scm - DrRacket*
2018-08-15 19:40:34 - [sway/ipc-server.c:324] Sending window::new event
2018-08-15 19:40:34 - [sway/tree/layout.c:110] Adding 0x55d51bd07370 (4, 0.000000x0.000000) to 0x55d51ba1e0f0 (3, 0.000000x0.000000)
2018-08-15 19:40:34 - [sway/ipc-server.c:324] Sending window::floating event
2018-08-15 19:40:34 - [sway/ipc-server.c:324] Sending window::focus event
2018-08-15 19:40:34 - [sway/ipc-server.c:324] Sending window::title event
2018-08-15 19:40:34 - [sway/tree/arrange.c:165] Arranging layout for 0x55d51ba1e0f0 (null) 0.000000x0.000000+0.000000,0.000000
2018-08-15 19:40:34 - [sway/desktop/transaction.c:293] Transaction 0x55d51bce79b0 committing with 4 instructions
2018-08-15 19:40:34 - [sway/ipc-server.c:324] Sending window::focus event
2018-08-15 19:40:34 - [sway/ipc-server.c:324] Sending window::close event
2018-08-15 19:40:34 - [sway/tree/arrange.c:165] Arranging layout for 0x55d51ba1e0f0 (null) 0.000000x0.000000+0.000000,0.000000
2018-08-15 19:40:35 - [sway/tree/arrange.c:252] Arranging output 'DP-1' at 0.000000,0.000000
2018-08-15 19:40:35 - [sway/tree/arrange.c:211] Usable area for ws: 1920x1177@0,23
2018-08-15 19:40:35 - [sway/tree/arrange.c:304] Removing gaps: not gapped: 0x55d51ba22b00
2018-08-15 19:40:35 - [sway/tree/arrange.c:337] Adding gaps: 0x55d51ba22b00
2018-08-15 19:40:35 - [sway/tree/arrange.c:220] Arranging workspace '2' at 0.000000, 23.000000
2018-08-15 19:40:35 - [sway/tree/arrange.c:165] Arranging layout for 0x55d51ba22b00 2 1920.000000x1177.000000+0.000000,23.000000
2018-08-15 19:40:35 - [sway/tree/arrange.c:304] Removing gaps: not gapped: 0x55d51bcece70
2018-08-15 19:40:35 - [sway/tree/arrange.c:48] Arranging 0x55d51ba22b00 horizontally
2018-08-15 19:40:35 - [sway/tree/arrange.c:54] Calculating arrangement for 0x55d51bcece70:4 (will scale 1920.000000 by 1.000000)
2018-08-15 19:40:35 - [sway/tree/arrange.c:337] Adding gaps: 0x55d51bcece70
2018-08-15 19:40:35 - [sway/tree/arrange.c:252] Arranging output 'eDP-1' at 1920.000000,0.000000
2018-08-15 19:40:35 - [sway/tree/arrange.c:211] Usable area for ws: 1920x1057@0,23
2018-08-15 19:40:35 - [sway/tree/arrange.c:304] Removing gaps: not gapped: 0x55d51ba14b10
2018-08-15 19:40:35 - [sway/tree/arrange.c:337] Adding gaps: 0x55d51ba14b10
2018-08-15 19:40:35 - [sway/tree/arrange.c:220] Arranging workspace '1' at 1920.000000, 23.000000
2018-08-15 19:40:35 - [sway/tree/arrange.c:165] Arranging layout for 0x55d51ba14b10 1 1920.000000x1057.000000+1920.000000,23.000000
2018-08-15 19:40:35 - [sway/desktop/transaction.c:258] Transaction 0x55d51bce79b0 timed out (1 waiting)
2018-08-15 19:40:35 - [sway/desktop/transaction.c:145] Applying transaction 0x55d51bce79b0
2018-08-15 19:40:35 - [sway/desktop/transaction.c:293] Transaction 0x55d51bcee3e0 committing with 3 instructions
2018-08-15 19:40:35 - [sway/desktop/transaction.c:339] Transaction 0x55d51bcee3e0 has nothing to wait for
2018-08-15 19:40:35 - [sway/desktop/transaction.c:145] Applying transaction 0x55d51bcee3e0
Gdk-Message: 19:40:35.173: Window 0x558761974b10 is a temporary window without parent, application will not be able to position it on screen.
Gdk-Message: 19:40:35.173: Window 0x558761974b10 is a temporary window without parent, application will not be able to position it on screen.
(EE) failed to read Wayland events: Broken pipe
failed to read Wayland events: Broken pipe
Gdk-Message: 19:40:35.508: Error reading events from display: Connection reset by peer
Exiting due to signal.
```

**Comment by RyanDwyer** [comment]
The latest commit in master (98ed05225e06618533fa0439fdc83463cb9f1d2e) might have fixed it - can you please try that?
