### ISSUE TITLE
Deferred commands causing crashes again

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/sway#2598]
*sigh*

```
#0  0x000055e354434690 in seat_set_focus_warp (seat=0x55e356585060, node=0x55e3567c1ac0, warp=true, notify=true) at ../sway/input/seat.c:723
        x = 960
        y = 550.5
        last_focus = 0x55e3568752c0
        last_workspace = 0x55e356873250
        new_workspace = 0x55e3567c1ac0
        container = 0x0
        last_output = 0x55e3565c2050
        new_output = 0x0
        new_output_last_ws = 0x0
#1  0x000055e354434743 in seat_set_focus (seat=0x55e356585060, node=0x55e3567c1ac0) at ../sway/input/seat.c:738
#2  0x000055e35445621f in view_execute_criteria (view=0x55e356873440) at ../sway/tree/view.c:416
        seat = 0x55e356585060
        prior_focus = 0x55e3567c1ac0
        criterias = 0x55e356872c30
#3  0x000055e3544567bf in view_map (view=0x55e356873440, wlr_surface=0x55e356874490) at ../sway/tree/view.c:558
        __func__ = "view_map"
        seat = 0x55e356585060
        ws = 0x55e356873250
        node = 0x55e356873250
        target_sibling = 0x0
#4  0x000055e35445c3d2 in handle_map (listener=0x55e356873688, data=0x55e356877550) at ../sway/desktop/xwayland.c:389
        xwayland_view = 0x55e356873440
        xsurface = 0x55e356877550
        view = 0x55e356873440
#5  0x00007efc49c0026e in wlr_signal_emit_safe (signal=signal@entry=0x55e3568776b8, data=data@entry=0x55e356877550) at ../util/signal.c:29
        pos = 0x55e356873688
        l = 0x55e356873688
        cursor = {link = {prev = 0x55e356873688, next = 0x7ffd7f26f5a0}, notify = 0x7efc49c001e0 <handle_noop>}
        end = {link = {prev = 0x7ffd7f26f580, next = 0x55e3568776b8}, notify = 0x7efc49c001e0 <handle_noop>}
#6  0x00007efc49bc95f6 in xwayland_surface_role_commit (wlr_surface=<optimized out>) at ../xwayland/xwm.c:686
        surface = 0x55e356877550
        __PRETTY_FUNCTION__ = "xwayland_surface_role_commit"
#7  0x00007efc49bf8402 in surface_commit_pending (surface=0x55e356874490) at ../types/wlr_surface.c:398
        invalid_buffer = true
        subsurface = 0x55e356874660
#8  0x00007efc49bf87f5 in surface_commit (client=<optimized out>, resource=<optimized out>) at ../types/wlr_surface.c:470
        surface = 0x55e356874490
        subsurface = <optimized out>
#9  0x00007efc480c71c8 in ffi_call_unix64 () at /home/sircmpwn/sources/sway/build/sway/../../../../../../lib64/libffi.so.6
#10 0x00007efc480c6c2a in ffi_call () at /home/sircmpwn/sources/sway/build/sway/../../../../../../lib64/libffi.so.6
#11 0x00007efc49c396ff in  () at /home/sircmpwn/sources/sway/build/sway/../../../../../../lib64/libwayland-server.so.0
#12 0x00007efc49c360a3 in  () at /home/sircmpwn/sources/sway/build/sway/../../../../../../lib64/libwayland-server.so.0
#13 0x00007efc49c37702 in wl_event_loop_dispatch () at /home/sircmpwn/sources/sway/build/sway/../../../../../../lib64/libwayland-server.so.0
#14 0x00007efc49c362ac in wl_display_run () at /home/sircmpwn/sources/sway/build/sway/../../../../../../lib64/libwayland-server.so.0
#15 0x000055e354426e6f in server_run (server=0x55e354479a40 <server>) at ../sway/server.c:165
#16 0x000055e3544265ea in main (argc=3, argv=0x7ffd7f26fda8) at ../sway/main.c:446
        verbose = 0
        debug = 1
        validate = 0
        long_options = 
            {{name = 0x55e354463a4c "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x55e354463a51 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x55e354463a58 "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x55e354463a61 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x55e354463a67 "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x55e354463a6f "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x55e354463a77 "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        config_path = 0x0
        usage = 0x55e3544635d0 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = -1
        suid = false
```

**Comment by SirCmpwn** [comment]
Can no longer reproduce this
