### ISSUE TITLE
Crash when resuming from suspend after external display is disabled

### ISSUE THREAD

**Issue by ggreer** [swaywm/sway#2626]
I recently updated sway & wlroots from master (sway 7a295e89329ed7f17b3e370d826305d8334dceaf & wlroots b2112686df29e5d7df7fbd10eedf94710d12756c). Now I'm experiencing crashes related to external monitors and suspend/resume. The way I've been able to consistently reproduce a crash is:

1. Start sway.
2. Plug in external monitor. Sway automatically starts outputting to it and initializes it with a new workspace.
3. Disable external monitor. In my case the command is `swaymsg output DP-1 disable`. Sway automatically moves all workspaces to my laptop's builtin display.
4. Unplug external monitor.
5. Suspend to RAM.
6. Resume from suspend. At this point sway has crashed. Here's a backtrace from a core dump:

```
Core was generated by `sway'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007faea88865d0 in drm_connector_cleanup (conn=0x55c17fda6960) at ../backend/drm/drm.c:1158
1158				if (!crtc->planes[i]) {
(gdb) bt
#0  0x00007faea88865d0 in drm_connector_cleanup (conn=0x55c17fda6960) at ../backend/drm/drm.c:1158
#1  0x00007faea8885d22 in scan_drm_connectors (drm=0x55c17f710ef0) at ../backend/drm/drm.c:1013
#2  0x00007faea8881c10 in drm_invalidated (listener=0x55c17f710fd0, data=0x55c17f707430) at ../backend/drm/backend.c:112
#3  0x00007faea88c8605 in wlr_signal_emit_safe (signal=0x55c17f721c20, data=0x55c17f707430) at ../util/signal.c:29
#4  0x00007faea888e2d5 in udev_event (fd=6, mask=1, data=0x55c17f707430) at ../backend/session/session.c:51
#5  0x00007faea8b00da2 in wl_event_loop_dispatch (loop=0x55c17f6fef40, timeout=timeout@entry=-1) at src/event-loop.c:641
#6  0x00007faea8aff9ba in wl_display_run (display=0x55c17f701500) at src/wayland-server.c:1260
#7  0x000055c17ecec819 in server_run (server=0x55c17ef3fd60 <server>) at ../sway/server.c:165
#8  0x000055c17ecebf94 in main (argc=1, argv=0x7ffdd6751cd8) at ../sway/main.c:446
```

I went back to commit 73423c988c864167447cd4292bacd3a248ef07f8 of wlroots (before https://github.com/swaywm/wlroots/pull/1229 was merged), but the crash still happens. My previous 
 (non-crashing) versions of sway & wlroots were a couple of weeks old, but I'm not sure what the specific shas were. If I find the version that doesn't crash, I'll update this issue.

**Comment by ggreer** [comment]
I built your disabled-crtc branch and no more crashes. Thanks!

**Comment by ggreer** [comment]
It looks like https://github.com/swaywm/sway/pull/2628 fixed my other crash. Closing this because all my crashes are fixed in master. Thanks!
