### ISSUE TITLE
segfault using back_and_forth just after startup

### ISSUE THREAD

**Issue by krgn** [swaywm/sway#2851]
Hi.

right after starting a sway session, issuing `back_and_forth` leads to a crash. I think its because there is no previous workspace to switch with, resulting `ws` to be `NULL` in `sway/commands/workspace.c:155`

```		
		} else if (strcasecmp(argv[0], "back_and_forth") == 0) {
			if (!(ws = workspace_by_name(argv[0])) && prev_workspace_name) {
				ws = workspace_create(NULL, prev_workspace_name);
			}
```

Here is a backtrace:

```
(gdb) bt full
#0  workspace_switch (workspace=0x0, no_auto_back_and_forth=no_auto_back_and_forth@entry=false) at ../sway/tree/workspace.c:394
        seat = 0x1411e70
        active_ws = 0x1433070
        next = <optimized out>
#1  0x000000000042fd6c in cmd_workspace (argc=1, argv=<optimized out>) at ../sway/commands/workspace.c:155
        no_auto_back_and_forth = false
        ws = <optimized out>
        error = <optimized out>
        output_location = <optimized out>
        gaps_location = <optimized out>
#2  0x000000000040c46a in execute_command (_exec=<optimized out>, seat=<optimized out>, seat@entry=0x0, con=con@entry=0x0) at ../sway/commands.c:321
        res = <optimized out>
        argc = 2
        argv = 0x144b2f0
        handler = 0x6584a0 <handlers+704>
        results = 0x0
        exec = 0x1437c80 "workspace back_and_forth"
        head = 0x0
        cmdlist = 0x0
        cmd = <optimized out>
        views = 0x0
        __func__ = "execute_command"
        node = 0x1433070
#3  0x0000000000426ba6 in seat_execute_command (seat=seat@entry=0x1411e70, binding=0x1398ae0) at ../sway/commands/bind.c:282
        results = <optimized out>
#4  0x00000000004234d9 in handle_keyboard_key (listener=0x1393e90, data=0x7ffcd8934020) at ../sway/input/keyboard.c:280
        keyboard = 0x1393e80
        seat = 0x1411e70
        wlr_seat = 0x1411fc0
        wlr_device = 0x11e8078
        event = 0x7ffcd8934020
        input_inhibited = false
        keycode = <optimized out>
        translated_keysyms = 0x1432f48
        translated_modifiers = 64
        translated_keysyms_len = <optimized out>
        raw_keysyms = 0x1432f48
        raw_modifiers = 64
        raw_keysyms_len = <optimized out>
        code_modifiers = <optimized out>
        handled = <optimized out>
        binding_released = 0x0
        binding = 0x1398ae0
#5  0x00007fed4b2e00dc in wlr_signal_emit_safe () from /nix/store/bpzsad1zl2vmi84y8z2wy45cn87j0ygx-wlroots-unstable-2018-10-11/lib/libwlroots.so.0
No symbol table info available.
#6  0x00007fed4b2d063e in wlr_keyboard_notify_key () from /nix/store/bpzsad1zl2vmi84y8z2wy45cn87j0ygx-wlroots-unstable-2018-10-11/lib/libwlroots.so.0
No symbol table info available.
#7  0x00007fed4b2e2306 in handle_x11_input_event () from /nix/store/bpzsad1zl2vmi84y8z2wy45cn87j0ygx-wlroots-unstable-2018-10-11/lib/libwlroots.so.0
No symbol table info available.
#8  0x00007fed4b2e1960 in x11_event () from /nix/store/bpzsad1zl2vmi84y8z2wy45cn87j0ygx-wlroots-unstable-2018-10-11/lib/libwlroots.so.0
No symbol table info available.
#9  0x00007fed4b51a542 in wl_event_loop_dispatch () from /nix/store/q6dxx22af29q1l0j7vfykqy6w33nrvcc-wayland-1.16.0/lib/libwayland-server.so.0
No symbol table info available.
#10 0x00007fed4b51915a in wl_display_run () from /nix/store/q6dxx22af29q1l0j7vfykqy6w33nrvcc-wayland-1.16.0/lib/libwayland-server.so.0
No symbol table info available.
#11 0x0000000000414ad5 in server_run (server=<optimized out>) at ../sway/server.c:174
No locals.
#12 0x000000000040b3ec in main (argc=<optimized out>, argv=<optimized out>) at ../sway/main.c:383
        verbose = 0
        debug = 0
        validate = 0
        long_options = {{name = 0x443695 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x445beb "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x44369a "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x4436a3 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x4435d1 "version", has_arg = 0,
            flag = 0x0, val = 118}, {name = 0x442778 "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x4436a9 "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        config_path = <optimized out>
        usage = 0x443848 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = <optimized out>
```

If `ws` is still `NULL`, it should probably return at that point, without calling `workspace_switch`.

**Comment by krgn** [comment]
Thanks! :+1:
