### ISSUE TITLE
sway segfaults on startup

### ISSUE THREAD

**Issue by m0rr1gan** [swaywm/sway#3462]
Sway segfaults when starting from a tty with default config file.

sway -v:
sway version 1.0-beta.2-218-g60220fce (Jan 18 2019, branch 'master')

sway -c /etc/sway/config -d:
https://ptpb.pw/3N5G

coredump gdb sway and bt full:
https://ptpb.pw/90TY

I am running the latest version of sway and wlroots.
https://github.com/swaywm/sway/pull/3460 does not fix this for me

**Comment by emersion** [comment]
Can you try https://github.com/swaywm/sway/pull/3463?

**Comment by emersion** [comment]
If it doesn't fix it, please run recompile sway with `meson build-asan -Db_sanitize=address && build-asan/sway/sway`

**Comment by mnd999** [comment]
Does temporarily commenting out your output lines fix it? I've had the same thing and that fixes it for me.
I am able to add them back in once sway is up and running.

**Comment by emersion** [comment]
@mnd999 Please try the PR if you can reproduce the crash.

**Comment by mnd999** [comment]
@emersion No, that patch doesn't help me either.

My backtrace:

```
Reading symbols from /home/mark/dev/sway/build/sway/sway...done.
[New LWP 2626]
[New LWP 2632]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `dev/sway/build/sway/sway'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000056339d1498ea in arrange_output (output=0x56339dd87100) at ../sway/tree/arrange.c:243
243		output->lx = output_box->x;
[Current thread is 1 (Thread 0x7eff316ef9c0 (LWP 2626))]
(gdb) bt
#0  0x000056339d1498ea in arrange_output (output=0x56339dd87100) at ../sway/tree/arrange.c:243
#1  0x000056339d119fb4 in arrange_layers (output=0x56339dd87100) at ../sway/desktop/layer_shell.c:180
#2  0x000056339d11c41d in handle_transform (listener=0x56339dd87218, data=0x56339dc83190)
    at ../sway/desktop/output.c:530
#3  0x00007eff33cd307e in wlr_signal_emit_safe (signal=0x56339dc83320, data=0x56339dc83190)
    at ../util/signal.c:29
#4  0x000056339d13181d in apply_output_config (oc=0x56339dc78b80, output=0x56339dd87100)
    at ../sway/config/output.c:226
#5  0x000056339d15529a in output_enable (output=0x56339dd87100, oc=0x56339dc78b80) at ../sway/tree/output.c:81
#6  0x000056339d11c80b in handle_new_output (listener=0x56339d176c58 <server+56>, data=0x56339dc83190)
    at ../sway/desktop/output.c:607
#7  0x00007eff33cd307e in wlr_signal_emit_safe (signal=0x56339db6c008, data=0x56339dc83190)
    at ../util/signal.c:29
#8  0x00007eff33cd307e in wlr_signal_emit_safe
    (signal=signal@entry=0x56339db721e8, data=data@entry=0x56339dc83190) at ../util/signal.c:29
#9  0x00007eff33c9c30d in scan_drm_connectors (drm=<optimized out>) at ../backend/drm/drm.c:1256
#10 0x00007eff33c99183 in backend_start (backend=<optimized out>) at ../backend/drm/backend.c:26
#11 0x00007eff33ca26d6 in multi_backend_start (wlr_backend=0x56339db6bfe0) at ../backend/multi/backend.c:31
#12 0x000056339d118b75 in server_start (server=0x56339d176c20 <server>) at ../sway/server.c:184
#13 0x000056339d1180a6 in main (argc=1, argv=0x7ffc6197bba8) at ../sway/main.c:378
```

**Comment by m0rr1gan** [comment]
> Can you try #3463?

This worked for me. Thanks!

**Comment by mnd999** [comment]
Same, thanks! :+1:
