### ISSUE TITLE
crash in render_containers_linear on switching displays

### ISSUE THREAD

**Issue by sanga** [swaywm/sway#3515]
steps to repro:

```
      sway output HDMI-A-1 enable
        sway output HDMI-A-1 background /home/tsampson/Wallpapers/cathedral_cove.jpg center
        sway output eDP-1 disable
```

Versions:

```
sway version 1.0-beta.2-268-g8b056cfc (Jan 23 2019, branch 'master')
c41d01306de59235256d96902cced49a8eef15e9
```

```
#0  0x0000560512134bfa in render_containers_linear (output=0x56051430aa80, damage=0x7ffe6cb55780, parent=0x7ffe6cb55640) at ../sway/desktop/render.c:675
        i = 0
#1  0x00005605121351cd in render_containers (output=0x56051430aa80, damage=0x7ffe6cb55780, parent=0x7ffe6cb55640) at ../sway/desktop/render.c:848
#2  0x0000560512135379 in render_workspace (output=0x56051430aa80, damage=0x7ffe6cb55780, ws=0x560514055980, focused=32) at ../sway/desktop/render.c:890
        data = {layout = L_NONE, box = {x = 0, y = 0, width = 0, height = 0}, children = 0x0, focused = 32, active_child = 0x0}
#3  0x0000560512135b9c in output_render (output=0x56051430aa80, when=0x7ffe6cb55770, damage=0x7ffe6cb55780) at ../sway/desktop/render.c:1037
        clear_color = {0.25, 0.25, 0.25, 1}
        nrects = 1
        rects = 0x7ffe6cb55780
        wlr_output = 0x560513f09dd0
        renderer = 0x560513ef5b20
        __PRETTY_FUNCTION__ = "output_render"
        workspace = 0x560514055980
        fullscreen_con = 0x0
        seat = 0x1
        focus = 0x7ffe00000002
        width = 1823823568
        height = 1
        transform = 32766
#4  0x0000560512131dda in damage_handle_frame (listener=0x56051430abf8, data=0x56051430ac40) at ../sway/desktop/output.c:377
        output = 0x56051430aa80
        now = {tv_sec = 27905, tv_nsec = 446922699}
        needs_swap = true
        damage = {extents = {x1 = 0, y1 = 0, x2 = 3840, y2 = 2160}, data = 0x0}
#5  0x00007f2b474ff4df in wlr_signal_emit_safe (signal=0x56051430aca0, data=0x56051430ac40) at ../util/signal.c:29
        pos = 0x56051430abf8
        l = 0x56051430abf8
        cursor = {link = {prev = 0x56051430abf8, next = 0x7ffe6cb557f0}, notify = 0x7f2b474ff429 <handle_noop>}
        end = {link = {prev = 0x7ffe6cb557d0, next = 0x56051430aca0}, notify = 0x7f2b474ff429 <handle_noop>}
#6  0x00007f2b474ecf9e in output_handle_frame (listener=0x56051430ad38, data=0x560513f09dd0) at ../types/wlr_output_damage.c:50
        output_damage = 0x56051430ac40
#7  0x00007f2b474ff4df in wlr_signal_emit_safe (signal=0x560513f09ef0, data=0x560513f09dd0) at ../util/signal.c:29
        pos = 0x56051430ad38
        l = 0x56051430ad38
        cursor = {link = {prev = 0x56051430ad38, next = 0x7ffe6cb55890}, notify = 0x7f2b474ff429 <handle_noop>}
        end = {link = {prev = 0x7ffe6cb55870, next = 0x560513f09ef0}, notify = 0x7f2b474ff429 <handle_noop>}
#8  0x00007f2b474efed1 in wlr_output_send_frame (output=0x560513f09dd0) at ../types/wlr_output.c:417
#9  0x00007f2b474b3624 in page_flip_handler (fd=9, seq=704626, tv_sec=27905, tv_usec=339350, data=0x560513f09dd0) at ../backend/drm/drm.c:1314
        conn = 0x560513f09dd0
        drm = 0x560513d64950
        present_time = {tv_sec = 27905, tv_nsec = 339350000}
        present_event = {output = 0x560513f09dd0, when = 0x7ffe6cb55910, seq = 704626, refresh = 33333333, flags = 7}
#10 0x00007f2b45c51b55 in drmHandleEvent () at /usr/lib/x86_64-linux-gnu/libdrm.so.2
#11 0x00007f2b474b36a9 in handle_drm_event (fd=9, mask=1, data=0x0) at ../backend/drm/drm.c:1324
        event = {version = 2, vblank_handler = 0x0, page_flip_handler = 0x7f2b474b34bb <page_flip_handler>, page_flip_handler2 = 0x0, sequence_handler = 0x0}
#12 0x00007f2b47542942 in wl_event_loop_dispatch () at /usr/lib/x86_64-linux-gnu/libwayland-server.so.0
#13 0x00007f2b4754156a in wl_display_run () at /usr/lib/x86_64-linux-gnu/libwayland-server.so.0
#14 0x000056051212ed1b in server_run (server=0x56051218ce20 <server>) at ../sway/server.c:201
#15 0x000056051212e2d0 in main (argc=1, argv=0x7ffe6cb56188) at ../sway/main.c:413
        verbose = 0
        debug = 0
        validate = 0
        allow_unsupported_gpu = 0
        long_options =
            {{name = 0x560512174d24 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x560512174d29 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x560512174d30 "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x560512174d39 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x560512174d3f "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x560512174d47 "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x560512174d4f "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x560512174d5e "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x560512174d6e "my-next-gpu-wont-be-nvidia", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        config_path = 0x0
        usage = 0x5605121748e0 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = -1```

**Comment by sanga** [comment]
Could be #3110 perhaps (sorry if this is a dupe)
