### ISSUE TITLE
Crash after closing nm-connection-editor and moving the mouse

### ISSUE THREAD

**Issue by Emantor** [swaywm/sway#3556]
Closed `nm-connection-editor` and moved the mouse afterwards. The surface seems to be total garbage.

```
#0  0x00005592195d4611 in surface_is_popup (surface=0x55921af3ec90) at ../sway/tree/container.c:348
        xdg_surface = 0x55921aefb6f0
#1  0x00005592195d474c in container_at
    (workspace=0x55921ab30090, lx=1095.0122844127277, ly=530.51595385286043, surface=0x7ffe5f62f880, sx=0x7ffe5f62f888, sy=0x7ffe5f62f890) at ../sway/tree/container.c:380
        c = 0x55921af36c30
        seat = 0x55921a9ce060
        focus = 0x55921af36c30
        is_floating = false
#2  0x00005592195b39d2 in node_at_coords
    (seat=0x55921a9ce060, lx=1095.0122844127277, ly=530.51595385286043, surface=0x7ffe5f62f880, sx=0x7ffe5f62f888, sy=0x7ffe5f62f890) at ../sway/input/cursor.c:140
        unmanaged = 0x55921a9cae70
        unmanaged_surface = 0x55921a9cae68
        wlr_output = 0x55921aa0cb70
        output = 0x55921a9d0d10
        ox = 1095.0122844127277
        oy = 530.51595385286043
        ws = 0x55921ab30090
        c = 0x15f62f880
#3  0x00005592195b3fa3 in cursor_rebase (cursor=0x55921a9ce560) at ../sway/input/cursor.c:281
        time_msec = 679432
        surface = 0x55921af3ec90
        sx = 133.01228441272769
        sy = 504.51595385286043
#4  0x00005592195a8d7a in transaction_apply (transaction=0x55921ab15af0) at ../sway/desktop/transaction.c:321
        seat = 0x55921a9ce060
#5  0x00005592195a8eb7 in transaction_progress_queue () at ../sway/desktop/transaction.c:355
        transaction = 0x55921ab15af0
#6  0x00005592195a9746 in transaction_commit_dirty () at ../sway/desktop/transaction.c:551
        transaction = 0x55921ab15af0
#7  0x00005592195b4681 in handle_cursor_motion (listener=0x55921a9ce5d0, data=0x7ffe5f62fb50)
    at ../sway/input/cursor.c:437
        cursor = 0x55921a9ce560
        event = 0x7ffe5f62fb50
        dx = 84.318594674302275
        dy = 21.308775284538349
        dx_unaccel = 115
        dy_unaccel = 29.0625
        surface = 0x55921af3ec90
        sx = 48.693689738425519
        sy = 483.20717856832209
        node = 0x55921af36c30
#8  0x00007fec1b7a2be9 in wlr_signal_emit_safe (signal=0x55921a9ce7c8, data=0x7ffe5f62fb50)
    at ../subprojects/wlroots/util/signal.c:29
        pos = 0x55921a9ce5d0
        l = 0x55921a9ce5d0
        cursor = {link = {prev = 0x55921a9ce5d0, next = 0x7ffe5f62fa60}, notify = 0x7fec1b7a2b33 <handle_noop>}
        end = {link = {prev = 0x7ffe5f62fa40, next = 0x55921a9ce7c8}, notify = 0x7fec1b7a2b33 <handle_noop>}
#9  0x00007fec1b78265f in handle_pointer_motion (listener=0x55921acb6210, data=0x7ffe5f62fb50)
    at ../subprojects/wlroots/types/wlr_cursor.c:351
        event = 0x7ffe5f62fb50
        device = 0x55921acb61e0
#10 0x00007fec1b7a2be9 in wlr_signal_emit_safe (signal=0x55921acb4f98, data=0x7ffe5f62fb50)
    at ../subprojects/wlroots/util/signal.c:29
        pos = 0x55921acb6210
        l = 0x55921acb6210
        cursor = {link = {prev = 0x55921acb6210, next = 0x7ffe5f62fb00}, notify = 0x7fec1b7a2b33 <handle_noop>}
        end = {link = {prev = 0x7ffe5f62fae0, next = 0x55921acb4f98}, notify = 0x7fec1b7a2b33 <handle_noop>}
#11 0x00007fec1b759ed7 in handle_pointer_motion (event=0x55921af30510, libinput_dev=0x55921ababef0)
    at ../subprojects/wlroots/backend/libinput/pointer.c:41
        wlr_dev = 0x55921aca9e60
        pevent = 0x55921af30510
        wlr_event = 
          {device = 0x55921aca9e60, time_msec = 3516678, delta_x = 84.318594674302275, delta_y = 21.308775284538349, unaccel_dx = 115, unaccel_dy = 29.0625}
#12 0x00007fec1b75989f in handle_libinput_event (backend=0x55921a82b130, event=0x55921af30510)
    at ../subprojects/wlroots/backend/libinput/events.c:240
        libinput_dev = 0x55921ababef0
        event_type = LIBINPUT_EVENT_POINTER_MOTION
#13 0x00007fec1b7586c7 in handle_libinput_readable (fd=25, mask=1, _backend=0x55921a82b130)
    at ../subprojects/wlroots/backend/libinput/backend.c:41
        backend = 0x55921a82b130
        event = 0x55921af30510
#14 0x00007fec1b0eb702 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#15 0x00007fec1b0ea2ac in wl_display_run () at /usr/lib/libwayland-server.so.0
#16 0x00005592195a0e6c in server_run (server=0x559219601d20 <server>) at ../sway/server.c:212
#17 0x00005592195a03b5 in main (argc=1, argv=0x7ffe5f62ff68) at ../sway/main.c:388
        verbose = 0
        debug = 0
        validate = 0
        allow_unsupported_gpu = 0
        long_options = 
            {{name = 0x5592195e8d24 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x5592195e8d29 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x5592195e8d30 "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x5592195e8d39 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x5592195e8d3f "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x5592195e8d47 "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x5592195e8d4f "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x5592195e8d5e "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x5592195e8d6e "my-next-gpu-wont-be-nvidia", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        config_path = 0x0
        usage = 0x5592195e8928 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = -1
```

**Comment by RedSoxFan** [comment]
I'm not able to reproduce this. It looks like the same trace as #3311.

Are you still able to reproduce? If so, can you please provide a debug log and your config?

**Comment by Emantor** [comment]
No, this was hard to reproduce even without the fix. I also assume this is fixed, will reopen if I see this again.
