### ISSUE TITLE
Segfault in view_from_wlr_xwayland_surface (xsurface=0x0) when closing window after moving workspace

### ISSUE THREAD

**Issue by Hello71** [swaywm/sway#3599]
* Sway Version: 1.0-rc1-24-ga3c53148

* Debug Log: Available upon request

* Configuration File: Available upon request. Notable options: `for_window [class="FTL" instance="FTL"] fullscreen`

* Steps to reproduce:
  1. start Faster Than Light
  2. move FTL to a different workspace (I used a keybinding)
  3. ~begin a new game~
  4. ~return to the hangar by Esc then "HANGAR"~
  5. ~return to the main menu with Esc~
  6. quit by "QUIT"

* Stack Trace:

```
#0  0x000055d26a5664a0 in view_from_wlr_xwayland_surface (xsurface=0x0) at ../sway/sway/desktop/xwayland.c:570
#1  0x000055d26a561eed in view_from_wlr_surface (wlr_surface=<optimized out>) at ../sway/sway/tree/view.c:866
        xsurface = <optimized out>
        role = <optimized out>
#2  0x000055d26a543417 in warp_to_constraint_cursor_hint (cursor=<optimized out>, cursor=<optimized out>) at ../sway/sway/input/cursor.c:1407
        sy = 956
        lx = <optimized out>
        sx = 1634
        view = <optimized out>
        con = <optimized out>
        ly = <optimized out>
        constraint = <optimized out>
#3  0x000055d26a5434b4 in handle_constraint_destroy (listener=<optimized out>, data=0x55d26b9b45b0) at ../sway/sway/input/cursor.c:1427
        sway_constraint = 0x55d26b8b9b60
        constraint = 0x55d26b9b45b0
        seat = <optimized out>
        cursor = 0x55d26b753fd0
#4  0x00007f3896059a6e in wlr_signal_emit_safe (signal=signal@entry=0x55d26b9b46a8, data=data@entry=0x55d26b9b45b0) at ../util/signal.c:29
        pos = 0x55d26b8b9b68
        l = 0x55d26b8b9b68
        cursor = {link = {prev = 0x55d26b9b46a8, next = 0x7ffe16a2d5f0}, notify = 0x7f38960599e0 <handle_noop>}
        end = {link = {prev = 0x7ffe16a2d5d0, next = 0x55d26b9b46a8}, notify = 0x7f38960599e0 <handle_noop>}
#5  0x00007f389604f910 in pointer_constraint_destroy (constraint=0x55d26b9b45b0) at ../types/wlr_pointer_constraints_v1.c:49
#6  0x00007f3896099c7f in  () at /usr/lib/libwayland-server.so.0
#7  0x00007f3896099cef in wl_resource_destroy () at /usr/lib/libwayland-server.so.0
#8  0x00007f38951066d0 in ffi_call_unix64 () at /usr/lib/libffi.so.6
#9  0x00007f38951060a0 in ffi_call () at /usr/lib/libffi.so.6
#10 0x00007f389609d6ff in  () at /usr/lib/libwayland-server.so.0
#11 0x00007f389609a0a3 in  () at /usr/lib/libwayland-server.so.0
#12 0x00007f389609b702 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#13 0x00007f389609a2ac in wl_display_run () at /usr/lib/libwayland-server.so.0
#14 0x000055d26a52a531 in main (argc=1, argv=0x7ffe16a2dd88) at ../sway/sway/main.c:389
        verbose = 0
        debug = 0
        validate = 0
        allow_unsupported_gpu = 0
        long_options =
            {{name = 0x55d26a56c357 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x55d26a56f08d "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x55d26a56c35c "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x55d26a56c365 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x55d26a56c2bb "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x55d26a56b40e "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x55d26a56c36b "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x55d26a56c37a "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x55d26a56c38a "my-next-gpu-wont-be-nvidia", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        config_path = 0x0
        usage = 0x55d26a56c698 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = <optimized out>
```

**Comment by ainola** [comment]
Same issue here when using the latest sway-git and wlroots-git version on archlinux. In my case I had been playing _Full Throttle Remastered_ under xwayland and the whole session blows up when I exit the game.

```
                Stack trace of thread 7189:
                #0  0x0000558e97a5cba5 view_from_wlr_xwayland_surface (sway)
                #1  0x0000558e97a57131 view_from_wlr_surface (sway)
                #2  0x0000558e97a3292d warp_to_constraint_cursor_hint (sway)
                #3  0x0000558e97a32a1c handle_constraint_destroy (sway)
                #4  0x00007f7ab030b2ce wlr_signal_emit_safe (libwlroots.so.0)
                #5  0x00007f7ab0300ac0 pointer_constraint_destroy (libwlroots.so.0)
                #6  0x00007f7ab034bc7f n/a (libwayland-server.so.0)
                #7  0x00007f7ab034bcef wl_resource_destroy (libwayland-server.so.0)
                #8  0x00007f7aaf3b76d0 ffi_call_unix64 (libffi.so.6)
                #9  0x00007f7aaf3b70a0 ffi_call (libffi.so.6)
                #10 0x00007f7ab034f6ff n/a (libwayland-server.so.0)
                #11 0x00007f7ab034c0a3 n/a (libwayland-server.so.0)
                #12 0x00007f7ab034d702 wl_event_loop_dispatch (libwayland-server.so.0)
                #13 0x00007f7ab034c2ac wl_display_run (libwayland-server.so.0)
                #14 0x0000558e97a1bfb3 server_run (sway)
                #15 0x0000558e97a1b4fc main (sway)
                #16 0x00007f7aafe8b223 __libc_start_main (libc.so.6)
                #17 0x0000558e97a0ddce _start (sway)
                
                Stack trace of thread 7218:
                #0  0x00007f7aafe53afc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00007f7aad4f3c84 n/a (i965_dri.so)
                #2  0x00007f7aad4f39a8 n/a (i965_dri.so)
                #3  0x00007f7aafe4da9d start_thread (libpthread.so.0)
                #4  0x00007f7aaff62b23 __clone (libc.so.6)
```
