### ISSUE TITLE
segfault in workspace_get_initial_output if I swaylock shortly after starting sway

### ISSUE THREAD

**Issue by sanga** [swaywm/sway#3616]
steps to repro
1. log in to sway through gdm
2. immediately lock the screen with swaylock

stacktrace

```
Reading symbols from /usr/local/bin/sway...done.
[New LWP 22305]
[New LWP 22309]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `sway'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055746ebb0dd9 in workspace_get_initial_output (name=0x5574704bc470 "6") at ../sway/tree/workspace.c:48
48		return focus->output;
[Current thread is 1 (Thread 0x7f364a898a80 (LWP 22305))]
#0  0x000055746ebb0dd9 in workspace_get_initial_output (name=0x5574704bc470 "6") at ../sway/tree/workspace.c:48
        wsc = 0x0
        seat = 0x5574704afe00
        focus = 0x0
#1  0x000055746ebb0ed9 in workspace_create (output=0x0, name=0x5574704bc470 "6") at ../sway/tree/workspace.c:69
        ws = 0x5574704bc470
#2  0x000055746ebaf153 in select_workspace (view=0x5574707697f0) at ../sway/tree/view.c:484
        criteria = 0x5574704bc3d0
        i = 0
        seat = 0x5574704afe00
        criterias = 0x55747058d2f0
        ws = 0x0
        pid = 1886592496
        node = 0x7ffe1b3fb3d0
        __PRETTY_FUNCTION__ = "select_workspace"
#3  0x000055746ebaf436 in view_map (view=0x5574707697f0, wlr_surface=0x557470758fe0, fullscreen=false, decoration=false) at ../sway/tree/view.c:568
        __PRETTY_FUNCTION__ = "view_map"
        seat = 0x5574704afe00
        ws = 0x55746ebb477d <wl_signal_add+38>
        node = 0x5574707698e0
        target_sibling = 0x55747030d158
#4  0x000055746ebb56b3 in handle_map (listener=0x557470769a18, data=0x5574706d7a10) at ../sway/desktop/xwayland.c:418
        xwayland_view = 0x5574707697f0
        xsurface = 0x5574706d7a10
        view = 0x5574707697f0
#5  0x00007f364dc6ace5 in wlr_signal_emit_safe (signal=0x5574706d7b78, data=0x5574706d7a10) at ../util/signal.c:29
        pos = 0x557470769a18
        l = 0x557470769a18
        cursor = {link = {prev = 0x557470769a18, next = 0x7ffe1b3fb4a0}, notify = 0x7f364dc6ac2f <handle_noop>}
        end = {link = {prev = 0x7ffe1b3fb480, next = 0x5574706d7b78}, notify = 0x7f364dc6ac2f <handle_noop>}
#6  0x00007f364dc12eeb in xwayland_surface_role_commit (wlr_surface=0x557470758fe0) at ../xwayland/xwm.c:703
        __PRETTY_FUNCTION__ = "xwayland_surface_role_commit"
        surface = 0x5574706d7a10
#7  0x00007f364dc62338 in surface_commit_pending (surface=0x557470758fe0) at ../types/wlr_surface.c:372
        invalid_buffer = true
        subsurface = 0x5574707591c8
#8  0x00007f364dc625b6 in surface_commit (client=0x55747056b100, resource=0x5574706bdbd0) at ../types/wlr_surface.c:444
        surface = 0x557470758fe0
        subsurface = 0x0
#9  0x00007f364c8f4dae in ffi_call_unix64 () at /usr/lib/x86_64-linux-gnu/libffi.so.6
#10 0x00007f364c8f471f in ffi_call () at /usr/lib/x86_64-linux-gnu/libffi.so.6
#11 0x00007f364dcb18fd in  () at /usr/lib/x86_64-linux-gnu/libwayland-server.so.0
#12 0x00007f364dcae379 in  () at /usr/lib/x86_64-linux-gnu/libwayland-server.so.0
#13 0x00007f364dcaf942 in wl_event_loop_dispatch () at /usr/lib/x86_64-linux-gnu/libwayland-server.so.0
#14 0x00007f364dcae56a in wl_display_run () at /usr/lib/x86_64-linux-gnu/libwayland-server.so.0
#15 0x000055746eb74ff7 in server_run (server=0x55746ebd5e40 <server>) at ../sway/server.c:212
#16 0x000055746eb74540 in main (argc=1, argv=0x7ffe1b3fbc38) at ../sway/main.c:395
        verbose = 0
        debug = 0
        validate = 0
        allow_unsupported_gpu = 0
        long_options = 
            {{name = 0x55746ebbce20 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x55746ebbce25 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x55746ebbce2c "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x55746ebbce35 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x55746ebbce3b "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x55746ebbce43 "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x55746ebbce4b "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x55746ebbce5a "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x55746ebbce6a "my-next-gpu-wont-be-nvidia", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        config_path = 0x0
        usage = 0x55746ebbc938 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = -1
```
version info

```
sway version 1.0-rc1-33-gec5da0ca (Feb  7 2019, branch 'master')
wlroots=20d404a091fa92f56be4825bbaf89e4027fda154
```

**Comment by sanga** [comment]
swaylock is at 37280a btw
