### ISSUE TITLE
Crash when running chromium ozone build in Wayland mode

### ISSUE THREAD

**Issue by hedgepigdaniel** [swaywm/sway#3660]
## Reproducing:
1. Compile chromium with Ozone support, e.g. with https://aur.archlinux.org/packages/chromium-ozone-wayland-git/
1. Start a sway session
1. Run chromium with `--ozone-platform=wayland`
1. Open a new tab by clicking the new tab icon
1. If Sway hasn't crashed yet, try loading a page, or some other basic thing

## Sway version

* sway 1.0-rc1-45-gfb4f2928 (Feb 12 2019, branch 'makepkg')
* wlroots 0.3.r14.g9e49ceb1-1

## Debug Log:
[Debug log](https://gist.github.com/hedgepigdaniel/9bfffea600890e5399e462c81a8fc6a3)

## Configuration
I copied the default configuration file, and added this:
```
output DP-3 position 0 0
output eDP-1 position 1440 1080
output eDP-1 scale 2
output DP-3 transform 270
```

## Stack trace
```
#0  0x00007fa34faa8d92 in wl_list_insert (list=0x55f93c895828, elm=0x55f93c8951c8) at src/wayland-util.c:49
#1  0x000055f93b650ad3 in wl_signal_add (signal=0x55f93c895620, listener=0x55f93c8951c8) at /usr/include/wayland-server-core.h:431
#2  0x000055f93b6530b5 in view_child_init (child=0x55f93c895190, impl=0x55f93b676c50 <subsurface_impl>, view=0x55f93c893260, surface=0x55f93c895370) at ../sway/sway/tree/view.c:826
        output = 0x1
#3  0x000055f93b652d7f in view_subsurface_create (view=0x55f93c893260, wlr_subsurface=0x55f93c895f00) at ../sway/sway/tree/view.c:750
        subsurface = 0x55f93c895190
#4  0x000055f93b651eca in view_handle_surface_new_subsurface (listener=0x55f93c893338, data=0x55f93c895f00) at ../sway/sway/tree/view.c:419
        view = 0x55f93c893260
        subsurface = 0x55f93c895f00
#5  0x00007fa34fa63a87 in wlr_signal_emit_safe (signal=signal@entry=0x55f93c892fa0, data=data@entry=0x55f93c895f00) at ../util/signal.c:29
        pos = 0x55f93c893338
        l = 0x55f93c893338
        cursor = {link = {prev = 0x55f93c893338, next = 0x7ffeddb9cd40}, notify = 0x7fa34fa63a13 <handle_noop>}
        end = {link = {prev = 0x7ffeddb9cd20, next = 0x55f93c892fa0}, notify = 0x7fa34fa63a13 <handle_noop>}
#6  0x00007fa34fa5ec38 in wlr_subsurface_create (surface=surface@entry=0x55f93c895370, parent=parent@entry=0x55f93c892cf0, version=1, id=id@entry=21, resource_list=resource_list@entry=0x55f93be66a98)
    at ../types/wlr_surface.c:896
        __PRETTY_FUNCTION__ = "wlr_subsurface_create"
        client = 0x55f93c881850
        subsurface = 0x55f93c895f00
        resource_link = <optimized out>
#7  0x00007fa34fa4e313 in subcompositor_handle_get_subsurface (client=<optimized out>, resource=0x55f93c857120, id=21, surface_resource=0x55f93c85cdb0, parent_resource=<optimized out>)
    at ../types/wlr_compositor.c:80
        subcompositor = 0x55f93be66a80
        surface = 0x55f93c895370
        parent = 0x55f93c892cf0
        msg = "get_subsurface: wl_subsurface@"
#8  0x00007fa34ed0e6d0 in ffi_call_unix64 () at /usr/lib/libffi.so.6
#9  0x00007fa34ed0e0a0 in ffi_call () at /usr/lib/libffi.so.6
#10 0x00007fa34faa7eb8 in wl_closure_invoke (closure=0x55f93bf61700, flags=2, target=<optimized out>, opcode=1, data=<optimized out>) at src/connection.c:1006
        count = <optimized out>
        cif = {abi = FFI_UNIX64, nargs = 5, arg_types = 0x7ffeddb9cf40, rtype = 0x7fa34ed0f180 <ffi_type_void>, bytes = 0, flags = 0}
        ffi_types = 
          {0x7fa34ed0f060 <ffi_type_pointer>, 0x7fa34ed0f060 <ffi_type_pointer>, 0x7fa34ed0f0e0 <ffi_type_uint32>, 0x7fa34ed0f060 <ffi_type_pointer>, 0x7fa34ed0f060 <ffi_type_pointer>, 0xffffffffffffffff, 0x55f93c882980, 0x7fa34f8baeb4 <recvmsg+100>, 0x55f93c882998, 0x34, 0x55, 0x7ffeddb9cfe0, 0x34, 0x55f93c88ab80, 0x34, 0x7ffeddb9d480, 0x7fa34faa701e <wl_connection_pending_input+5>, 0x7fa34faa70f1 <wl_connection_read+210>, 0x0, 0x200000000, 0x0, 0x0}
        ffi_args = 
          {0x7ffeddb9cf10, 0x7ffeddb9cf18, 0x55f93bf61718, 0x55f93bf61720, 0x55f93bf61728, 0x55f93bf61700, 0x3, 0x7fa34faa75d5 <wl_closure_init+129>, 0x14, 0x7fa34faa69ad <wl_buffer_copy+47>, 0x7fa34faafc18 <wl_subcompositor_requests+24>, 0x0, 0x15, 0x7fa34faa8a99 <wl_connection_demarshal+1125>, 0x55f93c88ab80, 0x55f93bf617d0, 0x55f93bf617dc, 0x55f93c881880, 0x7fa34faafc18 <wl_subcompositor_requests+24>, 0x7fa34faa3845 <log_closure+66>, 0x55f93c881880, 0x7fa34faafc18 <wl_subcompositor_requests+24>}
        implementation = <optimized out>
#11 0x00007fa34faa5332 in wl_client_connection_data (fd=<optimized out>, mask=<optimized out>, data=0x55f93c881850) at src/wayland-server.c:420
        client = 0x55f93c881850
        connection = 0x55f93c88ab80
        resource = 0x55f93c857120
        object = 0x55f93c857120
        closure = 0x55f93bf61700
        message = 0x7fa34faafc18 <wl_subcompositor_requests+24>
        p = {8, 1310721}
        resource_flags = <optimized out>
        opcode = 1
        size = <optimized out>
        since = <optimized out>
        len = <optimized out>
#12 0x00007fa34faa604f in wl_event_source_fd_dispatch (source=<optimized out>, ep=<optimized out>) at src/event-loop.c:95
--Type <RET> for more, q to quit, c to continue without paging--
        fd_source = <optimized out>
        mask = <optimized out>
#13 0x00007fa34faa67df in wl_event_loop_dispatch (loop=0x55f93bcb6f30, timeout=timeout@entry=-1) at src/event-loop.c:641
        ep = 
              {{events = 1, data = {ptr = 0x55f93c8580b0, fd = 1015382192, u32 = 1015382192, u64 = 94528950599856}}, {events = 1, data = {ptr = 0x55f93c8366e0, fd = 1015244512, u32 = 1015244512, u64 = 94528950462176}}, {events = 1390411520, data = {ptr = 0x55f9269b8a66, fd = 647727718, u32 = 647727718, u64 = 94528582945382}}, {events = 0, data = {ptr = 0xc, fd = 12, u32 = 12, u64 = 12}}, {events = 1015589760, data = {ptr = 0x3c88db98000055f9, fd = 22009, u32 = 22009, u64 = 4361977684989859321}}, {events = 22009, data = {ptr = 0x6fe4, fd = 28644, u32 = 28644, u64 = 28644}}, {events = 1336569542, data = {ptr = 0x7fa3, fd = 32675, u32 = 32675, u64 = 32675}}, {events = 0, data = {ptr = 0x1, fd = 1, u32 = 1, u64 = 1}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 43, data = {ptr = 0x7ffeddb9d200, fd = -575024640, u32 = 3719942656, u64 = 140732618363392}}, {events = 1, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x302033312d32302d, fd = 758263853, u32 = 758263853, u64 = 3467827999379959853}}, {events = 942750256, data = {ptr = 0x55f93c88cb6c, fd = 1015597932, u32 = 1015597932, u64 = 94528950815596}}, {events = 12, data = {ptr = 0x3c88bb8800000000, fd = 0, u32 = 0, u64 = 4361942431898271744}}, {events = 22009, data = {ptr = 0x38, fd = 56, u32 = 56, u64 = 56}}, {events = 20, data = {ptr = 0x100000000, fd = 0, u32 = 0, u64 = 4294967296}}, {events = 1, data = {ptr = 0x55f90000005c, fd = 92, u32 = 92, u64 = 94527935217756}}, {events = 1390411520, data = {ptr = 0x2800000002, fd = 2, u32 = 2, u64 = 171798691842}}, {events = 48, data = {ptr = 0x7ffeddb9d320, fd = -575024352, u32 = 3719942944, u64 = 140732618363680}}, {events = 3719942752, data = {ptr = 0x52dfff0000007ffe, fd = 32766, u32 = 32766, u64 = 5971772006381682686}}, {events = 647727718, data = {ptr = 0x55f93be75830, fd = 1005017136, u32 = 1005017136, u64 = 94528940234800}}, {events = 1, data = {ptr = 0x3b65fecb00000000, fd = 0, u32 = 0, u64 = 4280107168717340672}}, {events = 22009, data = {ptr = 0xd3, fd = 211, u32 = 211, u64 = 211}}, {events = 1004959705, data = {ptr = 0x4f97e710000055f9, fd = 22009, u32 = 22009, u64 = 5735306706385131001}}, {events = 32675, data = {ptr = 0x55f93bcc07b0, fd = 1003227056, u32 = 1003227056, u64 = 94528938444720}}, {events = 1336061462, data = {ptr = 0x24b00007fa3, fd = 32675, u32 = 32675, u64 = 2521145835427}}, {events = 0, data = {ptr = 0x269b8a6652dfff00, fd = 1390411520, u32 = 1390411520, u64 = 2781969366913122048}}, {events = 1015585152, data = {ptr = 0x3bcc06f8000055f9, fd = 22009, u32 = 22009, u64 = 4308826605708400121}}, {events = 22009, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 1003226832, data = {ptr = 0x55f9, fd = 22009, u32 = 22009, u64 = 22009}}, {events = 0, data = {ptr = 0x7fa34faa54be <wl_display_flush_clients+68>, fd = 1336562878, u32 = 1336562878, u64 = 140339392959678}}}
        source = <optimized out>
        i = 0
        count = 1
#14 0x00007fa34faa551a in wl_display_run (display=0x55f93bcc06d0) at src/wayland-server.c:1260
#15 0x000055f93b618007 in server_run (server=0x55f93b678d20 <server>) at ../sway/sway/server.c:212
#16 0x000055f93b617550 in main (argc=2, argv=0x7ffeddb9d488) at ../sway/sway/main.c:403
        verbose = 0
        debug = 1
        validate = 0
        allow_unsupported_gpu = 0
        long_options = 
            {{name = 0x55f93b65fe60 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x55f93b65fe65 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x55f93b65fe6c "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x55f93b65fe75 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x55f93b65fe7b "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x55f93b65fe83 "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x55f93b65fe8b "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x55f93b65fe9a "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x55f93b65feaa "my-next-gpu-wont-be-nvidia", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        config_path = 0x0
        usage = 0x55f93b65f928 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = -1
```

**Comment by hedgepigdaniel** [comment]
I'm not sure what fixed it, but I used to be able to reproduce this reliably and I haven't seen it for a while despite using wayland chromium, so I assume it was fixed somehow.
