### ISSUE TITLE
[wlroots] SIGSEGV when doing nothing

### ISSUE THREAD

**Issue by nagisa** [swaywm/sway#3782]
# Version

This is a somewhat older build of sway, not sure if still applicable or not, but reporting just in case:

```
sway version 1.0-beta.2-305-g0952c9f9 (Feb  2 2019, branch 'master')
```

Let me know if there is anything I should extract from the coredump before I upgrade.

# Reproduction steps

No idea, honestly. I was reading stuff on firefox with my finger on touchpad and sway crashed. The cursor wasn’t being moved nor there was any specific actions being done that could make sway crash.

# Stack trace

Seems to not involve sway. Is this the right place for the report?

```
#0  0x00007f60195b6093 in wl_list_insert () at /usr/lib/libwayland-server.so.0
#1  0x00007f6019570ee9 in wlr_signal_emit_safe (signal=signal@entry=0x55afdfae49e0, data=data@entry=0x55afdfae49b0) at ../util/signal.c:19
#2  0x00007f60195478ba in wlr_data_source_destroy (source=0x55afdfae49b0) at ../types/data_device/wlr_data_source.c:42
#3  0x00007f60195478ba in wlr_data_source_destroy (source=0x55afdfae49b0) at ../types/data_device/wlr_data_source.c:37
#4  0x00007f6019547b86 in data_source_handle_resource_destroy (resource=0x55afdf867600) at ../types/data_device/wlr_data_source.c:228
#5  0x00007f60195b1c7f in  () at /usr/lib/libwayland-server.so.0
#6  0x00007f60195b1cef in wl_resource_destroy () at /usr/lib/libwayland-server.so.0
#7  0x00007f60188136d0 in ffi_call_unix64 () at /usr/lib/libffi.so.6
#8  0x00007f60188130a0 in ffi_call () at /usr/lib/libffi.so.6
#9  0x00007f60195b56ff in  () at /usr/lib/libwayland-server.so.0
#10 0x00007f60195b20a3 in  () at /usr/lib/libwayland-server.so.0
#11 0x00007f60195b3702 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#12 0x00007f60195b22ac in wl_display_run () at /usr/lib/libwayland-server.so.0
#13 0x000055afde7bbe6c in server_run (server=0x55afde81cd20 <server>) at ../sway/sway/server.c:212
#14 0x000055afde7bb3b5 in main (argc=1, argv=0x7fffadc5b758) at ../sway/sway/main.c:388
```

Seems to be caused by DnD?

```
(gdb) up
#1  0x00007f6019570ee9 in wlr_signal_emit_safe (signal=signal@entry=0x55afdfae49e0, data=data@entry=0x55afdfae49b0) at ../util/signal.c:19
19	../util/signal.c: No such file or directory.
(gdb) p *signal
$2 = {listener_list = {prev = 0x55afdf85c420, next = 0x7fffadc5af80}}
(gdb) up
#2  0x00007f60195478ba in wlr_data_source_destroy (source=0x55afdfae49b0) at ../types/data_device/wlr_data_source.c:42
42	../types/data_device/wlr_data_source.c: No such file or directory.
(gdb) p *source
$5 = {impl = 0x55afdfae49f0, mime_types = {size = 72, alloc = 128, data = 0x55afdfad2140}, actions = 3, accepted = true, current_dnd_action = WL_DATA_DEVICE_MANAGER_DND_ACTION_COPY, compositor_action = 0, events = {destroy = {
      listener_list = {prev = 0x55afdf85c420, next = 0x7fffadc5af80}}}}
```

Null pointer dereference:

```
(gdb) frame 0
#0  0x00007f60195b6093 in wl_list_insert () from /usr/lib/libwayland-server.so.0
(gdb) disassemble 
Dump of assembler code for function wl_list_insert:
   0x00007f60195b6080 <+0>:	mov    0x8(%rdi),%rax
   0x00007f60195b6084 <+4>:	mov    %rdi,(%rsi)
   0x00007f60195b6087 <+7>:	mov    %rax,0x8(%rsi)
   0x00007f60195b608b <+11>:	mov    %rsi,0x8(%rdi)
   0x00007f60195b608f <+15>:	mov    0x8(%rsi),%rax
=> 0x00007f60195b6093 <+19>:	mov    %rsi,(%rax)
   0x00007f60195b6096 <+22>:	retq   
End of assembler dump.
(gdb) info registers
rax            0x0                 0
rbx            0x7f6019570ea0      140050718723744
rcx            0x0                 0
rdx            0x7f601959fb70      140050718915440
rsi            0x7fffadc5afa0      140736108801952
rdi            0x55afdf85c420      94213857723424
rbp            0x7fffadc5af80      0x7fffadc5af80
rsp            0x7fffadc5af78      0x7fffadc5af78
r8             0x0                 0
r9             0x18                24
r10            0x7fffadc5afd0      140736108802000
r11            0x7f6019547600      140050718553600
r12            0x7fffadc5afa0      140736108801952
r13            0x55afdfae49b0      94213860379056
r14            0x55afdfae49e0      94213860379104
r15            0x7fffadc5b1b0      140736108802480
rip            0x7f60195b6093      0x7f60195b6093 <wl_list_insert+19>
eflags         0x10202             [ IF RF ]
cs             0x33                51
ss             0x2b                43
ds             0x0                 0
es             0x0                 0
fs             0x0                 0
gs             0x0                 0
```

**Comment by emersion** [comment]
This code has changed a lot since beta.2. Please upgrade to the latest wlroots and sway, and re-open if you can reproduce again.
