### ISSUE TITLE
Scratchpad windows broken with deco_rect fix

### ISSUE THREAD

**Issue by Emantor** [swaywm/sway#3825]
19df2e590602abe0b5e1b53bc11debdb37be3fbe breaks my scratchpad terminal:
```
#0  container_parent_layout (con=0x5571396d9240) at ../sway/tree/container.c:1166
1166		return con->workspace->layout;
[Current thread is 1 (Thread 0x7fcd3974b9c0 (LWP 22301))]
(gdb) bt f
#0  0x00005571376bf580 in container_parent_layout (con=0x5571396d9240) at ../sway/tree/container.c:1166
#1  0x0000557137681a42 in get_deco_rect (c=0x5571396d9240, deco_rect=0x7ffeb4575c10) at ../sway/ipc-json.c:354
        parent_layout = 32766
#2  0x00005571376825ac in ipc_json_describe_node (node=0x5571396d9240) at ../sway/ipc-json.c:537
        deco_rect = {x = 0, y = 0, width = 0, height = 0}
        seat = 0x55713912b9d0
        focused = false
        name = 0x5571396be860 "tmux new-session -A -s quick"
        box = {x = 480, y = 282, width = 1600, height = 900}
        focus = 0x0
        data = {node = 0x0, object = 0x0}
        object = 0x7c00000077
#3  0x00005571376826cc in ipc_json_describe_node_recursive (node=0x5571396d9240) at ../sway/ipc-json.c:571
        object = 0x0
        i = 32766
        children = 0x7fcd3bc38135 <array_list_new+69>
#4  0x00005571376816e1 in ipc_json_describe_scratchpad_output () at ../sway/ipc-json.c:300
        container = 0x5571396d9240
        i = 0
        box = {x = 0, y = 0, width = 4480, height = 1440}
        workspace_focus = 0x5571396c9750
        workspace = 0x5571396c9940
        floating_array = 0x5571396ebe10
        output_focus = 0x7ffeb4576340
        output = 0x0
        nodes = 0x7fcd3bc38135 <array_list_new+69>
#5  0x0000557137682708 in ipc_json_describe_node_recursive (node=0x557139128630) at ../sway/ipc-json.c:578
        object = 0x5571396d9bd0
        i = 32717
        children = 0x5571396c95d0
#6  0x00005571376862e3 in ipc_client_handle_command (client=0x5571396a22b0) at ../sway/ipc-server.c:756
        tree = 0x5571376cb607 <_sway_log+181>
        json_string = 0x5571376cfd63 "[%s:%d] Client %d readable"
        __PRETTY_FUNCTION__ = "ipc_client_handle_command"
        buf = 0x5571396d9cf0 ""
        client_valid = true
#7  0x00005571376845e1 in ipc_client_handle_readable (client_fd=114, mask=1, data=0x5571396a22b0) at ../sway/ipc-server.c:258
        client = 0x5571396a22b0
        read_available = 14
        buf = "i3-ipc\000\000\000\000\004\000\000"
        buf32 = 0x7ffeb4575fb0
        received = 14
#8  0x00007fcd3b8d6702 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#9  0x00007fcd3b8d52ac in wl_display_run () at /usr/lib/libwayland-server.so.0
#10 0x000055713768846f in server_run (server=0x5571376e9d60 <server>) at ../sway/server.c:216
#11 0x0000557137687986 in main (argc=1, argv=0x7ffeb4576348) at ../sway/main.c:401
        verbose = 0
        debug = 0
        validate = 0
        allow_unsupported_gpu = 0
        long_options = 
            {{name = 0x5571376d0ed0 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x5571376d0ed5 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x5571376d0edc "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x5571376d0ee5 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x5571376d0eeb "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x5571376d0ef3 "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x5571376d0efb "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x5571376d0f0a "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x5571376d0f1a "my-next-gpu-wont-be-nvidia", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        config_path = 0x0
        usage = 0x5571376d0998 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = -1
```

**Comment by emersion** [comment]
https://github.com/swaywm/sway/pull/3826
