### ISSUE TITLE
segfault in container_init_floating

### ISSUE THREAD

**Issue by yorickvP** [swaywm/sway#3954]
* Sway Version: 1.0

* Debug Log: https://pub.yori.cc/sway-crash10.log

* Configuration File: https://pub.yori.cc/i3_config

Finally, explain the steps you took in plain English to reproduce the problem below.

1. disconnect from docking station

* Stack Trace, if sway crashes:
```
#0  0x000000000044819f in container_init_floating ()
#1  0x0000000000449e32 in container_set_floating ()
#2  0x000000000044dd61 in view_map ()
#3  0x00000000004235e3 in handle_map ()
#4  0x00007f96a300c9fc in wlr_signal_emit_safe ()
   from /nix/store/qy5an0g3krz886f5qvw64b03br1nlmd9-wlroots-408eca7dfa12eda0f1b0ec6050e99ee2e6a8f2b4/lib/libwlroots.so.2
#5  0x00007f96a2ff2049 in handle_xdg_surface_commit ()
   from /nix/store/qy5an0g3krz886f5qvw64b03br1nlmd9-wlroots-408eca7dfa12eda0f1b0ec6050e99ee2e6a8f2b4/lib/libwlroots.so.2
#6  0x00007f96a3006dd2 in surface_commit_pending ()
   from /nix/store/qy5an0g3krz886f5qvw64b03br1nlmd9-wlroots-408eca7dfa12eda0f1b0ec6050e99ee2e6a8f2b4/lib/libwlroots.so.2
#7  0x00007f96a3007088 in surface_commit () from /nix/store/qy5an0g3krz886f5qvw64b03br1nlmd9-wlroots-408eca7dfa12eda0f1b0ec6050e99ee2e6a8f2b4/lib/libwlroots.so.2
#8  0x00007f96a27cd05e in ffi_call_unix64 () from /nix/store/kbbiky87bsdndh63m7919sxkf3gsh5zq-libffi-3.2.1/lib/../lib64/libffi.so.6
#9  0x00007f96a27cc023 in ffi_call () from /nix/store/kbbiky87bsdndh63m7919sxkf3gsh5zq-libffi-3.2.1/lib/../lib64/libffi.so.6
#10 0x00007f96a3050b94 in wl_closure_invoke () from /nix/store/9n45jlbvwi49hlmm0kqlgllhnznq1x04-wayland-1.16.0/lib/libwayland-server.so.0
#11 0x00007f96a304d61f in wl_client_connection_data () from /nix/store/9n45jlbvwi49hlmm0kqlgllhnznq1x04-wayland-1.16.0/lib/libwayland-server.so.0
#12 0x00007f96a304ebe2 in wl_event_loop_dispatch () from /nix/store/9n45jlbvwi49hlmm0kqlgllhnznq1x04-wayland-1.16.0/lib/libwayland-server.so.0
#13 0x00007f96a304d7fa in wl_display_run () from /nix/store/9n45jlbvwi49hlmm0kqlgllhnznq1x04-wayland-1.16.0/lib/libwayland-server.so.0
#14 0x000000000040e509 in main ()
```
Release build, built without debug.

**Comment by yorickvP** [comment]
docking station: caldigit TS3+, on a Dell XPS 9360
