### ISSUE TITLE
crash on detaching laptop from thunderbolt dock

### ISSUE THREAD

**Issue by sanga** [swaywm/sway#4149]
steps to repro
1. disconnected from thunderbolt 3 dock with external display connected to it
=> crash

stacktrace

```
Reading symbols from /usr/local/bin/sway...
[New LWP 16544]
[New LWP 16547]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `sway'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
[Current thread is 1 (Thread 0x7fa9ce1c0400 (LWP 16544))]
#0  0x00007fa9cf6c8ed7 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {512, 140367306490231, 47172124672, 94357032519456, 94357032519557, 94357032519456, 94357032519456, 94357032519573, 94357032519756, 94357032519456, 94357032519756, 0, 0, 0, 0, 0}}
        pid = <optimized out>
        tid = <optimized out>
#1  0x00007fa9cf6aa535 in __GI_abort () at abort.c:79
        save_stage = 1
        act = 
          {__sigaction_handler = {sa_handler = 0x55d13560a030, sa_sigaction = 0x55d13560a030}, sa_mask = {__val = {0, 94357032519456, 6, 0, 0, 0, 21474836480, 140732117766472, 140732117766320, 140367307718896, 140367307703688, 0, 9398871474071887616, 140367307688423, 0, 140367307703688}}, sa_flags = -812128032, sa_restorer = 0x7fa9cf97e900}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007fa9cf6aa40f in __assert_fail_base
    (fmt=0x7fa9cf838588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x7fa9cf97e900 "wlr_backend_is_drm(wlr_backend)", file=0x7fa9cf97e8e0 "../backend/drm/backend.c", line=20, function=<optimized out>) at assert.c:92
        str = 0x55d13560a030 "\200\237d5\321U"
        total = 4096
#3  0x00007fa9cf6ba012 in __GI___assert_fail
    (assertion=0x7fa9cf97e900 "wlr_backend_is_drm(wlr_backend)", file=0x7fa9cf97e8e0 "../backend/drm/backend.c", line=20, function=0x7fa9cf97ea60 <__PRETTY_FUNCTION__.12710> "get_drm_backend_from_backend") at assert.c:101
#4  0x00007fa9cf91e79d in get_drm_backend_from_backend (wlr_backend=0x7fa9cf869f40 <main_arena+768>) at ../backend/drm/backend.c:20
        __PRETTY_FUNCTION__ = "get_drm_backend_from_backend"
#5  0x00007fa9cf923a71 in page_flip_handler (fd=9, seq=8998305, tv_sec=278911, tv_usec=434578, data=0x55d13569e040) at ../backend/drm/drm.c:1309
        conn = 0x55d13569e040
        drm = 0x55d1350c61d0
        present_time = {tv_sec = 278911, tv_nsec = 427251000}
        present_event = {output = 0x55d13529a1c0, when = 0x7ffebfe35260, seq = 2137098506, refresh = 16663333, flags = 7}
#6  0x00007fa9cec3cd85 in drmHandleEvent () at /usr/lib/x86_64-linux-gnu/libdrm.so.2
#7  0x00007fa9cf923c20 in handle_drm_event (fd=9, mask=1, data=0x0) at ../backend/drm/drm.c:1351
        event = {version = 2, vblank_handler = 0x0, page_flip_handler = 0x7fa9cf923a32 <page_flip_handler>, page_flip_handler2 = 0x0, sequence_handler = 0x0}
#8  0x00007fa9cf9bc942 in wl_event_loop_dispatch () at /usr/lib/x86_64-linux-gnu/libwayland-server.so.0
#9  0x00007fa9cf9bb56a in wl_display_run () at /usr/lib/x86_64-linux-gnu/libwayland-server.so.0
#10 0x000055d133b37a2e in server_run (server=0x55d133b9ef00 <server>) at ../sway/server.c:216
#11 0x000055d133b36f45 in main (argc=1, argv=0x7ffebfe35ab8) at ../sway/main.c:397
        verbose = 0
        debug = 0
        validate = 0
        allow_unsupported_gpu = 0
        long_options = 
            {{name = 0x55d133b83f44 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x55d133b83f49 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x55d133b83f50 "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x55d133b83f59 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x55d133b83f5f "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x55d133b83f67 "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x55d133b83f6f "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x55d133b83f7e "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x55d133b83f8e "my-next-gpu-wont-be-nvidia", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        config_path = 0x0
        usage = 0x55d133b83a18 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = -1
```
version info

```
sway version 1.1-rc1-2-g51c07779 (May  4 2019, branch 'master')
wlroots=6ae6b5dbb6c4f33f3c8ba12cd889100376d1edd8
```

**Comment by sanga** [comment]
I hit the same stack just now whilst plugging the laptop into the dock.

**Comment by Emantor** [comment]
This is a wlroots issue, see swaywm/wlroots#1297.

**Comment by emersion** [comment]
Closing as a duplicate
