### ISSUE TITLE
Segfault in wl_list_insert

### ISSUE THREAD

**Issue by chebykinn** [swaywm/sway#4375]
version: `sway version 1.1-rc1-49-g5becce80 (Jul  4 2019, branch 'master')`
backtrace:
```
#0  0x00007fb9a0d77153 in wl_list_insert () at /usr/lib/x86_64-linux-gnu/libwayland-server.so.0
#1  0x000000000045feb0 in wl_signal_add (signal=0x1e05670, listener=0x1e06400) at /usr/include/wayland-server-core.h:431
#2  0x00000000004608bd in view_child_init (child=0x1e063a0, impl=0x475f58 <subsurface_impl>, view=0x205ee40, surface=0x1e053c0) at ../sway/tree/view.c:891
        output = 0x7fb9a00d83a2 <__libc_calloc+882>
#3  0x00000000004615a9 in view_subsurface_create (view=0x205ee40, wlr_subsurface=0x20c3740) at ../sway/tree/view.c:784
        subsurface = 0x1e063a0
#4  0x000000000045fef4 in view_handle_surface_new_subsurface (listener=0x205ef18, data=0x20c3740) at ../sway/tree/view.c:424
        view = 0x205ee40
        subsurface = 0x20c3740
#5  0x00007fb9a0b31b6f in  () at /usr/local/lib/x86_64-linux-gnu/libwlroots.so.3
#6  0x00007fb9a0b29b7a in wlr_subsurface_create () at /usr/local/lib/x86_64-linux-gnu/libwlroots.so.3
#7  0x00007fb9a0b0bf27 in  () at /usr/local/lib/x86_64-linux-gnu/libwlroots.so.3
#8  0x00007fb99dd32dae in ffi_call_unix64 () at /usr/lib/x86_64-linux-gnu/libffi.so.6
#9  0x00007fb99dd3271f in ffi_call () at /usr/lib/x86_64-linux-gnu/libffi.so.6
#10 0x00007fb9a0d767e4 in  () at /usr/lib/x86_64-linux-gnu/libwayland-server.so.0
#11 0x00007fb9a0d7326f in  () at /usr/lib/x86_64-linux-gnu/libwayland-server.so.0
#12 0x00007fb9a0d74832 in wl_event_loop_dispatch () at /usr/lib/x86_64-linux-gnu/libwayland-server.so.0
#13 0x00007fb9a0d7344a in wl_display_run () at /usr/lib/x86_64-linux-gnu/libwayland-server.so.0
#14 0x000000000041bd5d in server_run (server=0x685e50 <server>) at ../sway/server.c:202
#15 0x000000000041af58 in main (argc=1, argv=0x7ffc12efaae8) at ../sway/main.c:400
        verbose = 0
        debug = 0
        validate = 0
        allow_unsupported_gpu = 0
        long_options =
            {{name = 0x46d751 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x470df0 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x46d756 "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x46d75f "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x46dc0c "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x46c1d5 "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x46d765 "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x46d774 "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x46d784 "my-next-gpu-wont-be-nvidia", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        config_path = 0x0
        usage = 0x46d79f "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = -1
(gdb)
```

**Comment by emersion** [comment]
How to reproduce?

**Comment by chebykinn** [comment]
It looks random for me, if I find a way to reproduce, i'll write it here, right now I have no clue.

**Comment by joshuarubin** [comment]
I'm getting the same when copying from neovim to the wayland clipboard:
```
Process 16354 (sway) of user 1000 dumped core.
                                                  
                                                  Stack trace of thread 16354:
                                                  #0  0x00007f1211e9b1b0 wl_list_insert (libwayland-server.so.0)
                                                  #1  0x00007f1211e2ce7f wlr_seat_keyboard_enter (libwlroots.so.3)
                                                  #2  0x000055edcdefc368 n/a (sway)
                                                  #3  0x000055edcdefca40 n/a (sway)
                                                  #4  0x000055edcdefd69f n/a (sway)
                                                  #5  0x000055edcdefde4a n/a (sway)
                                                  #6  0x00007f1211e53cfe n/a (libwlroots.so.3)
                                                  #7  0x00007f1211e53cfe n/a (libwlroots.so.3)
                                                  #8  0x00007f1211e1d51f n/a (libwlroots.so.3)
                                                  #9  0x00007f1211e1c10c n/a (libwlroots.so.3)
                                                  #10 0x00007f1211e987f2 wl_event_loop_dispatch (libwayland-server.so.0)
                                                  #11 0x00007f1211e9739c wl_display_run (libwayland-server.so.0)
                                                  #12 0x000055edcded1592 n/a (sway)
                                                  #13 0x00007f1212499ee3 __libc_start_main (libc.so.6)
                                                  #14 0x000055edcded18be n/a (sway)
                                                  
                                                  Stack trace of thread 16356:
                                                  #0  0x00007f1211d5c415 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                                  #1  0x00007f120feb39dc n/a (radeonsi_dri.so)
                                                  #2  0x00007f120feb35d8 n/a (radeonsi_dri.so)
                                                  #3  0x00007f1211d5657f start_thread (libpthread.so.0)
                                                  #4  0x00007f121256f0e3 __clone (libc.so.6)
```

**Comment by emersion** [comment]
@joshuarubin This is a different one, already fixed in master.

**Comment by joshuarubin** [comment]
Great, thx. Sorry for spamming this issue!
