### ISSUE TITLE
rdp backend wlroots and sway 1.2

### ISSUE THREAD

**Issue by kristoferus75** [swaywm/sway#4549]
Hi !

I have now compiled wlrrots with enabled freerdp in the PKGBIULD 
and i use sway1.2 on arch linux 

wlroots-git-0.7.0.r2.gbf90474b
sway1.2

but if i start terminal : 

```
WLR_RDP_TLS_CERT_PATH=cert/tls.crt 
 WLR_RDP_TLS_KEY_PATH=cert/tls.key 
WLR_RDP_ADDRESS=0.0.0.0 
WLR_BACKENDS=rdp 
export WLR_RDP_TLS_CERT_PATH
export WLR_RDP_TLS_KEY_PATH
export WLR_RDP_ADDRESS
export WLR_BACKENDS
```

sway -Vd -c /home/schuster/.config/sway/config > sway-rdp.log 2>&1

not start with error and in the log is this:

```
2019-09-06 20:26:15 - [xwayland/selection/selection.c:117] not handling selection events: no seat assigned to xwayland
2019-09-06 20:26:15 - [xwayland/xwm.c:830] XCB_CREATE_NOTIFY (4194307)
2019-09-06 20:26:15 - [sway/desktop/xwayland.c:589] New xwayland surface title='(null)' class='(null)'
2019-09-06 20:26:15 - [xwayland/selection/selection.c:117] not handling selection events: no seat assigned to xwayland
2019-09-06 20:26:15 - [xwayland/xwm.c:967] XCB_PROPERTY_NOTIFY (4194305)
2019-09-06 20:26:15 - [xwayland/xwm.c:441] XCB_ATOM_WM_NAME: termite
2019-09-06 20:26:15 - [xwayland/selection/selection.c:117] not handling selection events: no seat assigned to xwayland
2019-09-06 20:26:15 - [xwayland/xwm.c:967] XCB_PROPERTY_NOTIFY (4194305)
2019-09-06 20:26:15 - [xwayland/selection/selection.c:117] not handling selection events: no seat assigned to xwayland
2019-09-06 20:26:15 - [xwayland/xwm.c:967] XCB_PROPERTY_NOTIFY (4194307)
2019-09-06 20:26:15 - [xwayland/xwm.c:722] unhandled X11 property 277 (XdndAware) for window 4194307
2019-09-06 20:26:15 - [xwayland/selection/selection.c:117] not handling selection events: no seat assigned to xwayland
2019-09-06 20:26:15 - [xwayland/xwm.c:967] XCB_PROPERTY_NOTIFY (4194307)
2019-09-06 20:26:15 - [xwayland/xwm.c:607] WM_NORMAL_HINTS (18)
2019-09-06 20:26:15 - [xwayland/selection/selection.c:117] not handling selection events: no seat assigned to xwayland
2019-09-06 20:26:15 - [xwayland/xwm.c:830] XCB_CREATE_NOTIFY (4194318)
2019-09-06 20:26:15 - [sway/desktop/xwayland.c:584] New xwayland unmanaged surface
2019-09-06 20:26:15 - [xwayland/selection/selection.c:117] not handling selection events: no seat assigned to xwayland
2019-09-06 20:26:15 - [xwayland/xwm.c:1206] XCB_CLIENT_MESSAGE (4194307)
2019-09-06 20:26:15 - [xwayland/selection/selection.c:117] not handling selection events: no seat assigned to xwayland
2019-09-06 20:26:15 - [xwayland/xwm.c:967] XCB_PROPERTY_NOTIFY (4194307)
2019-09-06 20:26:15 - [xwayland/xwm.c:722] unhandled X11 property 329 (_GTK_THEME_VARIANT) for window 4194307
2019-09-06 20:26:15 - [xwayland/selection/selection.c:117] not handling selection events: no seat assigned to xwayland
2019-09-06 20:26:15 - [xwayland/selection/selection.c:117] not handling selection events: no seat assigned to xwayland
2019-09-06 20:26:15 - [xwayland/xwm.c:967] XCB_PROPERTY_NOTIFY (4194307)
2019-09-06 20:26:15 - [xwayland/xwm.c:555] WM_HINTS (9)
2019-09-06 20:26:15 - [xwayland/selection/selection.c:117] not handling selection events: no seat assigned to xwayland
2019-09-06 20:26:15 - [xwayland/xwm.c:922] XCB_MAP_REQUEST (4194307)
2019-09-06 20:26:15 - [xwayland/selection/selection.c:117] not handling selection events: no seat assigned to xwayland
2019-09-06 20:26:15 - [xwayland/xwm.c:967] XCB_PROPERTY_NOTIFY (4194307)
2019-09-06 20:26:15 - [xwayland/xwm.c:722] unhandled X11 property 257 (WM_STATE) for window 4194307
2019-09-06 20:26:15 - [xwayland/selection/selection.c:117] not handling selection events: no seat assigned to xwayland
2019-09-06 20:26:15 - [xwayland/xwm.c:967] XCB_PROPERTY_NOTIFY (4194307)
2019-09-06 20:26:15 - [xwayland/selection/selection.c:117] not handling selection events: no seat assigned to xwayland
2019-09-06 20:26:15 - [xwayland/selection/selection.c:117] not handling selection events: no seat assigned to xwayland
2019-09-06 20:26:15 - [xwayland/xwm.c:941] XCB_MAP_NOTIFY (4194307)
2019-09-06 20:26:15 - [xwayland/selection/selection.c:117] not handling selection events: no seat assigned to xwayland
2019-09-06 20:26:15 - [xwayland/xwm.c:1206] XCB_CLIENT_MESSAGE (4194307)
2019-09-06 20:26:15 - [types/wlr_surface.c:609] New wlr_surface 0x5610073b0910 (res 0x561007381b60)
2019-09-06 20:26:15 - [xwayland/xwm.c:1375] New xwayland surface: 0x5610073b0910
2019-09-06 20:26:15 - [xwayland/xwm.c:390] XCB_ATOM_WM_CLASS: termite Termite
2019-09-06 20:26:15 - [xwayland/xwm.c:441] XCB_ATOM_WM_NAME: Scratchpad
2019-09-06 20:26:15 - [xwayland/xwm.c:525] WM_PROTOCOLS (4)
2019-09-06 20:26:15 - [xwayland/xwm.c:555] WM_HINTS (9)
2019-09-06 20:26:15 - [xwayland/xwm.c:607] WM_NORMAL_HINTS (18)
2019-09-06 20:26:15 - [xwayland/xwm.c:502] NET_WM_WINDOW_TYPE (1)
2019-09-06 20:26:15 - [xwayland/xwm.c:441] XCB_ATOM_WM_NAME: Scratchpad
2019-09-06 20:26:15 - [xwayland/xwm.c:479] NET_WM_PID 9384
2019-09-06 20:26:15 - [xwayland/selection/selection.c:117] not handling selection events: no seat assigned to xwayland
2019-09-06 20:26:15 - [xwayland/xwm.c:967] XCB_PROPERTY_NOTIFY (4194307)
2019-09-06 20:26:15 - [xwayland/xwm.c:607] WM_NORMAL_HINTS (18)
2019-09-06 20:26:15 - [GLES2] FS SIMD8 shader: 5 inst, 0 loops, 24 cycles, 0:0 spills:fills, Promoted 0 constants, compacted 80 to 48 bytes.
2019-09-06 20:26:15 - [GLES2] FS SIMD16 shader: 5 inst, 0 loops, 34 cycles, 0:0 spills:fills, Promoted 0 constants, compacted 80 to 48 bytes.
2019-09-06 20:26:15 - [GLES2] VS SIMD8 shader: 28 inst, 0 loops, 116 cycles, 0:0 spills:fills, Promoted 0 constants, compacted 448 to 336 bytes.
2019-09-06 20:26:15 - [GLES2] FS SIMD8 shader: 14 inst, 0 loops, 308 cycles, 0:0 spills:fills, Promoted 0 constants, compacted 224 to 176 bytes.
2019-09-06 20:26:15 - [GLES2] FS SIMD16 shader: 14 inst, 0 loops, 322 cycles, 0:0 spills:fills, Promoted 0 constants, compacted 224 to 176 bytes.
2019-09-06 20:26:15 - [sway/tree/root.c:231] Looking up workspace for pid 9384
2019-09-06 20:26:15 - [sway/tree/view.c:525] select_workspace:Expected to find a workspace
(EE) 2019-09-06 20:26:16 - failed to read Wayland events: Connection reset by peer
[common/ipc-client.c:88] Unable to receive IPC response
Gdk-Message: 20:26:16.029: termite: Fatal IO error 11 (Die Ressource ist zur Zeit nicht verfügbar) on X server :0.

Traceback (most recent call last):
  File "/usr/bin/bumblebee-status", line 54, in main
    engine.run()
  File "/usr/share/bumblebee-status/bumblebee/engine.py", line 272, in run
    self.write_output()
  File "/usr/share/bumblebee-status/bumblebee/engine.py", line 291, in write_output
    self._output.end()
  File "/usr/share/bumblebee-status/bumblebee/output.py", line 179, in end
    sys.stdout.flush()
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/bumblebee-status", line 80, in <module>
    main()
  File "/usr/bin/bumblebee-status", line 64, in main
    output.end()
  File "/usr/share/bumblebee-status/bumblebee/output.py", line 179, in end
    sys.stdout.flush()
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
```
regards

kristoferus

**Comment by emersion** [comment]
This log is truncated. Send a full debug log.

**Comment by kristoferus75** [comment]
ok here the full log file !

[sway-rdp.log](https://github.com/swaywm/sway/files/3585323/sway-rdp.log)

**Comment by emersion** [comment]
```
2019-09-06 20:26:15 - [EGL] eglGetPlatformDisplay: EGL_BAD_PARAMETER error: In internal function: Additional INFO may be available
2019-09-06 20:26:15 - [EGL] eglGetPlatformDisplay: EGL_BAD_PARAMETER error: In function eglGetPlatformDisplay(), unsupported EGL Platform
```

**Comment by torpak** [comment]
It seems, you are using an nvidia card (bumblebee wouldn't make sense otherwise) try using nuveau driver instead of nvidia driver. Better yet: switch off your nvidia card and use the intel card, which works very well with sway.

**Comment by kristoferus75** [comment]
Hi !

No i have no nvidia card installed ! But it was bumblebee-status installed -> no idea why !-> deinstalled !

But now i get an other error -> see log file !
[sway-rdp.log](https://github.com/swaywm/sway/files/3587350/sway-rdp.log)

**Comment by rvanheusden** [comment]
I'm using the latest versions of sway (a085e64) + wlroots (a14d650) and encountering similar errors, specifically:
```
[sway/server.c:53] Initializing Wayland server
[render/gles2/renderer.c:360] failed to bind wl_display to EGL
[...]
[wayland] unable to lock lockfile /run/user/1000/wayland-0.lock, maybe another compositor is running
```
and then some of these:
```
[sway/tree/root.c:275] Recording workspace for process 9370
[sway/tree/root.c:283] Bailing out, no workspace
```
and finally this:
```
[sway/tree/root.c:231] Looking up workspace for pid 9384
[sway/tree/view.c:525] select_workspace:Expected to find a workspace
```

I can run run Sway normally; running it with the RDP backend triggers these errors. I can also post a full log if needed, but it seems that @kristoferus75's most recent log covers the common errors.

**Comment by aemino** [comment]
I'm using the latest versions of sway (a085e64) + wlroots (a14d650) and encountering similar errors, specifically:
```
[sway/server.c:53] Initializing Wayland server
[render/gles2/renderer.c:360] failed to bind wl_display to EGL
[...]
[wayland] unable to lock lockfile /run/user/1000/wayland-0.lock, maybe another compositor is running
```
and then some of these:
```
[sway/tree/root.c:275] Recording workspace for process 9370
[sway/tree/root.c:283] Bailing out, no workspace
```
and finally this:
```
[sway/tree/root.c:231] Looking up workspace for pid 9384
[sway/tree/view.c:525] select_workspace:Expected to find a workspace
```

I can run run Sway normally; running it with the RDP backend triggers these errors. I can also post a full log if needed, but it seems that @kristoferus75's most recent log covers the common errors.

**Comment by emersion** [comment]
The RDP backend has been removed. Use wayvnc instead.
