### ISSUE TITLE
SEGFAULT when running QEMU

### ISSUE THREAD

**Issue by norcalli** [swaywm/sway#4567]
* Sway Version

```json
{
   "human_readable": "1.2-rc1-25-ga298cad0 (Sep 15 2019, branch 'master')",
   "variant": "sway",
   "major": 1,
   "minor": 2,
   "patch": 0,
   "loaded_config_file_name": "\/home\/ashkan\/.config\/sway\/config"
 }
```

* Stack Trace

```gdb
Program terminated with signal SIGSEGV, Segmentation fault. 
#0  0x000055a1bd009d94 in is_transient_for (child=0x55a1befd2ff0, ancestor=0x55a1befd2ff0) at ../sway/desktop/xdg_shell.c:220 
220             while (surface && surface->role == WLR_XDG_SURFACE_ROLE_TOPLEVEL) { 
[Current thread is 1 (Thread 0x7f9344a730c0 (LWP 3998681))] 
(gdb) print surface 
$1 = (struct wlr_xdg_surface *) 0x1 
(gdb) bt full 
#0  0x000055a1bd009d94 in is_transient_for (child=0x55a1befd2ff0, ancestor=0x55a1befd2ff0) at ../sway/desktop/xdg_shell.c:220 
        surface = 0x1 
#1  0x000055a1bd0416b1 in view_is_transient_for (child=0x55a1befd2ff0, ancestor=0x55a1befd2ff0) at ../sway/tree/view.c:1169 
#2  0x000055a1bd03c08a in container_is_transient_for (child=0x55a1befc3e50, ancestor=0x55a1befc3e50) 
    at ../sway/tree/container.c:1366 
#3  0x000055a1bd01418c in seat_set_focus (seat=0x55a1be99b690, node=0x55a1befc3e50) at ../sway/input/seat.c:948 
        last_focus = 0x55a1bef4bf10 
        last_workspace = 0x55a1bea4abf0 
        new_workspace = 0x55a1bea4abf0 
        container = 0x55a1befc3e50 
        new_output = 0x55a1be995e00 
        new_output_last_ws = 0x55a1be99b690 
#4  0x000055a1bd014614 in seat_set_focus_container (seat=0x55a1be99b690, con=0x55a1befc3e50) at ../sway/input/seat.c:1066 
#5  0x000055a1bd03ad3a in container_fullscreen_workspace (con=0x55a1befc3e50) at ../sway/tree/container.c:960 
        seat = 0x55a1be99b690 
        focus_ws = 0x55a1bea4abf0 
        __PRETTY_FUNCTION__ = "container_fullscreen_workspace" 
        enable = true 
#6  0x000055a1bd03b319 in container_set_fullscreen (con=0x55a1befc3e50, mode=FULLSCREEN_WORKSPACE) 
    at ../sway/tree/container.c:1069 
#7  0x000055a1bd03fe2a in view_map 
    (view=0x55a1befd2ff0, wlr_surface=0x55a1befc4330, fullscreen=2, fullscreen_output=0x0, decoration=false) 
    at ../sway/tree/view.c:633 
        __PRETTY_FUNCTION__ = "view_map" 
        ws = 0x55a1bea4abf0 
        seat = 0x55a1be99b690 
        node = 0x55a1bef4bf10 
        target_sibling = 0x55a1bef4bf10 
#8  0x000055a1bd00a5a8 in handle_map (listener=0x55a1befd31a0, data=0x55a1befc46e0) at ../sway/desktop/xdg_shell.c:431 
        xdg_shell_view = 0x55a1befd2ff0 
        view = 0x55a1befd2ff0 
        xdg_surface = 0x55a1befc46e0 
        csd = false 
#9  0x00007f9346209b67 in wlr_signal_emit_safe (signal=0x55a1befc47d8, data=0x55a1befc46e0) at ../util/signal.c:29 
        pos = 0x55a1befd31a0 
        l = 0x55a1befd31a0 
        cursor = {link = {prev = 0x55a1befd31a0, next = 0x7ffd81632460}, notify = 0x7f9346209ab1 <handle_noop>} 
        end = {link = {prev = 0x7ffd81632440, next = 0x55a1befc47d8}, notify = 0x7f9346209ab1 <handle_noop>} 
#10 0x00007f93461e2c11 in handle_xdg_surface_commit (wlr_surface=0x55a1befc4330) at ../types/xdg_shell/wlr_xdg_surface.c:356 
        surface = 0x55a1befc46e0 
        __PRETTY_FUNCTION__ = "handle_xdg_surface_commit" 
--Type <RET> for more, q to quit, c to continue without paging--c 
#11 0x00007f93462028b6 in surface_commit_pending (surface=0x55a1befc4330) at ../types/wlr_surface.c:372 
        invalid_buffer = true 
        subsurface = 0x55a1befc4518 
#12 0x00007f9346202b34 in surface_commit (client=0x55a1befb09b0, resource=0x55a1befc4650) at ../types/wlr_surface.c:444 
        surface = 0x55a1befc4330 
        subsurface = 0x0 
#13 0x00007f93454d36d0 in ffi_call_unix64 () at /usr/lib/libffi.so.6 
#14 0x00007f93454d30a0 in ffi_call () at /usr/lib/libffi.so.6 
#15 0x00007f934625282f in  () at /usr/lib/libwayland-server.so.0 
#16 0x00007f934624f193 in  () at /usr/lib/libwayland-server.so.0 
#17 0x00007f93462507f2 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0 
#18 0x00007f934624f39c in wl_display_run () at /usr/lib/libwayland-server.so.0 
#19 0x000055a1bcfffc7d in server_run (server=0x55a1bd066f40 <server>) at ../sway/server.c:202 
#20 0x000055a1bcfff2f1 in main (argc=2, argv=0x7ffd81632be8) at ../sway/main.c:400 
        verbose = 0 
        debug = 0 
        validate = 0 
        allow_unsupported_gpu = 1 
        long_options = {{name = 0x55a1bd04d018 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x55a1bd04d01d "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x55a1bd04d024 "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x55a1bd04d02d "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x55a1bd04d033 "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x55a1bd04d03b "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x55a1bd04d043 "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x55a1bd04d052 "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x55a1bd04d062 "my-next-gpu-wont-be-nvidia", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}} 
        config_path = 0x0 
        usage = 0x55a1bd04cae0 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"... 
        c = -1 
(gdb) 
```

As you can see from the stack trace, the problem statement is `while (surface && surface->role == WLR_XDG_SURFACE_ROLE_TOPLEVEL) {` where `surface` is set to `0x1` somewhere in the tree climbing code from `sway/desktop/xdg_shell.c:220` here:

```c
static bool is_transient_for(struct sway_view *child,
		struct sway_view *ancestor) {
	if (xdg_shell_view_from_view(child) == NULL) {
		return false;
	}
	struct wlr_xdg_surface *surface = child->wlr_xdg_surface;
	while (surface && surface->role == WLR_XDG_SURFACE_ROLE_TOPLEVEL) {
		if (surface->toplevel->parent == ancestor->wlr_xdg_surface) {
			return true;
		}
		surface = surface->toplevel->parent;
	}
	return false;
}
```

Big problem for me. I've been having crashes since I updated to master this last week.

**Comment by norcalli** [comment]
```gdb
(gdb) print child 
$2 = (struct sway_view *) 0x55a1befd2ff0 
(gdb) print child->wlr_xdg_surface 
$3 = (struct wlr_xdg_surface *) 0x55a1befc46e0 
(gdb) print child->wlr_xdg_surface->toplevel 
$4 = (struct wlr_xdg_toplevel *) 0x55a1befc36d0 
(gdb) print child->wlr_xdg_surface->toplevel->parent 
$5 = (struct wlr_xdg_surface *) 0x1 
(gdb) 
```

**Comment by norcalli** [comment]
I tried an old version of sway and it's still happening with latest wlroots, which means this is likely happening from outside of sway.

**Comment by norcalli** [comment]
Could this be similar to https://github.com/swaywm/sway/issues/2840?

**Comment by RedSoxFan** [comment]
https://github.com/swaywm/wlroots/pull/1794 should prevent this from happening. Maybe there is a missing case somewhere?

**Comment by norcalli** [comment]
I haven't run into this recently, so I'm going to close it and reopen if I can make a more reproducible test case.
