### ISSUE TITLE
segfault in container_is_floating when assigning with tiling criteria.

### ISSUE THREAD

**Issue by RPigott** [swaywm/sway#4578]
* Sway Version: sway version 1.2-rc1-51-gda0ad4c3 (Sep 22 2019, branch 'makepkg')

* Debug Log: [sway.log](https://gist.githubusercontent.com/RPigott/998852adb061935a17504037181926fd/raw/5b947a143d82d092dc16aa07f328bd3c58ef1d5c/sway.log)

<details>
<summary>added sway config lines</summary>

```
assign [app_id="transmission-gtk" tiling] 5
bindsym $mod+z exec transmission-gtk
```
</details>

* Steps to reproduce:

1. Assign a view with 'app_id' and 'tiling' criteria to a (non-focused?) workspace (in sway config)
2. Create a view matching the criteria
3. Segfault

I think that's it actually. I used transmission-gtk. I haven't tested with other applications. Maybe xdg-shell specific looking at the stack trace, but I don't know. Let me know if you can/can't reproduce.

<details>
<summary>
stack trace
</summary>

```
#0  0x0000557d6c7e7d61 in container_is_floating (container=0x0) at ../sway/sway/tree/container.c:805
#1  0x0000557d6c7b473f in criteria_matches_view (view=0x557d6d564900, criteria=0x557d6d037e30) at ../sway/sway/criteria.c:190
#2  0x0000557d6c7b473f in criteria_matches_view (criteria=0x557d6d037e30, view=0x557d6d564900) at ../sway/sway/criteria.c:100
#3  0x0000557d6c7b4915 in criteria_for_view (view=view@entry=0x557d6d564900, types=types@entry=(CT_ASSIGN_OUTPUT | CT_ASSIGN_WORKSPACE | CT_ASSIGN_WORKSPACE_NUMBER)) at ../sway/sway/criteria.c:229
        criteria = 0x557d6d037e30
        i = 1
        criterias = 0x557d6d009450
        matches = 0x557d6d039d20
#4  0x0000557d6c7ed47a in select_workspace (view=0x557d6d564900) at ../sway/sway/tree/view.c:475
        seat = 0x557d6d0057c0
        criterias = <optimized out>
        ws = <optimized out>
        node = <optimized out>
        __PRETTY_FUNCTION__ = "select_workspace"
        __PRETTY_FUNCTION__ = "view_map"
        ws = <optimized out>
        seat = <optimized out>
        node = <optimized out>
        target_sibling = <optimized out>
#5  0x0000557d6c7ed47a in view_map (view=view@entry=0x557d6d564900, wlr_surface=0x557d6d564440, fullscreen=<optimized out>, fullscreen_output=<optimized out>, decoration=<optimized out>) at ../sway/sway/tree/view.c:579
        __PRETTY_FUNCTION__ = "view_map"
        ws = <optimized out>
        seat = <optimized out>
        node = <optimized out>
        target_sibling = <optimized out>
#6  0x0000557d6c7c3569 in handle_map (listener=0x557d6d564ab0, data=<optimized out>) at ../sway/sway/desktop/xdg_shell.c:431
        xdg_shell_view = 0x557d6d564900
        view = 0x557d6d564900
        xdg_surface = 0x557d6d548370
        csd = <optimized out>
#7  0x00007f85134fcffe in wlr_signal_emit_safe (signal=signal@entry=0x557d6d548468, data=data@entry=0x557d6d548370) at ../util/signal.c:29
        pos = 0x557d6d564ab0
        l = 0x557d6d564ab0
        cursor = {link = {prev = 0x557d6d564ab0, next = 0x7ffc9ba10060}, notify = 0x7f85134fcf70 <handle_noop>}
        end = {link = {prev = 0x7ffc9ba10040, next = 0x557d6d548468}, notify = 0x7f85134fcf70 <handle_noop>}
#8  0x00007f85134e174a in handle_xdg_surface_commit (wlr_surface=<optimized out>) at ../types/xdg_shell/wlr_xdg_surface.c:360
        surface = 0x557d6d548370
        __PRETTY_FUNCTION__ = "handle_xdg_surface_commit"
#9  0x00007f85134f83aa in surface_commit_pending (surface=surface@entry=0x557d6d564440) at ../types/wlr_surface.c:372
        invalid_buffer = true
        subsurface = 0x557d6d564628
#10 0x00007f85134f86a8 in surface_commit (client=<optimized out>, resource=<optimized out>) at ../types/wlr_surface.c:444
        surface = 0x557d6d564440
        subsurface = <optimized out>
#11 0x00007f85127e16d0 in ffi_call_unix64 () at /usr/lib/libffi.so.6
#12 0x00007f85127e10a0 in ffi_call () at /usr/lib/libffi.so.6
#13 0x00007f851354482f in  () at /usr/lib/libwayland-server.so.0
#14 0x00007f8513541193 in  () at /usr/lib/libwayland-server.so.0
#15 0x00007f85135427f2 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#16 0x00007f851354139c in wl_display_run () at /usr/lib/libwayland-server.so.0
#17 0x0000557d6c7b0583 in main (argc=2, argv=0x7ffc9ba10828) at ../sway/sway/main.c:400
        verbose = 0
        debug = 1
        validate = 0
        allow_unsupported_gpu = 0
        long_options = 
            {{name = 0x557d6c7f64db "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x557d6c7f91b9 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x557d6c7f64e0 "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x557d6c7f64e9 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x557d6c7f643f "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x557d6c7f55df "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x557d6c7f64ef "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x557d6c7f64fe "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x557d6c7f650e "my-next-gpu-wont-be-nvidia", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        config_path = 0x0
        usage = 0x557d6c7f6820 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = <optimized out>
```
</details>

**Comment by RPigott** [comment]
Fixed by #4580 .
