### ISSUE TITLE
sway 1.2 freezing (but not crashing) after monitors power back on

### ISSUE THREAD

**Issue by jpeeler** [swaywm/sway#4601]
This problem is not easily reproducible, happens about twice a week or so. After the monitors are put to sleep (either directly `swaymsg "output * dpms off"` or in this case indirectly via swayidle) occasionally after trying to resume sway freezes. I've checked and sway has not crashed, but has simply become unresponsive:

$ strace -p 3405
trace: Process 3405 attached
futex(0x55a29053b598, FUTEX_WAIT_PRIVATE, 2, NULL

Debug log gist: https://gist.github.com/jpeeler/d0c5a573b611a292bbaf8fb83c490bf5

The screens just remain powered on, but are just black.

**Comment by Emantor** [comment]
Which graphics card are you using? The debug log is truncated and does not contain the full information. Are the last lines truly the last log entries? This could indicate an infinite loop inside the DRM connector scanning code.

**Comment by dinnymate** [comment]
I'm experiencing this too, in 1.2-rc1. I have an intel hd graphics 620. I also have an AMD card if that helps (amdgpu driver).

**Comment by cpdef** [comment]
Me too, sometimes i can fix that unplugging a usb device and replugging it, idk whether it is related.
1.1-rc1-4-g8c8e6a6c

**Comment by jpeeler** [comment]
@Emantor Yes, that is the very last log entry. Sway becomes totally unresponsive.

I have an intel and nvidia card. Here's the output of drm_info: https://gist.github.com/jpeeler/fd4249f443618f0df168966f9a8d20c2.

This will be quite an interesting bug if a USB removal is a workaround. Will try it the next time the error occurs.

**Comment by Emantor** [comment]
Which kernel versions are these? The log indicates a legacy backend which I do not expect for modern intel or amdgpu cards.

**Comment by jpeeler** [comment]
Kernel version: 5.2.16-200.fc30.x86_64. Can you elaborate on what backend you are referring to? Just to clarify, there is no AMD in use here (I assume you meant nouveau).

**Comment by Emantor** [comment]
Inside wlroots the drm backend implements the `atomic` and `legacy` interface. The logfile you posted uses the `legacy` interface to interact with the kernel driver and from the small log snippet you posted its not clear which card does the rendering in your setup. For more info you can dive into [the linux gpu driver docs on KMS](https://dri.freedesktop.org/docs/drm/gpu/drm-kms.html). Also I just noticed that this is for 1.2, can you test with latest master to try and reproduce the issue?

**Comment by dinnymate** [comment]
Any progress on this? Sway is essentially unusable, i have to reboot every time i close my laptop lid. Can't even switch ttys.

**Comment by ascent12** [comment]
A stacktrace of the sway process would be helpful. Being stuck on a futex call seems very odd.

**Comment by jpeeler** [comment]
Ok, apparently this issue doesn't occur as often as I thought, more like every 2-3 weeks. Anyway, here's the gdb output that's hopefully sufficient. I'm using the package in Fedora.

```
Thread 3 (Thread 0x7f002a920700 (LWP 2700)):
#0  0x00007f00390393c5 in pthread_cond_wait@@GLIBC_2.3.2 () at /lib64/libpthread.so.0
#1  0x00007f002f89fb4b in util_queue_thread_func () at /usr/lib64/dri/nouveau_dri.so
#2  0x00007f002f89f75b in impl_thrd_routine () at /usr/lib64/dri/nouveau_dri.so
#3  0x00007f00390334c0 in start_thread () at /lib64/libpthread.so.0
#4  0x00007f0039148553 in clone () at /lib64/libc.so.6

Thread 2 (Thread 0x7f00348db700 (LWP 2693)):
#0  0x00007f00390393c5 in pthread_cond_wait@@GLIBC_2.3.2 () at /lib64/libpthread.so.0
#1  0x00007f00353ed6fb in util_queue_thread_func () at /usr/lib64/dri/i965_dri.so
#2  0x00007f00353ed30b in impl_thrd_routine () at /usr/lib64/dri/i965_dri.so
#3  0x00007f00390334c0 in start_thread () at /lib64/libpthread.so.0
#4  0x00007f0039148553 in clone () at /lib64/libc.so.6

Thread 1 (Thread 0x7f0035f16ac0 (LWP 2689)):
#0  0x00007f003903c73d in __lll_lock_wait () at /lib64/libpthread.so.0
#1  0x00007f0039035ce9 in pthread_mutex_lock () at /lib64/libpthread.so.0
#2  0x00007f00340a4273 in eglMakeCurrent () at /lib64/libEGL_mesa.so.0
#3  0x00007f0038bf0f30 in  () at /lib64/libEGL.so.1
#4  0x00007f00392d9f95 in wlr_egl_make_current () at /lib64/libwlroots.so.3
#5  0x00007f00392dc103 in gles2_texture_destroy () at /lib64/libwlroots.so.3
#6  0x00007f0038bb5f27 in gbm_bo_destroy () at /lib64/libgbm.so.1
#7  0x00007f00340b8ed8 in dri2_drm_destroy_surface () at /lib64/libEGL_mesa.so.0
#8  0x00007f00340b4c76 in dri2_make_current () at /lib64/libEGL_mesa.so.0
#9  0x00007f00340a436d in eglMakeCurrent () at /lib64/libEGL_mesa.so.0
#10 0x00007f0038bf0f30 in  () at /lib64/libEGL.so.1
#11 0x00007f00392d9f95 in wlr_egl_make_current () at /lib64/libwlroots.so.3
#12 0x00007f00392dc103 in gles2_texture_destroy () at /lib64/libwlroots.so.3
#13 0x00007f0038bb5f27 in gbm_bo_destroy () at /lib64/libgbm.so.1
#14 0x00007f00340b8ed8 in dri2_drm_destroy_surface () at /lib64/libEGL_mesa.so.0
#15 0x00007f00340a8cff in eglDestroySurface () at /lib64/libEGL_mesa.so.0
#16 0x00007f00392da7c6 in wlr_egl_destroy_surface () at /lib64/libwlroots.so.3
#17 0x00007f00392cb3f7 in finish_drm_surface () at /lib64/libwlroots.so.3
#18 0x00007f00392c8457 in dealloc_crtc () at /lib64/libwlroots.so.3
#19 0x00007f00392c85d9 in drm_connector_cleanup () at /lib64/libwlroots.so.3
#20 0x00007f00392ca256 in scan_drm_connectors () at /lib64/libwlroots.so.3
#21 0x00007f0039306cac in wlr_signal_emit_safe () at /lib64/libwlroots.so.3
#22 0x00007f00392d19a7 in udev_event () at /lib64/libwlroots.so.3
#23 0x00007f003934c36a in wl_event_loop_dispatch () at /lib64/libwayland-server.so.0
#24 0x00007f003934af25 in wl_display_run () at /lib64/libwayland-server.so.0
#25 0x000055714a9c246d in main (argc=1, argv=0x7ffcd0c895e8) at ../sway/main.c:400
        verbose = 0
        debug = 0
        validate = 0
        allow_unsupported_gpu = 0
        long_options = {{name = 0x55714aa084bd "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x55714aa0b2b9 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x55714aa084c2 "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x55714aa084cb "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x55714aa08421 "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x55714aa075e3 "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x55714aa084d1 "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x55714aa084e0 "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x55714aa084f0 "my-next-gpu-wont-be-nvidia", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        config_path = 0x0
        usage = 0x55714aa08800 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = <optimized out>
Detaching from program: /usr/bin/sway, process 2689
[Inferior 1 (process 2689) detached]
```
As far as reproducing on master, I will try to eventually do that.

**Comment by dinnymate** [comment]
hmm. That's strange. I can consistently freeze my whole laptop by closing the lid.
