### ISSUE TITLE
Inkscape 1.0 Beta Appimage crashes Sway.

### ISSUE THREAD

**Issue by Wychmire** [swaywm/sway#4721]
https://inkscape.org/release/inkscape-master/gnulinux/appimage/dl/

* Sway Version: sway version 1.2-37afbc4d (Nov 12 2019, branch 'master'

* Debug Log: https://0x0.st/zE0T.log

* Configuration File: I couldn't reproduce with the default config file. https://hg.sr.ht/~wychmire/dotfiles/browse/default/config/sway/config

Not using systemd so I'm uncertain how to get a stacktrace. The log mentions `note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.`, but I don't that message is from Sway.

Download the latest successful appimage build currently [this one](https://gitlab.com/inkscape/inkscape/-/jobs/348729129). Extract the zipped folder and run Inkscape (Takes a very long time to launch the first time run, less time during subsequent runs).

Select the "Draw Bezier curves and straight lines" button on the left-hand side. Click once anywhere on the canvas, move the mouse, click once more. Press Enter to create the line.

On the right-hand side, go to Stroke Style under the Fill and Stroke section. Mess with values until Sway crashes, I've found the quickest crash is by setting the width measurement to px, and then adjusting the width. Not 100% reliable, so configure Join, Cap, and Order options until crash.

**Comment by progandy** [comment]
I think these resources might help to to create/locate the coredump file When you have found the file, then you can use ```gdb <executable_path> <coredump_file_path>``` and ```bt full```.

http://man7.org/linux/man-pages/man5/core.5.html
https://linux-audit.com/understand-and-configure-core-dumps-work-on-linux/
http://www.linuxhowtos.org/Tips%20and%20Tricks/coredump.htm

**Comment by Wychmire** [comment]
Alright, I think I got it. I ran `gdb /usr/bin/sway ~/core.13342` and then once in the gdb prompt ran `bt full`. Here's the output:
```
Reading symbols from /usr/bin/sway...
(No debugging symbols found in /usr/bin/sway)
[New LWP 13342]
[New LWP 13345]
[New LWP 13355]
[New LWP 13354]
[New LWP 13360]
[New LWP 13351]
[New LWP 13346]
[New LWP 13352]
[New LWP 13349]
[New LWP 13347]
[New LWP 13356]
[New LWP 13348]
[New LWP 13353]
[New LWP 13357]
[New LWP 13359]
[New LWP 13350]
[New LWP 13358]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `sway -d'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f66bb66a583 in wl_list_insert () from /usr/lib/libwayland-server.so.0
[Current thread is 1 (Thread 0x7f66b5fdb000 (LWP 13342))]
(gdb) bt full
#0  0x00007f66bb66a583 in wl_list_insert () from /usr/lib/libwayland-server.so.0
No symbol table info available.
#1  0x000056158cd5ac0e in ?? ()
No symbol table info available.
#2  0x000056158cd5add7 in ?? ()
No symbol table info available.
#3  0x00007f66bb5e6cec in ?? () from /usr/lib/libwlroots.so.3
No symbol table info available.
#4  0x00007f66bb5e9b2d in wlr_subsurface_create () from /usr/lib/libwlroots.so.3
No symbol table info available.
#5  0x00007f66ba736a7e in ffi_call_unix64 () from /usr/lib/libffi.so.6
No symbol table info available.
#6  0x00007f66ba73643f in ffi_call () from /usr/lib/libffi.so.6
No symbol table info available.
#7  0x00007f66bb669c2d in ?? () from /usr/lib/libwayland-server.so.0
No symbol table info available.
#8  0x00007f66bb666689 in ?? () from /usr/lib/libwayland-server.so.0
No symbol table info available.
#9  0x00007f66bb667c42 in wl_event_loop_dispatch () from /usr/lib/libwayland-server.so.0
No symbol table info available.
#10 0x00007f66bb66687a in wl_display_run () from /usr/lib/libwayland-server.so.0
No symbol table info available.
#11 0x000056158cd55511 in ?? ()
No symbol table info available.
#12 0x00007f66bbe6fdeb in __libc_start_main (main=0x56158cd54020, argc=2,
    argv=0x7ffd95e02af8, init=<optimized out>, fini=<optimized out>,
    rtld_fini=<optimized out>, stack_end=0x7ffd95e02ae8) at ../csu/libc-start.c:308
        self = <optimized out>
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, 6864682971528692832, 94650557093904,
                140727117949680, 0, 0, 906475560287601760, 982399025917592672},
              mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x7ffd95e02b10,
              0x7f66bc056130}, data = {prev = 0x0, cleanup = 0x0, canceltype = -1780471024}}}
        not_first_call = <optimized out>
#13 0x000056158cd5583a in ?? ()
No symbol table info available.
```

**Comment by emersion** [comment]
The backtrace you provided doesn't contain debug symbols. This most likely happens because the Sway binary you're using doesn't have debug information bundled.

Can you try again with a manually compiled Sway binary?

**Comment by Xyene** [comment]
Closing this issue due to inactivity. If the issue persists, please feel free to reopen an issue with a new trace (including debug symbols).
