### ISSUE TITLE
swaybar segfault

### ISSUE THREAD

**Issue by jhalmen** [swaywm/sway#4749]
swaybar just crashed, hope this backtrace proves useful.
I'm using a tablet+stylus to take notes currently, i'm pretty sure the crash is related to that.
`sway version 1.2-37afbc4d (Nov 13 2019, branch 'makepkg')`

i haven't tried to reproduce it yet, but i'll update if i manage to.

backtrace:
```
#0  0x00005655048a21ab in update_cursor (seat=0x5655064829a0) at ../sway/swaybar/input.c:86
        pointer = 0x5655064829b8
        cursor_theme = 0x0
        cursor_size = <optimized out>
        env_cursor_size = <optimized out>
        scale = 1
        cursor = 0x0
#1  0x00007fd80d2f46d0 in ffi_call_unix64 () at /usr/lib/libffi.so.6
#2  0x00007fd80d2f40a0 in ffi_call () at /usr/lib/libffi.so.6
#3  0x00007fd80de56f8f in  () at /usr/lib/libwayland-client.so.0
#4  0x00007fd80de536ba in  () at /usr/lib/libwayland-client.so.0
#5  0x00007fd80de54bfc in wl_display_dispatch_queue_pending () at /usr/lib/libwayland-client.so.0
#6  0x000056550489f4ae in display_in (fd=<optimized out>, mask=<optimized out>, data=0x5655048b6360 <swaybar>) at ../sway/swaybar/bar.c:463
        bar = 0x5655048b6360 <swaybar>
#7  0x00005655048abfdc in loop_poll (loop=0x5655064791b0) at ../sway/common/loop.c:84
        pfd = <optimized out>
        event = <optimized out>
        events = <optimized out>
        i = 0
        ms = 2147483647
#8  0x00005655048a04e6 in bar_run (bar=0x5655048b6360 <swaybar>) at ../sway/swaybar/bar.c:504
#9  0x000056550489f19f in main (argc=3, argv=0x7fffd50bfd38) at ../sway/swaybar/main.c:101
        socket_path = 0x565506471980 "\001"
        debug = false
        long_options =
            {{name = 0x5655048aeb68 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x5655048aeb6d "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x5655048aeb75 "socket", has_arg = 1, flag = 0x0, val = 115}, {name = 0x5655048aeb7c "bar_id", has_arg = 1, flag = 0x0, val = 98}, {name = 0x5655048aeb83 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        usage = 0x5655048aebd0 "Usage: swaybar [options...]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -v, --version          Show the version number and quit.\n  -s, --socket <socket>  Connect to sway via socket.\n  -b, "...
        c = <optimized out>
```

**Comment by ianyfan** [comment]
Maybe your cursor has no left pointer? Strange

**Comment by jhalmen** [comment]
this hasn't happened in quite a while, can't remember the exact circumstances. so i'll just close this.
i'll be taking notes digitally more often in the coming months, if anything crashes again i'll open another issue.
thanks for taking a look!
