### ISSUE TITLE
Crash when unplugging keyboard

### ISSUE THREAD

**Issue by minus7** [swaywm/sway#4752]
Sway crashes when any keyboard is unplugged. In my case a YubiKey, but a standard USB keyboard has the same effect.

Likely related to #4744 

sway version 1.2-3334d11a (Nov 25 2019, branch 'master')

Backtrace:
```
(gdb) bt                                                                                                                      
#0  0x00007ffff7f2ba01 in wlr_keyboard_group_remove_keyboard (group=0x0, keyboard=0x555556160ef0)                             
    at ../subprojects/wlroots/types/wlr_keyboard_group.c:299                                                                  
#1  0x000055555558492d in sway_keyboard_group_remove (keyboard=0x55555613ff20) at ../sway/input/keyboard.c:670                
#2  0x0000555555585402 in sway_keyboard_destroy (keyboard=0x55555613ff20) at ../sway/input/keyboard.c:921                     
#3  0x000055555558689d in seat_device_destroy (seat_device=0x555556161080) at ../sway/input/seat.c:38                         
#4  0x000055555558887e in seat_remove_device (seat=0x555555a8c750, input_device=0x555556160a70) at ../sway/input/seat.c:811   
#5  0x000055555557ee4a in handle_device_destroy (listener=0x555556160a90, data=0x555556160e70)                                
    at ../sway/input/input-manager.c:188                                                                                      
#6  0x00007ffff7f45240 in wlr_signal_emit_safe (signal=0x555556160eb0, data=0x555556160e70)                                   
    at ../subprojects/wlroots/util/signal.c:29                                                                                
#7  0x00007ffff7f29201 in wlr_input_device_destroy (dev=0x555556160e70) at ../subprojects/wlroots/types/wlr_input_device.c:34 
#8  0x00007ffff7eed1d9 in handle_device_removed (backend=0x555555609940, libinput_dev=0x55555607ae10)                         
    at ../subprojects/wlroots/backend/libinput/events.c:214                                                                   
#9  0x00007ffff7eed4c6 in handle_libinput_event (backend=0x555555609940, event=0x555556164a80)                                
    at ../subprojects/wlroots/backend/libinput/events.c:234                                                                   
#10 0x00007ffff7eec36a in handle_libinput_readable (fd=35, mask=1, _backend=0x555555609940)                                   
    at ../subprojects/wlroots/backend/libinput/backend.c:41                                                                   
#11 0x00007ffff78d37f2 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0                                        
#12 0x00007ffff78d239c in wl_display_run () at /usr/lib/libwayland-server.so.0                                                
#13 0x000055555557316f in server_run (server=0x5555555df080 <server>) at ../sway/server.c:209                                 
#14 0x000055555557278f in main (argc=2, argv=0x7fffffffdf88) at ../sway/main.c:403                                            
```

**Comment by emersion** [comment]
Probably related to https://github.com/swaywm/sway/pull/4373
