### ISSUE TITLE
Sway crashes on show scratchpad when focused window already is inside the scratchpad

### ISSUE THREAD

**Issue by hakeee** [swaywm/sway#4788]
I use a rofi to focus windows, including those in scratchpad
It does this in the background `swaymsg [con_id=<id of client> focus`
This works good for top level windows in the scratchpad, and shows the client.
For "nested" clients, such as a terminal in a tabbed view, it does not show the window
If you then tried to show the scratchpad sway crashes.

* Sway Version: 1.2
* Debug Log: https://gist.github.com/hakeee/3e64be7964ed26ee38c31052502b28a4
* Configuration File: `default` but with `termite` as terminal

* Steps to reproduce the crash:
1. Start sway
2. Open a terminal 
   This terminal gets con_id=5
3. Create a tabbed view
4. Open another terminal
5. Select parent (both tabs)
6. Move to scratchpad `swaymsg move scratchpad`
7. Open a new terminal
8. Execute `swaymsg [con_id=5] focus` 
   I believe the tabbed view should appear here with the terminal foused but it does not. 
   It would be nice if it did.
9. Show scratchpad `swaymsg scratchpad show`

* Stack Trace, if sway crashes: 
```
#0  0x00005574b8a91f5e in  ()
#1  0x00005574b8a92fde in  ()
#2  0x00005574b8a9c1bf in  ()
#3  0x00005574b8ac32c7 in  ()
#4  0x00005574b8aa7477 in  ()
#5  0x00005574b8ab026a in  ()
#6  0x00007fc240f5cb0e in  () at /usr/lib/libwlroots.so.3
#7  0x00007fc240f4afdd in wlr_keyboard_notify_key () at /usr/lib/libwlroots.so.3
#8  0x00007fc240f213b7 in  () at /usr/lib/libwlroots.so.3
#9  0x00007fc240f2032c in  () at /usr/lib/libwlroots.so.3
#10 0x00007fc240fa37f2 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#11 0x00007fc240fa239c in wl_display_run () at /usr/lib/libwayland-server.so.0
#12 0x00005574b8a86592 in  ()
#13 0x00007fc2415a5153 in __libc_start_main () at /usr/lib/libc.so.6
#14 0x00005574b8a868be in  ()
```

**Comment by RPigott** [comment]
I can reproduce.

OP's backtrace is missing debug symbols, so here's a proper one form master:

<details>
<summary>
proper backtrace ad189d27
</summary>

```
#0  0x000055d6c848ed2c in arrange_workspace (workspace=workspace@entry=0x0) at ../sway/sway/tree/arrange.c:251
        output = <optimized out>
        area = <optimized out>
        first_arrange = <optimized out>
        prev_x = <optimized out>
        prev_y = <optimized out>
        diff_x = <optimized out>
        diff_y = <optimized out>
#1  0x000055d6c848f0f5 in arrange_workspace (workspace=workspace@entry=0x0) at ../sway/sway/tree/arrange.c:252
#2  0x000055d6c8493792 in root_scratchpad_hide (con=0x55d6ca785870) at ../sway/sway/tree/root.c:166
        seat = 0x55d6c9b811b0
        focus = 0x55d6ca76b700
        ws = 0x0
#3  0x000055d6c8485579 in scratchpad_toggle_auto () at ../sway/sway/commands/scratchpad.c:34
        seat = <optimized out>
        focus = <optimized out>
        ws = <optimized out>
        con = <optimized out>
        __PRETTY_FUNCTION__ = "scratchpad_toggle_auto"
        error = <optimized out>
#4  0x000055d6c8485579 in cmd_scratchpad (argc=<optimized out>, argv=<optimized out>) at ../sway/sway/commands/scratchpad.c:127
        error = <optimized out>
#5  0x000055d6c8457548 in execute_command (_exec=<optimized out>, seat=seat@entry=0x55d6c9b811b0, con=0x0) at ../sway/sway/commands.c:286
        node = <optimized out>
        res = <optimized out>
        argc = 2
        argv = 0x55d6ca5d50a0
        handler = 0x55d6c84bb120 <command_handlers+256>
        cmd = <optimized out>
        matched_delim = 0 '\000'
        views = 0x0
        __PRETTY_FUNCTION__ = "execute_command"
        exec = 0x55d6ca6f9df0 "scratchpad show"
        head = 0x0
        res_list = 0x55d6ca628810
#6  0x000055d6c847baf3 in seat_execute_command (seat=seat@entry=0x55d6c9b811b0, binding=0x55d6ca10eb90) at ../sway/sway/commands/bind.c:624
        con = <optimized out>
        res_list = <optimized out>
        success = <optimized out>
#7  0x000055d6c846eb8b in handle_key_event (keyboard=<optimized out>, event=0x7fff1df8dd20) at ../sway/sway/input/keyboard.c:422
        seat = 0x55d6c9b811b0
        wlr_seat = 0x55d6ca0b0e00
        wlr_device = 0x55d6ca39ab70
        device_identifier = 0x55d6ca6c2990 "0:0:"
        exact_identifier = <optimized out>
        input_inhibited = <optimized out>
        keycode = 20
        raw_keysyms = 0x55d6ca3bbe68
        raw_modifiers = 64
        raw_keysyms_len = <optimized out>
        translated_keysyms = 0x55d6ca3bbe68
        translated_modifiers = 64
        translated_keysyms_len = 1
        code_modifiers = <optimized out>
        handled = <optimized out>
        binding_released = 0x0
        binding = 0x55d6ca10eb90
#8  0x00007f913c6e55ee in wlr_signal_emit_safe (signal=signal@entry=0x55d6ca317b30, data=data@entry=0x7fff1df8dd20) at ../util/signal.c:29
        pos = 0x55d6ca3b7b60
        l = 0x55d6ca3b7b60
        cursor = {link = {prev = 0x55d6ca3b7b60, next = 0x7fff1df8dc20}, notify = 0x7f913c6e5560 <handle_noop>}
        end = {link = {prev = 0x7fff1df8dc00, next = 0x55d6ca317b30}, notify = 0x7f913c6e5560 <handle_noop>}
#9  0x00007f913c6d3695 in wlr_keyboard_notify_key (keyboard=0x55d6ca317a30, event=0x7fff1df8dd20) at ../types/wlr_keyboard.c:96
        updated = <optimized out>
#10 0x00007f913c6e55ee in wlr_signal_emit_safe (signal=signal@entry=0x55d6ca5ef4c0, data=data@entry=0x7fff1df8dd20) at ../util/signal.c:29
        pos = 0x55d6ca61dec8
        l = 0x55d6ca61dec8
        cursor = {link = {prev = 0x55d6ca61dec8, next = 0x55d6ca5fa6a8}, notify = 0x7f913c6e5560 <handle_noop>}
        end = {link = {prev = 0x55d6ca5fa6a8, next = 0x55d6ca5ef4c0}, notify = 0x7f913c6e5560 <handle_noop>}
#11 0x00007f913c6d3695 in wlr_keyboard_notify_key (keyboard=0x55d6ca5ef3c0, event=0x7fff1df8dd20) at ../types/wlr_keyboard.c:96
        updated = <optimized out>
#12 0x00007f913c6a9b47 in handle_keyboard_key (event=<optimized out>, libinput_dev=<optimized out>) at ../backend/libinput/keyboard.c:82
        wlr_dev = 0x55d6ca5d7810
        kbevent = 0x55d6ca7de210
        wlr_event = {time_msec = 4426224, keycode = 12, update_state = true, state = WLR_KEY_PRESSED}
        state = <optimized out>
#13 0x00007f913c6a8adc in handle_libinput_readable (fd=<optimized out>, mask=<optimized out>, _backend=0x55d6c99cfd40) at ../backend/libinput/backend.c:41
        backend = 0x55d6c99cfd40
        event = 0x55d6ca7de210
#14 0x00007f913c72b7f2 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#15 0x00007f913c72a39c in wl_display_run () at /usr/lib/libwayland-server.so.0
#16 0x000055d6c845658c in main (argc=1, argv=0x7fff1df8e0e8) at ../sway/sway/main.c:403
        verbose = 0
        debug = 0
        validate = 0
        allow_unsupported_gpu = 0
        long_options = 
            {{name = 0x55d6c849f47b "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x55d6c84a26d1 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x55d6c849f480 "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x55d6c849f489 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x55d6c849f3df "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x55d6c849e57c "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x55d6c849f48f "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x55d6c849f49e "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x55d6c849f4ae "my-next-gpu-wont-be-nvidia", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        config_path = 0x0
        usage = 0x55d6c849f7e0 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = <optimized out>
```
</details>
