### ISSUE TITLE
Sway crashes on system suspend when swayidle is running and no windows are open

### ISSUE THREAD

**Issue by rmsacks** [swaywm/sway#4862]
### Steps to reproduce
- Start sway
- Make sure swayidle is running (I have the following command running as a systemd user service)
```
swayidle -w timeout 300 'swaylock -f -c 000000' timeout 600 'swaymsg "output * dpms off"' resume 'swaymsg "output * dpms on"' before-sleep 'swaylock -f -c 000000'
```
- Make sure there are no windows opened
- Suspend system (In my case, I close my laptop lid)

### Sway version
```
[~] > sway -v
sway version 1.2-d510684c (Jan  1 2020, branch 'master')
```

### Configuration
[Here](https://gist.github.com/rmsacks/207b53a202676fefc43f62f2d64715d9)

### Debug log
[Here](https://gist.github.com/rmsacks/abc6b10bd7cd00f7060af48200dcfd05)

### Stack trace
```
[~] > coredumpctl debug
Hint: You are currently not seeing messages from other users and the system.
      Users in groups 'adm', 'systemd-journal', 'wheel' can see all messages.
      Pass -q to turn off this notice.
           PID: 20961 (sway)
           UID: 1000 (robert)
           GID: 1000 (robert)
        Signal: 11 (SEGV)
     Timestamp: Wed 2020-01-01 23:09:36 EST (47s ago)
  Command Line: sway -d
    Executable: /usr/local/bin/sway
 Control Group: /user.slice/user-1000.slice/session-28.scope
          Unit: session-28.scope
         Slice: user-1000.slice
       Session: 28
     Owner UID: 1000 (robert)
       Boot ID: c96c93af534c47119f809e3577a3cc25
    Machine ID: 60c1530a8c1243fc87198505adac9b43
      Hostname: everest
       Storage: /var/lib/systemd/coredump/core.sway.1000.c96c93af534c47119f809e3577a3cc25.20961.1577938176000000000000.lz4
       Message: Process 20961 (sway) of user 1000 dumped core.

                Stack trace of thread 20961:
                #0  0x0000562bbc1540f5 node_is_view (sway + 0x600f5)
                #1  0x0000562bbc129fe4 seat_set_exclusive_client (sway + 0x35fe4)
                #2  0x0000562bbc11f121 handle_inhibit_activate (sway + 0x2b121)
                #3  0x00007f3282d83466 wlr_signal_emit_safe (libwlroots.so.4 + 0x86466)
                #4  0x00007f3282d67ae4 inhibit_manager_get_inhibitor (libwlroots.so.4 + 0x6aae4)
                #5  0x00007f3281b0369a ffi_call_unix64 (libffi.so.6 + 0x669a)
                #6  0x00007f3281b02fb6 ffi_call (libffi.so.6 + 0x5fb6)
                #7  0x00007f328270f82f n/a (libwayland-server.so.0 + 0xc82f)
                #8  0x00007f328270c193 n/a (libwayland-server.so.0 + 0x9193)
                #9  0x00007f328270d7f2 wl_event_loop_dispatch (libwayland-server.so.0 + 0xa7f2)
                #10 0x00007f328270c39c wl_display_run (libwayland-server.so.0 + 0x939c)
                #11 0x0000562bbc113104 server_run (sway + 0x1f104)
                #12 0x0000562bbc112724 main (sway + 0x1e724)
                #13 0x00007f32824e8153 __libc_start_main (libc.so.6 + 0x27153)
                #14 0x0000562bbc10425e _start (sway + 0x1025e)

                Stack trace of thread 20963:
                #0  0x00007f3281feac45 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfc45)
                #1  0x00007f3280df9d0c n/a (i965_dri.so + 0x4f6d0c)
                #2  0x00007f3280df9908 n/a (i965_dri.so + 0x4f6908)
                #3  0x00007f3281fe44cf start_thread (libpthread.so.0 + 0x94cf)
                #4  0x00007f32825c02d3 __clone (libc.so.6 + 0xff2d3)

                Stack trace of thread 20966:
                #0  0x00007f3281feac45 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfc45)
                #1  0x00007f3280df9d0c n/a (i965_dri.so + 0x4f6d0c)
                #2  0x00007f3280df9908 n/a (i965_dri.so + 0x4f6908)
                #3  0x00007f3281fe44cf start_thread (libpthread.so.0 + 0x94cf)
                #4  0x00007f32825c02d3 __clone (libc.so.6 + 0xff2d3)

                Stack trace of thread 20964:
                #0  0x00007f3281feac45 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfc45)
                #1  0x00007f3280df9d0c n/a (i965_dri.so + 0x4f6d0c)
                #2  0x00007f3280df9908 n/a (i965_dri.so + 0x4f6908)
                #3  0x00007f3281fe44cf start_thread (libpthread.so.0 + 0x94cf)
                #4  0x00007f32825c02d3 __clone (libc.so.6 + 0xff2d3)

                Stack trace of thread 20965:
                #0  0x00007f3281feac45 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfc45)
                #1  0x00007f3280df9d0c n/a (i965_dri.so + 0x4f6d0c)
                #2  0x00007f3280df9908 n/a (i965_dri.so + 0x4f6908)
                #3  0x00007f3281fe44cf start_thread (libpthread.so.0 + 0x94cf)
                #4  0x00007f32825c02d3 __clone (libc.so.6 + 0xff2d3)

GNU gdb (GDB) 8.3.1
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/local/bin/sway...
[New LWP 20961]
[New LWP 20963]
[New LWP 20966]
[New LWP 20964]
[New LWP 20965]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `sway -d'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000562bbc1540f5 in node_is_view (node=0x0) at ../sway/tree/node.c:44
44		return node->type == N_CONTAINER && node->sway_container->view;
[Current thread is 1 (Thread 0x7f3281609940 (LWP 20961))]
/usr/lib/../share/gcc-9.2.0/python/libstdcxx/v6/xmethods.py:731: SyntaxWarning: list indices must be integers or slices, not str; perhaps you missed a comma?
  refcounts = ['_M_refcount']['_M_pi']
(gdb) bt full
#0  0x0000562bbc1540f5 in node_is_view (node=0x0) at ../sway/tree/node.c:44
#1  0x0000562bbc129fe4 in seat_set_exclusive_client (seat=0x562bbd469d70, client=0x562bbd859010) at ../sway/input/seat.c:1204
        focus = 0x0
        now = {
          tv_sec = 140734802548204,
          tv_nsec = 140734802548200
        }
        point = 0x81ac9cdda94cf500
#2  0x0000562bbc11f121 in handle_inhibit_activate (listener=0x562bbd469b10, data=0x562bbd469cc0) at ../sway/input/input-manager.c:278
        input_manager = 0x562bbd469ac0
        seat = 0x562bbd469d70
#3  0x00007f3282d83466 in wlr_signal_emit_safe (signal=0x562bbd469cf0, data=0x562bbd469cc0) at ../subprojects/wlroots/util/signal.c:29
        pos = 0x562bbd469b10
        l = 0x562bbd469b10
        cursor = {
          link = {
            prev = 0x562bbd469b10,
            next = 0x7fff5fe9d4e0
          },
          notify = 0x7f3282d833b0 <handle_noop>
        }
        end = {
          link = {
            prev = 0x7fff5fe9d4c0,
            next = 0x562bbd469cf0
          },
          notify = 0x7f3282d833b0 <handle_noop>
        }
#4  0x00007f3282d67ae4 in inhibit_manager_get_inhibitor (client=0x562bbd859010, resource=0x562bbd8e8b90, id=3) at ../subprojects/wlroots/types/wlr_input_inhibitor.c:74
        manager = 0x562bbd469cc0
        wl_resource = 0x562bbd90a1b0
#5  0x00007f3281b0369a in ffi_call_unix64 () at /usr/lib/libffi.so.6
#6  0x00007f3281b02fb6 in ffi_call () at /usr/lib/libffi.so.6
#7  0x00007f328270f82f in  () at /usr/lib/libwayland-server.so.0
#8  0x00007f328270c193 in  () at /usr/lib/libwayland-server.so.0
#9  0x00007f328270d7f2 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#10 0x00007f328270c39c in wl_display_run () at /usr/lib/libwayland-server.so.0
#11 0x0000562bbc113104 in server_run (server=0x562bbc181100 <server>) at ../sway/server.c:209
#12 0x0000562bbc112724 in main (argc=2, argv=0x7fff5fe9dc18) at ../sway/main.c:403
        verbose = 0
        debug = 1
        validate = 0
        allow_unsupported_gpu = 0
        long_options = {{
            name = 0x562bbc164ff8 "help",
            has_arg = 0,
            flag = 0x0,
            val = 104
          }, {
            name = 0x562bbc164ffd "config",
            has_arg = 1,
            flag = 0x0,
            val = 99
          }, {
            name = 0x562bbc165004 "validate",
            has_arg = 0,
            flag = 0x0,
            val = 67
          }, {
            name = 0x562bbc16500d "debug",
            has_arg = 0,
            flag = 0x0,
            val = 100
          }, {
            name = 0x562bbc165013 "version",
            has_arg = 0,
            flag = 0x0,
            val = 118
          }, {
            name = 0x562bbc16501b "verbose",
            has_arg = 0,
            flag = 0x0,
            val = 86
          }, {
            name = 0x562bbc165023 "get-socketpath",
            has_arg = 0,
            flag = 0x0,
            val = 112
          }, {
            name = 0x562bbc165032 "unsupported-gpu",
            has_arg = 0,
            flag = 0x0,
            val = 117
          }, {
            name = 0x562bbc165042 "my-next-gpu-wont-be-nvidia",
            has_arg = 0,
            flag = 0x0,
            val = 117
          }, {
            name = 0x0,
            has_arg = 0,
            flag = 0x0,
            val = 0
          }}
        config_path = 0x0
        usage = 0x562bbc164ad0 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, then exit.\n  -d, --debug", ' ' <repeats 12 times>, "Enables full logging, including debug information.\n  -v, --version          Show the version number and quit.\n  -V, --verbose          Enables more verbose logging.\n      --get-socketpath   Gets the IPC socket path and prints it, then exits.\n\n"
        c = -1
(gdb)
```

### Fix?
I did manage to fix this issue by adding this if statement to `node_is_view()` in `sway/tree/node.c`:

```
bool node_is_view(struct sway_node *node) {
        if (!node) {
                return false;
        }
        return node->type == N_CONTAINER && node->sway_container->view;
}
```

But I haven't created a pull request yet because I don't yet know the codebase well enough to tell if this will have any unexpected side effects.

**Comment by RedSoxFan** [comment]
The issue here is that the noop output doesn't have a workspace. Since all workspaces on the outputs are empty, none get evacuated to the noop output. Either the last remaining workspace should be evacuated or a new workspace should be created for the noop output in this case. I'm not sure which would be better

**Comment by danielstaleiny** [comment]
can confirm, I observe behavior when I turn off the display and and turn it on. System never recovers.

**Comment by philipflohr** [comment]
I observer the same behavior if only external monitors are attached to my laptop and the internal screen is disabled.
The system can be recovered by switching to the console and kill sway.

**Comment by travankor** [comment]
I ran into this crash when I think another program crashed (leaving the workspace empty?).

Backtrace:
<details>
```

```
</details>

>Either the last remaining workspace should be evacuated or a new workspace should be created for the noop output in this case. I'm not sure which would be better

The first option sounds better tbh
