### ISSUE TITLE
Cannot nest Wayland sessions e.g., Sway on Sway

### ISSUE THREAD

**Issue by jbeich** [swaywm/sway#4866]
Regressed by https://github.com/swaywm/wlroots/commit/5d1ba0f44687. See also https://github.com/swaywm/wlroots/issues/1976.

Sway server creates a window for Sway client but nothing is rendered there, so it remains transparent. Can be worked around by using Sway 1.2 as a client.

Steps to reproduce:
```
$ sway # start DRM session
$ echo 'exec alacritty' >sway.config
$ sway -d -c sway.config # start Wayland session
```

Good/bad output:
```diff
@@ -72,7 +72,7 @@
 [GLES2] FS SIMD16 shader: 8 inst, 0 loops, 260 cycles, 0:0 spills:fills, Promoted 0 constants, compacted 128 to 80 bytes.
 [GLES2] VS SIMD8 shader: 20 inst, 0 loops, 79 cycles, 0:0 spills:fills, Promoted 0 constants, compacted 320 to 240 bytes.
 [backend/noop/backend.c:51] Creating noop backend
-[sway/main.c:366] Starting sway version 1.2-rc1-151-g658b7796 / wlroots version 0.8.1-77-ge0e5a167
+[sway/main.c:366] Starting sway version 1.2-rc1-153-g2b5e7503 / wlroots version 0.8.1-82-g31f72128
 [sway/server.c:54] Initializing Wayland server
 [types/wlr_idle.c:247] idle manager created
 [wayland] unable to lock lockfile /var/run/holo/wayland-0.lock, maybe another compositor is running
@@ -96,8 +96,11 @@
 [GLES2] FS SIMD16 shader: 5 inst, 0 loops, 34 cycles, 0:0 spills:fills, Promoted 0 constants, compacted 80 to 48 bytes.
 [GLES2] VS SIMD8 shader: 28 inst, 0 loops, 116 cycles, 0:0 spills:fills, Promoted 0 constants, compacted 448 to 336 bytes.
 [GLES2] FS SIMD16 shader: 2 inst, 0 loops, 0 cycles, 0:0 spills:fills, Promoted 0 constants, compacted 32 to 32 bytes.
-[sway/desktop/output.c:867] New output 0x80250ce00: WL-1
-[sway/config/output.c:364] Auto-detected output scale: 1.000000
+[GLES2] FS SIMD16 shader: 2 inst, 0 loops, 0 cycles, 0:0 spills:fills, Promoted 0 constants, compacted 32 to 32 bytes.
+[sway/desktop/output.c:871] New output 0x80250ce00: WL-1
+[sway/config/output.c:337] Turning on output WL-1
+[sway/config/output.c:357] Auto-detected output scale: 1.000000
+[sway/config/output.c:396] Committing output WL-1
 [sway/tree/workspace.c:284] Workspace: Generating new workspace name for output WL-1
 [sway/tree/output.c:133] Creating default workspace 1
 [sway/tree/workspace.c:64] Adding workspace 1 for output WL-1
@@ -134,61 +137,51 @@
 [sway/tree/arrange.c:292] Arranging workspace '1' at 0.000000, 0.000000
 [sway/tree/arrange.c:262] Usable area for ws: 1280x720@0,0
 [sway/tree/arrange.c:292] Arranging workspace '1' at 0.000000, 0.000000
-[sway/desktop/transaction.c:412] Transaction 0x803743830 committing with 2 instructions
-[sway/desktop/transaction.c:280] Applying transaction 0x803743830
+[sway/desktop/transaction.c:412] Transaction 0x803743800 committing with 2 instructions
+[sway/desktop/transaction.c:280] Applying transaction 0x803743800
 [sway/input/input-manager.c:216] adding device: '0:0:wayland'
 [sway/input/seat.c:817] adding device 0:0:wayland to seat seat0
 [GLES2] FS SIMD8 shader: 14 inst, 0 loops, 308 cycles, 0:0 spills:fills, Promoted 0 constants, compacted 224 to 176 bytes.
 [GLES2] FS SIMD16 shader: 14 inst, 0 loops, 322 cycles, 0:0 spills:fills, Promoted 0 constants, compacted 224 to 176 bytes.
-[GLES2] FS SIMD16 shader: 2 inst, 0 loops, 0 cycles, 0:0 spills:fills, Promoted 0 constants, compacted 32 to 32 bytes.
 [sway/config.c:644] Running deferred commands
 [sway/commands.c:255] Handling command 'exec alacritty'
 [sway/commands/exec_always.c:46] Executing alacritty
-[sway/commands/exec_always.c:87] Child process created with pid 55962
-[sway/tree/root.c:281] Recording workspace for process 55962
+[sway/commands/exec_always.c:87] Child process created with pid 76218
+[sway/tree/root.c:281] Recording workspace for process 76218
 [sway/server.c:208] Running compositor on wayland display 'wayland-1'
 [GLES2] FS SIMD16 shader: 2 inst, 0 loops, 0 cycles, 0:0 spills:fills, Promoted 0 constants, compacted 32 to 32 bytes.
-[GLES2] FS SIMD16 shader: 2 inst, 0 loops, 0 cycles, 0:0 spills:fills, Promoted 0 constants, compacted 32 to 32 bytes.
 [sway/desktop/layer_shell.c:178] Usable area changed, rearranging output
 [sway/tree/arrange.c:262] Usable area for ws: 1770x710@0,0
 [sway/tree/arrange.c:292] Arranging workspace '1' at 0.000000, 0.000000
 [sway/tree/arrange.c:262] Usable area for ws: 1770x710@0,0
 [sway/tree/arrange.c:292] Arranging workspace '1' at 0.000000, 0.000000
-[sway/desktop/transaction.c:412] Transaction 0x803743980 committing with 1 instructions
-[sway/desktop/transaction.c:280] Applying transaction 0x803743980
+[sway/desktop/transaction.c:412] Transaction 0x803743830 committing with 1 instructions
+[sway/desktop/transaction.c:280] Applying transaction 0x803743830
 [sway/tree/arrange.c:262] Usable area for ws: 1770x710@0,0
 [sway/tree/arrange.c:292] Arranging workspace '1' at 0.000000, 0.000000
-[sway/desktop/transaction.c:412] Transaction 0x803743980 committing with 1 instructions
-[sway/desktop/transaction.c:280] Applying transaction 0x803743980
-[GLES2] FS SIMD16 shader: 2 inst, 0 loops, 0 cycles, 0:0 spills:fills, Promoted 0 constants, compacted 32 to 32 bytes.
+[sway/desktop/transaction.c:412] Transaction 0x803743830 committing with 1 instructions
+[sway/desktop/transaction.c:280] Applying transaction 0x803743830
 [types/wlr_surface.c:607] New wlr_surface 0x80250d880 (res 0x8037ae200)
-[types/wlr_relative_pointer_v1.c:146] relative_pointer_v1 0x80373e170 created for client 0x803785880
-[types/wlr_surface.c:607] New wlr_surface 0x80250dc00 (res 0x8037b0400)
+[types/wlr_relative_pointer_v1.c:146] relative_pointer_v1 0x80373e9c0 created for client 0x803785b00
+[types/wlr_surface.c:607] New wlr_surface 0x80250dc00 (res 0x8037aec00)
 [types/wlr_surface.c:607] New wlr_surface 0x80250df80 (res 0x8037aeb00)
 [types/wlr_surface.c:607] New wlr_surface 0x80250e300 (res 0x8037ae600)
 [types/wlr_surface.c:607] New wlr_surface 0x80250e680 (res 0x8037adf00)
 [types/wlr_surface.c:607] New wlr_surface 0x80250ea00 (res 0x803779f80)
 [types/wlr_surface.c:607] New wlr_surface 0x80250ed80 (res 0x803779980)
-[types/xdg_shell/wlr_xdg_surface.c:442] new xdg_surface 0x803785b00 (res 0x8037a9f00)
+[types/xdg_shell/wlr_xdg_surface.c:442] new xdg_surface 0x80381b280 (res 0x8037a9f00)
 [sway/desktop/xdg_shell.c:498] New xdg_shell toplevel title='(null)' app_id='(null)'
-[types/wlr_xdg_decoration_v1.c:202] new xdg_toplevel_decoration 0x803802460 (res 0x8037aa100)
+[types/wlr_xdg_decoration_v1.c:202] new xdg_toplevel_decoration 0x8038022a0 (res 0x8037aa100)
 [types/wlr_surface.c:607] New wlr_surface 0x80250f100 (res 0x8037b1d00)
-[GLES2] FS SIMD16 shader: 2 inst, 0 loops, 0 cycles, 0:0 spills:fills, Promoted 0 constants, compacted 32 to 32 bytes.
-[GLES2] FS SIMD16 shader: 2 inst, 0 loops, 0 cycles, 0:0 spills:fills, Promoted 0 constants, compacted 32 to 32 bytes.
 [sway/tree/root.c:237] Looking up workspace for pid 0
 [sway/tree/arrange.c:262] Usable area for ws: 1770x710@0,0
 [sway/tree/arrange.c:292] Arranging workspace '1' at 0.000000, 0.000000
-[sway/tree/arrange.c:77] Arranging 0x7fffffffd7c0 horizontally
+[sway/tree/arrange.c:77] Arranging 0x7fffffffd7d0 horizontally
 [sway/tree/arrange.c:262] Usable area for ws: 1770x710@0,0
 [sway/tree/arrange.c:292] Arranging workspace '1' at 0.000000, 0.000000
-[sway/tree/arrange.c:77] Arranging 0x7fffffffd860 horizontally
-[sway/desktop/transaction.c:412] Transaction 0x8034ad3d0 committing with 3 instructions
-[GLES2] FS SIMD16 shader: 2 inst, 0 loops, 0 cycles, 0:0 spills:fills, Promoted 0 constants, compacted 32 to 32 bytes.
-[sway/desktop/transaction.c:489] Transaction 0x8034ad3d0 is ready
-[sway/desktop/transaction.c:280] Applying transaction 0x8034ad3d0
-[sway/tree/container.c:1133] Container 0x8024f3e80 entered output 0x803814200
-[GLES2] FS SIMD16 shader: 2 inst, 0 loops, 0 cycles, 0:0 spills:fills, Promoted 0 constants, compacted 32 to 32 bytes.
-[GLES2] FS SIMD16 shader: 2 inst, 0 loops, 0 cycles, 0:0 spills:fills, Promoted 0 constants, compacted 32 to 32 bytes.
-[GLES2] FS SIMD16 shader: 2 inst, 0 loops, 0 cycles, 0:0 spills:fills, Promoted 0 constants, compacted 32 to 32 bytes.
-[GLES2] FS SIMD16 shader: 2 inst, 0 loops, 0 cycles, 0:0 spills:fills, Promoted 0 constants, compacted 32 to 32 bytes.
-^Cthread 'main' panicked at 'Failed to read from wayland socket: Broken pipe (os error 32)', alacritty-0.4.0/cargo-crates/wayland-client-0.23.6/src/lib.rs:288:33
+[sway/tree/arrange.c:77] Arranging 0x7fffffffd870 horizontally
+[sway/desktop/transaction.c:412] Transaction 0x803743d10 committing with 3 instructions
+[sway/desktop/transaction.c:377] Transaction 0x803743d10 timed out (1 waiting)
+[sway/desktop/transaction.c:280] Applying transaction 0x803743d10
+[sway/tree/container.c:1133] Container 0x8024f1400 entered output 0x803814200
+^Cthread 'main' panicked at 'Wayland connection lost.: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', src/libcore/result.rs:1165:5
```

**Comment by jbeich** [comment]
Originally found via Cage (nesting fullscreen Firefox windows) but then I could reproduce on Wayfire and even Sway despite ef2332f7a648.

**Comment by jbeich** [comment]
... despite Sway adapting to new wlroots API

**Comment by emersion** [comment]
Fixed in https://github.com/swaywm/wlroots/pull/1977
