### ISSUE TITLE
Spurious crash when closing an X window

### ISSUE THREAD

**Issue by YaLTeR** [swaywm/sway#4901]
* Sway Version: 1.2-1e2a2b07 (Jan  7 2020, branch 'master')
* Configuration File: [1](https://github.com/YaLTeR/dotfiles/blob/89e97240380ad2346e20b065cb462c7e1ba14b1b/common/.config/sway/config) [2](https://github.com/YaLTeR/dotfiles/blob/89e97240380ad2346e20b065cb462c7e1ba14b1b/desktop/.config/sway/local)

I was playing [Celeste](https://store.steampowered.com/app/504230/Celeste/) with full-screen mode enabled, then I quit it with <kbd>Meta</kbd>+<kbd>Q</kbd> (my close window sway hotkey). This has never caused a crash before.

* Stack Trace, if sway crashes:
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  is_transient_for (child=0x5624d357e740, ancestor=0x5624d357e740) at ../sway/sway/desktop/xwayland.c:274

269		if (xwayland_view_from_view(child) == NULL) {
270			return false;
271		}
272		struct wlr_xwayland_surface *surface = child->wlr_xwayland_surface;
273		while (surface) {
274			if (surface->parent == ancestor->wlr_xwayland_surface) {
275				return true;
276			}
277			surface = surface->parent;
278		}

Thread 21 (Thread 0x7f2b7effd700 (LWP 1163)):
#0  0x00007f2bbcc11c45 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2bb5e95a5c in  () at /usr/lib/dri/radeonsi_dri.so
#2  0x00007f2bb5e95658 in  () at /usr/lib/dri/radeonsi_dri.so
#3  0x00007f2bbcc0b4cf in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f2bbcd232d3 in clone () at /usr/lib/libc.so.6

Thread 20 (Thread 0x7f2b7e7fc700 (LWP 1164)):
#0  0x00007f2bbcc11c45 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2bb5e95a5c in  () at /usr/lib/dri/radeonsi_dri.so
#2  0x00007f2bb5e95658 in  () at /usr/lib/dri/radeonsi_dri.so
#3  0x00007f2bbcc0b4cf in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f2bbcd232d3 in clone () at /usr/lib/libc.so.6

Thread 19 (Thread 0x7f2b7ffff700 (LWP 1161)):
#0  0x00007f2bbcc11c45 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2bb5e95a5c in  () at /usr/lib/dri/radeonsi_dri.so
#2  0x00007f2bb5e95658 in  () at /usr/lib/dri/radeonsi_dri.so
#3  0x00007f2bbcc0b4cf in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f2bbcd232d3 in clone () at /usr/lib/libc.so.6

Thread 18 (Thread 0x7f2ba77fe700 (LWP 1155)):
#0  0x00007f2bbcc11c45 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2bb5e95a5c in  () at /usr/lib/dri/radeonsi_dri.so
#2  0x00007f2bb5e95658 in  () at /usr/lib/dri/radeonsi_dri.so
#3  0x00007f2bbcc0b4cf in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f2bbcd232d3 in clone () at /usr/lib/libc.so.6

Thread 17 (Thread 0x7f2ba5ffb700 (LWP 1158)):
#0  0x00007f2bbcc11c45 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2bb5e95a5c in  () at /usr/lib/dri/radeonsi_dri.so
#2  0x00007f2bb5e95658 in  () at /usr/lib/dri/radeonsi_dri.so
#3  0x00007f2bbcc0b4cf in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f2bbcd232d3 in clone () at /usr/lib/libc.so.6

Thread 16 (Thread 0x7f2ba4ff9700 (LWP 1160)):
#0  0x00007f2bbcc11c45 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2bb5e95a5c in  () at /usr/lib/dri/radeonsi_dri.so
#2  0x00007f2bb5e95658 in  () at /usr/lib/dri/radeonsi_dri.so
#3  0x00007f2bbcc0b4cf in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f2bbcd232d3 in clone () at /usr/lib/libc.so.6

Thread 15 (Thread 0x7f2ba6ffd700 (LWP 1156)):
#0  0x00007f2bbcc11c45 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2bb5e95a5c in  () at /usr/lib/dri/radeonsi_dri.so
#2  0x00007f2bb5e95658 in  () at /usr/lib/dri/radeonsi_dri.so
#3  0x00007f2bbcc0b4cf in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f2bbcd232d3 in clone () at /usr/lib/libc.so.6

Thread 14 (Thread 0x7f2b6532d700 (LWP 1169)):
#0  0x00007f2bbcc11c45 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2b67027d0c in  () at /usr/lib/dri/i965_dri.so
#2  0x00007f2b67027908 in  () at /usr/lib/dri/i965_dri.so
#3  0x00007f2bbcc0b4cf in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f2bbcd232d3 in clone () at /usr/lib/libc.so.6

Thread 13 (Thread 0x7f2b7f7fe700 (LWP 1162)):
#0  0x00007f2bbcc11c45 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2bb5e95a5c in  () at /usr/lib/dri/radeonsi_dri.so
[m#2  0x00007f2bb5e95658 in  () at /usr/lib/dri/radeonsi_dri.so
#3  0x00007f2bbcc0b4cf in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f2bbcd232d3 in clone () at /usr/lib/libc.so.6

Thread 12 (Thread 0x7f2bacf0a700 (LWP 1153)):
#0  0x00007f2bbcc11c45 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2bb5e95a5c in  () at /usr/lib/dri/radeonsi_dri.so
#2  0x00007f2bb5e95658 in  () at /usr/lib/dri/radeonsi_dri.so
#3  0x00007f2bbcc0b4cf in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f2bbcd232d3 in clone () at /usr/lib/libc.so.6

Thread 11 (Thread 0x7f2bae862700 (LWP 1150)):
#0  0x00007f2bbcc11c45 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2bb5e95a5c in  () at /usr/lib/dri/radeonsi_dri.so
#2  0x00007f2bb5e95658 in  () at /usr/lib/dri/radeonsi_dri.so
#3  0x00007f2bbcc0b4cf in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f2bbcd232d3 in clone () at /usr/lib/libc.so.6

Thread 10 (Thread 0x7f2ba7fff700 (LWP 1154)):
#0  0x00007f2bbcc11c45 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2bb5e95a5c in  () at /usr/lib/dri/radeonsi_dri.so
#2  0x00007f2bb5e95658 in  () at /usr/lib/dri/radeonsi_dri.so
#3  0x00007f2bbcc0b4cf in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f2bbcd232d3 in clone () at /usr/lib/libc.so.6

Thread 9 (Thread 0x7f2b65b2e700 (LWP 1168)):
#0  0x00007f2bbcc11c45 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2b67027d0c in  () at /usr/lib/dri/i965_dri.so
#2  0x00007f2b67027908 in  () at /usr/lib/dri/i965_dri.so
#3  0x00007f2bbcc0b4cf in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f2bbcd232d3 in clone () at /usr/lib/libc.so.6

Thread 8 (Thread 0x7f2b6632f700 (LWP 1167)):
#0  0x00007f2bbcc11c45 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2b67027d0c in  () at /usr/lib/dri/i965_dri.so
#2  0x00007f2b67027908 in  () at /usr/lib/dri/i965_dri.so
#3  0x00007f2bbcc0b4cf in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f2bbcd232d3 in clone () at /usr/lib/libc.so.6

Thread 7 (Thread 0x7f2ba57fa700 (LWP 1159)):
#0  0x00007f2bbcc11c45 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2bb5e95a5c in  () at /usr/lib/dri/radeonsi_dri.so
#2  0x00007f2bb5e95658 in  () at /usr/lib/dri/radeonsi_dri.so
#3  0x00007f2bbcc0b4cf in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f2bbcd232d3 in clone () at /usr/lib/libc.so.6

Thread 6 (Thread 0x7f2b67fff700 (LWP 1165)):
#0  0x00007f2bbcc11c45 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2bb5e95a5c in  () at /usr/lib/dri/radeonsi_dri.so
#2  0x00007f2bb5e95658 in  () at /usr/lib/dri/radeonsi_dri.so
#3  0x00007f2bbcc0b4cf in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f2bbcd232d3 in clone () at /usr/lib/libc.so.6

Thread 5 (Thread 0x7f2ba67fc700 (LWP 1157)):
#0  0x00007f2bbcc11c45 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2bb5e95a5c in  () at /usr/lib/dri/radeonsi_dri.so
#2  0x00007f2bb5e95658 in  () at /usr/lib/dri/radeonsi_dri.so
#3  0x00007f2bbcc0b4cf in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f2bbcd232d3 in clone () at /usr/lib/libc.so.6

Thread 4 (Thread 0x7f2badf0c700 (LWP 1151)):
#0  0x00007f2bbcc11c45 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2bb5e95a5c in  () at /usr/lib/dri/radeonsi_dri.so
#2  0x00007f2bb5e95658 in  () at /usr/lib/dri/radeonsi_dri.so
#3  0x00007f2bbcc0b4cf in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f2bbcd232d3 in clone () at /usr/lib/libc.so.6

Thread 3 (Thread 0x7f2b66b30700 (LWP 1166)):
#0  0x00007f2bbcc11c45 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2b67027d0c in  () at /usr/lib/dri/i965_dri.so
#2  0x00007f2b67027908 in  () at /usr/lib/dri/i965_dri.so
#3  0x00007f2bbcc0b4cf in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f2bbcd232d3 in clone () at /usr/lib/libc.so.6

Thread 2 (Thread 0x7f2bad70b700 (LWP 1152)):
#0  0x00007f2bbcc11c45 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2bb5e95a5c in  () at /usr/lib/dri/radeonsi_dri.so
#2  0x00007f2bb5e95658 in  () at /usr/lib/dri/radeonsi_dri.so
#3  0x00007f2bbcc0b4cf in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f2bbcd232d3 in clone () at /usr/lib/libc.so.6

Thread 1 (Thread 0x7f2bb6c5da00 (LWP 1098)):
#0  0x00005624d0e48da0 in is_transient_for (child=0x5624d357e740, ancestor=0x5624d357e740) at ../sway/sway/desktop/xwayland.c:274
        surface = 0x71
#1  0x00005624d0e16d25 in output_render (output=output@entry=0x5624d2e35480, when=when@entry=0x7ffff8b0f390, damage=damage@entry=0x7ffff8b0f3a0) at ../sway/sway/desktop/render.c:1022
        floater = 0x5624d35af870
        i = 0
        clear_color = {0, 0, 0, 1}
        nrects = 1
        rects = <optimized out>
        wlr_output = 0x5624d2e79840
        renderer = 0x5624d2231fd0
        __PRETTY_FUNCTION__ = "output_render"
        workspace = 0x5624d35157c0
        fullscreen_con = 0x5624d35af870
        seat = <optimized out>
        focus = <optimized out>
        width = -366864128
        height = 1
        frame_damage = {extents = {x1 = -756574144, y1 = 22052, x2 = -756853136, y2 = 22052}, data = 0x7ffff8b0f3a0}
        transform = <optimized out>
#2  0x00005624d0e13632 in output_repaint_timer_handler (data=0x5624d2e35480) at ../sway/sway/desktop/output.c:562
        now = {tv_sec = 7667, tv_nsec = 960792875}
        output = 0x5624d2e35480
        surface_needs_frame = true
        workspace = <optimized out>
        fullscreen_con = <optimized out>
        needs_frame = true
        damage = {extents = {x1 = 0, y1 = 0, x2 = 2560, y2 = 1440}, data = 0x0}
#3  0x00007f2bbcf2010a in  () at /usr/lib/libwayland-server.so.0
#4  0x00007f2bbcf207f2 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#5  0x00007f2bbcf1f39c in wl_display_run () at /usr/lib/libwayland-server.so.0
#6  0x00005624d0e0558c in main (argc=2, argv=0x7ffff8b0f788) at ../sway/sway/main.c:403
        verbose = 0
        debug = 0
        validate = 0
        allow_unsupported_gpu = 1
        long_options = {{name = 0x5624d0e4f45b "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x5624d0e527b1 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x5624d0e4f460 "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x5624d0e4f469 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x5624d0e4f3bf "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x5624d0e4e55c "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x5624d0e4f46f "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x5624d0e4f47e "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x5624d0e4f48e "my-next-gpu-wont-be-nvidia", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        config_path = 0x0
        usage = 0x5624d0e4f7c0 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = <optimized out>
```

**Comment by YaLTeR** [comment]
Got the same crash with the same 0x71 surface when changing [Half-Life](https://store.steampowered.com/app/70/HalfLife/) from full-screen to windowed, which I think makes it re-create its X window.
