### ISSUE TITLE
sway crashes with segmentation fault on some X11 app

### ISSUE THREAD

**Issue by xdavidwu** [swaywm/sway#5028]
* Sway Version: 1.4-af294289

* Debug Log:

https://gist.github.com/xdavidwu/c5fe4476c3fdaa567a14ebf8fd0c81a8

gdb bt full and p *view->wlr_xwayland_surface are also in the gist above

* Stack Trace, if sway crashes:

```
#0  get_int_prop (view=0x55e0eb3f4f90, prop=VIEW_PROP_WINDOW_TYPE)
    at ../sway/desktop/xwayland.c:181
#1  0x000055e0e8a93a9c in view_get_window_type (view=0x55e0eb3f4f90)
    at ../sway/tree/view.c:128
#2  0x000055e0e8a49930 in ipc_json_describe_view
    (c=0x55e0eb3ff5c0, object=0x55e0eb42adc0) at ../sway/ipc-json.c:491
#3  0x000055e0e8a49cdc in ipc_json_describe_container
    (c=0x55e0eb3ff5c0, object=0x55e0eb42adc0) at ../sway/ipc-json.c:550
#4  0x000055e0e8a49fb5 in ipc_json_describe_node (node=0x55e0eb3ff5c0)
    at ../sway/ipc-json.c:618
#5  0x000055e0e8a4a001 in ipc_json_describe_node_recursive
    (node=0x55e0eb3ff5c0) at ../sway/ipc-json.c:629
#6  0x000055e0e8a4a177 in ipc_json_describe_node_recursive
    (node=0x55e0ea8a92b0) at ../sway/ipc-json.c:654
#7  0x000055e0e8a4a109 in ipc_json_describe_node_recursive
    (node=0x55e0ea8a0fc0) at ../sway/ipc-json.c:647
#8  0x000055e0e8a4a09c in ipc_json_describe_node_recursive
    (node=0x55e0ea850240) at ../sway/ipc-json.c:640
#9  0x000055e0e8a4e370 in ipc_client_handle_command
    (client=0x55e0eb4101e0, payload_length=0, payload_type=IPC_GET_TREE)
    at ../sway/ipc-server.c:799
#10 0x000055e0e8a4c60d in ipc_client_handle_readable
    (client_fd=61, mask=1, data=0x55e0eb4101e0) at ../sway/ipc-server.c:269
#11 0x00007f4e104effaa in wl_event_loop_dispatch ()
    at /usr/lib/libwayland-server.so.0
#12 0x00007f4e104ee4e7 in wl_display_run () at /usr/lib/libwayland-server.so.0
#13 0x000055e0e8a50395 in server_run (server=0x55e0e8abf100 <server>)
    at ../sway/server.c:209
#14 0x000055e0e8a4f9b5 in main (argc=2, argv=0x7ffd64b8a948)
    at ../sway/main.c:409
```

crashed at 

```
#0  get_int_prop (view=0x55e0eb3f4f90, prop=VIEW_PROP_WINDOW_TYPE)
    at ../sway/desktop/xwayland.c:181
181			return *view->wlr_xwayland_surface->window_type;
```

and `view->wlr_xwayland_surface->window_type` was null.

To reproduce, launch xev and sway will crash.

**Comment by emersion** [comment]
There's already a patch to fix this one: https://github.com/swaywm/sway/pull/5026

**Comment by xdavidwu** [comment]
Oh I forgot to check PR page first. Thanks for pointing that out and the fix!
