### ISSUE TITLE
Blank screen and crash on interaction

### ISSUE THREAD

**Issue by x1125** [swaywm/sway#5037]
After an update my Sway is starting with a complete blank screen.
Once an action is issued (e.g. open terminal or thunar), it crashes.

I'm using an Intel HD GPU.

Sway version 1.4

Debug Log: [pastebin.com](https://pastebin.com/GFS47yKK)

Stack trace:
```
                Stack trace of thread 1058:
                #0  0x000055e49b91f442 n/a (sway + 0x1d442)
                #1  0x000055e49b91f6c9 n/a (sway + 0x1d6c9)
                #2  0x00007ff2dc2583fe n/a (libwlroots.so.5 + 0x683fe)
                #3  0x00007ff2dc25df46 n/a (libwlroots.so.5 + 0x6df46)
                #4  0x00007ff2dc2531fa n/a (libwlroots.so.5 + 0x631fa)
                #5  0x00007ff2dc253508 n/a (libwlroots.so.5 + 0x63508)
                #6  0x00007ff2dbcf269a ffi_call_unix64 (libffi.so.6 + 0x669a)
                #7  0x00007ff2dbcf1fb6 ffi_call (libffi.so.6 + 0x5fb6)
                #8  0x00007ff2dc2a4f62 n/a (libwayland-server.so.0 + 0xcf62)
                #9  0x00007ff2dc2a12dc n/a (libwayland-server.so.0 + 0x92dc)
                #10 0x00007ff2dc2a2faa wl_event_loop_dispatch (libwayland-server.so.0 + 0xafaa)
                #11 0x00007ff2dc2a14e7 wl_display_run (libwayland-server.so.0 + 0x94e7)
                #12 0x000055e49b9115ff n/a (sway + 0xf5ff)
                #13 0x00007ff2dc8ba023 __libc_start_main (libc.so.6 + 0x27023)
                #14 0x000055e49b91194e n/a (sway + 0xf94e)
                
                Stack trace of thread 1060:
                #0  0x00007ff2dc162cf5 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfcf5)
                #1  0x00007ff2dac78e1c n/a (i965_dri.so + 0x4f8e1c)
                #2  0x00007ff2dac78a18 n/a (i965_dri.so + 0x4f8a18)
                #3  0x00007ff2dc15c46f start_thread (libpthread.so.0 + 0x946f)
                #4  0x00007ff2dc9923d3 __clone (libc.so.6 + 0xff3d3)
                
                Stack trace of thread 1061:
                #0  0x00007ff2dc162cf5 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfcf5)
                #1  0x00007ff2dac78e1c n/a (i965_dri.so + 0x4f8e1c)
                #2  0x00007ff2dac78a18 n/a (i965_dri.so + 0x4f8a18)
                #3  0x00007ff2dc15c46f start_thread (libpthread.so.0 + 0x946f)
                #4  0x00007ff2dc9923d3 __clone (libc.so.6 + 0xff3d3)
                
                Stack trace of thread 1062:
                #0  0x00007ff2dc162cf5 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfcf5)
                #1  0x00007ff2dac78e1c n/a (i965_dri.so + 0x4f8e1c)
                #2  0x00007ff2dac78a18 n/a (i965_dri.so + 0x4f8a18)
                #3  0x00007ff2dc15c46f start_thread (libpthread.so.0 + 0x946f)
                #4  0x00007ff2dc9923d3 __clone (libc.so.6 + 0xff3d3)
                
                Stack trace of thread 1063:
                #0  0x00007ff2dc162cf5 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfcf5)
                #1  0x00007ff2dac78e1c n/a (i965_dri.so + 0x4f8e1c)
                #2  0x00007ff2dac78a18 n/a (i965_dri.so + 0x4f8a18)
                #3  0x00007ff2dc15c46f start_thread (libpthread.so.0 + 0x946f)
                #4  0x00007ff2dc9923d3 __clone (libc.so.6 + 0xff3d3)

=== bt full ===

#0  0x000055e49b91f442 in  ()
#1  0x000055e49b91f6c9 in  ()
#2  0x00007ff2dc2583fe in  () at /usr/lib/libwlroots.so.5
#3  0x00007ff2dc25df46 in  () at /usr/lib/libwlroots.so.5
#4  0x00007ff2dc2531fa in  () at /usr/lib/libwlroots.so.5
#5  0x00007ff2dc253508 in  () at /usr/lib/libwlroots.so.5
#6  0x00007ff2dbcf269a in ffi_call_unix64 () at /usr/lib/libffi.so.6
#7  0x00007ff2dbcf1fb6 in ffi_call () at /usr/lib/libffi.so.6
#8  0x00007ff2dc2a4f62 in  () at /usr/lib/libwayland-server.so.0
#9  0x00007ff2dc2a12dc in  () at /usr/lib/libwayland-server.so.0
#10 0x00007ff2dc2a2faa in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#11 0x00007ff2dc2a14e7 in wl_display_run () at /usr/lib/libwayland-server.so.0
#12 0x000055e49b9115ff in  ()
#13 0x00007ff2dc8ba023 in __libc_start_main () at /usr/lib/libc.so.6
#14 0x000055e49b91194e in  ()
```

What I tried as well:
* Using [sway-git](https://aur.archlinux.org/packages/sway-git/), [swaybg-git](https://aur.archlinux.org/packages/swaybg-git/) and [wlroots-git](https://aur.archlinux.org/packages/wlroots-git/)
* Using stock Arch kernel 5.5.5 instead of the [vfio version](https://aur.archlinux.org/pkgbase/linux-vfio/)
* Using stock config from /etc/sway
* Unplugging second monitor and not using HDMI switches in between

I'm using MESA 19.3.4, so [this issue](https://github.com/swaywm/sway/issues/5033) is probably something else.

I have a dedicated GPU (nvidia) which is used within QEMU, but untouched from the system. I could verify that by comparing the previous Sway debug logs which had the card listed as "nvidia".

I think the error's root lies within the `HDMI-A-1: Atomic commit failed (modeset): Permission denied` line.

PS: If it helps, [here](https://pastebin.com/dKERJbWK) is a list of Arch packages I've updated, possibly breaking things.

**Comment by emersion** [comment]
The backtrace you provided doesn't contain debug symbols. This most likely happens because the Sway binary you're using doesn't have debug information bundled.

Can you try again with a manually compiled Sway binary? See https://github.com/swaywm/sway/wiki/Development-Setup#compiling-as-a-subproject

**Comment by x1125** [comment]
Sure, here it is:
```
#0  0x00007f5736e3fce5 in raise () at /lib64/libc.so.6
#1  0x0000562844a8ff16 in _sway_assert (condition=false, format=0x562844aa01d8 "[%s:%d] %s:Expected to find a workspace") at ../common/log.c:31
        args = {{gp_offset = 40, fp_offset = 48, overflow_arg_area = 0x7ffe385ad910, reg_save_area = 0x7ffe385ad850}}
#2  0x0000562844a87e2a in select_workspace (view=0x5628460c5870) at ../sway/tree/view.c:526
        seat = 0x562845cad510
        criterias = 0x5628460313c0
        ws = 0x0
        node = 0x0
        __PRETTY_FUNCTION__ = "select_workspace"
#3  0x0000562844a88025 in view_map (view=0x5628460c5870, wlr_surface=0x5628460c5af0, fullscreen=false, fullscreen_output=0x0, decoration=false) at ../sway/tree/view.c:581
        __PRETTY_FUNCTION__ = "view_map"
        ws = 0x0
        seat = 0x562844a8d913 <wl_signal_add+38>
        node = 0x5628460c5968
        target_sibling = 0x5628455dfba8
#4  0x0000562844a8e998 in handle_map (listener=0x5628460c5aa0, data=0x5628460b5c80) at ../sway/desktop/xwayland.c:443
        xwayland_view = 0x5628460c5870
        xsurface = 0x5628460b5c80
        view = 0x5628460c5870
#5  0x00007f57376c87f0 in wlr_signal_emit_safe (signal=0x5628460b5de8, data=0x5628460b5c80) at ../subprojects/wlroots/util/signal.c:29
        pos = 0x5628460c5aa0
        l = 0x5628460c5aa0
        cursor = {link = {prev = 0x5628460c5aa0, next = 0x7ffe385ada50}, notify = 0x7f57376c873a <handle_noop>}
        end = {link = {prev = 0x7ffe385ada30, next = 0x5628460b5de8}, notify = 0x7f57376c873a <handle_noop>}
#6  0x00007f57376d22af in xwayland_surface_role_commit (wlr_surface=0x5628460c5af0) at ../subprojects/wlroots/xwayland/xwm.c:738
        __PRETTY_FUNCTION__ = "xwayland_surface_role_commit"
        surface = 0x5628460b5c80
#7  0x00007f57376c0918 in surface_commit_pending (surface=0x5628460c5af0) at ../subprojects/wlroots/types/wlr_surface.c:370
        invalid_buffer = true
        subsurface = 0x5628460c5cd8
#8  0x00007f57376c0b96 in surface_commit (client=0x5628460b2e00, resource=0x5628460b3a50) at ../subprojects/wlroots/types/wlr_surface.c:442
        surface = 0x5628460c5af0
        subsurface = 0x0
#9  0x00007f573663769a in ffi_call_unix64 () at /lib64/libffi.so.6
#10 0x00007f5736636fb6 in ffi_call () at /lib64/libffi.so.6
#11 0x00007f5737051f62 in  () at /lib64/libwayland-server.so.0
#12 0x00007f573704e2dc in  () at /lib64/libwayland-server.so.0
#13 0x00007f573704ffaa in wl_event_loop_dispatch () at /lib64/libwayland-server.so.0
#14 0x00007f573704e4e7 in wl_display_run () at /lib64/libwayland-server.so.0
#15 0x0000562844a43395 in server_run (server=0x562844ab2100 <server>) at ../sway/server.c:209
#16 0x0000562844a429b5 in main (argc=2, argv=0x7ffe385ae208) at ../sway/main.c:409
        verbose = 0
        debug = 1
        validate = 0
        allow_unsupported_gpu = 0
        long_options = 
            {{name = 0x562844a960c8 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x562844a960cd "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x562844a960d4 "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x562844a960dd "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x562844a960e3 "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x562844a960eb "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x562844a960f3 "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x562844a96102 "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x562844a96112 "my-next-gpu-wont-be-nvidia", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        config_path = 0x0
        usage = 0x562844a95ba0 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
```

Git commit f2a60d
[updated debug log](https://pastebin.com/pPbLigWd)

**Comment by x1125** [comment]
It works again :)
I reinstalled current stable versions for Sway (v1.4) and wlroots (v0.10.0) and everything is fine again.
