### ISSUE TITLE
Sway crashes when external monitor gets attached

### ISSUE THREAD

**Issue by g00nix** [swaywm/sway#5381]
I am opening a ticket following the discussion on IRC.

Behavior: Sway opens and works, however when plugging in external monitor (either thunderbolt or HDMI), sway crashes.

Please find details bellow. If any other information is needed, please let me know.

Setup: Lenovo X1 Extreme Gen 2 (with Hybrid Graphics activate in BIOS)
CPU: i7-9750H
GPU: GeForce GTX 1650 Mobile

sway version: `sway version 1.4-848a6fdb (May 24 2020, branch 'master')`
wlroots version: `wlroots-git 0.10.0.r145.gaf2f69e6-1`
kernel vesion: `5.6.14-arch1-1`

coredumpctl gdb sway + bt full:
```
coredumpctl gdb sway
           PID: 846 (sway)
           UID: 1000 (g00n1x)
           GID: 1000 (g00n1x)
        Signal: 7 (BUS)
     Timestamp: Sun 2020-05-24 20:22:54 EEST (4min 58s ago)
  Command Line: sway -d
    Executable: /usr/bin/sway
 Control Group: /user.slice/user-1000.slice/session-1.scope
          Unit: session-1.scope
         Slice: user-1000.slice
       Session: 1
     Owner UID: 1000 (g00n1x)
       Boot ID: e2a9c7dd8a20464a85ede7232cdd08bd
    Machine ID: 4116cdb6b5ce4fa28887c7c8f36b6570
      Hostname: extreme
       Storage: /var/lib/systemd/coredump/core.sway.1000.e2a9c7dd8a20464a85ede7232cdd08bd.846.1590340974000000000000.lz4
       Message: Process 846 (sway) of user 1000 dumped core.
                
                Stack trace of thread 876:
                #0  0x00007fac2799135e n/a (n/a + 0x0)
                #1  0x00007fac25761556 n/a (iris_dri.so + 0x5d2556)
                #2  0x00007fac25776d46 n/a (iris_dri.so + 0x5e7d46)
                #3  0x00007fac2577761e n/a (iris_dri.so + 0x5e861e)
                #4  0x00007fac257620c8 n/a (iris_dri.so + 0x5d30c8)
                #5  0x00007fac2707d422 start_thread (libpthread.so.0 + 0x9422)
                #6  0x00007fac27195bf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 873:
                #0  0x00007fac2799135e n/a (n/a + 0x0)
                #1  0x00007fac25761790 n/a (iris_dri.so + 0x5d2790)
                #2  0x00007fac2576937e n/a (iris_dri.so + 0x5da37e)
                #3  0x00007fac25776d46 n/a (iris_dri.so + 0x5e7d46)
                #4  0x00007fac2577761e n/a (iris_dri.so + 0x5e861e)
                #5  0x00007fac257620c8 n/a (iris_dri.so + 0x5d30c8)
                #6  0x00007fac2707d422 start_thread (libpthread.so.0 + 0x9422)
                #7  0x00007fac27195bf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 874:
                #0  0x00007fac2799135e n/a (n/a + 0x0)
                #1  0x00007fac25761556 n/a (iris_dri.so + 0x5d2556)
                #2  0x00007fac25776d46 n/a (iris_dri.so + 0x5e7d46)
                #3  0x00007fac2577761e n/a (iris_dri.so + 0x5e861e)
                #4  0x00007fac257620c8 n/a (iris_dri.so + 0x5d30c8)
                #5  0x00007fac2707d422 start_thread (libpthread.so.0 + 0x9422)
                #6  0x00007fac27195bf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 872:
                #0  0x00007fac2799135e n/a (n/a + 0x0)
                #1  0x00007fac25761556 n/a (iris_dri.so + 0x5d2556)
                #2  0x00007fac25776d46 n/a (iris_dri.so + 0x5e7d46)
                #3  0x00007fac2577761e n/a (iris_dri.so + 0x5e861e)
                #4  0x00007fac257620c8 n/a (iris_dri.so + 0x5d30c8)
                #5  0x00007fac2707d422 start_thread (libpthread.so.0 + 0x9422)
                #6  0x00007fac27195bf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 870:
                #0  0x00007fac2799135e n/a (n/a + 0x0)
                #1  0x00007fac25761556 n/a (iris_dri.so + 0x5d2556)
                #2  0x00007fac25776d46 n/a (iris_dri.so + 0x5e7d46)
                #3  0x00007fac2577761e n/a (iris_dri.so + 0x5e861e)
                #4  0x00007fac257620c8 n/a (iris_dri.so + 0x5d30c8)
                #5  0x00007fac2707d422 start_thread (libpthread.so.0 + 0x9422)
                #6  0x00007fac27195bf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 869:
                #0  0x00007fac2799135e n/a (n/a + 0x0)
                #1  0x00007fac25761556 n/a (iris_dri.so + 0x5d2556)
                #2  0x00007fac25776d46 n/a (iris_dri.so + 0x5e7d46)
                #3  0x00007fac2577761e n/a (iris_dri.so + 0x5e861e)
                #4  0x00007fac257620c8 n/a (iris_dri.so + 0x5d30c8)
                #5  0x00007fac2707d422 start_thread (libpthread.so.0 + 0x9422)
                #6  0x00007fac27195bf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 875:
                #0  0x00007fac2799135e n/a (n/a + 0x0)
                #1  0x00007fac25761790 n/a (iris_dri.so + 0x5d2790)
                #2  0x00007fac2576937e n/a (iris_dri.so + 0x5da37e)
                #3  0x00007fac25776d46 n/a (iris_dri.so + 0x5e7d46)
                #4  0x00007fac2577761e n/a (iris_dri.so + 0x5e861e)
                #5  0x00007fac257620c8 n/a (iris_dri.so + 0x5d30c8)
                #6  0x00007fac2707d422 start_thread (libpthread.so.0 + 0x9422)
                #7  0x00007fac27195bf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 871:
                #0  0x00007fac2799135e n/a (n/a + 0x0)
                #1  0x00007fac25761556 n/a (iris_dri.so + 0x5d2556)
                #2  0x00007fac25776d46 n/a (iris_dri.so + 0x5e7d46)
                #3  0x00007fac2577761e n/a (iris_dri.so + 0x5e861e)
                #4  0x00007fac257620c8 n/a (iris_dri.so + 0x5d30c8)
                #5  0x00007fac2707d422 start_thread (libpthread.so.0 + 0x9422)
                #6  0x00007fac27195bf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 867:
                #0  0x00007fac2799135e n/a (n/a + 0x0)
                #1  0x00007fac25761556 n/a (iris_dri.so + 0x5d2556)
                #2  0x00007fac25776d46 n/a (iris_dri.so + 0x5e7d46)
                #3  0x00007fac2577761e n/a (iris_dri.so + 0x5e861e)
                #4  0x00007fac257620c8 n/a (iris_dri.so + 0x5d30c8)
                #5  0x00007fac2707d422 start_thread (libpthread.so.0 + 0x9422)
                #6  0x00007fac27195bf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 877:
                #0  0x00007fac2799135e n/a (n/a + 0x0)
                #1  0x00007fac25761556 n/a (iris_dri.so + 0x5d2556)
                #2  0x00007fac25776d46 n/a (iris_dri.so + 0x5e7d46)
                #3  0x00007fac2577761e n/a (iris_dri.so + 0x5e861e)
                #4  0x00007fac257620c8 n/a (iris_dri.so + 0x5d30c8)
                #5  0x00007fac2707d422 start_thread (libpthread.so.0 + 0x9422)
                #6  0x00007fac27195bf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 878:
                #0  0x00007fac2799135e n/a (n/a + 0x0)
                #1  0x00007fac25761790 n/a (iris_dri.so + 0x5d2790)
                #2  0x00007fac2576937e n/a (iris_dri.so + 0x5da37e)
                #3  0x00007fac25776d46 n/a (iris_dri.so + 0x5e7d46)
                #4  0x00007fac2577761e n/a (iris_dri.so + 0x5e861e)
                #5  0x00007fac257620c8 n/a (iris_dri.so + 0x5d30c8)
                #6  0x00007fac2707d422 start_thread (libpthread.so.0 + 0x9422)
                #7  0x00007fac27195bf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 882:
                #0  0x00007fac27083e32 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe32)
                #1  0x00007fac25765dd4 n/a (iris_dri.so + 0x5d6dd4)
                #2  0x00007fac25762098 n/a (iris_dri.so + 0x5d3098)
                #3  0x00007fac2707d422 start_thread (libpthread.so.0 + 0x9422)
                #4  0x00007fac27195bf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 879:
                #0  0x00007fac27083e32 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe32)
                #1  0x00007fac25765dd4 n/a (iris_dri.so + 0x5d6dd4)
                #2  0x00007fac25762098 n/a (iris_dri.so + 0x5d3098)
                #3  0x00007fac2707d422 start_thread (libpthread.so.0 + 0x9422)
                #4  0x00007fac27195bf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 883:
                #0  0x00007fac27083e32 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe32)
                #1  0x00007fac25765dd4 n/a (iris_dri.so + 0x5d6dd4)
                #2  0x00007fac25762098 n/a (iris_dri.so + 0x5d3098)
                #3  0x00007fac2707d422 start_thread (libpthread.so.0 + 0x9422)
                #4  0x00007fac27195bf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 864:
                #0  0x00007fac27083e32 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe32)
                #1  0x00007fac255f4dec n/a (iris_dri.so + 0x465dec)
                #2  0x00007fac255f4cf8 n/a (iris_dri.so + 0x465cf8)
                #3  0x00007fac2707d422 start_thread (libpthread.so.0 + 0x9422)
                #4  0x00007fac27195bf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 865:
                #0  0x00007fac27083e32 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe32)
                #1  0x00007fac255f4dec n/a (iris_dri.so + 0x465dec)
                #2  0x00007fac255f4cf8 n/a (iris_dri.so + 0x465cf8)
                #3  0x00007fac2707d422 start_thread (libpthread.so.0 + 0x9422)
                #4  0x00007fac27195bf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 863:
                #0  0x00007fac27083e32 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe32)
                #1  0x00007fac255f4dec n/a (iris_dri.so + 0x465dec)
                #2  0x00007fac255f4cf8 n/a (iris_dri.so + 0x465cf8)
                #3  0x00007fac2707d422 start_thread (libpthread.so.0 + 0x9422)
                #4  0x00007fac27195bf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 886:
                #0  0x00007fac27083e32 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe32)
                #1  0x00007fac25765dd4 n/a (iris_dri.so + 0x5d6dd4)
                #2  0x00007fac25762098 n/a (iris_dri.so + 0x5d3098)
                #3  0x00007fac2707d422 start_thread (libpthread.so.0 + 0x9422)
                #4  0x00007fac27195bf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 881:
                #0  0x00007fac27083e32 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe32)
                #1  0x00007fac25765dd4 n/a (iris_dri.so + 0x5d6dd4)
                #2  0x00007fac25762098 n/a (iris_dri.so + 0x5d3098)
                #3  0x00007fac2707d422 start_thread (libpthread.so.0 + 0x9422)
                #4  0x00007fac27195bf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 884:
                #0  0x00007fac27083e32 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe32)
                #1  0x00007fac25765dd4 n/a (iris_dri.so + 0x5d6dd4)
                #2  0x00007fac25762098 n/a (iris_dri.so + 0x5d3098)
                #3  0x00007fac2707d422 start_thread (libpthread.so.0 + 0x9422)
                #4  0x00007fac27195bf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 887:
                #0  0x00007fac27083e32 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe32)
                #1  0x00007fac25765dd4 n/a (iris_dri.so + 0x5d6dd4)
                #2  0x00007fac25762098 n/a (iris_dri.so + 0x5d3098)
                #3  0x00007fac2707d422 start_thread (libpthread.so.0 + 0x9422)
                #4  0x00007fac27195bf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 888:
                #0  0x00007fac27083e32 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe32)
                #1  0x00007fac25765dd4 n/a (iris_dri.so + 0x5d6dd4)
                #2  0x00007fac25762098 n/a (iris_dri.so + 0x5d3098)
                #3  0x00007fac2707d422 start_thread (libpthread.so.0 + 0x9422)
                #4  0x00007fac27195bf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 880:
                #0  0x00007fac27083e32 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe32)
                #1  0x00007fac25765dd4 n/a (iris_dri.so + 0x5d6dd4)
                #2  0x00007fac25762098 n/a (iris_dri.so + 0x5d3098)
                #3  0x00007fac2707d422 start_thread (libpthread.so.0 + 0x9422)
                #4  0x00007fac27195bf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 889:
                #0  0x00007fac27083e32 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe32)
                #1  0x00007fac25765dd4 n/a (iris_dri.so + 0x5d6dd4)
                #2  0x00007fac25762098 n/a (iris_dri.so + 0x5d3098)
                #3  0x00007fac2707d422 start_thread (libpthread.so.0 + 0x9422)
                #4  0x00007fac27195bf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 885:
                #0  0x00007fac27083e32 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe32)
                #1  0x00007fac25765dd4 n/a (iris_dri.so + 0x5d6dd4)
                #2  0x00007fac25762098 n/a (iris_dri.so + 0x5d3098)
                #3  0x00007fac2707d422 start_thread (libpthread.so.0 + 0x9422)
                #4  0x00007fac27195bf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 866:
                #0  0x00007fac27083e32 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe32)
                #1  0x00007fac255f4dec n/a (iris_dri.so + 0x465dec)
                #2  0x00007fac255f4cf8 n/a (iris_dri.so + 0x465cf8)
                #3  0x00007fac2707d422 start_thread (libpthread.so.0 + 0x9422)
                #4  0x00007fac27195bf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 846:
                #0  0x00007fac27083e32 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe32)
                #1  0x00007fac25e56554 n/a (iris_dri.so + 0xcc7554)
                #2  0x00007fac257766e7 n/a (iris_dri.so + 0x5e76e7)
                #3  0x00007fac252c3f0d n/a (iris_dri.so + 0x134f0d)
                #4  0x00007fac252979e9 n/a (iris_dri.so + 0x1089e9)
                #5  0x00007fac1c1eed28 n/a (libEGL_mesa.so.0 + 0x1cd28)
                #6  0x00007fac1c1ec75a n/a (libEGL_mesa.so.0 + 0x1a75a)
                #7  0x00007fac1c1e26ea n/a (libEGL_mesa.so.0 + 0x106ea)
                #8  0x00007fac272fe400 wlr_egl_swap_buffers (libwlroots.so.5 + 0x26400)
                #9  0x00007fac2730834f n/a (libwlroots.so.5 + 0x3034f)
                #10 0x00007fac273070ee n/a (libwlroots.so.5 + 0x2f0ee)
                #11 0x00007fac273043b1 n/a (libwlroots.so.5 + 0x2c3b1)
                #12 0x00007fac27304840 n/a (libwlroots.so.5 + 0x2c840)
                #13 0x00007fac273057a4 n/a (libwlroots.so.5 + 0x2d7a4)
                #14 0x00007fac27305de0 n/a (libwlroots.so.5 + 0x2dde0)
                #15 0x00007fac27339dfa wlr_output_commit (libwlroots.so.5 + 0x61dfa)
                #16 0x000055625f67ef3a apply_output_config (sway + 0x33f3a)
                #17 0x000055625f6693ff handle_new_output (sway + 0x1e3ff)
                #18 0x00007fac2734631e n/a (libwlroots.so.5 + 0x6e31e)
                #19 0x00007fac2734631e n/a (libwlroots.so.5 + 0x6e31e)
                #20 0x00007fac2730629d n/a (libwlroots.so.5 + 0x2e29d)
                #21 0x00007fac2734631e n/a (libwlroots.so.5 + 0x6e31e)
                #22 0x00007fac27314c90 n/a (libwlroots.so.5 + 0x3cc90)
                #23 0x00007fac27395faa wl_event_loop_dispatch (libwayland-server.so.0 + 0xafaa)
                #24 0x00007fac273944e7 wl_display_run (libwayland-server.so.0 + 0x94e7)
                #25 0x000055625f6595a0 main (sway + 0xe5a0)
                #26 0x00007fac270bd002 __libc_start_main (libc.so.6 + 0x27002)
                #27 0x000055625f65971e _start (sway + 0xe71e)
                
                Stack trace of thread 868:
                #0  0x00007fac270851ca __pthread_barrier_wait (libpthread.so.0 + 0x111ca)
                #1  0x00007fac25777612 n/a (iris_dri.so + 0x5e8612)
                #2  0x00007fac257620c8 n/a (iris_dri.so + 0x5d30c8)
                #3  0x00007fac2707d422 start_thread (libpthread.so.0 + 0x9422)
                #4  0x00007fac27195bf3 __clone (libc.so.6 + 0xffbf3)
                
                Stack trace of thread 890:
                #0  0x00007fac27083e32 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe32)
                #1  0x00007fac25765dd4 n/a (iris_dri.so + 0x5d6dd4)
                #2  0x00007fac25762098 n/a (iris_dri.so + 0x5d3098)
                #3  0x00007fac2707d422 start_thread (libpthread.so.0 + 0x9422)
                #4  0x00007fac27195bf3 __clone (libc.so.6 + 0xffbf3)

GNU gdb (GDB) 9.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/sway...
[New LWP 876]
[New LWP 873]
[New LWP 874]
[New LWP 872]
[New LWP 870]
[New LWP 869]
[New LWP 875]
[New LWP 871]
[New LWP 867]
[New LWP 877]
[New LWP 878]
[New LWP 882]
[New LWP 879]
[New LWP 883]
[New LWP 864]
[New LWP 865]
[New LWP 863]
[New LWP 886]
[New LWP 881]
[New LWP 884]
[New LWP 887]
[New LWP 888]
[New LWP 880]
[New LWP 889]
[New LWP 885]
[New LWP 866]
[New LWP 846]
[New LWP 868]
[New LWP 890]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
--Type <RET> for more, q to quit, c to continue without paging--
Core was generated by `sway -d'.
Program terminated with signal SIGBUS, Bus error.
#0  0x00007fac2799135e in ?? ()
[Current thread is 1 (Thread 0x7fabfa7fc700 (LWP 876))]
(gdb) bt full
#0  0x00007fac2799135e in  ()
#1  0xffffffffffffffff in  ()
#2  0xffffffffffffffff in  ()
#3  0xffffffffffffffff in  ()
#4  0xffffffffffffffff in  ()
#5  0xffffffffffffffff in  ()
#6  0xffffffffffffffff in  ()
#7  0xffffffffffffffff in  ()
#8  0xffffffffffffffff in  ()
#9  0x6163696c70706100 in  ()
#10 0x766564006e6f6974 in  ()
#11 0x00000000399868c8 in  ()
#12 0x0000000000000000 in  ()
(gdb) 

```

**Comment by shibumi** [comment]
This is maybe related to: https://github.com/swaywm/sway/issues/5362

**Comment by emersion** [comment]
Sway's thread is stuck in `pthread_cond_wait`, so this is likely a Mesa iris bug.

**Comment by emersion** [comment]
Sway log: [log.txt](https://github.com/swaywm/sway/files/4674205/log.txt)

This is a hybrid GPU laptop with an intel iGPU and an NVIDIA dGPU. Nouveau doesn't support OpenGL for this card so Mesa falls back to llvmpipe.

**Comment by 20k-ultra** [comment]
@emersion, I have the exact same setup as OP and when I disable hybrid graphics to run discrete the problem is resolved. However, Sway will begin to consume near 100% CPU load on all cores and make the machine practically unresponsive. This happens even when the monitor is disconnected. If I revert to hybrid graphics then all is good except the Nouveau doesn't support OpenGL so Sway crashes.

Let me know if there is any other logs I can provide to help. The logs do contain an error message just before it starts logging my system is too slow so hopefully that's a good lead.

[sway.log](https://github.com/swaywm/sway/files/4693067/sway.log)
![20200527_23h25m22s_grim](https://user-images.githubusercontent.com/3946250/83095876-4b675300-a072-11ea-9c18-106ad90ebcc3.png)

**Comment by emersion** [comment]
@20k-ultra You're using llvmpipe with a single nouveau card (no Intel card).

**Comment by 20k-ultra** [comment]
There seems to be no possible way I can find to have sway/wayland run on my integrated intel graphics so I can display to an external monitor. I've spent a few hours looking at various documentation and software (bumblee and prime) but it seems impossible to do it with Wayland.

Shouldn't you just close this issue @emersion since there's nothing we can do to run external monitor with this machine ? I'm only asking because it's making me think we should keep searching for a way and post back how we did. Had I known about [nvidia's lack of support](https://drewdevault.com/2017/10/26/Fuck-you-nvidia.html) I would have 100% considered another laptop but this is what I have right now.

**Comment by g00nix** [comment]
> I have the exact same setup as OP and when I disable hybrid graphics to run discrete the problem is resolved. However, Sway will begin to consume near 100% CPU load on all cores and make the machine practically unresponsive. This happens even when the monitor is disconnected.

oh, so the trick is to turn hybrid graphics off in the BIOS and start sway only on the external monitor?

**Comment by 20k-ultra** [comment]
I don't know if starting sway only on the external will prevent the cpu usage but disabling hybrid graphics will allow Sway to display on both the laptop and screen. The cpu load is just so high it makes the laptop unresponsive. When I did this I could move my cursor from the monitor to my laptop as if everything was fine. I only noticed the high cpu load when opening terminal and having extreme lag. The wallpaper was set as well.

**Comment by g00nix** [comment]
Companies with dominating market share on the hardware market (and nvidia dominates the laptop market, so you literally can not take the card out) should be legally forced to offer support for secure environments. Persons, companies and governments should push this.

You can not force people to run shady software on hardware that has access to productions systems. An operating system with decades of history of security vulnerabilities and backdoors is way beyond "shady" and I do not find it acceptable to be able to use your hardware only by accepting to risk your career and the career of many other people (letting aside the fact that you will work a lot more efficiently on an open operating system)

The only way to guarantee that the software is clean is to open source it. This is mandatory for low level software (like operating systems and drivers for critical hardware like the GPU).

This ticket here should be closed, since this is clearly not a sway bug. This bug must be reported at nvidia. If they do not start to offer proper support for secure business laptops, the only way to solve this is probably a class action lawsuit.

**Comment by 20k-ultra** [comment]
You're preaching to the choir lol

**Comment by emersion** [comment]
>There seems to be no possible way I can find to have sway/wayland run on my integrated intel graphics so I can display to an external monitor. I've spent a few hours looking at various documentation and software (bumblee and prime) but it seems impossible to do it with Wayland.

It should be possible to do a copy via system memory. I'm going to close this as a duplicate of https://github.com/swaywm/wlroots/issues/1347.

**Comment by progandy** [comment]
A very ugly workaround comes to mind: 

run an X server on the nvidia card,  
create a virtual output in sway,
then use wf-recorder to record the virtual output and play it on the X server

    DISPLAY=:2 SDL_VIDEODRIVER=x11 wf-recorder -o HEADLESS1 -c rawvideo -m sdl -f pipe:xorg-bridge

**Comment by d4g** [comment]
@progandy I tried to use LP_NUM_THREADS=0 but the whole system was unresponsive. So this is probably not a viable solution. I will probably try the hack or wait until #1347 gets implemented.
