### ISSUE TITLE
Fatal crash using virtual pointer scroll

### ISSUE THREAD

**Issue by RPigott** [swaywm/sway#5578]
```
$ swaymsg -t get_version
sway version 1.5-3520fd2c (Jul 26 2020, branch 'master')
```

I don't have more details atm. There is probably an error in my client as well.

<details>
<summary>bt full</summary>

```
#0  idle_source_from_device (device=0x0) at ../sway/sway/input/cursor.c:281
        idle_source = <optimized out>
#1  cursor_handle_activity (cursor=0x555bee69dd70, device=0x0) at ../sway/sway/input/cursor.c:281
        idle_source = <optimized out>
#2  0x0000555bed1acb3b in handle_pointer_axis (listener=0x555bee69dee8, data=0x555beecd5228) at ../sway/sway/input/cursor.c:405
        cursor = 0x555bee69dd70
        event = 0x555beecd5228
#3  0x00007ff75011460e in wlr_signal_emit_safe (signal=<optimized out>, data=0x555beecd5228) at ../util/signal.c:29
        pos = 0x555bee69dee8
        l = 0x555bee69dee8
        cursor = {link = {prev = 0x555bee69dee8, next = 0x7ffd0f3c4170}, notify = 0x7ff750114580 <handle_noop>}
        end = {link = {prev = 0x7ffd0f3c4150, next = 0x555bee6a94e8}, notify = 0x7ff750114580 <handle_noop>}
#4  0x00007ff75011460e in wlr_signal_emit_safe (signal=<optimized out>, data=data@entry=0x555beecd5228) at ../util/signal.c:29
        pos = 0x555beed0d818
        l = 0x555beed0d818
        cursor = {link = {prev = 0x555beed0d818, next = 0x7ffd0f3c41e0}, notify = 0x7ff750114580 <handle_noop>}
        end = {link = {prev = 0x7ffd0f3c41c0, next = 0x555beed8cf48}, notify = 0x7ff750114580 <handle_noop>}
#5  0x00007ff7501114ab in virtual_pointer_frame (client=<optimized out>, resource=<optimized out>) at ../types/wlr_virtual_pointer_v1.c:127
        i = 1
        pointer = 0x555beecd5190
#6  0x00007ff74fa18a8d in  () at /usr/lib/libffi.so.7
#7  0x00007ff74fa1801b in  () at /usr/lib/libffi.so.7
#8  0x00007ff750166f62 in  () at /usr/lib/libwayland-server.so.0
#9  0x00007ff7501632dc in  () at /usr/lib/libwayland-server.so.0
#10 0x00007ff750164faa in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#11 0x00007ff7501634e7 in wl_display_run () at /usr/lib/libwayland-server.so.0
#12 0x0000555bed1945c0 in main (argc=1, argv=0x7ffd0f3c4968) at ../sway/sway/main.c:410
        verbose = 0
        debug = 0
        validate = 0
        allow_unsupported_gpu = 0
        long_options = 
            {{name = 0x555bed1e545b "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x555bed1e8e09 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x555bed1e5460 "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x555bed1e5469 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x555bed1e53bf "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x555bed1e4543 "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x555bed1e546f "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x555bed1e547e "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x555bed1e548e "my-next-gpu-wont-be-nvidia", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        config_path = 0x0
        usage = 0x555bed1e5800 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = <optimized out>
```
</details>

**Comment by RPigott** [comment]
For future reference this crash occurs when a virtual pointer device submits a vertical and horizontal axis event in the same frame.
