### ISSUE TITLE
Crash in handle_constraint_destroy when closing X11 app

### ISSUE THREAD

**Issue by quantum5** [swaywm/sway#5740]
- **Sway Version:**
  - `sway version 1.5-d6ac3075 (Oct 13 2020, branch 'master')`

- **Debug Log:**
  - Can't reproduce again, unable to provide debug logs.

- **Stack Trace:**
```
#0  0x00005561da506f20 in view_from_wlr_xwayland_surface (xsurface=0x0) at ../sway/desktop/xwayland.c:673
#1  0x00005561da4d573a in warp_to_constraint_cursor_hint (cursor=<optimized out>, cursor=<optimized out>) at ../sway/input/cursor.c:1242
        constraint = 0x5561dbfeb320
#2  0x00005561da4d57fa in handle_constraint_destroy (listener=0x5561dbe3c778, data=0x5561dbfeb320) at ../sway/input/cursor.c:1266
        sway_constraint = 0x5561dbe3c750
        constraint = 0x5561dbfeb320
        cursor = 0x5561db342f10
#3  0x00007f38f397cb8c in wlr_signal_emit_safe (signal=signal@entry=0x5561dbfeb428, data=data@entry=0x5561dbfeb320) at ../util/signal.c:29
        pos = 0x5561dbe3c778
        l = 0x5561dbe3c778
        cursor = {link = {prev = 0x5561dbfeb428, next = 0x7fff8c150830}, notify = 0x7f38f397cb00 <handle_noop>}
        end = {link = {prev = 0x7fff8c150810, next = 0x5561dbfeb428}, notify = 0x7f38f397cb00 <handle_noop>}
#4  0x00007f38f3971ae5 in pointer_constraint_destroy (constraint=0x5561dbfeb320) at ../types/wlr_pointer_constraints_v1.c:49
#5  0x00007f38f39c83de in destroy_resource (element=element@entry=0x5561dc01f8c0, data=data@entry=0x0, flags=0) at ../src/wayland-server.c:724
        resource = 0x5561dc01f8c0
#6  0x00007f38f39c843e in wl_resource_destroy (resource=0x5561dc01f8c0) at ../src/wayland-server.c:741
        client = 0x5561db756a20
        id = 66
        flags = <optimized out>
#7  0x00007f38f2b778ee in ffi_call_unix64 () at ../src/x86/unix64.S:76
#8  0x00007f38f2b772bf in ffi_call (cif=cif@entry=0x7fff8c150a20, fn=<optimized out>, rvalue=<optimized out>, rvalue@entry=0x0, avalue=avalue@entry=0x7fff8c150af0) at ../src/x86/ffi64.c:525
        classes = {X86_64_INTEGER_CLASS, X86_64_NO_CLASS, 3691116736, 21857}
        stack = <optimized out>
        argp = <optimized out>
        arg_types = <optimized out>
        gprcount = <optimized out>
        ssecount = <optimized out>
        ngpr = 1
        nsse = 0
        i = <optimized out>
        avn = <optimized out>
        ret_in_memory = <optimized out>
        reg_args = <optimized out>
#9  0x00007f38f39cc4bd in wl_closure_invoke (closure=0x5561dc01f790, flags=2, target=<optimized out>, opcode=0, data=<optimized out>) at ../src/connection.c:1018
        count = <optimized out>
        cif = {abi = FFI_UNIX64, nargs = 2, arg_types = 0x7fff8c150a40, rtype = 0x7f38f2b78180 <ffi_type_void>, bytes = 0, flags = 0}
        ffi_types = 
          {0x7f38f2b78060 <ffi_type_pointer>, 0x7f38f2b78060 <ffi_type_pointer>, 0x420001500000000, 0x68, 0x13, 0x40, 0x7fff8c150ac0, 0x7f38f39ccbd0 <wl_os_recvmsg_cloexec+32>, 0x5561db81f6e0, 0x1, 0x7fff8c150ac0, 0x5561db971f40, 0x7fff8c150ca0, 0x5561db756a20, 0x4, 0x7f38f39cad7b <wl_connection_read+235>, 0x0, 0x0, 0x7fff8c150b00, 0x2, 0x7fff8c150b20, 0x7f38f39b1180 <zwp_locked_pointer_v1_requests>}
        ffi_args = 
          {0x7fff8c150a10, 0x7fff8c150a18, 0x7f38f39b1180 <zwp_locked_pointer_v1_requests>, 0x7f38f39cb1f0 <wl_closure_init+224>, 0x5561db971f40, 0x0, 0x8, 0x5561db756a50, 0x0, 0x7f38f39cbceb <wl_connection_demarshal+155>, 0x5561dc01f868, 0x5561db971f40, 0x1, 0x5561dc01f790, 0x8dbd80820, 0x5561db9fc280, 0x7f38f39b1180 <zwp_locked_pointer_v1_requests>, 0x5561db756a50, 0x0, 0x7f38f39c6767 <log_closure+71>, 0x7f38f39b1180 <zwp_locked_pointer_v1_requests>, 0xf38b6925}
        implementation = <optimized out>
#10 0x00007f38f39c87c9 in wl_client_connection_data (fd=<optimized out>, mask=<optimized out>, data=0x5561db756a20) at ../src/wayland-server.c:432
        client = 0x5561db756a20
        connection = 0x5561db971f40
        resource = 0x5561dc01f8c0
        object = 0x5561dc01f8c0
        closure = 0x5561dc01f790
        message = 0x7f38f39b1180 <zwp_locked_pointer_v1_requests>
        p = {66, 524288}
        resource_flags = <optimized out>
        opcode = 0
        size = <optimized out>
        since = <optimized out>
        len = <optimized out>
#11 0x00007f38f39ca36a in wl_event_loop_dispatch (loop=0x5561dab42940, timeout=timeout@entry=-1) at ../src/event-loop.c:1027
        ep = 
              {{events = 1, data = {ptr = 0x5561db861050, fd = -611970992, u32 = 3682996304, u64 = 93878783184976}}, {events = 4, data = {ptr = 0x5561dbf14a90, fd = -604943728, u32 = 3690023568, u64 = 93878790212240}}, {events = 4, data = {ptr = 0x5561dbcf5ab0, fd = -607167824, u32 = 3687799472, u64 = 93878787988144}}, {events = 4, data = {ptr = 0x5561dbee2b30, fd = -605148368, u32 = 3689818928, u64 = 93878790007600}}, {events = 3684631024, data = {ptr = 0x8c150d2000005561, fd = 21857, u32 = 21857, u64 = 10093988570910971233}}, {events = 32767, data = {ptr = 0x5561db9f3208, fd = -610323960, u32 = 3684643336, u64 = 93878784832008}}, {events = 3684635128, data = {ptr = 0x8c150d6000005561, fd = 21857, u32 = 21857, u64 = 10093988845788878177}}, {events = 32767, data = {ptr = 0x7f38f39caacd <wl_connection_flush+365>, fd = -207836467, u32 = 4087130829, u64 = 139882582026957}}, {events = 32, data = {ptr = 0x8c150d9000000000, fd = 0, u32 = 0, u64 = 10093989051947286528}}, {events = 32767, data = {ptr = 0x7fff8c150d80, fd = -1944777344, u32 = 2350189952, u64 = 140735543577984}}, {events = 3690786640, data = {ptr = 0x434d4, fd = 275668, u32 = 275668, u64 = 275668}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 2350189920, data = {ptr = 0x100007fff, fd = 32767, u32 = 32767, u64 = 4295000063}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 21857, data = {ptr = 0x2243f119593a1c00, fd = 1496980480, u32 = 1496980480, u64 = 2469082111902620672}}, {events = 3684636364, data = {ptr = 0x2000005561, fd = 21857, u32 = 21857, u64 = 137438975329}}, {events = 0, data = {ptr = 0x5561db972f48, fd = -610848952, u32 = 3684118344, u64 = 93878784307016}}, {events = 8, data = {ptr = 0x1400000000, fd = 0, u32 = 0, u64 = 85899345920}}, {events = 0, data = {ptr = 0x100000001, fd = 1, u32 = 1, u64 = 4294967297}}, {events = 152, data = {ptr = 0xf39c840000000000, fd = 0, u32 = 0, u64 = 17554050583118217216}}, {events = 32568, data = {ptr = 0x108000000ef, fd = 239, u32 = 239, u64 = 1133871366383}}, {events = 3690849920, data = {ptr = 0x8c150e2400005561, fd = 21857, u32 = 21857, u64 = 10093989687602468193}}, {events = 32767, data = {ptr = 0x2243f119593a1c00, fd = 1496980480, u32 = 1496980480, u64 = 2469082111902620672}}, {events = 3690849928, data = {ptr = 0xdbfb77f000005561, fd = 21857, u32 = 21857, u64 = 15851395186136470881}}, {events = 21857, data = {ptr = 0x6e, fd = 110, u32 = 110, u64 = 110}}, {events = 3669241416, data = {ptr = 0x8c150eb000005561, fd = 21857, u32 = 21857, u64 = 10093990288897889633}}, {events = 32767, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 4, data = {ptr = 0xf37c0b8a00000000, fd = 0, u32 = 0, u64 = 17544910935662002176}}, {events = 32568, data = {ptr = 0x5561dbd83db8, fd = -606585416, u32 = 3688381880, u64 = 93878788570552}}, {events = 1496980480, data = {ptr = 0xdbd83d702243f119, fd = 574877977, u32 = 574877977, u64 = 15841479241096229145}}, {events = 21857, data = {ptr = 0x5561db9b50e0, fd = -610578208, u32 = 3684389088, u64 = 93878784577760}}}
        source = <optimized out>
        i = <optimized out>
        count = <optimized out>
        has_timers = <optimized out>
#12 0x00007f38f39c89ba in wl_display_run (display=0x5561dab42e00) at ../src/wayland-server.c:1351
#13 0x00005561da4bf9d1 in main (argc=1, argv=0x7fff8c150ff8) at ../sway/main.c:412
        verbose = 0
        debug = 0
        validate = 0
        allow_unsupported_gpu = 0
        long_options = {{name = 0x5561da50c45b "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x5561da50fd49 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x5561da50c460 "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x5561da50c469 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x5561da50c3bf "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x5561da50b4a1 "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x5561da50c46f "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x5561da50c47e "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x5561da50c48e "my-next-gpu-wont-be-nvidia", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        config_path = 0x0
        usage = 0x5561da50c800 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = <optimized out>
```

- **Description:**
  - This happened when attempting to close an [X11 app](https://github.com/gnif/LookingGlass) with the keybinding for `kill`. I am unable to reproduce it before or after, despite repeating the same actions.
  - No other information is available, will update if crash is seen again.

**Comment by Xyene** [comment]
It looks like we got sent a destroy event for the constraint after the surface got destroyed. This should be valid according to the spec:

>   If the surface the lock was requested on is destroyed and the lock is not
      yet activated, the wp_locked_pointer object is now defunct and must be
      destroyed.

However, wlroots should be passing a constraint destroyed event to sway when the xsurface goes away, and silently handle any subsequent resource destroys.
