### ISSUE TITLE
Crash in tiling resize when a sibling container dies

### ISSUE THREAD

**Issue by RPigott** [swaywm/sway#5746]
```
$ swaymsg -pt get_version
sway version 1.5-e68a2ff6 (Oct 19 2020, branch 'makepkg')
$ pacman -Q termite
termite 15-3
```
That's cc8d318aa1ab + `git cherry-pick` 0bcc01082684 a1701b5c4e0f

I was testing out the new tiling resize performance from #5744 and encountered this crash.

Steps to reproduce:

1. Make a workspace with layout `H[termite V[termite termite]]`
2. Grab the bottom right termite in a tiling resize action
4. Close the top right termite leaving `H[termite V[termite]]`.
5. Release the tiling resize button
6. Crash

EDIT: added proper steps to reproduce.

<details>
<summary>
backtrace
</summary>

```
#0  0x000055aa50e3f4de in container_set_resizing (con=0x55aa52ee2960, resizing=false) at ../sway/sway/tree/container.c:764
        i = 0
#1  0x000055aa50e2096f in handle_button (seat=0x55aa52844e20, time_msec=<optimized out>, device=<optimized out>, button=<optimized out>, state=<optimized out>) at ../sway/sway/input/seatop_resize_tiling.c:63
        e = <optimized out>
#2  0x000055aa50e16264 in dispatch_cursor_button (state=<optimized out>, button=273, time_msec=<optimized out>, device=0x55aa52a0deb0, cursor=0x55aa52845440) at ../sway/sway/input/cursor.c:375
        cursor = 0x55aa52845440
        event = 0x7ffd775edd60
#3  handle_pointer_button (listener=0x55aa528455a0, data=0x7ffd775edd60) at ../sway/sway/input/cursor.c:393
        cursor = 0x55aa52845440
        event = 0x7ffd775edd60
#4  0x00007fa8fe2107ae in wlr_signal_emit_safe (signal=<optimized out>, data=0x7ffd775edd60) at ../util/signal.c:29
        pos = 0x55aa528455a0
        l = 0x55aa528455a0
        cursor = {link = {prev = 0x55aa528455a0, next = 0x7ffd775edca0}, notify = 0x7fa8fe210720 <handle_noop>}
        end = {link = {prev = 0x7ffd775edc80, next = 0x55aa52845748}, notify = 0x7fa8fe210720 <handle_noop>}
#5  0x00007fa8fe2107ae in wlr_signal_emit_safe (signal=<optimized out>, data=data@entry=0x7ffd775edd60) at ../util/signal.c:29
        pos = 0x55aa52a0b600
        l = 0x55aa52a0b600
        cursor = {link = {prev = 0x55aa52a0b600, next = 0x7ffd775edd10}, notify = 0x7fa8fe210720 <handle_noop>}
        end = {link = {prev = 0x7ffd775edcf0, next = 0x55aa52a0df58}, notify = 0x7fa8fe210720 <handle_noop>}
#6  0x00007fa8fe1d74af in handle_pointer_button (event=<optimized out>, libinput_dev=<optimized out>) at ../backend/libinput/pointer.c:88
        wlr_dev = 0x55aa52a0deb0
        pevent = 0x55aa53081400
        wlr_event = {device = 0x55aa52a0deb0, time_msec = 52731, button = 273, state = WLR_BUTTON_RELEASED}
#7  0x00007fa8fe1d601c in handle_libinput_readable (fd=<optimized out>, mask=<optimized out>, _backend=0x55aa52108050) at ../backend/libinput/backend.c:41
        backend = 0x55aa52108050
        event = 0x55aa53081400
#8  0x00007fa8fe25ffaa in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#9  0x00007fa8fe25e4e7 in wl_display_run () at /usr/lib/libwayland-server.so.0
#10 0x000055aa50dfd5d4 in main (argc=1, argv=0x7ffd775ee158) at ../sway/sway/main.c:412
        verbose = 0
        debug = 0
        validate = 0
        allow_unsupported_gpu = 0
        long_options = 
            {{name = 0x55aa50e4f4db "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x55aa50e52dc9 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x55aa50e4f4e0 "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x55aa50e4f4e9 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x55aa50e4f43f "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x55aa50e4e557 "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x55aa50e4f4ef "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x55aa50e4f4fe "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x55aa50e4f50e "my-next-gpu-wont-be-nvidia", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        config_path = 0x0
        usage = 0x55aa50e4f880 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = <optimized out>
```
</details>

**Comment by RPigott** [comment]
nvm, looking at the bt it's actually pretty obvious – It was the sibling container that closed and caused the crash. Attempting to set the resizing hint on the closed container crashes sway.
