### ISSUE TITLE
Sway crash when /tmp/.X11-unix his own by another user and doesn't have 777 permissions

### ISSUE THREAD

**Issue by bbuccianti** [swaywm/sway#5844]
- **Sway Version:**
sway version v1.5

- **Debug Log:**
https://paste.sr.ht/~bbuccianti/3e15698ae7bb785826e26e7f77b544332be9e7c6

- **Stack Trace:**
I'm trying to get the coredump. Need to learn how to produce it with gdb and post it on later.

- **Description:**
I'm trying to run sway with another user on the same linux machine. A workaround possible is to chmod 777 on the /tmp/.X11-unix folder.

Thanks!

**Comment by bbuccianti** [comment]
Core dump produced!

```
#0  0x00007fe5b66ccef3 in wl_list_insert () at /usr/lib/x86_64-linux-gnu/libwayland-server.so.0
#1  0x00007fe5b666c1ec in wlr_output_init () at /usr/lib/x86_64-linux-gnu/libwlroots.so.6
#2  0x00007fe5b663a375 in  () at /usr/lib/x86_64-linux-gnu/libwlroots.so.6
#3  0x00007fe5b6636dc1 in  () at /usr/lib/x86_64-linux-gnu/libwlroots.so.6
#4  0x00007fe5b6641945 in  () at /usr/lib/x86_64-linux-gnu/libwlroots.so.6
#5  0x0000559202da7f47 in  ()
#6  0x0000559202d9c964 in  ()
#7  0x00007fe5b63ebcca in __libc_start_main (main=
    0x559202d9c450, argc=1, argv=0x7fff2e17be68, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fff2e17be58)
    at ../csu/libc-start.c:308
        result = <optimized out>
        unwind_buf = 
              {cancel_jmp_buf = {{jmp_buf = {0, -506814138561576820, 94085601413872, 0, 0, 0, -6040111414823862132, -6046074830919155572}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x1, 0x7fff2e17be68}, data = {prev = 0x0, cleanup = 0x0, canceltype = 1}}}
        not_first_call = <optimized out>
#8  0x0000559202d9cb1a in  ()
```

**Comment by emersion** [comment]
The backtrace you provided doesn't contain debug symbols. This most likely happens because the Sway binary you're using doesn't have debug information bundled.

Can you try again with a manually compiled Sway binary? See https://github.com/swaywm/sway/wiki/Development-Setup#compiling-as-a-subproject

**Comment by bbuccianti** [comment]
I've compiled sway from source following the instructions. Now, I don't get the segfault and sway starts and behaves ok, but I still get those error messages about permission denied. I've launched ```sway > sway.log 2>&1``` and this is the log.

```
00:00:00.105 [ERROR] [xwayland/sockets.c:63] Failed to bind socket /tmp/.X11-unix/X1: Permission denied
00:00:00.105 [ERROR] [xwayland/sockets.c:63] Failed to bind socket /tmp/.X11-unix/X2: Permission denied
00:00:00.105 [ERROR] [xwayland/sockets.c:63] Failed to bind socket /tmp/.X11-unix/X3: Permission denied
00:00:00.105 [ERROR] [xwayland/sockets.c:63] Failed to bind socket /tmp/.X11-unix/X4: Permission denied
00:00:00.105 [ERROR] [xwayland/sockets.c:63] Failed to bind socket /tmp/.X11-unix/X5: Permission denied
00:00:00.105 [ERROR] [xwayland/sockets.c:63] Failed to bind socket /tmp/.X11-unix/X6: Permission denied
00:00:00.105 [ERROR] [xwayland/sockets.c:63] Failed to bind socket /tmp/.X11-unix/X7: Permission denied
00:00:00.105 [ERROR] [xwayland/sockets.c:63] Failed to bind socket /tmp/.X11-unix/X8: Permission denied
00:00:00.105 [ERROR] [xwayland/sockets.c:63] Failed to bind socket /tmp/.X11-unix/X9: Permission denied
00:00:00.105 [ERROR] [xwayland/sockets.c:63] Failed to bind socket /tmp/.X11-unix/X10: Permission denied
00:00:00.105 [ERROR] [xwayland/sockets.c:63] Failed to bind socket /tmp/.X11-unix/X11: Permission denied
00:00:00.105 [ERROR] [xwayland/sockets.c:63] Failed to bind socket /tmp/.X11-unix/X12: Permission denied
00:00:00.105 [ERROR] [xwayland/sockets.c:63] Failed to bind socket /tmp/.X11-unix/X13: Permission denied
00:00:00.105 [ERROR] [xwayland/sockets.c:63] Failed to bind socket /tmp/.X11-unix/X14: Permission denied
00:00:00.105 [ERROR] [xwayland/sockets.c:63] Failed to bind socket /tmp/.X11-unix/X15: Permission denied
00:00:00.105 [ERROR] [xwayland/sockets.c:63] Failed to bind socket /tmp/.X11-unix/X16: Permission denied
00:00:00.105 [ERROR] [xwayland/sockets.c:63] Failed to bind socket /tmp/.X11-unix/X17: Permission denied
00:00:00.105 [ERROR] [xwayland/sockets.c:63] Failed to bind socket /tmp/.X11-unix/X18: Permission denied
00:00:00.105 [ERROR] [xwayland/sockets.c:63] Failed to bind socket /tmp/.X11-unix/X19: Permission denied
00:00:00.105 [ERROR] [xwayland/sockets.c:63] Failed to bind socket /tmp/.X11-unix/X20: Permission denied
00:00:00.105 [ERROR] [xwayland/sockets.c:63] Failed to bind socket /tmp/.X11-unix/X21: Permission denied
00:00:00.105 [ERROR] [xwayland/sockets.c:63] Failed to bind socket /tmp/.X11-unix/X22: Permission denied
00:00:00.105 [ERROR] [xwayland/sockets.c:63] Failed to bind socket /tmp/.X11-unix/X23: Permission denied
00:00:00.105 [ERROR] [xwayland/sockets.c:63] Failed to bind socket /tmp/.X11-unix/X24: Permission denied
00:00:00.105 [ERROR] [xwayland/sockets.c:63] Failed to bind socket /tmp/.X11-unix/X25: Permission denied
00:00:00.105 [ERROR] [xwayland/sockets.c:63] Failed to bind socket /tmp/.X11-unix/X26: Permission denied
00:00:00.105 [ERROR] [xwayland/sockets.c:63] Failed to bind socket /tmp/.X11-unix/X27: Permission denied
00:00:00.105 [ERROR] [xwayland/sockets.c:63] Failed to bind socket /tmp/.X11-unix/X28: Permission denied
00:00:00.105 [ERROR] [xwayland/sockets.c:63] Failed to bind socket /tmp/.X11-unix/X29: Permission denied
00:00:00.105 [ERROR] [xwayland/sockets.c:63] Failed to bind socket /tmp/.X11-unix/X30: Permission denied
00:00:00.105 [ERROR] [xwayland/sockets.c:63] Failed to bind socket /tmp/.X11-unix/X31: Permission denied
00:00:00.105 [ERROR] [xwayland/sockets.c:63] Failed to bind socket /tmp/.X11-unix/X32: Permission denied
00:00:00.105 [ERROR] [xwayland/sockets.c:181] No display available in the first 33
00:00:00.105 [sway/server.c:214] Failed to start Xwayland
2020-12-06 14:20:15 - [main.c:521] Missing a required Wayland interface
Modifiers specified, but DRI is too old
Modifiers specified, but DRI is too old
Modifiers specified, but DRI is too old
/bin/sh: 1: systemctl: not found

(process:5773): dconf-WARNING **: 14:20:16.734: failed to commit changes to dconf: Cannot autolaunch D-Bus without X11 $DISPLAY
dbus-update-activation-environment: error: unable to connect to D-Bus: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
2020-12-06 14:20:16 - [main.c:300] Found config DVI-D-1 for output DVI-D-1 (Unknown L22W931 0x00000101)
2020-12-06 14:20:16 - [main.c:300] Found config HDMI-A-1 for output HDMI-A-1 (Philips Consumer Electronics Company PHL 273V5 UK51815022302)
00:00:00.243 [swaybar/tray/tray.c:42] Failed to connect to user bus: No such file or directory
MPD error: Connection refused
CRITICAL: Cannot open X11 display.
[
  {
    "success": true
  }
]

(emacs:5806): Gtk-WARNING **: 14:20:20.217: Theme parsing error: gtk.css:3611:22: 'none' is not a valid color name
00:00:38.029 [common/ipc-client.c:87] Unable to receive IPC response
[341 14:20:54.531957] [glfw error 65544]: Wayland: fatal display error: Broken pipe
```

I think that Xwayland it's not launching properly?

**Comment by bbuccianti** [comment]
Nevermind, sorry for bother you.

I needed to pay attention to meson output. I doesn't have a couple of xcb libs necessary for Xwayland to work properly.

Now it's working ok, no segfault and no permissions denied on output log.

Thanks! I've switched to manually compiling sway instead of installing it through OS package manager.
