### ISSUE TITLE
[DRAFT] KRDC VNC client crashes sway

### ISSUE THREAD

**Issue by ngortheone** [swaywm/sway#5875]
Steps to reproduce

1. start kvm guest with `--graphics vnc`
2. run [KRDC](https://apps.kde.org/en/krdc) and connect to vnc on localhost
3.  TBD

### Please fill out the following:
- **Sway Version:**
`sway version 1.5.1`

- **Debug Log:**
  - Run `sway -d 2> ~/sway.log` from a TTY and upload it to a pastebin, such as gist.github.com.
  - This will record information about sway's activity. Please try to keep the reproduction as brief as possible and exit sway.

- **Configuration File:**
  - Please try to produce with the default configuration.
  - If you cannot reproduce with the default configuration, please try to find the minimal configuration to reproduce.
  - Upload the config to a pastebin such as gist.github.com.

- **Stack Trace:**
  - This is only needed if sway crashes.
  - If you use systemd, you should be able to open the coredump of the most recent crash with gdb with
    `coredumpctl gdb sway` and then `bt full` to obtain the stack trace.
  - If the lines mentioning sway or wlroots have `??` for the location, your binaries were built without debug symbols. Please compile both sway and wlroots from source and try to reproduce.

- **Description:**
  - The steps you took in plain English to reproduce the problem.

**Comment by ngortheone** [comment]
I am going to rebuild sway and wlroots with debug symbols to get better stacktrace

**Comment by ngortheone** [comment]
A better stack trace with symbols
```
Core was generated by `sway'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007faf31586957 in wlr_surface_is_subsurface (surface=surface@entry=0x0) at ../wlroots-0.12.0/types/wlr_compositor.c:16
16		return surface->role == &subsurface_role;
[Current thread is 1 (Thread 0x7faf309d89c0 (LWP 172558))]
(gdb) bt full
#0  0x00007faf31586957 in wlr_surface_is_subsurface (surface=surface@entry=0x0) at ../wlroots-0.12.0/types/wlr_compositor.c:16
#1  0x00007faf3159ad9d in wlr_surface_get_root_surface (surface=0x0, surface@entry=0x55caa6e6ad50) at ../wlroots-0.12.0/types/wlr_surface.c:1050
#2  0x00007faf315869e7 in subcompositor_handle_get_subsurface
    (client=<optimized out>, resource=0x55caa6e0e5a0, id=71, surface_resource=0x55caa6e606b0, parent_resource=<optimized out>)
    at ../wlroots-0.12.0/types/wlr_compositor.c:56
        surface = 0x55caa6e6c830
        parent = 0x55caa6e6ad50
        msg = "get_subsurface: wl_subsurface@"
#3  0x00007faf30f9feed in  () at /usr/lib64/libffi.so.7
#4  0x00007faf30f9f32a in  () at /usr/lib64/libffi.so.7
#5  0x00007faf315e325d in  () at /usr/lib64/libwayland-server.so.0
#6  0x00007faf315df817 in  () at /usr/lib64/libwayland-server.so.0
#7  0x00007faf315e1432 in wl_event_loop_dispatch () at /usr/lib64/libwayland-server.so.0
#8  0x00007faf315dfa05 in wl_display_run () at /usr/lib64/libwayland-server.so.0
#9  0x000055caa4b69df9 in server_run (server=server@entry=0x55caa4bc0ea0 <server>) at ../sway-1.5.1/sway/server.c:234
#10 0x000055caa4b697cb in main (argc=1, argv=0x7ffda87b80f8) at ../sway-1.5.1/sway/main.c:410
        verbose = 0
        debug = 0
        validate = 0
        allow_unsupported_gpu = 0
        long_options =
            {{name = 0x55caa4ba5392 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x55caa4ba8c01 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x55caa4ba5397 "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x55caa4ba53a0 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x55caa4ba52f6 "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x55caa4ba440d "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x55caa4ba53a6 "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x55caa4ba53b5 "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x55caa4ba53c5 "my-next-gpu-wont-be-nvidia", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        config_path = 0x0
        usage = 0x55caa4ba5730 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = <optimized out>
```
