### ISSUE TITLE
Sway crash when no monitor found.

### ISSUE THREAD

**Issue by layus** [swaywm/sway#5976]
- **Sway Version:**
  - `swaymsg -t get_version` or `sway -v`: sway version 1.5.1

- **Debug Log:** I really hope it will not be needed :-)
  
- **Configuration File:** https://gist.github.com/layus/2df83d751f1fbd0cbc00678dca55988d
  Most probably a swayidle dpms on/off issue: https://gist.github.com/layus/2df83d751f1fbd0cbc00678dca55988d#file-swayidle

- **Stack Trace:**

```txt
Thread debugging using libthread_db enabled]
Using host libthread_db library "/nix/store/1yvpgm763b3hvg8q4fzpzmflr5674x4j-glibc-2.32-10/lib/libthread_db.so.1".
Core was generated by `/nix/store/q1icr4h1nqrqikypsh2rxl9fvz075xs5-sway-unwrapped-1.5.1/bin/sway'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
49	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f4a866efa80 (LWP 10656))]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x00007f4a873d4523 in __GI_abort () at abort.c:79
#2  0x00007f4a873d441f in __assert_fail_base (fmt=0x7f4a875360b8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=0x7f4a87676de8 "head->state.mode != NULL || wl_list_empty(&head->state.output->modes)", 
    file=0x7f4a87676c10 "types/wlr_output_management_v1.c", line=693, function=<optimized out>) at assert.c:92
#3  0x00007f4a873e2d62 in __GI___assert_fail (
    assertion=0x7f4a87676de8 "head->state.mode != NULL || wl_list_empty(&head->state.output->modes)", 
    file=0x7f4a87676c10 "types/wlr_output_management_v1.c", line=693, 
    function=0x7f4a87676f40 <__PRETTY_FUNCTION__.6510> "head_send_state") at assert.c:101
#4  0x00007f4a876516c6 in head_send_state () from /nix/store/6yadng2x55m95akf56cndzkm3afif7yc-wlroots-0.12.0/lib/libwlroots.so.7
#5  0x00007f4a876523ce in wlr_output_manager_v1_set_configuration ()
   from /nix/store/6yadng2x55m95akf56cndzkm3afif7yc-wlroots-0.12.0/lib/libwlroots.so.7
#6  0x00007f4a876606ac in wlr_signal_emit_safe ()
   from /nix/store/6yadng2x55m95akf56cndzkm3afif7yc-wlroots-0.12.0/lib/libwlroots.so.7
#7  0x00007f4a876606ac in wlr_signal_emit_safe ()
   from /nix/store/6yadng2x55m95akf56cndzkm3afif7yc-wlroots-0.12.0/lib/libwlroots.so.7
#8  0x00007f4a8762611b in scan_drm_connectors ()
   from /nix/store/6yadng2x55m95akf56cndzkm3afif7yc-wlroots-0.12.0/lib/libwlroots.so.7
#9  0x00007f4a876606ac in wlr_signal_emit_safe ()
   from /nix/store/6yadng2x55m95akf56cndzkm3afif7yc-wlroots-0.12.0/lib/libwlroots.so.7
#10 0x00007f4a87634827 in udev_event () from /nix/store/6yadng2x55m95akf56cndzkm3afif7yc-wlroots-0.12.0/lib/libwlroots.so.7
#11 0x00007f4a876ad402 in wl_event_loop_dispatch (loop=0x223b4f0, timeout=timeout@entry=-1) at ../src/event-loop.c:1027
#12 0x00007f4a876ab9e5 in wl_display_run (display=0x2241fa0) at ../src/wayland-server.c:1351
#13 0x000000000040f9ac in main ()
```

- **Description:**

When I close the laptop lid, and turn off the external monitor (at the end of the day), I get back to the tty the next day, with a coredump and a terse `zsh:  IOT instruction (core dumped)  sway` message.

The assertion trace is quite clear: `head->state.mode != NULL || wl_list_empty(&head->state.output->modes)`

Possibly related to #5728

**Comment by emersion** [comment]
Just merged a fix for this: https://github.com/swaywm/sway/pull/5972

**Comment by layus** [comment]
Probably the quickest patch in history :-). Thanks !
