### ISSUE TITLE
Segfault on reload while XWayland application is running

### ISSUE THREAD

**Issue by Scrumplex** [swaywm/sway#6247]
### Please fill out the following:
- **Sway Version:**
sway version 1.6

- **Debug Log:**
* sway -d: https://termbin.com/oaxz
My normal way of starting sway (via systemd-cat) shows me the following message being repeated over and over until the session crashes: `_XSERVTransSocketUNIXAccept: accept() failed`

- **Configuration File:**
I can reproduce the issue with both the default config, as well as my own config.

- **Stack Trace:**
```
Core was generated by `sway'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f9f82618330 in fd_source_interface () from /usr/lib/libwayland-server.so.0
[Current thread is 1 (Thread 0x7f9f816c2e40 (LWP 15753))]
(gdb) bt full
#0  0x00007f9f82618330 in fd_source_interface () at /usr/lib/libwayland-server.so.0
#1  0x00007f9f8260d192 in wl_event_loop_dispatch (loop=0x5621b6a2bb90, timeout=timeout@entry=-1) at ../wayland-1.19.0/src/event-loop.c:1027
        ep = 
              {{events = 17, data = {ptr = 0x5621b750d590, fd = -1219439216, u32 = 3075528080, u64 = 94702809437584}}, {events = 1, data = {ptr = 0x5621b75786c0, fd = -1219000640, u32 = 3075966656, u64 = 94702809876160}}, {events = 17, data = {ptr = 0x5621b76bcc20, fd = -1217672160, u32 = 3077295136, u64 = 94702811204640}}, {events = 1, data = {ptr = 0x5621b77eb100, fd = -1216433920, u32 = 3078533376, u64 = 94702812442880}}, {events = 1565870512, data = {ptr = 0x2a400007fff, fd = 32767, u32 = 32767, u64 = 2903397924863}}, {events = 0, data = {ptr = 0x5621b77ee118, fd = -1216421608, u32 = 3078545688, u64 = 94702812455192}}, {events = 3078537480, data = {ptr = 0x5d5549f000005621, fd = 22049, u32 = 22049, u64 = 6725362913688704545}}, {events = 32767, data = {ptr = 0x7f9f8260d7e9 <wl_connection_flush+313>, fd = -2107582487, u32 = 2187384809, u64 = 140323063912425}}, {events = 0, data = {ptr = 0x2a400000000, fd = 0, u32 = 0, u64 = 2903397892096}}, {events = 0, data = {ptr = 0x7fff5d554a10, fd = 1565870608, u32 = 1565870608, u64 = 140734759258640}}, {events = 0, data = {ptr = 0x730, fd = 1840, u32 = 1840, u64 = 1840}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 1565870576, data = {ptr = 0x100007fff, fd = 32767, u32 = 32767, u64 = 4295000063}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0xfffffffffffffdf8, fd = -520, u32 = 4294966776, u64 = 18446744073709551096}}, {events = 3078539320, data = {ptr = 0x2a400005621, fd = 22049, u32 = 22049, u64 = 2903397914145}}, {events = 0, data = {ptr = 0x5621b7888fd8, fd = -1215787048, u32 = 3079180248, u64 = 94702813089752}}, {events = 620, data = {ptr = 0x7800000000, fd = 0, u32 = 0, u64 = 515396075520}}, {events = 0, data = {ptr = 0x100000001, fd = 1, u32 = 1, u64 = 4294967297}}, {events = 159, data = {ptr = 0xed000000cb, fd = 203, u32 = 203, u64 = 1017907249355}}, {events = 271, data = {ptr = 0x15300000131, fd = 305, u32 = 305, u64 = 1455993913649}}, {events = 373, data = {ptr = 0x1b900000197, fd = 407, u32 = 407, u64 = 1894080577943}}, {events = 475, data = {ptr = 0x21f000001fd, fd = 509, u32 = 509, u64 = 2332167242237}}, {events = 577, data = {ptr = 0x28500000263, fd = 611, u32 = 611, u64 = 2770253906531}}, {events = 679, data = {ptr = 0x2eb000002c9, fd = 713, u32 = 713, u64 = 3208340570825}}, {events = 781, data = {ptr = 0x3510000032f, fd = 815, u32 = 815, u64 = 3646427235119}}, {events = 883, data = {ptr = 0x3b700000395, fd = 917, u32 = 917, u64 = 4084513899413}}, {events = 985, data = {ptr = 0x6a8ca900000003fb, fd = 1019, u32 = 1019, u64 = 7677697282224948219}}, {events = 4025427206, data = {ptr = 0x5621b6a37b60, fd = -1230800032, u32 = 3064167264, u64 = 94702798076768}}, {events = 1787603200, data = {ptr = 0xefef2506, fd = -269540090, u32 = 4025427206, u64 = 4025427206}}, {events = 0, data = {ptr = 0x5621b6a32278, fd = -1230822792, u32 = 3064144504, u64 = 94702798054008}}}
        source = <optimized out>
        i = 0
        count = <optimized out>
        has_timers = <optimized out>
#2  0x00007f9f8260ac67 in wl_display_run (display=0x5621b6a32250) at ../wayland-1.19.0/src/wayland-server.c:1351
#3  0x00005621b4d09901 in server_run (server=<optimized out>) at ../sway-1.6/sway/server.c:275
        config_path = 0x0
        usage = 0x5621b4d63c30 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = <optimized out>
        long_options = 
            {{name = 0x5621b4d6332d "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x5621b4d6660c "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x5621b4d63332 "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x5621b4d6333b "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x5621b4d631ed "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x5621b4d619e1 "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x5621b4d63341 "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x5621b4d63350 "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x5621b4d63360 "my-next-gpu-wont-be-nvidia", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        validate = 0
        debug = 0
        allow_unsupported_gpu = 0
        verbose = 0
#4  main (argc=<optimized out>, argv=<optimized out>) at ../sway-1.6/sway/main.c:431
        config_path = 0x0
        usage = 0x5621b4d63c30 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = <optimized out>
        long_options = 
            {{name = 0x5621b4d6332d "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x5621b4d6660c "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x5621b4d63332 "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x5621b4d6333b "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x5621b4d631ed "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x5621b4d619e1 "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x5621b4d63341 "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x5621b4d63350 "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x5621b4d63360 "my-next-gpu-wont-be-nvidia", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        validate = 0
        debug = 0
        allow_unsupported_gpu = 0
        verbose = 0
(gdb) 
```

- **Description:**
* Run sway
* Start XWayland (I am using Discord here)
* `swaymsg reload`

**Comment by Scrumplex** [comment]
I need to check if other XWayland apps are affected too

**Comment by Scrumplex** [comment]
I can also reproduce this with Steam

**Comment by Synthetica9** [comment]
It's definitely not _all_ xwayland apps; I can reload with Xeyes open just fine

**Comment by Cyfraka** [comment]
dmenu and Firefox (if not running on wayland) too.

**Comment by Scrumplex** [comment]
I am suspecting that it only happens when WebViews are involved? I could only reproduce it with Electron or CEF applications

**Comment by binex-dsk** [comment]
can not reproduce, did you compile with Xwayland support
