### ISSUE TITLE
Segfault in `cmd_fullscreen`

### ISSUE THREAD

**Issue by Xyene** [swaywm/sway#6260]
Sway 6999927875d0d755f7f762440f001b78d69e4acf.

Got this while un-fullscreening a container:

```
(gdb) bt full
#0  0x000055ca6e24d1cb in cmd_fullscreen (argc=1, argv=0x55ca70b09c88) at ../sway/commands/fullscreen.c:36
        error = 0x0
        node = 0x55ca7056e4b0
        container = 0x0
        workspace = 0x55ca7056e4b0
        is_fullscreen = false
        global = false
        enable = false
        mode = FULLSCREEN_NONE
#1  0x000055ca6e213eda in execute_command (_exec=0x55ca6ff31bf0 "fullscreen toggle", seat=0x55ca6ff066e0, con=0x0) at ../sway/commands.c:291
        res = 0x40
        argc = 2
        argv = 0x55ca70b09c80
        handler = 0x55ca6e2964e0 <command_handlers+64>
        cmd = 0x55ca70a37170 "fullscreen toggle"
        matched_delim = 0 '\000'
        containers = 0x0
        using_criteria = false
        __PRETTY_FUNCTION__ = "execute_command"
        exec = 0x55ca70a37170 "fullscreen toggle"
        head = 0x0
        res_list = 0x55ca70bd3650
#2  0x000055ca6e2499e6 in seat_execute_command (seat=0x55ca6ff066e0, binding=0x55ca6ff31d50) at ../sway/commands/bind.c:631
        con = 0x0
        res_list = 0x7ffc7ce81990
        success = false
#3  0x000055ca6e234d8c in handle_key_event (keyboard=0x55ca70135eb0, event=0x7ffc7ce81b50) at ../sway/input/keyboard.c:491
        seat = 0x55ca6ff066e0
        wlr_seat = 0x55ca6ff068f0
        wlr_device = 0x55ca6ff76360
        device_identifier = 0x55ca70958200 "0:0:"
        exact_identifier = false
        input_inhibited = false
        sway_inhibitor = 0x0
        shortcuts_inhibited = false
        keyinfo = {keycode = 41, code_modifiers = 8, raw_keysyms = 0x55ca6ff948a8, raw_modifiers = 8, raw_keysyms_len = 1, translated_keysyms = 0x55ca6ff948a8, translated_modifiers = 8, translated_keysyms_len = 1}
        handled = false
        binding_released = 0x0
        binding = 0x55ca6ff31d50
#4  0x000055ca6e23501b in handle_keyboard_group_key (listener=0x55ca6ffb7aa0, data=0x7ffc7ce81b50) at ../sway/input/keyboard.c:563
        sway_group = 0x55ca6ffb7a90
#5  0x00007f42f0be86a1 in wlr_signal_emit_safe (signal=0x55ca6ff91be0, data=0x7ffc7ce81b50) at ../subprojects/wlroots/util/signal.c:29
        pos = 0x55ca6ffb7aa0
        l = 0x55ca6ffb7aa0
        cursor = {link = {prev = 0x55ca6ffb7aa0, next = 0x7ffc7ce819e0}, notify = 0x7f42f0be85fa <handle_noop>}
        end = {link = {prev = 0x7ffc7ce81a00, next = 0x55ca6ff91be0}, notify = 0x7f42f0be85fa <handle_noop>}
#6  0x00007f42f0bc8967 in wlr_keyboard_notify_key (keyboard=0x55ca6ff91ae0, event=0x7ffc7ce81b50) at ../subprojects/wlroots/types/wlr_keyboard.c:93
        updated = 111
#7  0x00007f42f0bc94c5 in handle_keyboard_key (listener=0x55ca702b8fb8, data=0x7ffc7ce81b50) at ../subprojects/wlroots/types/wlr_keyboard_group.c:133
        group_device = 0x55ca702b8fb0
#8  0x00007f42f0be86a1 in wlr_signal_emit_safe (signal=0x55ca70259010, data=0x7ffc7ce81b50) at ../subprojects/wlroots/util/signal.c:29
        pos = 0x55ca702b8fb8
        l = 0x55ca702b8fb8
        cursor = {link = {prev = 0x55ca702b8fb8, next = 0x55ca701772b0}, notify = 0x7f42f0be85fa <handle_noop>}
        end = {link = {prev = 0x55ca701772b0, next = 0x55ca70259010}, notify = 0x7f42f0be85fa <handle_noop>}
#9  0x00007f42f0bc8967 in wlr_keyboard_notify_key (keyboard=0x55ca70258f10, event=0x7ffc7ce81b50) at ../subprojects/wlroots/types/wlr_keyboard.c:93
        updated = 124
#10 0x00007f42f0b9a575 in handle_keyboard_key (event=0x55ca70a7e6d0, libinput_dev=0x55ca70012860) at ../subprojects/wlroots/backend/libinput/keyboard.c:82
        wlr_dev = 0x55ca70169200
        kbevent = 0x55ca70a7e6d0
        wlr_event = {time_msec = 13364545, keycode = 33, update_state = true, state = WL_KEYBOARD_KEY_STATE_PRESSED}
        state = LIBINPUT_KEY_STATE_PRESSED
#11 0x00007f42f0b9a129 in handle_libinput_event (backend=0x55ca6f771670, event=0x55ca70a7e6d0) at ../subprojects/wlroots/backend/libinput/events.c:237
        libinput_dev = 0x55ca70012860
        event_type = LIBINPUT_EVENT_KEYBOARD_KEY
#12 0x00007f42f0b98ee3 in handle_libinput_readable (fd=33, mask=1, _backend=0x55ca6f771670) at ../subprojects/wlroots/backend/libinput/backend.c:58
        backend = 0x55ca6f771670
        ret = 0
        event = 0x55ca70a7e6d0
#13 0x00007f42f051d39a in wl_event_loop_dispatch () from /lib/x86_64-linux-gnu/libwayland-server.so.0
No symbol table info available.
#14 0x00007f42f051b9ea in wl_display_run () from /lib/x86_64-linux-gnu/libwayland-server.so.0
No symbol table info available.
#15 0x000055ca6e22264e in server_run (server=0x55ca6e298580 <server>) at ../sway/server.c:254
No locals.
#16 0x000055ca6e221b48 in main (argc=3, argv=0x7ffc7ce81f88) at ../sway/main.c:433
        verbose = 1
        debug = 1
        validate = 0
        allow_unsupported_gpu = 0
        long_options = {{name = 0x55ca6e27a160 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x55ca6e27a165 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x55ca6e27a16c "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x55ca6e27a175 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x55ca6e27a17b "version", 
            has_arg = 0, flag = 0x0, val = 118}, {name = 0x55ca6e27a183 "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x55ca6e27a18b "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x55ca6e27a19a "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x55ca6e27a1aa "my-next-gpu-wont-be-nvidia", 
            has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        config_path = 0x0
        usage = 0x55ca6e279ba0 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = -1
```

Easy to reproduce.

- On one monitor, open `H[T[kitty] T[kitty*]]` (the `T`s may not be relevant, but my `workspace_layout` is `tiling`).
- Fullscreen the kitty window.
- On the other monitor, open another kitty window and focus it.
- `move` `left` (or `right`) to move the kitty window from one monitor under the one that is fullscreen on the other monitor.
- Press the keybinding for fullscreen.
- Sway crashes with the above stacktrace.

**Comment by RPigott** [comment]
I'm guessing this is fixed by #6205 as well. Your fullscreen command focused the workspace the second kitty left.
