### ISSUE TITLE
crash when using nvui with NvuiFrameless v:false

### ISSUE THREAD

**Issue by tom-kuca** [swaywm/sway#6470]
- **Sway Version:**
sway version 1.6-96102184 (Jul 19 2021, branch 'master')

- **Debug Log:**
See https://gist.github.com/tom-kuca/5279d5c658319459c00ba7ec1387c976

- **Configuration File:**
I wasn't able to find a way to start the program with default config, I created a single line config
```
 exec /home/tomas/bin/nn
```

- **Stack Trace:**
  
```
Core was generated by `sway -c config.min -d'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007ff6102cfb70 in wl_list_insert () from /usr/lib/libwayland-server.so.0
[Current thread is 1 (Thread 0x7ff60f331fc0 (LWP 2614204))]
(gdb) bt full
#0  0x00007ff6102cfb70 in wl_list_insert () at /usr/lib/libwayland-server.so.0
#1  0x000055a8734590a1 in  ()
#2  0x000055a87345925c in  ()
#3  0x00007ff61027b84e in wlr_signal_emit_safe () at /usr/lib/libwlroots.so.10
#4  0x00007ff60f9c3acd in  () at /usr/lib/libffi.so.7
#5  0x00007ff60f9c303a in  () at /usr/lib/libffi.so.7
#6  0x00007ff6102cf124 in  () at /usr/lib/libwayland-server.so.0
#7  0x00007ff6102ca57c in  () at /usr/lib/libwayland-server.so.0
#8  0x00007ff6102cd07a in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#9  0x00007ff6102cabe7 in wl_display_run () at /usr/lib/libwayland-server.so.0
#10 0x000055a87340f878 in  ()
#11 0x00007ff60ffdfb25 in __libc_start_main () at /usr/lib/libc.so.6
#12 0x000055a87340fbde in  ()
```

 
- **Description:**

I started an editor [nvui](https://github.com/rohit-px2/nvui) and I wrote a few lines of text. After a few seconds and about two lines, sway crashes. I was able to reproduce it multiple times, sway always crashed.

`/home/tomas/bin/nn`: 
```shell
#!/bin/sh


export GDK_SCALE=1
export GDK_DPI_SCALE=1
export QT_SCALE=1
export GDK_BACKEND=x11

exec ~/code/nvui/nvui --ext_cmdline --ext_popupmenu --ext_multigrid "$@"
```

nvui was started with configuration
```
 NvuiFrameless v:false
 ```

Without it, sway doesn't crash.

 nvui is a young project, it may do strange things. However, it should not be able to crash sway.

**Comment by emersion** [comment]
The backtrace you provided doesn't contain debug symbols. This most likely happens because the Sway binary you're using doesn't have debug information bundled.

Can you try again with a manually compiled Sway binary? See https://github.com/swaywm/sway/wiki/Development-Setup#compiling-as-a-subproject

**Comment by tom-kuca** [comment]
Sure. Here is the backtrace with debug symbols.

```
Core was generated by `/home/tomas/code/projects/sway/build/sway/sway -c config.min -d'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f004b69fb70 in wl_list_insert () from /usr/lib/libwayland-server.so.0
[Current thread is 1 (Thread 0x7f004a7b9940 (LWP 2671672))]
(gdb) bt full
#0  0x00007f004b69fb70 in wl_list_insert () at /usr/lib/libwayland-server.so.0
#1  0x000055f4e24b0ca0 in wl_signal_add (signal=0x55f4e4e61508, listener=0x55f4e4cc2b70) at /usr/include/wayland-server-core.h:441
#2  0x000055f4e24b3dd3 in view_child_init (child=0x55f4e4cc2ab0, impl=0x55f4e24de070 <subsurface_impl>, view=0x55f4e4e613f0, surface=0x55f4e4e61000) at ../sway/tree/view.c:1107
        workspace = 0x0
#3  0x000055f4e24b385e in view_child_subsurface_create (child=0x55f4e4cc5520, wlr_subsurface=0x55f4e4ebd8f0) at ../sway/tree/view.c:984
        subsurface = 0x55f4e4cc2ab0
#4  0x000055f4e24b3a58 in view_child_handle_surface_new_subsurface (listener=0x55f4e4cc5580, data=0x55f4e4ebd8f0) at ../sway/tree/view.c:1028
        child = 0x55f4e4cc5520
        subsurface = 0x55f4e4ebd8f0
#5  0x00007f004bda0c9b in wlr_signal_emit_safe (signal=0x55f4e4e18ae8, data=0x55f4e4ebd8f0) at ../subprojects/wlroots/util/signal.c:29
        pos = 0x55f4e4cc5580
        l = 0x55f4e4cc5580
        cursor = {link = {prev = 0x55f4e4cc5580, next = 0x7fff9a29c1b0}, notify = 0x7f004bda0be5 <handle_noop>}
        end = {link = {prev = 0x7fff9a29c190, next = 0x55f4e4e18ae8}, notify = 0x7f004bda0be5 <handle_noop>}
#6  0x00007f004bd956d1 in subsurface_create (surface=0x55f4e4e61000, parent=0x55f4e4e18840, version=1, id=54) at ../subprojects/wlroots/types/wlr_surface.c:1198
        client = 0x55f4e4e67310
        subsurface = 0x55f4e4ebd8f0
#7  0x00007f004bd71d81 in subcompositor_handle_get_subsurface (client=0x55f4e4e67310, resource=0x55f4e4ea0220, id=54, surface_resource=0x55f4e4e61360, parent_resource=0x55f4e4e71390) at ../subprojects/wlroots/types/wlr_compositor.c:70
        surface = 0x55f4e4e61000
        parent = 0x55f4e4e18840
        msg = "get_subsurface: wl_subsurface@"
#8  0x00007f004ad96acd in  () at /usr/lib/libffi.so.7
#9  0x00007f004ad9603a in  () at /usr/lib/libffi.so.7
#10 0x00007f004b69f124 in  () at /usr/lib/libwayland-server.so.0
#11 0x00007f004b69a57c in  () at /usr/lib/libwayland-server.so.0
#12 0x00007f004b69d07a in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#13 0x00007f004b69abe7 in wl_display_run () at /usr/lib/libwayland-server.so.0
#14 0x000055f4e2466430 in server_run (server=0x55f4e24e05a0 <server>) at ../sway/server.c:261
#15 0x000055f4e246584b in main (argc=4, argv=0x7fff9a29c988) at ../sway/main.c:395
        verbose = 0
        debug = 1
        validate = 0
        allow_unsupported_gpu = 0
        long_options = 
            {{name = 0x55f4e24c2080 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x55f4e24c2085 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x55f4e24c208c "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x55f4e24c2095 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x55f4e24c209b "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x55f4e24c20a3 "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x55f4e24c20ab "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x55f4e24c20ba "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x55f4e24c20ca "my-next-gpu-wont-be-nvidia", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        config_path = 0x55f4e4075b60 "config.min"
        usage = 0x55f4e24c1af0 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = -1
```

* sway version 1.6-daaec72a (Aug 30 2021, branch 'master')
