### ISSUE TITLE
Segfault during a libseat event when closing laptop lid

### ISSUE THREAD

**Issue by stevenengler** [swaywm/sway#6580]
### Please fill out the following:
- **Sway Version:**
```
sway version 1.6-8fa7b998 (Oct  4 2021, branch 'master')
```

- **Debug Log:**
https://paste.debian.net/hidden/10ad3fe2/

- **Configuration File:**
The default config from `/etc/sway/config`

- **Stack Trace:**
```
Core was generated by `sway --config /etc/sway/config -d'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000558dba8b94dc in ping_handler (m=0x558dbc28a660, userdata=0x0, ret_error=0x7ffeb36941a0) at ../subprojects/seatd/libseat/backend/logind.c:79
#1  0x00007fa4b1088cf7 in ?? () from /lib/x86_64-linux-gnu/libsystemd.so.0
#2  0x0000558dba8b9ee5 in dispatch_and_execute (base=0x558dbb8f2590, timeout=0) at ../subprojects/seatd/libseat/backend/logind.c:277
#3  0x0000558dba8b72e4 in libseat_dispatch (seat=0x558dbb8f2590, timeout=0) at ../subprojects/seatd/libseat/libseat.c:116
#4  0x0000558dba85b77a in libseat_event (fd=4, mask=1, data=0x558dbb8f23a0) at ../subprojects/wlroots/backend/session/session.c:41
#5  0x00007fa4b1206b6a in wl_event_loop_dispatch (loop=0x558dbb8ebb30, timeout=timeout@entry=-1) at ../src/event-loop.c:1027
#6  0x00007fa4b1205075 in wl_display_run (display=0x558dbb8f2210) at ../src/wayland-server.c:1364
#7  0x0000558dba7e00ba in server_run (server=0x558dba91dfa0 <server>) at ../sway/server.c:285
#8  0x0000558dba7df401 in main (argc=4, argv=0x7ffeb3694668) at ../sway/main.c:397
Stack level 0, frame at 0x7ffeb3694170:
 rip = 0x558dba8b94dc in ping_handler (../subprojects/seatd/libseat/backend/logind.c:79); saved rip = 0x7fa4b1088cf7
 called by frame at 0x7ffeb3694260
 source language c.
 Arglist at 0x7ffeb3694128, args: m=0x558dbc28a660, userdata=0x0, ret_error=0x7ffeb36941a0
 Locals at 0x7ffeb3694128, Previous frame's sp is 0x7ffeb3694170
 Saved registers:
  rbp at 0x7ffeb3694160, rip at 0x7ffeb3694168
session = 0x0
```

- **Description:**
Built sway using the most recent commits from sway, wlroots, wayland-protocols, seatd, wayland, and libxcb-render-util. I also tried building the most recent sway release, but I couldn't build it because of too many meson errors. This segfault occurs when I close the laptop lid, or when I switch ttys.

**Comment by emersion** [comment]
cc @kennylevinsen

**Comment by kennylevinsen** [comment]
@stevenengler Could you try https://git.sr.ht/~kennylevinsen/seatd/commit/e35c9cd02e95ec8a76bb4bb82f801a795e135bc9?

**Comment by stevenengler** [comment]
> @stevenengler Could you try https://git.sr.ht/~kennylevinsen/seatd/commit/e35c9cd02e95ec8a76bb4bb82f801a795e135bc9?

Thanks, that fixed that segfault! I can now switch ttys without crashing, but still cannot close the laptop lid due to a second segfault. This new error seems to be in another part of the code, so I made a new issue for it: #6583.

**Comment by kennylevinsen** [comment]
Closing as fixed in seatd master.
