### ISSUE TITLE
Segfault in `node_is_view` with NULL node ptr when closing laptop lid

### ISSUE THREAD

**Issue by stevenengler** [swaywm/sway#6583]
### Please fill out the following:
- **Sway Version:**
```
sway version 1.6-8fa7b998 (Oct  5 2021, branch 'master')
```

- **Debug Log:**
https://pastebin.com/qq36GsBH

- **Configuration File:**
The default from `/etc/sway/config` with the following changes to trigger the bug:

```
exec swayidle -w \
         timeout 300 'swaylock -f -c 000000' \
         timeout 600 'swaymsg "output * dpms off"' \
              resume 'swaymsg "output * dpms on"' \
         before-sleep 'swaylock -f -c 000000'

set $laptop_display 'eDP-1'

# also tried without the '--locked'
bindswitch --reload --locked lid:on output $laptop_display disable
bindswitch --reload --locked lid:off output $laptop_display enable
```

- **Stack Trace:**
```
#0  0x0000555d495f8b37 in node_is_view (node=0x0) at ../sway/tree/node.c:41
#1  0x0000555d495c96bd in seat_set_exclusive_client (seat=0x555d4a79c350, client=0x555d4ab39460) at ../sway/input/seat.c:1319
#2  0x0000555d495bcebd in handle_inhibit_activate (listener=0x555d4a79bff8, data=0x555d4a79c1e0) at ../sway/input/input-manager.c:284
#3  0x0000555d49671aeb in wlr_signal_emit_safe (signal=0x555d4a79c210, data=0x555d4a79c1e0) at ../subprojects/wlroots/util/signal.c:29
#4  0x0000555d49649fe5 in inhibit_manager_get_inhibitor (client=0x555d4ab39460, resource=0x555d4ab2aca0, id=3) at ../subprojects/wlroots/types/wlr_input_inhibitor.c:74
#5  0x00007fd2409f3ff5 in ?? () from /lib/x86_64-linux-gnu/libffi.so.7
#6  0x00007fd2409f340a in ?? () from /lib/x86_64-linux-gnu/libffi.so.7
#7  0x00007fd241407b78 in wl_closure_invoke (closure=0x555d4abdc2c0, flags=2, target=<optimized out>, opcode=0, data=<optimized out>) at ../src/connection.c:1025
#8  0x00007fd241403e82 in wl_client_connection_data (fd=<optimized out>, mask=<optimized out>, data=0x555d4ab39460) at ../src/wayland-server.c:433
#9  0x00007fd241405b6a in wl_event_loop_dispatch (loop=0x555d49ed2b30, timeout=timeout@entry=-1) at ../src/event-loop.c:1027
#10 0x00007fd241404075 in wl_display_run (display=0x555d49ed9210) at ../src/wayland-server.c:1364
#11 0x0000555d495b00ba in server_run (server=0x555d496edfa0 <server>) at ../sway/server.c:285
#12 0x0000555d495af401 in main (argc=4, argv=0x7fff7adaddd8) at ../sway/main.c:397
Stack level 0, frame at 0x7fff7adad590:
 rip = 0x555d495f8b37 in node_is_view (../sway/tree/node.c:41); saved rip = 0x555d495c96bd
 called by frame at 0x7fff7adad5f0
 source language c.
 Arglist at 0x7fff7adad578, args: node=0x0
 Locals at 0x7fff7adad578, Previous frame's sp is 0x7fff7adad590
 Saved registers:
  rbp at 0x7fff7adad580, rip at 0x7fff7adad588
No locals.
```

- **Description:**
Built sway using the most recent commits from sway, wlroots, wayland-protocols, seatd, wayland, and libxcb-render-util. For seatd, it was also run with [this patch](https://git.sr.ht/~kennylevinsen/seatd/commit/e35c9cd02e95ec8a76bb4bb82f801a795e135bc9) (edit: now in seatd master) from #6580. Bug occurs when the laptop lid is closed and re-opened.

**Comment by stevenengler** [comment]
Oops, looks like this is a duplicate of https://github.com/swaywm/sway/issues/6395.

**Comment by RPigott** [comment]
Yeah, closing as dup.
