### ISSUE TITLE
swaymsg: Segfaulting in main

### ISSUE THREAD

**Issue by Scrumplex** [swaywm/sway#6618]
Introduced by #6611

119f31edb4f0c61fd074229040dd93e047ff7cb4 works

### Please fill out the following:
- **Sway Version:** sway version 1.6-db70f649 (Oct 18 2021, branch 'master')

- **Backtrace:**

```
GNU gdb (GDB) 11.1
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from swaymsg...
Reading symbols from /usr/lib/debug/usr/bin/swaymsg.debug...
(gdb) run
Starting program: /usr/bin/swaymsg 

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7f8414b in json_tokener_parse_ex () from /usr/lib/libjson-c.so.5
(gdb) bt full
#0  0x00007ffff7f8414b in json_tokener_parse_ex () from /usr/lib/libjson-c.so.5
No symbol table info available.
#1  0x0000555555556521 in main (argc=<optimized out>, argv=<optimized out>) at ../sway/swaymsg/main.c:485
        socket_path = 0x55555555d2c0 "/run/user/1000/sway-ipc.1000.32198.sock"
        cmdtype = <optimized out>
        usage = 0x555555559550 "Usage: swaymsg [options] [message]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -m, --monitor          Monitor until killed (-t SUBSCRIBE only)\n  -p, --pretty", ' ' <repeats 11 times>, "Use pretty output ev"...
        c = <optimized out>
        type = <optimized out>
        command = 0x55555555d2a0 ""
        ret = 0
        socketfd = 3
        timeout = <optimized out>
        len = <optimized out>
        resp = 0x55555555d310 "[ ]"
        tok = 0x0
        obj = <optimized out>
        err = <optimized out>
        raw = false
        long_options = {{name = 0x55555555942e "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x555555559433 "monitor", has_arg = 0, flag = 0x0, val = 109}, {name = 0x55555555943b "pretty", has_arg = 0, flag = 0x0, val = 112}, {name = 0x555555559442 "quiet", has_arg = 0, 
            flag = 0x0, val = 113}, {name = 0x555555559448 "raw", has_arg = 0, flag = 0x0, val = 114}, {name = 0x55555555944c "socket", has_arg = 1, flag = 0x0, val = 115}, {name = 0x555555559200 "type", has_arg = 1, flag = 0x0, val = 116}, {name = 0x55555555910b "version", 
            has_arg = 0, flag = 0x0, val = 118}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        monitor = false
        quiet = false
```

- **Configuration File:**
 https://gitlab.com/Scrumplex/dotfiles/-/blob/567ec1baf904d85d7d527d4b7e251959840ed31a/sway/.config/sway/config

- **Description:**
I just ran swaymsg without arguments and it instantly segfaults.

**Comment by Xyene** [comment]
Do you have overcommit turned off? Have a virtual memory limit imposed by ulimit? Link a strange libc?

**Comment by ammgws** [comment]
I can reproduce the issue too:

```sh
> sysctl vm.overcommit_memory
vm.overcommit_memory = 0

>ulimit
unlimited
```

> Link a strange libc?

Don't think so
