### ISSUE TITLE
Core dump error

### ISSUE THREAD

**Issue by Zeioth** [swaywm/sway#6788]
### Please fill out the following:
- **Sway Version:** 1.6.1 (also happen with sway-git)

- **Debug Log:**
search for: [Process 2033 (sway) of user 1000 dumped core](https://pastebin.com/ABBCBdLu).

- **Configuration File:**
Irrelevant, as it's been working fine for many months with the same config, until maybe 1 month ago.

- **Stack Trace:**

bt full output
```bash
#0  0x00007faa24e40d22 in raise () at /usr/lib/libc.so.6
#1  0x00007faa24e2a862 in abort () at /usr/lib/libc.so.6
#2  0x00007faa24e2a747 in _nl_load_domain.cold () at /usr/lib/libc.so.6
#3  0x00007faa24e39616 in  () at /usr/lib/libc.so.6
#4  0x00007faa25083d85 in  () at /usr/lib/libwlroots.so.9
#5  0x00007faa2507b181 in wlr_renderer_begin_with_buffer () at /usr/lib/libwlroots.so.9
#6  0x00007faa250be0a6 in  () at /usr/lib/libwlroots.so.9
#7  0x00007faa250be516 in  () at /usr/lib/libwlroots.so.9
#8  0x00007faa250c8f9e in wlr_signal_emit_safe () at /usr/lib/libwlroots.so.9
#9  0x00007faa250c171b in  () at /usr/lib/libwlroots.so.9
#10 0x00007faa247e7d4a in  () at /usr/lib/libffi.so.8
#11 0x00007faa247e7267 in  () at /usr/lib/libffi.so.8
#12 0x00007faa2511c323 in  () at /usr/lib/libwayland-server.so.0
#13 0x00007faa251175cc in  () at /usr/lib/libwayland-server.so.0
#14 0x00007faa2511a1ca in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#15 0x00007faa25117d37 in wl_display_run () at /usr/lib/libwayland-server.so.0
#16 0x00007faa257e1980 in  ()
#17 0x00007faa24e2bb25 in __libc_start_main () at /usr/lib/libc.so.6
#18 0x00007faa257e1cee in  ()
```

- **Description:**
It happens randomly in the next instances: 

* When I turn on/off monitors
* When I press any key on swaylock.
* When reproducing video on vlc player

**Comment by Zeioth** [comment]
I correct myself, it doesn't seem to be happening anymore in sway-git+wlroots-git+mesa-git
