### ISSUE TITLE
Crash when typing password in swaylock

### ISSUE THREAD

**Issue by MayeulC** [swaywm/sway#6916]
### Please fill out the following:
- **Sway Version:** 1.7

- **Debug Log:** Unfortunately, I don't have it. It's not like I was expecing this to happen

- **Configuration File:** I'll attach if really necessary, but nothing too fancy.
- **Stack Trace:**

```
(gdb) bt full
#0  0x00007f0b67c8b34c in __pthread_kill_implementation () at /usr/lib/libc.so.6
#1  0x00007f0b67c3e4b8 in raise () at /usr/lib/libc.so.6
#2  0x00007f0b67c28534 in abort () at /usr/lib/libc.so.6
#3  0x00007f0b67c7f397 in __libc_message () at /usr/lib/libc.so.6
#4  0x00007f0b67c9533c in  () at /usr/lib/libc.so.6
#5  0x00007f0b67c95f84 in malloc_consolidate () at /usr/lib/libc.so.6
#6  0x00007f0b67c98103 in _int_malloc () at /usr/lib/libc.so.6
#7  0x00007f0b67c9a489 in calloc () at /usr/lib/libc.so.6
#8  0x00007f0b684367b5 in lh_table_new (size=size@entry=32, free_fn=free_fn@entry=0x0, hash_fn=0x7f0b6843c1f0 <lh_char_hash>, equal_fn=0x7f0b684345b0 <lh_char_equal>) at /usr/src/debug/json-c/linkhash.c:511
        i = <optimized out>
        t = 0x562acba6dc10
        __PRETTY_FUNCTION__ = "lh_table_new"
#9  0x00007f0b68436a37 in lh_table_resize (t=t@entry=0x562acba3d900, new_size=32) at /usr/src/debug/json-c/linkhash.c:540
        new_t = <optimized out>
        ent = <optimized out>
#10 0x00007f0b68436934 in lh_table_insert_w_hash (t=0x562acba3d900, k=0x562acba6e3b0, v=0x562acba5b5b0, h=1234730074, opts=opts@entry=0) at /usr/src/debug/json-c/linkhash.c:587
        new_size = <optimized out>
        n = <optimized out>
#11 0x00007f0b68438b1c in json_object_object_add_ex (jso=jso@entry=0x562acba280d0, key=key@entry=0x562ac9513515 "deco_rect", val=<optimized out>, opts=opts@entry=0) at /usr/src/debug/json-c/json_object.c:611
        k = <optimized out>
        existing_value = 0x0
        existing_entry = <optimized out>
        hash = <optimized out>
        __PRETTY_FUNCTION__ = "json_object_object_add_ex"
#12 0x00007f0b68438bac in json_object_object_add (jso=jso@entry=0x562acba280d0, key=key@entry=0x562ac9513515 "deco_rect", val=<optimized out>) at /usr/src/debug/json-c/json_object.c:622
#13 0x0000562ac94bce0c in ipc_json_create_node (id=1, type=0x562ac951355a "root", name=name@entry=0x562ac951355a "root", focused=<optimized out>, focus=focus@entry=0x562acba761b0, box=0x7fff16c0f580, box@entry=0x7fff16c0f610) at ../sway-1.7/sway/ipc-json.c:230
        object = 0x562acba280d0
#14 0x0000562ac94bd12d in ipc_json_describe_node (node=node@entry=0x562acab894f0) at ../sway-1.7/sway/ipc-json.c:702
        seat = 0x562acb20e0a0
        focused = <optimized out>
        name = 0x562ac951355a "root"
        box = {x = 0, y = 0, width = 2688, height = 1360}
        focus = 0x562acba761b0
        object = <optimized out>
#15 0x0000562ac94be436 in ipc_json_describe_node_recursive (node=0x562acab894f0) at ../sway-1.7/sway/ipc-json.c:723
        object = <optimized out>
        i = <optimized out>
        children = <optimized out>
#16 0x0000562ac94c377b in ipc_client_handle_command (client=0x562acb917db0, payload_length=0, payload_type=IPC_GET_TREE) at ../sway-1.7/sway/ipc-server.c:797
        tree = <optimized out>
        json_string = <optimized out>
        buf = 0x562acb9b7dd0 ""
#17 0x0000562ac94c45d4 in ipc_client_handle_command (payload_type=IPC_GET_TREE, payload_length=0, client=0x562acb917db0) at ../sway-1.7/sway/ipc-server.c:609
        pending_length = 0
        pending_type = IPC_GET_TREE
        client = 0x562acb917db0
        read_available = 14
        buf = "i3-ipc\000\000\000\000\004\000\000"
        received = <optimized out>
#18 ipc_client_handle_readable (client_fd=<optimized out>, mask=<optimized out>, data=0x562acb917db0) at ../sway-1.7/sway/ipc-server.c:267
        pending_length = 0
        pending_type = IPC_GET_TREE
        client = 0x562acb917db0
        read_available = 14
        buf = "i3-ipc\000\000\000\000\004\000\000"
        received = <optimized out>
#19 0x00007f0b67f6a1ca in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#20 0x00007f0b67f67d37 in wl_display_run () at /usr/lib/libwayland-server.so.0
#21 0x0000562ac94bba4a in server_run (server=<optimized out>) at ../sway-1.7/sway/server.c:304
        config_path = 0x0
        usage = 0x562ac9515c98 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = <optimized out>
        long_options = {{name = 0x562ac9515323 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x562ac951858f "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x562ac9515328 "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x562ac9515331 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x562ac9515208 "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x562ac9513a11 "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x562ac9515337 "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x562ac9515346 "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        validate = 0
        debug = 0
        allow_unsupported_gpu = 0
        verbose = 0
#22 main (argc=<optimized out>, argv=<optimized out>) at ../sway-1.7/sway/main.c:431
        config_path = 0x0
        usage = 0x562ac9515c98 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = <optimized out>
        long_options = {{name = 0x562ac9515323 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x562ac951858f "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x562ac9515328 "validate", has_arg = 0, flag = 0x0, val = 67}, {name = 0x562ac9515331 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x562ac9515208 "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x562ac9513a11 "verbose", has_arg = 0, flag = 0x0, val = 86}, {name = 0x562ac9515337 "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x562ac9515346 "unsupported-gpu", has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        validate = 0
        debug = 0
        allow_unsupported_gpu = 0
        verbose = 0
```

- **Description:**
  - I walked away from my computer for a while, swaylock started up
  - I came back to it and started entering my password
  - swaylock displayed the typing animation for a few letters, and I was dropped back to the tty.

It could be an OOM, although I have 16GB RAM and only Firefox was running. Moreover, the system was booted up less than 2 hours before the crash.

**Comment by emersion** [comment]
Smells like memory corruption. Would be nice to manage to repro with ASan.

**Comment by MayeulC** [comment]
I could try to rebuild with ASan, but I am not sure if I'll ever reproduce that crash. Is the slowdown important with sway?
