### ISSUE TITLE
sway segfault, reliable trigger

### ISSUE THREAD

**Issue by wolfboxpen** [swaywm/sway#6918]
sway 1.7
kernel 5.16.16

gpu: VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Caicos [Radeon HD 6450/7450/8450 / R5 230 OEM]

Reproduction:
Calibre epub viewer floating window (denied access to /dev/dri, with access reproduction fails)
mod+mouse+drag resize (not immediate trigger, if lucky may not trigger in the first second at all)
triggers sway segfault

GDB:
```
(gdb) bt full
#0  __memmove_sse2_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:248
No locals.
#1  0x0000789c467c8b32 in ?? () from /usr/lib64/dri/r600_dri.so
No symbol table info available.
#2  0x0000789c46ce9f27 in ?? () from /usr/lib64/dri/r600_dri.so
No symbol table info available.
#3  0x0000789c47287f3f in ?? () from /usr/lib64/dri/r600_dri.so
No symbol table info available.
#4  0x0000789c467cfdf7 in ?? () from /usr/lib64/dri/r600_dri.so
No symbol table info available.
#5  0x0000789c467d0873 in ?? () from /usr/lib64/dri/r600_dri.so
No symbol table info available.
#6  0x0000789c46965115 in ?? () from /usr/lib64/dri/r600_dri.so
No symbol table info available.
#7  0x0000789c469670ee in ?? () from /usr/lib64/dri/r600_dri.so
No symbol table info available.
#8  0x0000789c49e7f382 in gles2_texture_from_pixels (wlr_renderer=0x5d995d207f50, drm_format=909199186, stride=2858, width=1429, 
    height=1043, data=0x789c2fc01000) at ../render/gles2/texture.c:225
        renderer = 0x5d995d207f50
        fmt = 0x789c49f0a950 <formats+144>
        drm_fmt = 0x789c49f08f90 <pixel_format_info+208>
        __PRETTY_FUNCTION__ = "gles2_texture_from_pixels"
        texture = 0x5d995d995300
        prev_ctx = {display = 0x0, context = 0x0, draw_surface = 0x0, read_surface = 0x0}
        __func__ = "gles2_texture_from_pixels"
#9  0x0000789c49e7f833 in gles2_texture_from_buffer (wlr_renderer=0x5d995d207f50, buffer=0x5d995d878750)
    at ../render/gles2/texture.c:349
        tex = 0x0
        renderer = 0x5d995d207f50
--Type <RET> for more, q to quit, c to continue without paging--
        data = 0x789c2fc01000
        format = 909199186
        stride = 2858
        dmabuf = {width = 91, height = 119, format = 110, modifier = 102913280484752, n_planes = 42352, offset = {0, 1232296448, 
            30876, 1859558656}, stride = {2759580012, 1569906528, 23961, 1646037792}, fd = {32766, 1569906528, 23961, 1233207889}}
#10 0x0000789c49e799e6 in wlr_texture_from_buffer (renderer=0x5d995d207f50, buffer=0x5d995d878750) at ../render/wlr_texture.c:69
No locals.
#11 0x0000789c49ec9604 in wlr_client_buffer_create (buffer=0x5d995d878750, renderer=0x5d995d207f50) at ../types/wlr_buffer.c:240
        texture = 0xa47bd96c6ed69d00
        client_buffer = 0x7ffe621c8950
#12 0x0000789c49ecb1bb in surface_apply_damage (surface=0x5d995d92df40) at ../types/wlr_compositor.c:342
        buffer = 0x5d995d92dfc0
#13 0x0000789c49ecb610 in surface_commit_state (surface=0x5d995d92df40, next=0x5d995d92e0c8) at ../types/wlr_compositor.c:435
        __PRETTY_FUNCTION__ = "surface_commit_state"
        invalid_buffer = true
        subsurface = 0xa47bd96c6ed69d00
#14 0x0000789c49ecb9da in surface_handle_commit (client=0x5d995d8f3ed0, resource=0x5d995d90ea50) at ../types/wlr_compositor.c:523
        surface = 0x5d995d92df40
#15 0x0000789c489dde6d in ?? () from /usr/lib64/libffi.so.7
No symbol table info available.
#16 0x0000789c489dd2aa in ?? () from /usr/lib64/libffi.so.7
No symbol table info available.
#17 0x0000789c497c9085 in ?? () from /usr/lib64/libwayland-server.so.0
No symbol table info available.
#18 0x0000789c497cd0bc in ?? () from /usr/lib64/libwayland-server.so.0
No symbol table info available.
#19 0x0000789c497cbc12 in wl_event_loop_dispatch () from /usr/lib64/libwayland-server.so.0
No symbol table info available.
#20 0x0000789c497cc365 in wl_display_run () from /usr/lib64/libwayland-server.so.0
--Type <RET> for more, q to quit, c to continue without paging--
No symbol table info available.
#21 0x00005d995c74a1b4 in server_run (server=0x5d995c7c46c0 <server>) at ../sway/server.c:307
No locals.
#22 0x00005d995c749415 in main (argc=1, argv=0x7ffe621c9228) at ../sway/main.c:431
        verbose = false
        debug = false
        validate = false
        allow_unsupported_gpu = false
        long_options = {{name = 0x5d995c7a621c "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x5d995c7a6221 "config", 
            has_arg = 1, flag = 0x0, val = 99}, {name = 0x5d995c7a6228 "validate", has_arg = 0, flag = 0x0, val = 67}, {
            name = 0x5d995c7a6231 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x5d995c7a6237 "version", has_arg = 0, 
            flag = 0x0, val = 118}, {name = 0x5d995c7a623f "verbose", has_arg = 0, flag = 0x0, val = 86}, {
            name = 0x5d995c7a6247 "get-socketpath", has_arg = 0, flag = 0x0, val = 112}, {name = 0x5d995c7a6256 "unsupported-gpu", 
            has_arg = 0, flag = 0x0, val = 117}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        config_path = 0x0
        usage = 0x5d995c7a5c88 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = -1
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) info registers
rax            0x789c2d16c800      132612166699008
rbx            0xb2a               2858
rcx            0x442               1090
rdx            0xb2a               2858
rsi            0x789c2fed9000      132612214329344
rdi            0x789c2d16cee8      132612166700776
rbp            0xb2c               0xb2c
rsp            0x7ffe621c8198      0x7ffe621c8198
r8             0x0                 0
r9             0x0                 0
r10            0x1                 1
r11            0x413               1043
r12            0x413               1043
r13            0xc00               3072
r14            0x789c2fed9444      132612214330436
r15            0x413               1043
rip            0x789c4961dc94      0x789c4961dc94 <__memmove_sse2_unaligned_erms+68>
eflags         0x10297             [ CF PF AF SF IF RF ]
cs             0x33                51
ss             0x2b                43
ds             0x0                 0
es             0x0                 0
fs             0x0                 0
gs             0x0                 0
(gdb) x/4i $rip
=> 0x789c4961dc94 <__memmove_sse2_unaligned_erms+68>:	rep movsb %ds:(%rsi),%es:(%rdi)
   0x789c4961dc96 <__memmove_sse2_unaligned_erms+70>:	ret    
   0x789c4961dc97 <__memmove_sse2_unaligned_erms+71>:	cmp    $0x8,%dl
   0x789c4961dc9a <__memmove_sse2_unaligned_erms+74>:	jae    0x789c4961dcae <__memmove_sse2_unaligned_erms+94>
(gdb) 
```

**Comment by emersion** [comment]
Sounds like a driver bug
