### ISSUE TITLE
HEAD segfaults when running from outside build/ directory

### ISSUE THREAD

**Issue by ldelossa** [swaywm/sway#7045]
### Please fill out the following:
- **Sway Version:**
  - sway version 1.8-dev

- **Debug Log:**
  - https://gist.github.com/ldelossa/fcf8740bd728003b9b66d0ee4461a7d9 (using config.in from source repo)

- **Configuration File:**
  - I'm reproducing with /config.in config file in this repository.

- **Stack Trace:**
```
#0  __strlen_evex () at ../sysdeps/x86_64/multiarch/strlen-evex.S:77
#1  0x00007ffff7661a38 in __vfprintf_internal (s=s@entry=0x7fffffffd4b0, format=format@entry=0x47d188 "%s %s %s", ap=ap@entry=0x7fffffffd630, mode_flags=mode_flags@entry=0)
    at vfprintf-internal.c:1517
#2  0x00007ffff767206c in __vsnprintf_internal (string=0x7fffffffd760 "", maxlen=<optimized out>, format=0x47d188 "%s %s %s", args=args@entry=0x7fffffffd630, mode_flags=mode_flags@entry=0)
    at vsnprintf.c:114
#3  0x00007ffff764ab26 in __GI___snprintf (s=<optimized out>, maxlen=<optimized out>, format=<optimized out>) at snprintf.c:31
#4  0x0000000000440e3d in output_get_identifier (identifier=0x7fffffffd760 "", len=128, output=0xc9b430) at ../sway/config/output.c:30
#5  0x00000000004413ce in merge_id_on_name (oc=0xcbef80) at ../sway/config/output.c:157
#6  0x00000000004417cc in store_output_config (oc=0xcbef80) at ../sway/config/output.c:211
#7  0x000000000045091f in cmd_output (argc=0, argv=0xcd34a8) at ../sway/commands/output.c:104
#8  0x00000000004107e3 in config_command (exec=0xca5f70 "output DP-4  bg  $wallpaper stretch", new_block=0x7fffffffda18) at ../sway/commands.c:422
#9  0x00000000004135a5 in read_config (file=0x49a2d0, config=0xc9de40, swaynag=0xc9de48) at ../sway/config.c:859
#10 0x00000000004123fe in load_config (path=0xc9de10 "/home/louis/.config/sway/config", config=0xc9de40, swaynag=0xc9de48) at ../sway/config.c:428
#11 0x000000000041271c in load_main_config (file=0x0, is_active=false, validating=false) at ../sway/config.c:543
#12 0x000000000041dcf3 in main (argc=1, argv=0x7fffffffdd38) at ../sway/main.c:411
```

- **Description:**
I typically compile `sway` with `wlroots` as a sub-project pointed to is local gitlab repo on my system. I typically run bleeding edge of both. 

Recently, it appears that `sway` segfaults when starting. 
Oddly enough if I run `sway` directly from its meson `build/sway` directory, everything works fine.
  
I can actually avoid the issue by symlinking each sway binary from its build directory into `/usr/local/bin`. 

The provided stack trace seems to segfault within the `snprintf` ASM. I'm not sure why any of this works when running from the `build/` directory vs running from any directory outside of it.

**Comment by emersion** [comment]
Make sure you're updating Sway and wlroots together. Latest Sway commit has a NULL check here.

**Comment by ldelossa** [comment]
@emersion I just confirmed. 

Pulled down latest sway:

```
~/git/c/sway master*
🖭  git log -n 1
commit e5728052b59fb5b476c78c9f18b812a85d7f4503 (HEAD -> master, origin/master, origin/HEAD)
Author: Kenny Levinsen <kl@kl.wtf>
Date:   Wed Jun 1 20:01:19 2022 +0200

    Refuse to start when SUID is detected
    
    This ensures that those surprised by the deprecation of SUID operation
    receive an error rather than accidentally having sway run as root.
    
    This detection will be removed in a future release.
```

Pulled down latest wlroots 

```
~/git/c/wlroots master
🖭  git log -n 1      
commit 2b10ae62ad9c1a3de5d96dafbf0f86a9e897fc8e (HEAD -> master, origin/master, origin/HEAD)
Author: Isaac Freund <mail@isaacfreund.com>
Date:   Thu Jun 2 20:18:16 2022 +0200

    backend/drm: fix check for no-op commits
    
    Since 6936e163b, we short-circut no-op commits as an optimization.
    However, the logic in the check was slightly off.
```

I symlink the above wlroots repo into sway's subprojects

```
~/git/c/sway master*
🖭  ls -lah ./subprojects 
Permissions Size User  Date Modified Name
lrwxrwxrwx@   25 louis 28 Oct  2021   wlroots -> /home/louis/git/c/wlroots
```

When I do a meson build and install, I hit a segfault. 

```
🖭  sway
00:00:00.024 [wlr] [types/wlr_drm_lease_v1.c:713] No DRM backend supplied, failed to create wlr_drm_lease_v1_manager
zsh: segmentation fault (core dumped)  sway
```

As soon as I symlink it myself like this:

```
~/git/c/sway master*
🖭  sudo ln -s /home/louis/git/c/sway/build/sway/sway /usr/local/bin/sway
```

Sway starts without issue. 

I'm fully aware this maybe a local problem, if you don't see this as a problem with Sway feel free to close the issue. I'm just a bit perplexed by this, since I've done this quite a bit to run bleeding edge.
