### ISSUE TITLE
no_focus on first window in tabbed layout

### ISSUE THREAD

**Issue by vicencb** [swaywm/sway#7322]
- Sway Version: 1.7

- Configuration File:
workspace_layout tabbed
no_focus [title=".*"]
bindsym Mod4+t exec foot
bindsym Mod4+Tab focus next

- Description:
The expected behaviour of no_focus is as stated in the man page: "has no effect on the first window in a workspace".
The actual behaviour is that none of the first windows created have focus, although they are all decorated like having focus.
Also, focus can not be switched between windows with the keyboard. The only workaround found so far is by moving the mouse cursor.
This issue happens with the tabbed layout.
Once there is a window with focus, then it works as expected: no new windows will take focus away of the currently focused one and changing focus manually works.

**Comment by vicencb** [comment]
This fixes the issue, but
i don't know the meaning of `view->container->pending.parent` and
no extensive tests performed, so,
please, review.

```diff
--- a/sway/tree/view.c
+++ b/sway/tree/view.c
@@ -639,7 +639,7 @@ static bool should_focus(struct sway_view *view) {
 
 	// If the view is the only one in the focused workspace, it'll get focus
 	// regardless of any no_focus criteria.
-	if (!view->container->pending.parent && !prev_con) {
+	if (!prev_con) {
 		size_t num_children = view->container->pending.workspace->tiling->length +
 			view->container->pending.workspace->floating->length;
 		if (num_children == 1) {
```

**Comment by z33ky** [comment]
I'm having the same issue.

I've attached a debugger to see where `view->container->pending.parent` gets set, which occurs in [container_add_child()](https://github.com/swaywm/sway/blob/909a2ddb5fff528e735341529a028d2ef21836db/sway/tree/container.c#L1497).
```
#0  container_add_child (parent=0x555555906640, child=0x55555592e8d0) at ../sway/tree/container.c:1497
#1  0x00005555555c9eb2 in container_split (child=0x55555592e8d0, layout=L_TABBED) at ../sway/tree/container.c:1618
#2  0x00005555555d2964 in workspace_add_tiling (workspace=0x555555b75700, con=0x55555592e8d0) at ../sway/tree/workspace.c:948
#3  0x00005555555ceaa0 in view_map (view=0x5555558ee860, wlr_surface=0x55555568f3e0, fullscreen=false, fullscreen_output=0x0, decoration=false) at ../sway/tree/view.c:854
```
Looking up the callstack in [workspace_add_tiling()](https://github.com/swaywm/sway/blob/909a2ddb5fff528e735341529a028d2ef21836db/sway/tree/workspace.c#L948) this seems to be conditional depending on `config->default_layout != L_NONE`, with `config->default_layout` corresponding to the `workspace_layout` setting in the config file.

I can't infer much more from a glance, but I hope this may help a more involved developer with tracing down the underlying issue, or evaluating the formerly proposed change/fix.
