### ISSUE TITLE
sway sigsegv when merging firefox windows

### ISSUE THREAD

**Issue by enedil** [swaywm/sway#7378]
### Please fill out the following:
- **Sway Version:**
  - `sway version 1.7`

- **Debug Log:**
  - I wanted to attach, but the issue no longer reproduces when I started sway again

- **Configuration File:**
  I omitted all registered keybindings and irrelevant `set`s
```
output DP-1 pos 1920 0
output HDMI-A-1 pos 0 0
output eDP-2 pos 0 0
output eDP-1 pos 0 1440

default_border pixel 1
workspace_auto_back_and_forth yes

gaps outer 1
exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway
exec_always dunst &
```

- **Stack Trace:**
```
pwndbg> bt full
#0  0x00007f736c5d6c24 in wlr_surface_is_xdg_surface () at /lib64/libwlroots.so.10
#1  0x0000565099234152 in view_from_wlr_surface (wlr_surface=<optimized out>) at ../sway/tree/view.c:1162
        role = <optimized out>
#2  0x00005650991f945c in sway_idle_inhibit_v1_application_inhibitor_for_view (view=0x56509a6aee80) at ../sway/desktop/idle_inhibit_v1.c:86
        inhibitor = 0x565099fd0ea0
#3  0x00005650991ee2d5 in view_inhibit_idle (view=<optimized out>) at ../sway/tree/view.c:178
        user_inhibitor = 0x0
        application_inhibitor = <optimized out>
        window_box = {
          x = 1,
          y = 1,
          width = 1916,
          height = 1046
        }
        geometry = {
          x = 0,
          y = 0,
          width = 2556,
          height = 1406
        }
        user_inhibitor = <optimized out>
        application_inhibitor = <optimized out>
        app_id = <optimized out>
        visible = <optimized out>
        idle_inhibitors = <optimized out>
        parent = <optimized out>
        parent_box = {
          x = 1,
          y = 1471,
          width = 1918,
          height = 1048
        }
        con_marks = 0x565099fb6e10
        deco_box = {
          x = 0,
          y = 0,
          width = 0,
          height = 0
        }
        marks = 0x56509a708fc0
        seat = 0x565099dbba40
        focused = <optimized out>
        name = <optimized out>
        box = {
          x = 1,
          y = 1471,
          width = 1918,
          height = 1048
        }
        focus = <optimized out>
        object = 0x56509a68d8a0
#4  ipc_json_describe_view (object=0x56509a68d8a0, c=0x56509a6b5a70) at ../sway/ipc-json.c:518
        window_box = {
          x = 1,
          y = 1,
          width = 1916,
          height = 1046
        }
        geometry = {
          x = 0,
          y = 0,
          width = 2556,
          height = 1406
        }
        user_inhibitor = <optimized out>
        application_inhibitor = <optimized out>
        app_id = <optimized out>
        visible = <optimized out>
        idle_inhibitors = <optimized out>
        parent = <optimized out>
        parent_box = {
          x = 1,
          y = 1471,
          width = 1918,
          height = 1048
        }
        con_marks = 0x565099fb6e10
        deco_box = {
          x = 0,
          y = 0,
          width = 0,
          height = 0
        }
        marks = 0x56509a708fc0
        seat = 0x565099dbba40
        focused = <optimized out>
        name = <optimized out>
        box = {
          x = 1,
          y = 1471,
          width = 1918,
          height = 1048
        }
        focus = <optimized out>
        object = 0x56509a68d8a0
#5  ipc_json_describe_container (object=0x56509a68d8a0, c=0x56509a6b5a70) at ../sway/ipc-json.c:645
        parent = <optimized out>
        parent_box = {
          x = 1,
          y = 1471,
          width = 1918,
          height = 1048
        }
        con_marks = 0x565099fb6e10
        deco_box = {
          x = 0,
          y = 0,
          width = 0,
          height = 0
        }
        marks = 0x56509a708fc0
        seat = 0x565099dbba40
        focused = <optimized out>
        name = <optimized out>
        box = {
          x = 1,
          y = 1471,
          width = 1918,
          height = 1048
        }
        focus = <optimized out>
        object = 0x56509a68d8a0
#6  ipc_json_describe_node (node=node@entry=0x56509a6b5a70) at ../sway/ipc-json.c:712
        seat = 0x565099dbba40
        focused = <optimized out>
        name = <optimized out>
        box = {
          x = 1,
          y = 1471,
          width = 1918,
          height = 1048
        }
        focus = <optimized out>
        object = 0x56509a68d8a0
#7  0x00005650991eef96 in ipc_json_describe_node_recursive (node=0x56509a6b5a70) at ../sway/ipc-json.c:723
        object = <optimized out>
        i = <optimized out>
        children = <optimized out>
#8  0x00005650991ef2fc in ipc_json_describe_node_recursive (node=0x56509a4d6a50) at ../sway/ipc-json.c:748
        con = <optimized out>
        object = 0x56509a6dd250
        i = <optimized out>
        children = 0x56509a6fa660
#9  0x00005650991eefe0 in ipc_json_describe_node_recursive (node=0x56509a4ce820) at ../sway/ipc-json.c:741
        ws = <optimized out>
        object = 0x56509a7043b0
        i = <optimized out>
        children = 0x56509a718290
#10 0x00005650991ef2a8 in ipc_json_describe_node_recursive (node=<optimized out>) at ../sway/ipc-json.c:734
        output = <optimized out>
        object = 0x56509a721c70
        i = <optimized out>
        children = 0x565099e97f60
#11 0x00005650991f4443 in ipc_client_handle_command (client=client@entry=0x56509a64ec70, payload_length=0, payload_type=IPC_GET_TREE) at ../sway/ipc-server.c:797
        tree = <optimized out>
        json_string = <optimized out>
        buf = 0x56509a4660d0 ""
        __PRETTY_FUNCTION__ = "ipc_client_handle_command"
#12 0x00005650991f4dc7 in ipc_client_handle_readable (client_fd=116, mask=<optimized out>, data=0x56509a64ec70) at ../sway/ipc-server.c:267
        pending_length = <optimized out>
        client = 0x56509a64ec70
        read_available = 14
        buf = "i3-ipc\000\000\000\000\004\000\000"
        received = <optimized out>
#13 0x00007f736c656532 in wl_event_loop_dispatch () at /lib64/libwayland-server.so.0
#14 0x00007f736c656c95 in wl_display_run () at /lib64/libwayland-server.so.0
#15 0x00005650991ec61b in server_run (server=<optimized out>) at ../sway/server.c:304
        config_path = 0x0
        usage = 0x565099244e40 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = <optimized out>
        long_options = {{
            name = 0x565099244498 "help",
            has_arg = 0,
            flag = 0x0,
            val = 104
          }, {
            name = 0x56509924774b "config",
            has_arg = 1,
            flag = 0x0,
            val = 99
          }, {
            name = 0x56509924449d "validate",
            has_arg = 0,
            flag = 0x0,
            val = 67
          }, {
            name = 0x5650992444a6 "debug",
            has_arg = 0,
            flag = 0x0,
            val = 100
          }, {
            name = 0x56509924437d "version",
            has_arg = 0,
            flag = 0x0,
            val = 118
          }, {
            name = 0x565099242a31 "verbose",
            has_arg = 0,
            flag = 0x0,
            val = 86
          }, {
            name = 0x5650992444ac "get-socketpath",
            has_arg = 0,
            flag = 0x0,
            val = 112
          }, {
            name = 0x5650992444bb "unsupported-gpu",
            has_arg = 0,
            flag = 0x0,
            val = 117
          }, {
            name = 0x0,
            has_arg = 0,
            flag = 0x0,
            val = 0
          }}
        validate = 0
        debug = 0
        allow_unsupported_gpu = 0
        verbose = 0
#16 main (argc=argc@entry=1, argv=argv@entry=0x7ffeab80ba58) at ../sway/main.c:431
        config_path = 0x0
        usage = 0x565099244e40 "Usage: sway [options] [command]\n\n  -h, --help", ' ' <repeats 13 times>, "Show help message and quit.\n  -c, --config <config>  Specify a config file.\n  -C, --validate         Check the validity of the config file, th"...
        c = <optimized out>
        long_options = {{
            name = 0x565099244498 "help",
            has_arg = 0,
            flag = 0x0,
            val = 104
          }, {
            name = 0x56509924774b "config",
            has_arg = 1,
            flag = 0x0,
            val = 99
          }, {
            name = 0x56509924449d "validate",
            has_arg = 0,
            flag = 0x0,
            val = 67
          }, {
            name = 0x5650992444a6 "debug",
            has_arg = 0,
            flag = 0x0,
            val = 100
          }, {
            name = 0x56509924437d "version",
            has_arg = 0,
            flag = 0x0,
            val = 118
          }, {
            name = 0x565099242a31 "verbose",
            has_arg = 0,
            flag = 0x0,
            val = 86
          }, {
            name = 0x5650992444ac "get-socketpath",
            has_arg = 0,
            flag = 0x0,
            val = 112
          }, {
            name = 0x5650992444bb "unsupported-gpu",
            has_arg = 0,
            flag = 0x0,
            val = 117
          }, {
            name = 0x0,
            has_arg = 0,
            flag = 0x0,
            val = 0
          }}
        validate = 0
        debug = 0
        allow_unsupported_gpu = 0
        verbose = 0
#17 0x00007f736c334510 in __libc_start_call_main (main=main@entry=0x5650991ead50 <main>, argc=argc@entry=1, argv=argv@entry=0x7ffeab80ba58) at ../sysdeps/nptl/libc_start_call_main.h:58
        self = <optimized out>
        result = <optimized out>
        unwind_buf = {
          cancel_jmp_buf = {{
              jmp_buf = {140731775760984, -4465800722577077287, 0, 140731775761000, 94904166774200, 140133723246592, 4466197429326072793, 4386666023996509145},
              mask_was_saved = 0
            }},
          priv = {
            pad = {0x0, 0x0, 0x7ffeab80ba58, 0x1},
            data = {
              prev = 0x0,
              cleanup = 0x0,
              canceltype = -1417627048
            }
          }
        }
        not_first_call = <optimized out>
#18 0x00007f736c3345c9 in __libc_start_main_impl (main=0x5650991ead50 <main>, argc=1, argv=0x7ffeab80ba58, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffeab80ba48) at ../csu/libc-start.c:381
#19 0x00005650991ec9d5 in _start ()
```
sorry that I couldn't install debug info for wlroots (it's not available in the repo), but as the issue no longer reproduces, I doubt that recompiling with debug would retrigger the issue

- **Description:**
This is not a reproducer. On the internal screen (eDP-1) I had two firefox windows, side-by side. Each of them contained one tab. I dragged a tab from the right side to move it into the left window, and that crashed sway. After reruning sway, I tried it again with the same tabs and it crashed again. After that, I tried running sway with debug log, and I couldn't see the crashes no more, even when I didn't log in from tty.

If you want a coredump, I could probably provide one (does it contain sensitive data?).

**Comment by enedil** [comment]
Edit: probably a dupe of #7368

**Comment by bl4ckb0ne** [comment]
Stacktrace seems a bit different, could you try to reproduce on sway/wlroots master?

**Comment by cod1r** [comment]
sway seems to crash for me occasionally when I make firefox attach and detach a tab a bunch of times. It eventually crashes but you have to do it again and again.

**Comment by bl4ckb0ne** [comment]
Issue has been fixed in wlroots master
