### ISSUE TITLE
sway segfault when merging firefox windows (xwayland)

### ISSUE THREAD

**Issue by slatian** [swaywm/sway#7449]
On Sway (version 1.8) merging a Firefox (running as xwayland client) tab that is in its own window into another Firefox window (the window that was previously home to a tab should disappear) semi-reliably triggers a sway segfault.  (for reproduction: I'm using Firefox 190.0.1)

## Configuration file

For reproducing the bug:
```
exec firefox
```

## Notes

I've also observed this (or at least a very similar) bug on my laptop which has intel graphics.

Sway takes a second between the trigger ad the crash, it stays responsive in this time.

If `MOZ_ENABLE_WAYLAND=1` is set this bug does not happen.

## Backtrace

This one is from a try that took multiple attempts: (I forgot the bt full, apologies)
```
(gdb) bt
#0  0x00007f5fca2b63b7 in wl_list_remove () from /usr/lib/libwayland-server.so.0
#1  0x00007f5fca24113f in ?? () from /usr/lib/libwlroots.so.11
#2  0x00007f5fca2196c0 in wlr_surface_destroy_role_object () from /usr/lib/libwlroots.so.11
#3  0x00007f5fca21cd21 in ?? () from /usr/lib/libwlroots.so.11
#4  0x00007f5fca2b7cdf in ?? () from /usr/lib/libwayland-server.so.0
#5  0x00007f5fca2b9972 in wl_resource_destroy () from /usr/lib/libwayland-server.so.0
#6  0x00007f5fc988fe6d in ?? () from /usr/lib/libffi.so.7
#7  0x00007f5fc988f2aa in ?? () from /usr/lib/libffi.so.7
#8  0x00007f5fca2b50b5 in ?? () from /usr/lib/libwayland-server.so.0
#9  0x00007f5fca2b92dc in ?? () from /usr/lib/libwayland-server.so.0
#10 0x00007f5fca2b7e22 in wl_event_loop_dispatch () from /usr/lib/libwayland-server.so.0
#11 0x00007f5fca2b8575 in wl_display_run () from /usr/lib/libwayland-server.so.0
#12 0x000055ea89f4c3a0 in ?? ()
#13 0x00007f5fc9f5f20c in __libc_start_call_main (main=main@entry=0x55ea89f4a9b0, argc=argc@entry=3, argv=argv@entry=0x7ffe87b9a678) at ../sysdeps/nptl/libc_start_call_main.h:58
#14 0x00007f5fc9f5f2bc in __libc_start_main_impl (main=0x55ea89f4a9b0, argc=3, argv=0x7ffe87b9a678, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7ffe87b9a668) at ../csu/libc-start.c:381
#15 0x000055ea89f4c811 in ?? ()
```

Log:
```
(gdb) run -c testsway
Starting program: /usr/bin/sway -c testsway
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib64/libthread_db.so.1".
[Detaching after vfork from child process 15160]
[…]
amdgpu: amdgpu_cs_ctx_create2 failed. (-13)
00:00:00.180 [wlr] [types/wlr_drm_lease_v1.c:715] No DRM backend supplied, failed to create wlr_drm_lease_v1_manager
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 708, clipping.
>                   X11 cannot support keycodes above 255.
Errors from xkbcomp are not fatal to the X server
```

For this one it crashed on the first try:
```
(gdb) bt full
#0  0x00007f3b27226ff0 in ?? () from /usr/lib/libwlroots.so.11
#1  0x00007f3b2722717c in ?? () from /usr/lib/libwlroots.so.11
#2  0x00007f3b271ff6c0 in wlr_surface_destroy_role_object () from /usr/lib/libwlroots.so.11
#3  0x00007f3b27202d21 in ?? () from /usr/lib/libwlroots.so.11
#4  0x00007f3b2729dcdf in ?? () from /usr/lib/libwayland-server.so.0
#5  0x00007f3b2729f972 in wl_resource_destroy () from /usr/lib/libwayland-server.so.0
#6  0x00007f3b26875e6d in ?? () from /usr/lib/libffi.so.7
#7  0x00007f3b268752aa in ?? () from /usr/lib/libffi.so.7
#8  0x00007f3b2729b0b5 in ?? () from /usr/lib/libwayland-server.so.0
#9  0x00007f3b2729f2dc in ?? () from /usr/lib/libwayland-server.so.0
#10 0x00007f3b2729de22 in wl_event_loop_dispatch () from /usr/lib/libwayland-server.so.0
#11 0x00007f3b2729e575 in wl_display_run () from /usr/lib/libwayland-server.so.0
#12 0x0000564dd97953a0 in ?? ()
#13 0x00007f3b26f4520c in __libc_start_call_main (main=main@entry=0x564dd97939b0, argc=argc@entry=3, argv=argv@entry=0x7ffdd4a638b8) at ../sysdeps/nptl/libc_start_call_main.h:58
        self = <optimized out>
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, -2270389117907501835, 140728171116728, 94892361071024, 94892361560696, 139892043620352, 2271604681959800053, 2165027219154140405}, 
              mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x3, 0x7ffdd4a638b8}, data = {prev = 0x0, cleanup = 0x0, canceltype = 3}}}
        not_first_call = <optimized out>
#14 0x00007f3b26f452bc in __libc_start_main_impl (main=0x564dd97939b0, argc=3, argv=0x7ffdd4a638b8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7ffdd4a638a8) at ../csu/libc-start.c:381
No locals.
#15 0x0000564dd9795811 in ?? ()
No symbol table info available.
```

Log for this one:
```
(gdb) run -c testsway
Starting program: /usr/bin/sway -c testsway
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib64/libthread_db.so.1".
[Detaching after vfork from child process 17816]
[… ]
amdgpu: amdgpu_cs_ctx_create2 failed. (-13)
00:00:00.172 [wlr] [types/wlr_drm_lease_v1.c:715] No DRM backend supplied, failed to create wlr_drm_lease_v1_manager
[… cretuen and end of 3 Threads]
[Detaching after fork from child process 17832]
[Detaching after fork from child process 17838]
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 708, clipping.
>                   X11 cannot support keycodes above 255.
Errors from xkbcomp are not fatal to the X server
ATTENTION: default value of option mesa_glthread overridden by environment.
ATTENTION: default value of option mesa_glthread overridden by environment.
00:00:01.357 [wlr] [xwayland/xwm.c:1518] xcb error: op ChangeWindowAttributes (no minor), code Window (no extension), sequence 190, value 6291513
[… Firefox chatter …]
00:00:11.285 [wlr] [xwayland/xwm.c:1518] xcb error: op ChangeWindowAttributes (no minor), code Window (no extension), sequence 494, value 93
00:00:11.487 [wlr] [xwayland/xwm.c:1518] xcb error: op ChangeProperty (no minor), code Window (no extension), sequence 536, value 6291575

Thread 1 "sway" received signal SIGSEGV, Segmentation fault.
```

## Debug logs:

This one was in a tty, it took multiple attempts to get sway to crash:
https://gist.github.com/slatian/ce57bbd52c2bb23941c0c9616754d578

This one was from inside my main sway session, it took multiple attempty to crash
https://gist.github.com/slatian/eab9b40919e2fc8fe2ab86b2d4c7e1bf

## Step by step reproduction instructions

* Stop Firefox in your main session or create a profile for testing
* Create a config file for sway that is able to run Firefox
* make sure there are no `MOZ_*` environment variables that interfere with default graphic behavior
* Start sway (either in your existing Wayland session or on a tty) using `sway -c testconfig`
* Open at least 2 tabs
* drag one tab out so that Firefox displays two windows (running the `firefox` command a second time works too)
* Drag the tab that is alone in its window from one window to the other and drop it in the other windows tab-bar
* If sway didn't crash, repeat the last two steps, for me it never took more than ~5 attempts
* Sway crashes with a segfault

**Comment by slatian** [comment]
If better logs are needed please don't hesitate to ask (I might need some help with gdb I don't use it very often)

**Comment by emersion** [comment]
Can you reproduce with Sway+wlroots master?

**Comment by rpigott** [comment]
Possible dupe of #7345.

**Comment by slatian** [comment]
> Can you reproduce with Sway+wlroots master?

Nope, seems to be fixed. Thanks!
