### ISSUE TITLE
freetube crashes sway

### ISSUE THREAD

**Issue by hboetes** [swaywm/sway#7453]
Whilst running freetube and the latest sway from git I noticed sway crashing:
```
% freetube
Gtk-Message: 02:35:53.775: Failed to load module "colorreload-gtk-module"
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
(node:4781) UnhandledPromiseRejectionWarning: Error: Cannot create a secure cookie from an insecure URL
(Use `freetube --trace-warnings ...` to show where the warning was created)
(node:4781) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4781) UnhandledPromiseRejectionWarning: Error: Cannot create a secure cookie from an insecure URL
(node:4781) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
X connection to :0 broken (explicit kill or server shutdown).
[4781:0216/023554.030413:ERROR:command_buffer_proxy_impl.cc(325)] GPU state invalid after WaitForGetOffsetInRange.
```

And in dmesg there was this message
```
[  244.037475] sway[4405]: segfault at 8 ip 00007f37a3adb799 sp 00007ffd08b61fc8 error 4 in libwayland-server.so.0.21.0[7f37a3ad8000+8000] likely on CPU 6 (core 3, socket 0)
[  244.037483] Code: 8b 7d 78 e8 39 cf ff ff 8b 7d 00 e8 81 d1 ff ff 5b 48 89 ef 5d 41 5c e9 25 cf ff ff 0f 1f 44 00 00 f3 0f 1e fa 66 48 0f 6e c7 <0f> 16 47 08 0f 11 06 48 89 77 08 48 8b 46 08 48 89 30 c3 0f 1f 40
```

I'll add gdb output to this bug report.

**Comment by hboetes** [comment]
It wasn't too much output,  so I didn't opt for the pastebin.

```
This GDB supports auto-downloading debuginfo from the following URLs:
https://debuginfod.fedoraproject.org/ 
Enable debuginfod for this session? (y or [n]) y
Debuginfod has been enabled.
To make this setting permanent, add 'set debuginfod enabled on' to .gdbinit.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `sway -d'.
Program terminated with signal SIGSEGV, Segmentation fault.

warning: Section `.reg-xstate/4405' in core file too small.
#0  0x00007f37a3adb799 in wl_list_insert (list=0x0, elm=0x16dfe98) at ../src/wayland-util.c:48
48              elm->next = list->next;
[Current thread is 1 (Thread 0x7f37a2a1e500 (LWP 4405))]
(gdb) bt
#0  0x00007f37a3adb799 in wl_list_insert (list=0x0, elm=0x16dfe98) at ../src/wayland-util.c:48
#1  0x00000000004710f4 in wl_signal_add (signal=0x15fa740, listener=0x16dfe98) at /usr/include/wayland-server-core.h:447
#2  0x000000000047188e in create_unmanaged (xsurface=0x15fa5e0) at ../sway/desktop/xwayland.c:193
#3  0x00000000004730e7 in handle_xwayland_surface (listener=0x49fc88 <server+328>, data=0x15fa5e0) at ../sway/desktop/xwayland.c:817
#4  0x00007f37a3adbb2c in wl_signal_emit_mutable (signal=<optimized out>, data=0x15fa5e0) at ../src/wayland-server.c:2179
#5  0x00007f37a3a5ca55 in xwayland_surface_create (xwm=0x16e2060, window_id=4194304, x=-100, y=-100, width=10, height=10, override_redirect=true) at ../xwayland/xwm.c:209
#6  0x00007f37a3a5e93d in xwm_handle_create_notify (xwm=0x16e2060, ev=0x16e23f0) at ../xwayland/xwm.c:971
#7  0x00007f37a3a600d8 in x11_event_handler (fd=115, mask=1, data=0x16e2060) at ../xwayland/xwm.c:1654
#8  0x00007f37a3add532 in wl_event_loop_dispatch (loop=0x6a22e0, timeout=timeout@entry=-1) at ../src/event-loop.c:1027
#9  0x00007f37a3addc95 in wl_display_run (display=0x6a21f0) at ../src/wayland-server.c:1431
#10 0x0000000000420365 in server_run (server=0x49fb40 <server>) at ../sway/server.c:334
#11 0x000000000041f4bd in main (argc=2, argv=0x7ffd08b62538) at ../sway/main.c:415
```

**Comment by emersion** [comment]
Are you sure you've compiled Sway with the latest wlroots?

**Comment by hboetes** [comment]
To add symbols to the sway and wlroots binaries I both recompiled them and since then this problem hasn't reoccurred.

I think it's safe to say the two were out of sync.
