### ISSUE TITLE
SIGSEGV at boot 

### ISSUE THREAD

**Issue by alxchk** [swaywm/sway#7469]
SIGSEGV during start

Current master: 4666d1785bfb6635e6e8604de383c91714bceebc
Logs/etc: https://gist.github.com/alxchk/4a8832293ebcd5f476d0a73d282954c0

**Comment by bl4ckb0ne** [comment]
Relevant bits

```
#1  0x000055c176b3abea in wl_signal_add (listener=0x55c17868c328, signal=0x55c1786930d0) at /usr/include/wayland-server-core.h:447
447		wl_list_insert(signal->listener_list.prev, &listener->link);
$1 = {link = {prev = 0x0, next = 0x0}, notify = 0x0}
$2 = {listener_list = {prev = 0x0, next = 0x0}}
#2  handle_new_output (listener=0x55c176ba1138 <server+120>, data=0x55c178692f90) at ../sway-9999/sway/desktop/output.c:966
966		wl_signal_add(&wlr_output->events.frame, &output->frame);
value has been optimized out
$3 = {node = {type = N_OUTPUT, {sway_root = 0x55c17868c170, sway_output = 0x55c17868c170, sway_workspace = 0x55c17868c170, sway_container = 0x55c17868c170}, id = 3, instruction = 0x0, ntxnrefs = 0, destroying = false, dirty = false, events = {destroy = {listener_list = {prev = 0x55c17868c1a0, next = 0x55c17868c1a0}}}}, wlr_output = 0x55c178692f90, server = 0x55c176ba10c0 <server>, link = {prev = 0x55c177791990, next = 0x55c1780872c0}, layers = {{prev = 0x55c17868c1d0, next = 0x55c17868c1d0}, {prev = 0x55c17868c1e0, next = 0x55c17868c1e0}, {prev = 0x55c17868c1f0, next = 0x55c17868c1f0}, {prev = 0x55c17868c200, next = 0x55c17868c200}}, usable_area = {x = 0, y = 0, width = 0, height = 0}, last_frame = {tv_sec = 0, tv_nsec = 0}, damage_ring = {width = 2147483647, height = 2147483647, current = {extents = {x1 = 0, y1 = 0, x2 = 0, y2 = 0}, data = 0x7f6e681f6e50}, previous = {{extents = {x1 = 0, y1 = 0, x2 = 0, y2 = 0}, data = 0x7f6e681f6e50}, {extents = {x1 = 0, y1 = 0, x2 = 0, y2 = 0}, data = 0x7f6e681f6e50}}, previous_idx = 0}, lx = 0, ly = 0, width = 0, height = 0, detected_subpixel = WL_OUTPUT_SUBPIXEL_UNKNOWN, scale_filter = SCALE_FILTER_NEAREST, current_mode = 0x0, enabling = false, enabled = false, workspaces = 0x55c1786269b0, current = {workspaces = 0x55c17859ac60, active_workspace = 0x0}, destroy = {link = {prev = 0x55c178693160, next = 0x55c178693160}, notify = 0x55c176b3b2f0 <handle_destroy>}, commit = {link = {prev = 0x55c178693110, next = 0x55c178693110}, notify = 0x55c176b3b4a0 <handle_commit>}, present = {link = {prev = 0x55c178693120, next = 0x55c178693120}, notify = 0x55c176b321d0 <handle_present>}, damage = {link = {prev = 0x55c1786930e0, next = 0x55c1786930e0}, notify = 0x55c176b32cd0 <handle_damage>}, frame = {link = {prev = 0x0, next = 0x0}, notify = 0x0}, needs_frame = {link = {prev = 0x0, next = 0x0}, notify = 0x0}, request_state = {link = {prev = 0x0, next = 0x0}, notify = 0x0}, events = {disable = {listener_list = {prev = 0x55c17868c370, next = 0x55c17868c370}}}, last_presentation = {tv_sec = 0, tv_nsec = 0}, refresh_nsec = 0, max_render_time = 0, repaint_timer = 0x0}
#3  0x00007f6e6813920c in wl_signal_emit_mutable (signal=<optimized out>, data=0x55c178692f90) at ../wayland-1.21.0/src/wayland-server.c:2179
2179			l->notify(l, data);
$4 = {link = {prev = 0x55c177791dd8, next = 0x7ffd2b6ad490}, notify = 0x55c176b3aa80 <handle_new_output>}
Undefined command: "pint".  Try "help".
Attempt to dereference a generic pointer.
$5 = (void *) 0x55c178692f90
#4  0x00007f6e6813920c in wl_signal_emit_mutable (signal=signal@entry=0x55c177797198, data=data@entry=0x55c178692f90) at ../wayland-1.21.0/src/wayland-server.c:2179
2179			l->notify(l, data);
#5  0x00007f6e6808dc98 in scan_drm_connectors (drm=<optimized out>, event=event@entry=0x0) at ../wlroots-9999/backend/drm/drm.c:1623
1623			wl_signal_emit_mutable(&drm->backend.events.new_output,
value has been optimized out
value has been optimized out
#6  0x00007f6e6808ea9b in backend_start (backend=<optimized out>) at ../wlroots-9999/backend/drm/backend.c:24
24		scan_drm_connectors(drm, NULL);
#7  0x00007f6e68087236 in multi_backend_start (wlr_backend=0x55c177791db0) at ../wlroots-9999/backend/multi/backend.c:31
31			if (!wlr_backend_start(sub->backend)) {
$6 = {impl = 0x7f6e68123f80 <backend_impl.lto_priv>, events = {destroy = {listener_list = {prev = 0x55c1780864d8, next = 0x55c1777abc10}}, new_input = {listener_list = {prev = 0x55c1777abbe0, next = 0x55c1777abbe0}}, new_output = {listener_list = {prev = 0x7ffd2b6ad4e0, next = 0x55c1777abbf8}}}}
$7 = {backend = 0x55c177797170, container = 0x55c177791db0, new_input = {link = {prev = 0x55c177797188, next = 0x55c177797188}, notify = 0x7f6e68083b60 <new_input_reemit>}, new_output = {link = {prev = 0x55c177797198, next = 0x7ffd2b6ad500}, notify = 0x7f6e68083b70 <new_output_reemit>}, destroy = {link = {prev = 0x55c177797178, next = 0x55c1777a8da0}, notify = 0x7f6e68084070 <handle_subbackend_destroy>}, link = {prev = 0x55c177793a28, next = 0x55c178086ee8}}
#8  0x000055c176b26e66 in server_start (server=<optimized out>) at ../sway-9999/sway/server.c:322
322		if (!wlr_backend_start(server->backend)) {
value has been optimized out
#9  main (argc=1, argv=0x7ffd2b6ad9b8) at ../sway-9999/sway/main.c:400
400		if (!server_start(&server)) {
$8 = {wl_display = 0x55c177791bd0, wl_event_loop = 0x55c177791cc0, socket = 0x55c1780655b0 "wayland-1", backend = 0x55c177
```

Can you reproduce on sway/wlroots master?

**Comment by alxchk** [comment]
Tried several times, and looks fine. Does not reproduced with latest master. Will reopen if crash once again
