### ISSUE TITLE
Crash with 01b0c113 

### ISSUE THREAD

**Issue by alxchk** [swaywm/sway#7584]
sway version 1.9-dev-01b0c113 (May 11 2023, branch 'HEAD')
wlroots: e353c5c63175c6b3abcbf588aa29285d09817fa4

Had strange crash(es) during startup, can't reproduce, but maybe traceback will highlight to some corner case.

During latest crash (with this traceback) I switched between VT1/VT12. 

```➤  bt
#0  0x00007fde2fe22fb7 in wl_resource_post_event (resource=resource@entry=0x563c87e65ab0, opcode=opcode@entry=0x0) at ../wayland-1.22.0/src/wayland-server.c:255
#1  0x00007fde2fd8ba25 in wl_keyboard_send_keymap (size=<optimized out>, fd=<optimized out>, format=0x1, resource_=0x563c87e65ab0) at /usr/include/wayland-server-protocol.h:4073
#2  seat_client_send_keymap (client=client@entry=0x563c87f5f380, keyboard=keyboard@entry=0x563c879c2b58) at ../wlroots-9999/types/seat/wlr_seat_keyboard.c:351
#3  0x00007fde2fd8f20b in seat_client_send_keymap (keyboard=0x563c879c2b58, client=0x563c87f5f380) at ../wlroots-9999/types/seat/wlr_seat_keyboard.c:339
#4  wlr_seat_set_keyboard (keyboard=0x563c879c2b58, seat=0x563c878d9250) at ../wlroots-9999/types/seat/wlr_seat_keyboard.c:150
#5  wlr_seat_set_keyboard (seat=0x563c878d9250, keyboard=0x563c879c2b58) at ../wlroots-9999/types/seat/wlr_seat_keyboard.c:118
#6  0x0000563c853234b9 in sway_keyboard_configure (keyboard=0x563c87cc4730) at ../sway-9999/sway/input/keyboard.c:1060
#7  0x0000563c85323d4a in seat_configure_keyboard (seat_device=0x563c88063550, seat=0x563c878d9040) at ../sway-9999/sway/input/seat.c:825
#8  seat_configure_device (seat=0x563c878d9040, input_device=<optimized out>) at ../sway-9999/sway/input/seat.c:911
#9  0x0000563c85324524 in seat_add_device (input_device=0x563c87c38410, seat=0x563c878d9040) at ../sway-9999/sway/input/seat.c:979
#10 seat_add_device (seat=0x563c878d9040, input_device=0x563c87c38410) at ../sway-9999/sway/input/seat.c:958
#11 0x0000563c85325072 in handle_new_input (listener=0x563c878d7790, data=0x563c879c2b58) at ../sway-9999/sway/input/input-manager.c:268
#12 0x00007fde2fe222ac in wl_signal_emit_mutable (signal=<optimized out>, data=0x563c879c2b58) at ../wayland-1.22.0/src/wayland-server.c:2241
#13 0x00007fde2fe222ac in wl_signal_emit_mutable (signal=signal@entry=0x563c86fe4d68, data=data@entry=0x563c879c2b58) at ../wayland-1.22.0/src/wayland-server.c:2241
#14 0x00007fde2fd7e765 in handle_device_added (libinput_dev=0x563c87ddaca0, backend=0x563c86fe4d50) at ../wlroots-9999/backend/libinput/events.c:89
#15 handle_libinput_event (event=0x563c87e0b670, backend=0x563c86fe4d50) at ../wlroots-9999/backend/libinput/events.c:159
#16 handle_libinput_readable (fd=<optimized out>, mask=<optimized out>, _backend=<optimized out>) at ../wlroots-9999/backend/libinput/backend.c:58
#17 handle_libinput_readable (fd=<optimized out>, mask=<optimized out>, _backend=0x563c86fe4d50) at ../wlroots-9999/backend/libinput/backend.c:48
#18 0x00007fde2fe23b92 in wl_event_loop_dispatch (loop=0x563c86fe3110, timeout=timeout@entry=0xffffffff) at ../wayland-1.22.0/src/event-loop.c:1027
#19 0x00007fde2fe24355 in wl_display_run (display=0x563c86fe3020) at ../wayland-1.22.0/src/wayland-server.c:1493
#20 0x0000563c85306428 in server_run (server=<optimized out>) at ../sway-9999/sway/server.c:334
#21 main (argc=0x2, argv=0x7fff6ce40808) at ../sway-9999/sway/main.c:415```

**Comment by alxchk** [comment]
Still have this on latest master. First launch causes SIGSEGV, next is ok

```#0  0x00007f5ab1015fb7 in wl_resource_post_event (resource=resource@entry=0x560c5f3d4190, opcode=opcode@entry=0)
    at ../wayland-1.22.0/src/wayland-server.c:255
#1  0x00007f5ab0f727a2 in wl_keyboard_send_keymap (size=50519, fd=144, format=1, resource_=0x560c5f3d4190)
    at /usr/include/wayland-server-protocol.h:4073
#2  seat_client_send_keymap (client=0x560c5f627b10, keyboard=<optimized out>) at ../wlroots-9999/types/seat/wlr_seat_keyboard.c:371
#3  0x00007f5ab0f7a1ab in wlr_seat_set_keyboard (keyboard=0x560c5f273778, seat=0x560c5f160f50)
    at ../wlroots-9999/types/seat/wlr_seat_keyboard.c:152
#4  wlr_seat_set_keyboard (seat=0x560c5f160f50, keyboard=0x560c5f273778) at ../wlroots-9999/types/seat/wlr_seat_keyboard.c:120
#5  0x0000560c5d1c1a39 in sway_keyboard_configure (keyboard=0x560c5f2dfab0) at ../sway-9999/sway/input/keyboard.c:1060
#6  0x0000560c5d1c22ca in seat_configure_keyboard (seat_device=0x560c5f45b660, seat=0x560c5f15f490) at ../sway-9999/sway/input/seat.c:825
#7  seat_configure_device (seat=0x560c5f15f490, input_device=<optimized out>) at ../sway-9999/sway/input/seat.c:911
#8  0x0000560c5d1c28e4 in seat_add_device (input_device=0x560c5f45f820, seat=0x560c5f15f490) at ../sway-9999/sway/input/seat.c:979
#9  seat_add_device (seat=0x560c5f15f490, input_device=0x560c5f45f820) at ../sway-9999/sway/input/seat.c:958
#10 0x0000560c5d1c3432 in handle_new_input (listener=0x560c5f15f240, data=0x560c5f273778) at ../sway-9999/sway/input/input-manager.c:268
#11 0x00007f5ab10152ac in wl_signal_emit_mutable (signal=<optimized out>, data=0x560c5f273778) at ../wayland-1.22.0/src/wayland-server.c:2241
#12 0x00007f5ab10152ac in wl_signal_emit_mutable (signal=signal@entry=0x560c5e82ac78, data=data@entry=0x560c5f273778)
    at ../wayland-1.22.0/src/wayland-server.c:2241
#13 0x00007f5ab0f6b9f5 in handle_device_added (libinput_dev=0x560c5f2a1a10, backend=0x560c5e82ac60)
    at ../wlroots-9999/backend/libinput/events.c:89
#14 handle_libinput_event (event=0x560c5f2d96e0, backend=0x560c5e82ac60) at ../wlroots-9999/backend/libinput/events.c:159
#15 handle_libinput_readable (fd=<optimized out>, mask=<optimized out>, _backend=<optimized out>) at ../wlroots-9999/backend/libinput/backend.c:58
#16 handle_libinput_readable (fd=<optimized out>, mask=<optimized out>, _backend=0x560c5e82ac60) at ../wlroots-9999/backend/libinput/backend.c:48
#17 0x00007f5ab1016b92 in wl_event_loop_dispatch (loop=0x560c5e829020, timeout=timeout@entry=-1) at ../wayland-1.22.0/src/event-loop.c:1027
#18 0x00007f5ab1017355 in wl_display_run (display=0x560c5e828f30) at ../wayland-1.22.0/src/wayland-server.c:1493
#19 0x0000560c5d1a448d in server_run (server=<optimized out>) at ../sway-9999/sway/server.c:338
#20 main (argc=1, argv=0x7ffd1c5d1908) at ../sway-9999/sway/main.c:415```
