### ISSUE TITLE
Swaynag segfault with latest sway/wlroots

### ISSUE THREAD

**Issue by dryya** [swaywm/sway#7671]
- **Sway Version:** sway version 1.9-dev, built from fc16fb65491bda0d059b8c9aeae3dc9962e5c690

- **Debug Log:** https://gist.github.com/dryya/62b45a0d13a721b72350a02e1c28943d

- **Configuration File:** Default

- **Stack Trace:** I will try to compile with debug symbols and reproduce soon.
```
$ coredumpctl gdb
           PID: 17790 (swaynag)
           UID: 1000 (genevieve)
           GID: 100 (users)
        Signal: 11 (SEGV)
     Timestamp: Wed 2023-07-12 21:41:02 EDT (4min 5s ago)
  Command Line: swaynag -t warning -m $'You pressed the exit shortcut. Do you really want to exit sway? This will end your Wayland session.' -b $'Yes, exit sway' $'swaymsg exit'
    Executable: /nix/store/rh27m3aih1l4bbk0qw176l887hx27z17-sway-unwrapped-+fc16fb6/bin/swaynag
 Control Group: /user.slice/user-1000.slice/session-6.scope
          Unit: session-6.scope
         Slice: user-1000.slice
       Session: 6
     Owner UID: 1000 (genevieve)
       Boot ID: 3a347d9bf0ea4c22a4213b8a9a5308a7
    Machine ID: d4243538cbff4b399e6bd2e7e226e7a9
      Hostname: seberg
       Storage: /var/lib/systemd/coredump/core.swaynag.1000.3a347d9bf0ea4c22a4213b8a9a5308a7.17790.1689212462000000.zst (present)
  Size on Disk: 381.2K
       Message: Process 17790 (swaynag) of user 1000 dumped core.
                
                Module libpcre.so.1 without build-id.
                Module libbrotlicommon.so.1 without build-id.
                Module libgraphite2.so.3 without build-id.
                Module libdatrie.so.1 without build-id.
                Module libselinux.so.1 without build-id.
                Module libGLX.so.0 without build-id.
                Module libXdmcp.so.6 without build-id.
                Module libXau.so.6 without build-id.
                Module libGLdispatch.so.0 without build-id.
                Module libexpat.so.1 without build-id.
                Module libbrotlidec.so.1 without build-id.
                Module libbz2.so.1 without build-id.
                Module libpangoft2-1.0.so.0 without build-id.
                Module libpcre2-8.so.0 without build-id.
                Module libffi.so.8 without build-id.
                Module libharfbuzz.so.0 without build-id.
                Module libthai.so.0 without build-id.
                Module libfribidi.so.0 without build-id.
                Module libGL.so.1 without build-id.
                Module libz.so.1 without build-id.
                Module libXext.so.6 without build-id.
                Module libX11.so.6 without build-id.
                Module libXrender.so.1 without build-id.
                Module libxcb-render.so.0 without build-id.
                Module libxcb.so.1 without build-id.
                Module libxcb-shm.so.0 without build-id.
                Module libpng16.so.16 without build-id.
                Module libEGL.so.1 without build-id.
                Module libfreetype.so.6 without build-id.
                Module libfontconfig.so.1 without build-id.
                Module libpangocairo-1.0.so.0 without build-id.
                Module libpango-1.0.so.0 without build-id.
                Module swaynag without build-id.
                Stack trace of thread 17790:
                #0  0x0000000000406b73 update_cursor (swaynag + 0x6b73)
                #1  0x00007f9e9feb288a ffi_call_unix64 (libffi.so.8 + 0x788a)
                #2  0x00007f9e9feb18de ffi_call_int (libffi.so.8 + 0x68de)
                #3  0x00007f9e9feb22fd ffi_call (libffi.so.8 + 0x72fd)
                #4  0x00007f9ea0944866 wl_closure_invoke (libwayland-client.so.0 + 0xa866)
                #5  0x00007f9ea0940bc9 dispatch_event.isra.0 (libwayland-client.so.0 + 0x6bc9)
                #6  0x00007f9ea0942524 wl_display_dispatch_queue_pending (libwayland-client.so.0 + 0x8524)
                #7  0x0000000000407179 swaynag_run (swaynag + 0x7179)
                #8  0x0000000000404c11 main (swaynag + 0x4c11)
                #9  0x00007f9ea076dace __libc_start_call_main (libc.so.6 + 0x23ace)
                #10 0x00007f9ea076db89 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x23b89)
                #11 0x0000000000404d15 _start (swaynag + 0x4d15)
                ELF object binary architecture: AMD x86-64

GNU gdb (GDB) 13.2
This GDB was configured as "x86_64-unknown-linux-gnu".

Reading symbols from /nix/store/rh27m3aih1l4bbk0qw176l887hx27z17-sway-unwrapped-+fc16fb6/bin/swaynag...
(No debugging symbols found in /nix/store/rh27m3aih1l4bbk0qw176l887hx27z17-sway-unwrapped-+fc16fb6/bin/swaynag)

warning: Can't open file /dev/shm/sway-457e-356a0dc1 (deleted) during file-backed mapping note processing

warning: Can't open file /dev/shm/sway-457e-35490e40 (deleted) during file-backed mapping note processing

warning: Can't open file /memfd:wayland-cursor (deleted) during file-backed mapping note processing
[New LWP 17790]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/nix/store/3n58xw4373jp0ljirf06d8077j15pc4j-glibc-2.37-8/lib/libthread_db.so.1".
Core was generated by `swaynag -t warning -m You pressed the exit shortcut. Do you really want to exit'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000406b73 in update_cursor ()
(gdb) bt full
#0  0x0000000000406b73 in update_cursor ()
No symbol table info available.
#1  0x00007f9e9feb288a in ffi_call_unix64 ()
   from /nix/store/g8l012l0q2xbl27da8zipg39mnpf40gb-libffi-3.4.4/lib/libffi.so.8
No symbol table info available.
#2  0x00007f9e9feb18de in ffi_call_int ()
   from /nix/store/g8l012l0q2xbl27da8zipg39mnpf40gb-libffi-3.4.4/lib/libffi.so.8
No symbol table info available.
#3  0x00007f9e9feb22fd in ffi_call () from /nix/store/g8l012l0q2xbl27da8zipg39mnpf40gb-libffi-3.4.4/lib/libffi.so.8
No symbol table info available.
#4  0x00007f9ea0944866 in wl_closure_invoke ()
   from /nix/store/3ycvv2k8j2nj4ia3rnlf47fdc5cyg5n4-wayland-1.22.0/lib/libwayland-client.so.0
No symbol table info available.
#5  0x00007f9ea0940bc9 in dispatch_event.isra ()
   from /nix/store/3ycvv2k8j2nj4ia3rnlf47fdc5cyg5n4-wayland-1.22.0/lib/libwayland-client.so.0
No symbol table info available.
#6  0x00007f9ea0942524 in wl_display_dispatch_queue_pending ()
   from /nix/store/3ycvv2k8j2nj4ia3rnlf47fdc5cyg5n4-wayland-1.22.0/lib/libwayland-client.so.0
No symbol table info available.
#7  0x0000000000407179 in swaynag_run ()
No symbol table info available.
#8  0x0000000000404c11 in main ()
No symbol table info available.
```

- **Description:** Any time after launching sway, pressing the default keybind to exit launches swaynag, which segfaults and disappears after about half a second. This occurs with `WLR_RENDERER` set to `pixman`, `gles2`, and `vulkan`.

**Comment by emersion** [comment]
Your cursor theme is probably missing "default".

See https://github.com/swaywm/sway/pull/7672
