### ISSUE TITLE
Assert failed in wlr_render_pass_add_texture()

### ISSUE THREAD

**Issue by emersion** [swaywm/sway#7836]
Smells like memory corruption but couldn't reproduce with ASan…

```
(gdb) bt
#0  0x00007f3130d4d83c in  () at /usr/lib/libc.so.6
#1  0x00007f3130cfd668 in raise () at /usr/lib/libc.so.6
#2  0x00007f3130ce54b8 in abort () at /usr/lib/libc.so.6
#3  0x00007f3130ce53dc in  () at /usr/lib/libc.so.6
#4  0x00007f3130cf5d26 in  () at /usr/lib/libc.so.6
#5  0x00007f31315e7929 in wlr_render_pass_add_texture (render_pass=0x55a476b778c0, options=0x7ffd889d56b0) at ../subprojects/wlroots/render/pass.c:33
#6  0x000055a474a38317 in render_texture
    (ctx=0x7ffd889d5ba0, texture=texture@entry=0x55a4770e9950, _src_box=_src_box@entry=0x7ffd889d5790, clip_box=clip_box@entry=0x7ffd889d5780, transform=<optimized out>, alpha=<optimized out>, alpha@entry=1, dst_box=0x7ffd889d5770) at ../sway/desktop/render.c:112
#7  0x000055a474a386ce in render_surface_iterator (output=<optimized out>, view=<optimized out>, surface=0x55a4770c0060, _box=<optimized out>, _data=0x7ffd889d5930)
    at ../sway/desktop/render.c:150
#8  0x000055a474a35b23 in output_for_each_surface_iterator (surface=0x55a4770c0060, sx=0, sy=0, _data=0x7ffd889d58d0) at ../sway/desktop/output.c:124
#9  0x00007f313162e2ae in surface_for_each_surface
    (surface=0x55a4770c0060, x=x@entry=0, y=y@entry=0, iterator=iterator@entry=0x55a474a35a20 <output_for_each_surface_iterator>, user_data=user_data@entry=0x7ffd889d58d0)
    at ../subprojects/wlroots/types/wlr_compositor.c:1043
#10 0x00007f31316304cf in wlr_surface_for_each_surface
    (surface=<optimized out>, iterator=iterator@entry=0x55a474a35a20 <output_for_each_surface_iterator>, user_data=user_data@entry=0x7ffd889d58d0)
    at ../subprojects/wlroots/types/wlr_compositor.c:1061
#11 0x000055a474a36325 in output_surface_for_each_surface
    (output=<optimized out>, surface=<optimized out>, ox=<optimized out>, oy=<optimized out>, iterator=iterator@entry=0x55a474a385b0 <render_surface_iterator>, user_data=user_data@entry=0x7ffd889d5930) at ../sway/desktop/output.c:142
#12 0x000055a474a380f9 in render_view_toplevels (ctx=ctx@entry=0x7ffd889d5ba0, view=view@entry=0x55a4770e1140, alpha=<optimized out>) at ../sway/desktop/render.c:258
#13 0x000055a474a397ca in render_view (ctx=ctx@entry=0x7ffd889d5ba0, con=con@entry=0x55a4770e8330, colors=colors@entry=0x55a476aef194) at ../sway/desktop/render.c:338
#14 0x000055a474a39dab in render_containers_linear (ctx=ctx@entry=0x7ffd889d5ba0, parent=parent@entry=0x7ffd889d5ac0) at ../sway/desktop/render.c:726
#15 0x000055a474a3a1c4 in render_containers (ctx=ctx@entry=0x7ffd889d5ba0, parent=parent@entry=0x7ffd889d5ac0) at ../sway/desktop/render.c:885
#16 0x000055a474a3af21 in render_workspace (focused=<optimized out>, ws=0x55a4770949e0, ctx=0x7ffd889d5ba0) at ../sway/desktop/render.c:927
#17 output_render (ctx=ctx@entry=0x7ffd889d5ba0) at ../sway/desktop/render.c:1104
#18 0x000055a474a36729 in output_repaint_timer_handler (data=data@entry=0x55a476cff5b0) at ../sway/desktop/output.c:663
#19 0x000055a474a377dc in handle_frame (listener=0x55a476cff760, user_data=<optimized out>) at ../sway/desktop/output.c:746
#20 0x00007f3130f3801e in wl_signal_emit_mutable () at /usr/lib/libwayland-server.so.0
#21 0x00007f313161aed4 in wlr_output_send_frame (output=<optimized out>) at ../subprojects/wlroots/types/output/output.c:880
#22 0x00007f31316030a8 in handle_page_flip (fd=<optimized out>, seq=689017, tv_sec=48465, tv_usec=566919, crtc_id=<optimized out>, data=<optimized out>)
    at ../subprojects/wlroots/backend/drm/drm.c:1762
#23 0x00007f3130cac907 in drmHandleEvent () at /usr/lib/libdrm.so.2
#24 0x00007f31316046c9 in handle_drm_event (fd=<optimized out>, mask=<optimized out>, data=0x55a4761ce350) at ../subprojects/wlroots/backend/drm/drm.c:1774
#25 0x00007f3130f39ae2 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
#26 0x00007f3130f3a2d7 in wl_display_run () at /usr/lib/libwayland-server.so.0
#27 0x000055a474a33430 in server_run (server=<optimized out>) at ../sway/server.c:386
#28 0x000055a474a26fc1 in main (argc=1, argv=0x7ffd889d6638) at ../sway/main.c:415
(gdb) frame 5
#5  0x00007f31315e7929 in wlr_render_pass_add_texture (render_pass=0x55a476b778c0, options=0x7ffd889d56b0) at ../subprojects/wlroots/render/pass.c:33
33			assert(box->x >= 0 && box->y >= 0 &&
(gdb) p *box
$1 = {x = 0, y = 0, width = 1122, height = 1461}
(gdb) p options->texture->width
$2 = 1920
(gdb) p options->texture->height
$3 = 1080
```

**Comment by emersion** [comment]
Closing in favor of https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3766
