### ISSUE TITLE
Sway hangs and endlessly accumulates file descriptors in some weird circumstances related to Xwayland and the clipboard

### ISSUE THREAD

**Issue by meithecatte** [swaywm/sway#7893]
- **Sway Version:** 1.8.1
- **Xwayland Version:** 23.2.3
- **Configuration File:** https://gist.github.com/meithecatte/6d12a9a0bc818b055c19fbc273c0cd91

I do not know how to reproduce this bug. However, I may have managed to capture enough information when it happened to make it possible to fix it nevertheless.

--> Maja (~quassel@45.142.146.28) has joined #sway
\<Maja> hello, my sway session has hung on me and i am trying to debug why
\<Maja> a few minutes ago, it had 207686 file descriptors open. a moment later, it had 415565. I then sent a SIGSTOP to the process
\<Maja> it's doing the following sequence of syscalls ad infinitum:

```c
pipe2([471095, 471096], 0)              = 0
fcntl(471095, F_SETFD, FD_CLOEXEC)      = 0
fcntl(471095, F_SETFL, O_RDONLY|O_NONBLOCK) = 0
fcntl(471096, F_SETFD, FD_CLOEXEC)      = 0
fcntl(471096, F_SETFL, O_RDONLY|O_NONBLOCK) = 0
poll([{fd=68, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=68, revents=POLLOUT}])
writev(68, [{iov_base="\1\0\t\0Fe\"\0\317\3\0\0\0\0\0\0\n\0\n\0\0\0\1\0@\0\0\0\0\10\0\0"..., iov_len=36}], 1) = 36
poll([{fd=68, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=68, revents=POLLIN|POLLOUT}])
recvmsg(68, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\20\0\273\255\317\3\0\0Fe\"\0\0\0\0\0\n\0\n\0\0\0\0\0\0\0\0\0\0\0\0\0", iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 32
writev(68, [{iov_base="\30\0\6\0Fe\"\0\1\0\0\0\366\0\0\0\f\1\0\0\0\0\0\0", iov_len=24}], 1) = 24
fcntl(471096, F_SETFL, O_WRONLY|O_NONBLOCK) = 0
fcntl(471095, F_DUPFD_CLOEXEC, 0)       = 471097
epoll_ctl(3, EPOLL_CTL_ADD, 471097, {events=EPOLLIN, data={u32=2913174560, u64=94827201135648}}) = 0
poll([{fd=68, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=68, revents=POLLIN|POLLOUT}])
recvmsg(68, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\36\0\274\255\0\0\0\0\2\0 \0Fe\"\0\1\0\0\0\366\0\0\0\f\1\0\0\0\0\0\0", iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 32
writev(68, [{iov_base="\16\0\2\0Fe\"\0\2\0\4\0Fe\"\0\0\10\0\0\0\0`\0", iov_len=24}], 1) = 24
poll([{fd=68, events=POLLIN}], 1, -1)   = 1 ([{fd=68, revents=POLLIN}])
recvmsg(68, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\1\30\275\255\0\0\0\0\317\3\0\0\0\0\0\0\n\0\n\0\0\0\0\0\0\0\0\0\0\0\0\0", iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 32
```
(addendum: immediately afterwards a call to pipe2 follows, and so on)

<details>
<summary>Long story short, I established that fd 68 is Xwayland, and captured a backtrace from one of the calls to fcntl in the strace'd sequence (a breakpoint for pipe2 wasn't hitting)</summary>

\<danieldg> try to figure out who the client on the other end of fd 68 is
\<danieldg> I suspect that client is repeating a request forever that is using up an fd
\<danieldg> that or attach gdb and get a backtrace for what is calling pipe2
\<Maja> the client is Xwayland
\<Maja> because of course
\<danieldg> lovely
\<Maja> okay, I *really* don't like what I'm seeing https://paste.debian.net/1302857/

[not reproducing that paste inline because it's not too relevant]

\<Maja> i'm not sure how to get the symbols to show up here but i know that /usr/lib/dri/radeonsi_dri.so in your backtrace is computer for "this is not a place of honor"
\<danieldg> it's probably calling the syscall via some other wrapper, lovely
\<danieldg> or did you actually find a caller of pipe2?
\<Maja> well it's the backtrace from a breakpoint on pipe2 being hit
\<Maja> wait no
\<Maja> sorry, I did a dumb
\<Maja> okay yeah, the breakpoint on pipe2 isn't being hit
\<Maja> but also, gdb is not showing symbols. when it usually does. probably because i had to run it as root
\<danieldg> maybe fcntl might be hit
\<Maja> not sure *why*, because /proc/sys/kernel/yama/ptrace_scope is already 0
\<Maja> ok, that does it

</details>

```
Thread 1 "sway" hit Breakpoint 2, 0x00007f3c471a52f0 in fcntl64 ()
   from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007f3c471a52f0 in fcntl64 () at /usr/lib/libc.so.6
#1  0x00007f3c4741eb52 in  () at /usr/lib/libwayland-server.so.0 [later resolved as wl_os_dupfd_cloexec.constprop.0]
#2  0x00007f3c474207b9 in wl_event_loop_add_fd () at /usr/lib/libwayland-server.so.0
#3  0x00007f3c473a6c01 in  () at /usr/lib/libwlroots.so.11 [later resolved as xwm_selection_transfer_start_outgoing.lto_priv.0]
#4  0x00007f3c473b1651 in  () at /usr/lib/libwlroots.so.11 [later resolved as xwm_map_shell_surface]
#5  0x00007f3c47422b8f in wl_event_loop_dispatch ()
    at /usr/lib/libwayland-server.so.0
#6  0x00007f3c474232d7 in wl_display_run () at /usr/lib/libwayland-server.so.0
#7  0x0000563e98eb2af5 in  ()
#8  0x00007f3c470cdcd0 in  () at /usr/lib/libc.so.6
#9  0x00007f3c470cdd8a in __libc_start_main () at /usr/lib/libc.so.6
#10 0x0000563e98eb2fa5 in  ()
```

<details>
<summary>we deliberated on why the symbols aren't there</summary>

\<Maja> doesn't look terribly useful to me :<
\<danieldg> if you can get debug symbols for the wlroots SO that would help point out what needs an FD
\<Maja> usually gdb offers "do you want to download symbols from the internet for this session"
\<Maja> but apparently it doesn't do that when you run it as root
\<danieldg> probably helping you be secure :p
\<danieldg> sway generally doesn't need to run in a less-debuggable context but I think some launchers might inherit that anti-ptrace bit
\<danieldg> s/launcher/display manager/
\<Maja> but doctor. my launcher is "type exec sway in tty1"
\<danieldg> well, you've confused me.  That's how I do it and I can attach strace/gdb.
\<Maja> i know! it's weird!

</details>

\<Maja> also, i tried sigstoping just the xwayland process but the session is still hung, sway stops in poll(68)
\<danieldg> I think sway survives killing the Xwayland process
\<danieldg> but that's destructive to X programs, of course
\<Maja> ok, i tried the sigstop again, and now it got a different timing and the session itself is alive again
\<Maja> now i get to use the good keyboard and monitor instead of ssh'ing in from my laptop :3
\<Maja> > destructive to X programs
\<Maja> of course
\<Maja> but also: i want to debug this now
\<danieldg> sadly I have no idea how xwyaland works so won't be much help
\<Maja> okay, welp, i flew too close to the sun and it got it out of the weird state and can't trigger it again
\<Maja> fwiw the specific xwayland client was gimp's save file dialog
\<Maja> and it closed all the file descriptors, too!

<details>
<summary>nevertheless, i managed to decode the backtrace i captured earlier</summary>

\<Maja> okay, i can still resolve the backtrace manually :p
\<Maja> mostly for my reference, here's the memory layout of my sway process https://paste.debian.net/1302863/
\<danieldg> you can turn that plus the gdb bt into offsets into your .so and then gdb a sway process (try a nested one) to get symbols
\<danieldg> just re-apply the offset at the new ASLR
\<danieldg> I've had to do that before when I only had debugsyms on one system and a crash on another
\<Maja> oh, i was about to nm | sort | eyeball the thing
\<Maja> apparently one of the calls in that backtrace is xwm_selection_transfer_start_outgoing.lto_priv.0. that looks... fun
\<Maja> it gets called by xwm_map_shell_surface
\<Maja> the immediate caller of fcntl64 is wl_os_dupfd_cloexec.constprop.0

</details>

\<danieldg> ah, clipboard stuff?
\<Maja> the hang happened after I fat-fingered some keybind, so, it might be clipboard-related
\<danieldg> that might be enough for someone who knows wlroots/xwayland to figure out what happened.  I suspect a loop of selection-set and paste events or something, resolved by you selecting something while xwayland was paused

**Comment by joanbm** [comment]
This is probably the same issue as #6974 and/or #7139.
