### ISSUE TITLE
Sway process crashed

### ISSUE THREAD

**Issue by UdaraWanasinghe** [swaywm/sway#8041]
- **Sway Version:**
  - 1.9

- **Stack Trace:**
```
Mar 07 08:22:47 archlinux kernel: sway[544]: segfault at 8 ip 00007795da239f5f sp 00007ffdd2d597f8 error 6 in libwayland-server.so.0.22.0[7795da237000+8000] likely on CPU 4 (core 0, socket 0)
Mar 07 08:22:47 archlinux kernel: Code: 00 66 2e 0f 1f 84 00 00 00 00 00 f3 0f 1e fa 48 8b 7f 38 ff 25 42 b0 00 00 66 90 f3 0f 1e fa 48 8b 17 48 8b 47 08 66 0f ef c0 <48> 89 42 08 48 89 10 0f 11 07 c3 66 0f 1f 44 00 00 f3 0f 1e fa 48
Mar 07 08:22:47 archlinux systemd[1]: Created slice Slice /system/systemd-coredump.
Mar 07 08:22:47 archlinux systemd[1]: Started Process Core Dump (PID 480752/UID 0).
Mar 07 08:22:54 archlinux systemd-coredump[480753]: Process 544 (sway) of user 1000 dumped core.
                                                    
                                                    Stack trace of thread 544:
                                                    #0  0x00007795da239f5f wl_list_remove (libwayland-server.so.0 + 0x9f5f)
                                                    #1  0x000060fb54fc66c2 n/a (sway + 0x5b6c2)
                                                    #2  0x00007795da23a01e wl_signal_emit_mutable (libwayland-server.so.0 + 0xa01e)
                                                    #3  0x00007795da1bdab7 n/a (libwlroots.so.12 + 0xacab7)
                                                    #4  0x00007795da1bf8f0 n/a (libwlroots.so.12 + 0xae8f0)
                                                    #5  0x00007795da23bb8f wl_event_loop_dispatch (libwayland-server.so.0 + 0xbb8f)
                                                    #6  0x00007795da23c2d7 wl_display_run (libwayland-server.so.0 + 0xc2d7)
                                                    #7  0x000060fb54f7ac5e n/a (sway + 0xfc5e)
                                                    #8  0x00007795d9ec9cd0 n/a (libc.so.6 + 0x25cd0)
                                                    #9  0x00007795d9ec9d8a __libc_start_main (libc.so.6 + 0x25d8a)
                                                    #10 0x000060fb54f7b125 n/a (sway + 0x10125)
                                                    
                                                    Stack trace of thread 906:
                                                    #0  0x00007795d9f2bebe n/a (libc.so.6 + 0x87ebe)
                                                    #1  0x00007795d9f2e750 pthread_cond_wait (libc.so.6 + 0x8a750)
                                                    #2  0x00007795d6c8681c n/a (iris_dri.so + 0x8681c)
                                                    #3  0x00007795d6c9e7ec n/a (iris_dri.so + 0x9e7ec)
                                                    #4  0x00007795d9f2f55a n/a (libc.so.6 + 0x8b55a)
                                                    #5  0x00007795d9faca3c n/a (libc.so.6 + 0x108a3c)
                                                    
                                                    Stack trace of thread 908:
                                                    #0  0x00007795d9faa88d syscall (libc.so.6 + 0x10688d)
                                                    #1  0x00007795da43e337 g_cond_wait (libglib-2.0.so.0 + 0xb3337)
                                                    #2  0x00007795da3b01b4 n/a (libglib-2.0.so.0 + 0x251b4)
                                                    #3  0x00007795da3b021c g_async_queue_pop (libglib-2.0.so.0 + 0x2521c)
                                                    #4  0x00007795d96a7c48 n/a (libpangoft2-1.0.so.0 + 0x8c48)
                                                    #5  0x00007795da416a45 n/a (libglib-2.0.so.0 + 0x8ba45)
                                                    #6  0x00007795d9f2f55a n/a (libc.so.6 + 0x8b55a)
                                                    #7  0x00007795d9faca3c n/a (libc.so.6 + 0x108a3c)
                                                    
                                                    Stack trace of thread 905:
                                                    #0  0x00007795d9f2bebe n/a (libc.so.6 + 0x87ebe)
                                                    #1  0x00007795d9f2e750 pthread_cond_wait (libc.so.6 + 0x8a750)
                                                    #2  0x00007795d6c8681c n/a (iris_dri.so + 0x8681c)
                                                    #3  0x00007795d6c9e7ec n/a (iris_dri.so + 0x9e7ec)
                                                    #4  0x00007795d9f2f55a n/a (libc.so.6 + 0x8b55a)
                                                    #5  0x00007795d9faca3c n/a (libc.so.6 + 0x108a3c)
                                                    
                                                    Stack trace of thread 902:
                                                    #0  0x00007795d9f2bebe n/a (libc.so.6 + 0x87ebe)
                                                    #1  0x00007795d9f2e750 pthread_cond_wait (libc.so.6 + 0x8a750)
                                                    #2  0x00007795d6c8681c n/a (iris_dri.so + 0x8681c)
                                                    #3  0x00007795d6c9e7ec n/a (iris_dri.so + 0x9e7ec)
                                                    #4  0x00007795d9f2f55a n/a (libc.so.6 + 0x8b55a)
                                                    #5  0x00007795d9faca3c n/a (libc.so.6 + 0x108a3c)
                                                    
                                                    Stack trace of thread 900:
                                                    #0  0x00007795d9f2bebe n/a (libc.so.6 + 0x87ebe)
                                                    #1  0x00007795d9f2e750 pthread_cond_wait (libc.so.6 + 0x8a750)
                                                    #2  0x00007795d6c8681c n/a (iris_dri.so + 0x8681c)
                                                    #3  0x00007795d6c9e7ec n/a (iris_dri.so + 0x9e7ec)
                                                    #4  0x00007795d9f2f55a n/a (libc.so.6 + 0x8b55a)
                                                    #5  0x00007795d9faca3c n/a (libc.so.6 + 0x108a3c)
                                                    
                                                    Stack trace of thread 903:
                                                    #0  0x00007795d9f2bebe n/a (libc.so.6 + 0x87ebe)
                                                    #1  0x00007795d9f2e750 pthread_cond_wait (libc.so.6 + 0x8a750)
                                                    #2  0x00007795d6c8681c n/a (iris_dri.so + 0x8681c)
                                                    #3  0x00007795d6c9e7ec n/a (iris_dri.so + 0x9e7ec)
                                                    #4  0x00007795d9f2f55a n/a (libc.so.6 + 0x8b55a)
                                                    #5  0x00007795d9faca3c n/a (libc.so.6 + 0x108a3c)
                                                    
                                                    Stack trace of thread 901:
                                                    #0  0x00007795d9f2bebe n/a (libc.so.6 + 0x87ebe)
                                                    #1  0x00007795d9f2e750 pthread_cond_wait (libc.so.6 + 0x8a750)
                                                    #2  0x00007795d6c8681c n/a (iris_dri.so + 0x8681c)
                                                    #3  0x00007795d6c9e7ec n/a (iris_dri.so + 0x9e7ec)
                                                    #4  0x00007795d9f2f55a n/a (libc.so.6 + 0x8b55a)
                                                    #5  0x00007795d9faca3c n/a (libc.so.6 + 0x108a3c)
                                                    ELF object binary architecture: AMD x86-64
Mar 07 08:22:54 archlinux systemd[1]: systemd-coredump@0-480752-0.service: Deactivated successfully.
Mar 07 08:22:54 archlinux systemd[1]: systemd-coredump@0-480752-0.service: Consumed 4.942s CPU time.
Mar 07 08:22:54 archlinux login[493]: pam_unix(login:session): session closed for user user1000
Mar 07 08:22:54 archlinux systemd[1]: getty@tty1.service: Deactivated successfully.
Mar 07 08:22:54 archlinux systemd[1]: getty@tty1.service: Scheduled restart job, restart counter is at 1.
Mar 07 08:22:54 archlinux systemd-logind[419]: Session 1 logged out. Waiting for processes to exit.
Mar 07 08:22:54 archlinux systemd[1]: Started Getty on tty1.
Mar 07 08:22:54 archlinux systemd[1]: Started Process Core Dump (PID 480809/UID 0).
Mar 07 08:22:54 archlinux systemd-coredump[480818]: Process 1363 (Xwayland) of user 1000 dumped core.
                                                    
                                                    Stack trace of thread 1363:
                                                    #0  0x00007507ac66a32c n/a (libc.so.6 + 0x8d32c)
                                                    #1  0x00007507ac6196c8 raise (libc.so.6 + 0x3c6c8)
                                                    #2  0x00007507ac6014b8 abort (libc.so.6 + 0x244b8)
                                                    #3  0x00005b7016eabc8d n/a (Xwayland + 0x169c8d)
                                                    #4  0x00005b7016eae28d n/a (Xwayland + 0x16c28d)
                                                    #5  0x00005b7016d744f1 n/a (Xwayland + 0x324f1)
                                                    #6  0x00007507ac602cd0 n/a (libc.so.6 + 0x25cd0)
                                                    #7  0x00007507ac602d8a __libc_start_main (libc.so.6 + 0x25d8a)
                                                    #8  0x00005b7016d74d85 n/a (Xwayland + 0x32d85)
                                                    
                                                    Stack trace of thread 1421:
                                                    #0  0x00007507ac664ebe n/a (libc.so.6 + 0x87ebe)
                                                    #1  0x00007507ac667750 pthread_cond_wait (libc.so.6 + 0x8a750)
                                                    #2  0x0000750795c8681c n/a (iris_dri.so + 0x8681c)
                                                    #3  0x0000750795c9e7ec n/a (iris_dri.so + 0x9e7ec)
                                                    #4  0x00007507ac66855a n/a (libc.so.6 + 0x8b55a)
                                                    #5  0x00007507ac6e5a3c n/a (libc.so.6 + 0x108a3c)
                                                    
                                                    Stack trace of thread 1455:
                                                    #0  0x00007507ac664ebe n/a (libc.so.6 + 0x87ebe)
                                                    #1  0x00007507ac667750 pthread_cond_wait (libc.so.6 + 0x8a750)
                                                    #2  0x0000750795c8681c n/a (iris_dri.so + 0x8681c)
                                                    #3  0x0000750795c9e7ec n/a (iris_dri.so + 0x9e7ec)
                                                    #4  0x00007507ac66855a n/a (libc.so.6 + 0x8b55a)
                                                    #5  0x00007507ac6e5a3c n/a (libc.so.6 + 0x108a3c)
                                                    
                                                    Stack trace of thread 1423:
                                                    #0  0x00007507ac664ebe n/a (libc.so.6 + 0x87ebe)
                                                    #1  0x00007507ac667750 pthread_cond_wait (libc.so.6 + 0x8a750)
                                                    #2  0x0000750795c8681c n/a (iris_dri.so + 0x8681c)
                                                    #3  0x0000750795c9e7ec n/a (iris_dri.so + 0x9e7ec)
                                                    #4  0x00007507ac66855a n/a (libc.so.6 + 0x8b55a)
                                                    #5  0x00007507ac6e5a3c n/a (libc.so.6 + 0x108a3c)
                                                    
                                                    Stack trace of thread 1424:
                                                    #0  0x00007507ac664ebe n/a (libc.so.6 + 0x87ebe)
                                                    #1  0x00007507ac667750 pthread_cond_wait (libc.so.6 + 0x8a750)
                                                    #2  0x0000750795c8681c n/a (iris_dri.so + 0x8681c)
                                                    #3  0x0000750795c9e7ec n/a (iris_dri.so + 0x9e7ec)
                                                    #4  0x00007507ac66855a n/a (libc.so.6 + 0x8b55a)
                                                    #5  0x00007507ac6e5a3c n/a (libc.so.6 + 0x108a3c)
                                                    
                                                    Stack trace of thread 1420:
                                                    #0  0x00007507ac664ebe n/a (libc.so.6 + 0x87ebe)
                                                    #1  0x00007507ac667750 pthread_cond_wait (libc.so.6 + 0x8a750)
                                                    #2  0x0000750795c8681c n/a (iris_dri.so + 0x8681c)
                                                    #3  0x0000750795c9e7ec n/a (iris_dri.so + 0x9e7ec)
                                                    #4  0x00007507ac66855a n/a (libc.so.6 + 0x8b55a)
                                                    #5  0x00007507ac6e5a3c n/a (libc.so.6 + 0x108a3c)
                                                    
                                                    Stack trace of thread 1456:
                                                    #0  0x00007507ac664ebe n/a (libc.so.6 + 0x87ebe)
                                                    #1  0x00007507ac667750 pthread_cond_wait (libc.so.6 + 0x8a750)
                                                    #2  0x0000750795c8681c n/a (iris_dri.so + 0x8681c)
                                                    #3  0x0000750795c9e7ec n/a (iris_dri.so + 0x9e7ec)
                                                    #4  0x00007507ac66855a n/a (libc.so.6 + 0x8b55a)
                                                    #5  0x00007507ac6e5a3c n/a (libc.so.6 + 0x108a3c)
                                                    ELF object binary architecture: AMD x86-64
Mar 07 08:22:54 archlinux systemd[1]: systemd-coredump@1-480809-0.service: Deactivated successfully.
```

- **Description:**
  - It crashed unexpectedly while I was working.

**Comment by emersion** [comment]
The backtrace you provided doesn't contain debug symbols. This most likely happens because the Sway binary you're using doesn't have debug information bundled.

Can you try again with a manually compiled Sway binary? See https://github.com/swaywm/sway/wiki/Development-Setup#compiling-as-a-subproject

**Comment by UdaraWanasinghe** [comment]
It crashed only once, and I'm not sure if I can reproduce the issue.

**Comment by mnd999** [comment]
Could be the same as my occasional IntelliJ crashes:

```
(gdb) bt
#0  0x000076270523cf5f in wl_list_remove (elm=elm@entry=0x5fa1fd0a74e8) at ../wayland-1.22.0/src/wayland-util.c:56
#1  0x00005fa1fb0dd6c2 in unmanaged_handle_dissociate (listener=0x5fa1fd0a74d0, data=<optimized out>)
    at ../sway-1.9/sway/desktop/xwayland.c:156
#2  0x000076270523d01e in wl_signal_emit_mutable (signal=signal@entry=0x5fa1fd09ec60, data=data@entry=0x0)
    at ../wayland-1.22.0/src/wayland-server.c:2241
#3  0x00007627051c0ab7 in xwayland_surface_dissociate (xsurface=xsurface@entry=0x5fa1fd09ea50) at ../wlroots-0.17.1/xwayland/xwm.c:398
#4  0x00007627051c28f0 in xwm_handle_unmap_notify (ev=0x5fa1fcde4000, xwm=0x5fa1fd433310) at ../wlroots-0.17.1/xwayland/xwm.c:1124
#5  x11_event_handler (fd=<optimized out>, mask=<optimized out>, data=<optimized out>) at ../wlroots-0.17.1/xwayland/xwm.c:1678
#6  x11_event_handler (fd=<optimized out>, mask=<optimized out>, data=<optimized out>) at ../wlroots-0.17.1/xwayland/xwm.c:1632
#7  0x000076270523eb8f in post_dispatch_check (loop=0x5fa1fc319110) at ../wayland-1.22.0/src/event-loop.c:943
#8  wl_event_loop_dispatch (loop=0x5fa1fc319110, timeout=timeout@entry=-1) at ../wayland-1.22.0/src/event-loop.c:1034
#9  0x000076270523f2d7 in wl_display_run (display=0x5fa1fc319020) at ../wayland-1.22.0/src/wayland-server.c:1493
#10 0x00005fa1fb091c5e in server_run (server=<optimized out>) at ../sway-1.9/sway/server.c:398
#11 main (argc=<optimized out>, argv=0x7fff2492b588) at ../sway-1.9/sway/main.c:415
```
