### ISSUE TITLE
Segfault in workspace_find_container (ws == NULL)

### ISSUE THREAD

**Issue by iwikal** [swaywm/sway#8310]
### Please fill out the following:
- **Sway Version:**
  - `sway version 1.9`

- **Debug Log:**
  - Sorry, haven't managed to reproduce

- **Configuration File:**
  - Sorry, haven't managed to reproduce.

- **Stack Trace:**
  - The value of `l->notify` in `wl_signal_emit_mutable` is `xdg_activation_v1_handle_request_activate`. It seems to be missing from the stacktrace though.
```
#0  0x00005689961d67fa in workspace_find_container (ws=ws@entry=0x0,
    test=test@entry=0x5689961d65f0 <find_urgent_iterator>, data=data@entry=0x0)
    at ../sway-1.9/sway/tree/workspace.c:696
        i = 0
        result = 0x0
#1  0x00005689961d86ee in workspace_detect_urgent (workspace=0x0)
    at ../sway-1.9/sway/tree/workspace.c:666
        new_urgent = <optimized out>
#2  0x0000734fda2ac42e in wl_signal_emit_mutable (signal=signal@entry=0x5689cffa1aa8,
    data=data@entry=0x7ffc2a264c10) at ../wayland-1.23.0/src/wayland-server.c:2314
        pos = 0x568996204480 <server+928>
        l = 0x568996204480 <server+928>
        cursor = {link = {prev = 0x568996204480 <server+928>, next = 0x7ffc2a264b90},
          notify = 0x734fda2a9180 <handle_noop>}
        end = {link = {prev = 0x7ffc2a264bb0, next = 0x5689cffa1aa8},
          notify = 0x734fda2a9180 <handle_noop>}
#3  0x0000734fda22b040 in activation_handle_activate (client=<optimized out>,
    activation_resource=<optimized out>, token_str=0x5689d09f2f1c "e649c19b8ca3907680969870537942af",
    surface_resource=<optimized out>) at ../wlroots-0.17.4/types/wlr_xdg_activation_v1.c:315
        activation = 0x5689cffa1a80
        surface = 0x5689d0bf21b0
        token = 0x5689d09b30d0
        found = true
        event = {activation = 0x5689cffa1a80, token = 0x5689d09b30d0, surface = 0x5689d0bf21b0}
#4  0x0000734fd98ca596 in ffi_call_unix64 () at ../src/x86/unix64.S:104
No locals.
#5  0x0000734fd98c700e in ffi_call_int (cif=cif@entry=0x7ffc2a264e20, fn=<optimized out>,
    rvalue=<optimized out>, avalue=<optimized out>, closure=closure@entry=0x0) at ../src/x86/ffi64.c:673
        classes = {X86_64_INTEGER_CLASS, 32764, 3649853260, 29519}
        stack = <optimized out>
        argp = 0x7ffc2a264c70 ""
        arg_types = <optimized out>
        gprcount = 4
        ssecount = <optimized out>
        ngpr = 1
        nsse = 0
        i = <optimized out>
        avn = <optimized out>
        flags = <optimized out>
        reg_args = <optimized out>
#6  0x0000734fd98c9bd3 in ffi_call (cif=cif@entry=0x7ffc2a264e20, fn=<optimized out>,
    rvalue=rvalue@entry=0x0, avalue=avalue@entry=0x7ffc2a264ef0) at ../src/x86/ffi64.c:710
        arg_types = 0x7ffc2a264e40
        i = <optimized out>
        nargs = 4
        max_reg_struct_size = <optimized out>
#7  0x0000734fda2aae45 in wl_closure_invoke (closure=closure@entry=0x5689d09f2e40,
    target=<optimized out>, target@entry=0x5689d08d3e10, opcode=opcode@entry=2, data=<optimized out>,
    data@entry=0x5689d08c8b50, flags=2) at ../wayland-1.23.0/src/connection.c:1228
        count = 2
        cif = {abi = FFI_UNIX64, nargs = 4, arg_types = 0x7ffc2a264e40,
          rtype = 0x734fd98cb1a0 <ffi_type_void>, bytes = 0, flags = 0}
        ffi_types = {0x734fd98cb2a0 <ffi_type_pointer>, 0x734fd98cb2a0 <ffi_type_pointer>,
          0x734fd98cb2a0 <ffi_type_pointer>, 0x734fd98cb2a0 <ffi_type_pointer>,
          0x734fd98cb330 <ffi_type_sint32>, 0x734fd98cb330 <ffi_type_sint32>, 0x7ffc2a264e80,
          0x32b2e156848ae800, 0xb, 0x2516, 0x57, 0x5689d0375080, 0x2, 0x0, 0x5689d09ecfe0,
          0x5689d09ecfe0, 0x7ffc2a265130, 0x5689d0a20770, 0x7ffc2a264fa0,
          0x734fda16986f <key_get_consumed+31>, 0xb, 0x56899619e99d <state_erase_key+173>}
        ffi_args = {0x7ffc2a264e00, 0x7ffc2a264e08, 0x5689d09f2e58, 0x5689d09f2e60, 0x734fda100ac0,
          0x62f00, 0x5689d0cf6100, 0x2, 0x7ffc2a264f80, 0x734fda2ac988 <log_closure+88>,
          0x5689d09644a0, 0x0, 0x7ffc2a264fa0, 0x5689cf4d9f00, 0x5689d0964570,
          0x734fda297850 <xdg_activation_v1_requests.lto_priv+48>, 0x0, 0x2, 0x7ffc2a264fe0,
          0x734fda2a9f38 <wl_closure_init+200>, 0x1040000000b, 0x104}
        implementation = <optimized out>
#8  0x0000734fda2afc42 in wl_client_connection_data (fd=<optimized out>, mask=<optimized out>,
    data=0x5689d08c8b50) at ../wayland-1.23.0/src/wayland-server.c:444
        client = 0x5689d08c8b50
        connection = 0x5689d08dc8d0
        resource = <optimized out>
        object = 0x5689d08d3e10
        closure = 0x5689d09f2e40
        message = 0x734fda297850 <xdg_activation_v1_requests.lto_priv+48>
        p = {14, 3407874}
        resource_flags = 0
        opcode = 2
        size = <optimized out>
        since = <optimized out>
        len = <optimized out>
#9  0x0000734fda2ae0a2 in wl_event_loop_dispatch (loop=0x5689cf4d9ff0, timeout=<optimized out>,
    timeout@entry=-1) at ../wayland-1.23.0/src/event-loop.c:1105
        ep = {{events = 1, data = {ptr = 0x5689d08c2770, fd = -796121232, u32 = 3498846064,
              u64 = 95149909354352}}, {events = 29519, data = {ptr = 0x5689d0ab80c0, fd = -794066752,
              u32 = 3500900544, u64 = 95149911408832}}, {events = 3498952912, data = {
              ptr = 0x3000005689, fd = 22153, u32 = 22153, u64 = 206158452361}}, {events = 0, data = {
              ptr = 0x7ffc2a265290, fd = 707154576, u32 = 707154576, u64 = 140721015640720}}, {
            events = 3498953008, data = {ptr = 0xffffffff00005689, fd = 22153, u32 = 22153,
              u64 = 18446744069414606473}}, {events = 4294967295, data = {ptr = 0x7ffc2a2653b0,
              fd = 707154864, u32 = 707154864, u64 = 140721015641008}}, {events = 3660228251, data = {
              ptr = 0x56890000734f, fd = 29519, u32 = 29519, u64 = 95146410537807}}, {events = 0,
            data = {ptr = 0x2c5e9928, fd = 744397096, u32 = 744397096, u64 = 744397096}}, {
            events = 707154672, data = {ptr = 0x3000007ffc, fd = 32764, u32 = 32764,
              u64 = 206158462972}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {
            events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0,
              fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {
            events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 2518213294, data = {
              ptr = 0xd078b16800005689, fd = 22153, u32 = 22153, u64 = 15021951617329026697}}, {
            events = 22153, data = {ptr = 0x30, fd = 48, u32 = 48, u64 = 48}}, {events = 3497568320,
            data = {ptr = 0x800005689, fd = 22153, u32 = 22153, u64 = 34359760521}}, {events = 0,
            data = {ptr = 0x18, fd = 24, u32 = 24, u64 = 24}}, {events = 1, data = {ptr = 0x8400000001,
              fd = 1, u32 = 1, u64 = 566935683073}}, {events = 147, data = {ptr = 0x5689000000e5,
              fd = 229, u32 = 229, u64 = 95146410508517}}, {events = 3493324720, data = {
              ptr = 0xd037e7a800005689, fd = 22153, u32 = 22153, u64 = 15003715392348640905}}, {
            events = 22153, data = {ptr = 0x3000000010, fd = 16, u32 = 16, u64 = 206158430224}}, {
            events = 707154960, data = {ptr = 0x2a26534000007ffc, fd = 32764, u32 = 32764,
              u64 = 3037206533051023356}}, {events = 32764, data = {ptr = 0x32b2e156848ae800,
              fd = -2071271424, u32 = 2223695872, u64 = 3653230009458026496}}, {events = 3660222848,
            data = {ptr = 0xd04e2fc00000734f, fd = 29519, u32 = 29519, u64 = 15009987109752697679}}, {
            events = 22153, data = {ptr = 0x5689961e834c, fd = -1776385204, u32 = 2518582092,
              u64 = 95148929090380}}, {events = 396, data = {ptr = 0xcff8e36000000000, fd = 0, u32 = 0,
              u64 = 14985977761531691008}}, {events = 22153, data = {ptr = 0x7, fd = 7, u32 = 7,
              u64 = 7}}, {events = 3492216352, data = {ptr = 0x848ae80000005689, fd = 22153,
              u32 = 22153, u64 = 9550701046490224265}}, {events = 850583894, data = {ptr = 0xb0000000a,
              fd = 10, u32 = 10, u64 = 47244640266}}, {events = 3500435888, data = {
              ptr = 0xcf4d9f2800005689, fd = 22153, u32 = 22153, u64 = 14937770533205333641}}, {
            events = 22153, data = {ptr = 0x5689cf4d9f48, fd = -816996536, u32 = 3477970760,
              u64 = 95149888479048}}}
        source = <optimized out>
        i = 0
        count = <optimized out>
        has_timers = <optimized out>
        use_timeout = false
        now = {tv_sec = 95149908121456, tv_nsec = -552}
        end = <optimized out>
#10 0x0000734fda2b010f in wl_display_run (display=0x5689cf4d9f00)
    at ../wayland-1.23.0/src/wayland-server.c:1530
No locals.
#11 0x0000568996188cd5 in server_run (server=<optimized out>) at ../sway-1.9/sway/server.c:398
No locals.
#12 main (argc=<optimized out>, argv=0x7ffc2a265648) at ../sway-1.9/sway/main.c:415
        config_path = 0x0
        c = <optimized out>
        validate = false
        debug = false
        allow_unsupported_gpu = false
        verbose = false
```
- **Description:**
  - I am using a Radeon RX 5700 XT with the `amdgpu` driver.
  - I don't quite remember the exact steps I took but what was a bit out of the ordinary was that I had a floating vertically split container in my scratchpad, and was toggling it between focused and hidden.
  - I was also encoding video using gstreamer inside a docker container and massaging that video data a bunch in firefox, don't think it's relevant, but it may have put some strain on the system.

**Comment by iwikal** [comment]
Nevermind, it seems to be fixed already in #8221
