### ISSUE TITLE
Crash on startup when connected to multi-monitor via Thunderbolt dock

### ISSUE THREAD

**Issue by J0nnyMak0** [swaywm/sway#8395]
I have a multi-gpu setup. When I am connected to my external monitors, all through a single thunderbolt dock, then I get a Sway crash on startup. If I connect at least one monitor directly to the computer and the rest through the dock, the cash goes away. Log and stack trace attached.

[gdb.txt](https://github.com/user-attachments/files/17442320/gdb.txt)
[sway.log](https://github.com/user-attachments/files/17442321/sway.log)

**Comment by emersion** [comment]
Can you still reproduce with latest commit?

Copying over the stack trace for discoverability:

```
#0  0x00007074180bc960 in drm_atomic_connector_prepare (state=0x5e2521014090, modeset=true) at ../subprojects/wlroots/backend/drm/atomic.c:244
        conn = 0x5e2521016fa0
        drm = 0x5e251fa94b90
        output = 0x5e2521016fa0
        crtc = 0x0
        mode_id = 553729984
        gamma_lut = 24101
        fb_damage_clips = 531188624
        in_fence_fd = 24101
        prev_vrr_enabled = false
        vrr_enabled = false
#1  0x00007074180bd557 in atomic_device_commit (drm=0x5e251fa94b90, state=0x7fffd72a4b40, page_flip=0x0, flags=0, test_only=true) at ../subprojects/wlroots/backend/drm/atomic.c:480
        i = 0
        ok = false
        atom = {req = 0x707417925ac0 <main_arena>, failed = 96}
#2  0x00007074180c010b in drm_commit (drm=0x5e251fa94b90, state=0x7fffd72a4b40, flags=0, test_only=true) at ../subprojects/wlroots/backend/drm/drm.c:617
        __PRETTY_FUNCTION__ = "drm_commit"
        page_flip = 0x0
        ok = false
#3  0x00007074180c485c in commit_drm_device (drm=0x5e251fa94b90, output_states=0x5e2520be5e30, output_states_len=5, test_only=true) at ../subprojects/wlroots/backend/drm/drm.c:2014
        conn_states = 0x5e2521014090
        ok = false
        modeset = true
        conn_states_len = 5
        flags = 0
        dev_state = {modeset = true, nonblock = false, connectors = 0x5e2521014090, connectors_len = 5}
#4  0x00007074180bdbcc in backend_test (backend=0x5e251fa94b90, states=0x5e2520be5e30, states_len=5) at ../subprojects/wlroots/backend/drm/backend.c:85
        drm = 0x5e251fa94b90
#5  0x00007074180ba2f1 in wlr_backend_test (backend=0x5e251fa94b90, states=0x5e2520be5e30, states_len=5) at ../subprojects/wlroots/backend/backend.c:453
        __PRETTY_FUNCTION__ = "wlr_backend_test"
#6  0x00007074180d3c18 in commit (backend=0x5e251fa7b2c0, states=0x5e2520c8ed60, states_len=5, test_only=true) at ../subprojects/wlroots/backend/multi/backend.c:139
        sub = 0x5e251fa94b90
        len = 5
        i = 0
        by_backend = 0x5e2520be5e30
        ok = true
#7  0x00007074180d3cba in multi_backend_test (backend=0x5e251fa7b2c0, states=0x5e2520c8ed60, states_len=5) at ../subprojects/wlroots/backend/multi/backend.c:155
#8  0x00007074180ba2f1 in wlr_backend_test (backend=0x5e251fa7b2c0, states=0x5e2520c8ed60, states_len=5) at ../subprojects/wlroots/backend/backend.c:453
        __PRETTY_FUNCTION__ = "wlr_backend_test"
#9  0x00007074181215e2 in manager_test (manager=0x7fffd72a4e30, states=0x5e2520c8ed60, states_len=5, explicit_modifiers=true) at ../subprojects/wlroots/types/wlr_output_swapchain_manager.c:180
        manager_output = 0x0
        ok = false
        __PRETTY_FUNCTION__ = "manager_test"
#10 0x000070741812188f in wlr_output_swapchain_manager_prepare (manager=0x7fffd72a4e30, states=0x5e25210116c0, states_len=5) at ../subprojects/wlroots/types/wlr_output_swapchain_manager.c:209
        ok = false
        pending = 0x5e2520c8ed60
#11 0x00005e24ee40416b in apply_resolved_output_configs (configs=0x5e2520f29ad0, configs_len=5, test_only=false, degrade_to_off=true) at ../sway/config/output.c:917
        states = 0x5e25210116c0
        swapchain_mgr = {backend = 0x5e251fa7b2c0, outputs = {size = 160, alloc = 256, data = 0x5e2521013ac0}}
        ok = false
        seat = 0x7fffd72a4df0
#12 0x00005e24ee404734 in apply_output_configs (ocs=0x5e2520b89520, ocs_len=1, test_only=false, degrade_to_off=true) at ../sway/config/output.c:1025
        configs_len = 5
        configs = 0x5e2520f29ad0
        config_idx = 5
        sway_output = 0x5e251fa7a6b8
        ok = 81
#13 0x00005e24ee4047be in apply_stored_output_configs () at ../sway/config/output.c:1035
#14 0x00005e24ee3e4ea5 in timer_modeset_handle (data=0x5e24ee463ce0 <server>) at ../sway/desktop/output.c:399
        server = 0x5e24ee463ce0 <server>
#15 0x00007074179c5446 in wl_timer_heap_dispatch (timers=0x5e251fa7a5e8) at ../wayland-1.23.1/src/event-loop.c:527
        now = {tv_sec = 1095, tv_nsec = 291486041}
        root = 0x5e2520fe77c0
        list_cursor = 0x5e2520fe77c0
        list_tail = <optimized out>
        now = {tv_sec = <optimized out>, tv_nsec = <optimized out>}
        root = <optimized out>
        list_cursor = <optimized out>
        list_tail = <optimized out>
```
