### ISSUE TITLE
Crash on shutdown in wlroots listener checks

### ISSUE THREAD

**Issue by emersion** [swaywm/sway#8509]
```

(gdb) bt
#0  0x00007420992a53f4 in ?? () from /usr/lib/libc.so.6
#1  0x000074209924c120 in raise () from /usr/lib/libc.so.6
#2  0x00007420992334c3 in abort () from /usr/lib/libc.so.6
#3  0x00007420992333df in ?? () from /usr/lib/libc.so.6
#4  0x0000742099244177 in __assert_fail () from /usr/lib/libc.so.6
#5  0x000074209a71289d in wlr_scene_node_destroy (node=0x51400004c440) at ../subprojects/wlroots/types/scene/wlr_scene.c:130
#6  0x000074209a713230 in wlr_scene_node_destroy (node=0x50c00012f580) at ../subprojects/wlroots/types/scene/wlr_scene.c:155
#7  0x000074209a713230 in wlr_scene_node_destroy (node=0x50c00012f280) at ../subprojects/wlroots/types/scene/wlr_scene.c:155
#8  0x000074209a713230 in wlr_scene_node_destroy (node=0x50c00012de40) at ../subprojects/wlroots/types/scene/wlr_scene.c:155
#9  0x000074209a713230 in wlr_scene_node_destroy (node=0x50c000130c00) at ../subprojects/wlroots/types/scene/wlr_scene.c:155
#10 0x000074209a713230 in wlr_scene_node_destroy (node=0x50c000000c40) at ../subprojects/wlroots/types/scene/wlr_scene.c:155
#11 0x000074209a713230 in wlr_scene_node_destroy (node=0x50c000000a00) at ../subprojects/wlroots/types/scene/wlr_scene.c:155
#12 0x000074209a713230 in wlr_scene_node_destroy (node=0x511000000cc0) at ../subprojects/wlroots/types/scene/wlr_scene.c:155
#13 0x000056579598ed69 in root_destroy (root=0x512000000040) at ../sway/tree/root.c:85
#14 0x00005657957f86c4 in main (argc=4, argv=0x7ffcf213c1e8) at ../sway/main.c:380
```

**Comment by Ferdi265** [comment]
Should this be considered fixed by #8578?

**Comment by emersion** [comment]
Indeed!
